### ISSUE TITLE
При изменении настроек сбивается шаг цены - становится по дефолту.

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#10]
Менял сейчас настройки прозрачности в клаудах и при каждом изменении цвета шаг сбрасывался на 0,5. У меня установлен 1

**Comment by ershner** [comment]
UPD. При прогрузке воркспейса - если шаг изменен(евро вместо 0,5  -  1), то прогружается правильно, но в строке шага значение отображается 0,5 и при любом нажатии на аплай - шаг меняется

**Comment by SBProX** [comment]
Пожалуйста высылайте скриншоты. Не понятно на каком инструменте.

**Comment by ershner** [comment]
![2019-05-06_23-20-27 (2)](https://user-images.githubusercontent.com/18483236/57252782-b43df080-7055-11e9-991a-b0b36268e7fc.png)
Евро - везде крому тикового графика стоит шаг=1. При прогрузки ворспейса - грузится правильно(шаг=1), но в отображается в панели инструментов как 0,5. Из-за этого при любом нажатии на аплай - шаг меняется на 0,5

**Comment by SBProX** [comment]
Завтра проверим, спасибо.

**Comment by r35p3ct** [comment]
Вот про этот шаг цены с самой первой версии пишу, что не сохраняется.

![sh](https://user-images.githubusercontent.com/7328803/57283369-a751e900-70b7-11e9-8f21-dda90b73f064.JPG)

**Comment by SBProX** [comment]
Исправлено. Сегодня вечером выйдет обновление, проверите, будет ли появляться ошибка.
Если будет - сделайте  reopen тикета.
