### ISSUE TITLE
После обновления от 13.05 не отображаются полоски направления баров

### ISSUE THREAD

**Issue by shandr1** [SBProX/SBProX-Dev#101]
Изменение ширины полоски бара не помогает
Галка скрывать направление при сжатии не влияет на проблему

**Comment by Artem074** [comment]
> Изменение ширины полоски бара не помогает
> Галка скрывать направление при сжатии не влияет на проблему

Хм... у меня отображаются
![2019-05-14_133305](https://user-images.githubusercontent.com/50441291/57683328-da165700-764c-11e9-9c16-092b4ea4d2f5.png)

**Comment by shandr1** [comment]
Скриншот с настройками прилагаю. Может что-то не так я настроил?
![Image 4+](https://user-images.githubusercontent.com/50615160/57685054-b1d42b80-763f-11e9-83db-0b340b8210c2.jpg)

**Comment by shandr1** [comment]
Разобрался, извините. После обновления не поставил на закладке "Графики" галку "Показывать направление бара".   Структура меню для меня оказалась интуитивно не очень проста.  В разных разделах меню приходится устанавливать параметры, которые касаются одного и того же действия (например, отображения направления баров). В разделе "Основные настройки" указываешь толщину и скрытие при сжатии, а в разделе "Графики" - отображать вообще или нет. ..
