### ISSUE TITLE
рисование канала - полный треш

### ISSUE THREAD

**Issue by in1moment** [SBProX/SBProX-Dev#1011]
Уважаемые разработчики! Вы издеваетесь над своими клиентами? Неужели нельзя сделать нормальное рисование трендов по трем точкам, как в XTick, TigerТrade, да даже в штатных терминалах брокеров? Это так сложно для Вас? Вы сами пробовали наложить канал? Хватит издеваться над пользователями, смените программистов!

**Comment by SBProX** [comment]
Платформа Beta еще, что вы от нас хотите?
Пользуйтесь XTick, если так все не нравится,  вас никто не заставляет.

**Comment by in1moment** [comment]
я вам деньги заплатил! Вам все равно на то, что недовольные пользователи будут хаить вашу программу на формах?
