### ISSUE TITLE
Просьба уволить программистов и набрать новых!

### ISSUE THREAD

**Issue by in1moment** [SBProX/SBProX-Dev#1013]
Уважаемые собственники терминала SBProX. Ваши программисты с высокой долей вероятности работают на ваших конкурентов. Только этим можно объяснить подрывную деятельность, которую они ведут своим уклонением от исправления вопиющих косяков программы. При этом сделать это мог бы даже студент. 
Исправив эти элементарные косяки вы могли бы увеличить доход от продаж программы в разы. Вы могли бы сделать платной подписку на нее (не менее 2000 рублей в месяц), а также продавать пожизненную лицензию за 30 тысяч рублей вместо 6500.
Что необходимо изменить для это.
- 1. Линковка фигур на другие графики с данным инструментом (прямоугольники, элипсы, рэйнджи и так далее);
- 2. Автопродление фигур по желанию пользователей (отдельная кнопка);
- 3. Рисование тренда по 3м точкам, а не через ж...;
- 4. Подключить рынок акций, индексов, валюты, торгуемой на ММВБ;
- 5. Уволить программистов с позором без выходного пособия.
С Уважением, пока Ваш пользователь.
-

**Comment by in1moment** [comment]
причем лучше начать с конца.

**Comment by Flawmaster** [comment]
Вы неадекватны? Все эти опции можно было бы добавить по востребованности - провести голосование. Разрабы обычно идут навстречу. Но, я сомневаюсь, что продление фигур "влево"(а не вправо) кому-то нужно. И к тому же Вас никто не заставлял покупать платформу - есть демоверсия для тестов: не нравится, не покупайте.
з.ы. очень много всего уже было исправлено и добавлено, и в будущем уверен, что еще много чего добавят, но на такие "вопли" Вам никто ничего делать не будет.

**Comment by SBProX** [comment]
@in1moment Вы кажется не читали, что платформа Beta и еще в разработке?
Или мы должны все за 5 минут исправить?

**Comment by in1moment** [comment]
Flawmaster, а вы случайно не разработчик, скрывающийся под левым ником? Гле вы видели, что я сказал про продление фигур влево? 
"никто не заставлял покупать платформу"
"никто ничего делать не будет"
Вы думаете собственник программы сказал бы также? именно собственник, а не ленивые школьники на месячной зарплате в должности программистов, которые только имитируют бурную деятельность перед работодателем?

**Comment by in1moment** [comment]
SBProX  сколько это можно делать? За 1 неделю можно исправить все косяки! 
Давайте конкретно, сколько по времени нужно 1 программисту чтоб исправить косяк №№ 1,2,3,4 в отдельности?

**Comment by SBProX** [comment]
@in1moment Во-первых не надо называть нас школьниками, во-вторых, мы не ваши наемные работники, чтобы перед вам отчитываться. 
Если вам не нравится платформа, то не используйте ее. А хамить нам в репозитории не нужно.

**Comment by in1moment** [comment]
Во-первых, зарплата которую вы получаете идет в том числе из моего кармана, поэтому должны вы мне, а не я вам!
Во-вторых, ваш работодатель был бы очень не доволен увидев такие комментарии от его имени:
"если вам не нравится платформа, то не используйте ее"
"никто не заставлял покупать платформу"
"никто ничего делать не будет"
А в третьих, я думаю что нужно провести голосование по вашей работе в телеграмм канале. На какую оценку оценят вас пользователи. Это я предложу сделать собственнику программы. Погуглю как его найти.

**Comment by in1moment** [comment]
Если кто из читающих этот пост знает как это сделать, прошу написать здесь - это ускорит процесс. Либо сделать самостоятельно.

**Comment by SBProX** [comment]
Владелец проекта: telegram: @sbproofficial

**Comment by in1moment** [comment]
Сомневаюсь. Электронная почта собственника, рабочий телефон?

**Comment by SBProX** [comment]
Нам не понятна ваша позиция, то есть вы сначала покупаете софт, а потом жалуетесь что в нем что-то не так. Хотя написано, что платформа Beta.
Стоило бы сначала ознакомиться с этим.
Теперь вы нам хамите в репозитории, обзываете ленивыми школьниками, и ведется откровенно неприятный диалог.
Зачем вы покупали ПО, зная о том, что софт сырой, а теперь такое пишете?
Обновления выходят по мере внесения изменений.

**Comment by in1moment** [comment]
Я вам задал вопрос. Сколько часов рабочего времени необходимо 1 программисту, для того чтоб исправить косяк № 1, 2, 3, 4 ?

**Comment by SBProX** [comment]
Мы и не должны вам отвечать на вопрос сколько времени.
Это наши внутренние процессы.

Если есть претензии: @sbproofficial, общайтесь с владельцем проекта.

**Comment by in1moment** [comment]
"Мы и не должны вам отвечать на вопрос сколько времени.
Это наши внутренние процессы."
))))))))))))))))
Да потому что на это требуется 2 часа! 
Мое мнение такое - вы водите за нос работодателя тем, что на форме появляется куча претензий, исправление которых вы целенаправленно затягиваете. Сидите на зарплате и ничего не делаете, либо завышаете значимость каждой проблемы и просите премии. А на деле работодатель теряет из-за вас миллионы, а пользователи нервы!
Либо второй вариант - вы просто ничего не умеете. Не можете сделать элементарного. Даже не знаете сколько времени займет изменение способа построения канала с уе... на нормальный. Потому что это форум может прочитать реальный программист, который вас засмеет, если увидит срок - неделя, месяц и тд.

**Comment by Flawmaster** [comment]
> Flawmaster, а вы случайно не разработчик, скрывающийся под левым ником? Где вы видели, что я сказал про продление фигур влево?

Я покупатель и тот, кто активно пользуется платформой. И, к кому же, у меня куплены обе версии программы. 
Как человек, не столь далекий от программирования (я QA Engineer), могу сказать что на исправление косяков явно не 2 часа нужно. И бы рекомендовал посмотреть в репозитории сколько запросов у пользователей - все добавляют/исправляют постепенно. К тому же по ходу только вы считаете ("изменение способа построения канала с уе... на нормальный") способ построения канала неудобным. А если еще кто-то, то допишут в нужной теме и способ поменяют. А из-за одного человека менять каждый раз все - нерационально.

**Comment by in1moment** [comment]
Только я считаю способ построения канала неудобным? Готов поспорить, такого мнения не менее половины пользователей. А те, кому все нравится или не использует каналы или не знает с чем сравнивать. Как у разработчиков появится время, возможно они сделают опрос в телеграмм канале по этому поводу и увидят общую картину. А оценивать важность проблемы по количестве постов или плюсиков в репозитории не правильно. Думаю что не более 1 процента пользователей здесь зарегистрированно.
