### ISSUE TITLE
Многооконный режим на одном экране

### ISSUE THREAD

**Issue by Alehus2** [SBProX/SBProX-Dev#1014]
Сделайте возможность открывать несколько графиков на одном экране. В 21 веке такая функция должна быть по умолчанию. И было бы классно если бы положение курсора дублировалось на других ТФ этого же инструмента.

**Comment by X-man77** [comment]
> Сделайте возможность открывать несколько графиков на одном экране. 

А сейчас что вам мешает открывать несколько графиков на одном экране? Не знание интерфейса? Или вы как-то по особому хотите их открывать? Поделитесь тогда - ежели толково, то сообщество поддержит.

**Comment by in1moment** [comment]
предложение хорошее. Объясню по другому. 
При наличии 2х и более мониторов трейдеры рассматривают 1 инструмент на разных таймфреймах, либо смотрят сразу 2-3 взаимосвязанных инструмента. Для того чтоб их открыть у вас в программе сейчас нужно каждое окно открывать в отдельности. Аналогично и с переключением на другие инструменты - закрывать каждое окно и открывать новые. Быыло бы удобно, чтоб можно было сделать привязку нескольких окон к 1 кнопке. Кто-то захочет разместить несколько окон на 1 экране (особенно на широкоформатном мониторе), кто-то на нескольких. Но фишка в том, что нужна возможность свернуть их 1 кнопкой либо открыть аналогичный конгломерат окон также 1 кнопкой.

**Comment by AlexSun88** [comment]
> > Сделайте возможность открывать несколько графиков на одном экране.
> 
> А сейчас что вам мешает открывать несколько графиков на одном экране? Не знание интерфейса? Или вы как-то по особому хотите их открывать? Поделитесь идеей тогда - ежели толково, то сообщество поддержит.

Если Alehus2 не против я посню, что имелось ввиду. Такая функция например есть в платформе TOS, где в правом, верхнем углу есть линковка на необходимое колличество окон, которые формируются по размеру автоматически активного, основного онка. Данный формат очень удобен друзья. Если у вас не 1 монитор или элементарно используете программу Dexpot(даёт делать по моему до 9 рабочих столов), то работая с большим колличеством инструментов и бирж, через линковку можно настраивать очень быстро весь необходимый тебе рабочий формат. Работа упрощается многократно! Попробуйте обработать Short list и Long List где в каждом по 200 акций... А ещё и тф несколько штук. Надеюсь донёс мысль. Если нет, просто посмотрите в платформе TOS эту функцию.

**Comment by Alehus2** [comment]
> > Сделайте возможность открывать несколько графиков на одном экране.
> 
> А сейчас что вам мешает открывать несколько графиков на одном экране? Не знание интерфейса? Или вы как-то по особому хотите их открывать? Поделитесь идеей тогда - ежели толково, то сообщество поддержит.

Ниже ребята правильно поняли. 
Возможно я торопился не до конца мысль донес. Что в ниньзе, что у вас, очень не удобно открывать один инструмент разными окнами. Почему так реализовано, не понятно. Удобно открывая одним окном видеть в нем те ТФ, которые тебе нужны по данному инструменту. 
Ну и повторюсь. Очень удобно, когда курсор с одного тф, дублируется на других тф. Интересующее тебя место на одном ТФ сразу перекрестием отображается на других ТФ.  Очень часто нужно разобрать что произошло в данный момент времени старшего тайфрема, на меньших тф.

**Comment by X-man77** [comment]
> > > Сделайте возможность открывать несколько графиков на одном экране.
 
> Возможно я торопился не до конца мысль донес. 

Да, мысль вы сформулировали не совсем определённо, под такую формулировку подходит несколько вариантов понимания. Поэтому и написал свой пост.    

>Удобно открывая одним окном видеть в нем те ТФ, которые тебе нужны по данному инструменту.

Если правильно понял - вы хотите внутри окна располагать вкладки каким-то особым образом? Например:  плиткой, и.т.д. Так, нет?  Не понятно почему, но разрабы не предусмотрели функцию изменения размера вкладки **внутри** окна. Для больших мониторов эта функция была-бы весьма полезна, для обычных - увы, слишком мелкое получится изображение. Надеюсь разрабы добавят функцию изменения размера вкладки.
 
> Ну и повторюсь. Очень удобно, когда курсор с одного тф, дублируется на других тф. Интересующее тебя место на одном ТФ сразу перекрестием отображается на других ТФ. Очень часто нужно разобрать что произошло в данный момент времени старшего тайфрема, на меньших тф.

Вопрос линковки поднимался не раз. С моей стороны было предложение сделать настройку линковки где трейдер указывал-бы что именно он хочет линковать - линии, фигуры, курсор, глубину истории, и.т.д. (тикет не нашёл к сожалению).  Но пока вопрос подвис, увы. 

Ваше предложение в 1-м посте поддерживаю.

**Comment by Alehus2** [comment]
Спасибо за ответ.
Вот прикрепляю картинку, как это выглядит в OANDA.
Есть кнопочка, в которой выбирается, как будут располагаться графики инструмента. 
и перекрестие, автоматически передвигается по всем ТФ в зависимости от активного ТФ.
![1](https://user-images.githubusercontent.com/56960322/74250980-7ebce680-4cfc-11ea-8b9f-841069922e3d.jpg)
Про линковку зайду почитаю.

**Comment by Alehus2** [comment]
И, кстати, из такого объединения графиков, автоматически выростает линковка. Они все между собой объединены одним окном.
Как пример, прикрепляю картинку.
![3](https://user-images.githubusercontent.com/56960322/74254085-03a9ff00-4d01-11ea-9458-2bad3ce69147.jpg)

**Comment by Alehus2** [comment]
Сразу напишу, чтобы не было вопросов. Данная платформа предоставляет не точные данные, как по графику, так и по объемам. Они с форэкса, а это уже не то.

**Comment by RoketAnny** [comment]
Перефразирую автора.
мне тоже не хватает **контейнера** для инструмента в котором открыто сразу 2-3 таймфрема
Сейчас реализация такая. 
Хочешь много окон, Меню => Новое окно графика
Открыл три окна, на инструмент нефть тф: Day, H1, m10 
- очень большой минус такой схемы все окна независимы, и чтобы их увидеть сразу вместе, каждую вкладку окна нужно персонально активировать, а если нужно свернуть, так же по одной и сворачиваешь. 

А если также ещё сделать на инструмент РТС, то вкладок уже 6 шт и в них уже начинаешь путаться.

Хотелось бы увидеть такую схему
Контейнер инструмента, например нефть, В одной общей оболочке находятся три окна, в каждом окне свой ТФ, и перекрестие на всех тф двигается синхронно.

Следующий контейнер уже другой инструмент, со своими окнами тф.
И контейнеры уже независимые окна, которые можно растащить по разным мониторам.
На одном мониторе контейнер с одним инструментом, на другом с другим.


Или другой подход

Возможно, это можно реализовать как вкладки, а в каждой вкладке независимые окна с тф
вот для примера quik
![image](https://user-images.githubusercontent.com/18662109/74591857-9feb4300-502c-11ea-966d-afced737ea42.png)

**Comment by SBProX** [comment]
Архитектура платформы изначально была построена по принципу - окна, и вкладки в окне.
Окна с графиками в другом окне - нужно  переписывать пол платформы.
Это не реализуемо в рамках SBProX
