### ISSUE TITLE
Рэнж бары

### ISSUE THREAD

**Issue by OlegT911** [SBProX/SBProX-Dev#1015]
Просьба сделать рэнж бары, с изменяемым диапазоном.

**Comment by weeclemans** [comment]
DUB https://github.com/SBProX/SBProX-Dev/issues/974
уже было

**Comment by SBProX** [comment]
Range бары пока сделать нет возможности

**Comment by OlegT911** [comment]
Поддержите новый тикет по рэнж бару #1608
