### ISSUE TITLE
Проблема с отображением РОС в профиле

### ISSUE THREAD

**Issue by Alehus2** [SBProX/SBProX-Dev#1016]
Добрый день. Ребята, обратите внимание. почему-то РОС бара выделяется не по максимальному объему.
![2](https://user-images.githubusercontent.com/56960322/74103597-5b5c3500-4b5e-11ea-822d-1d824e709c30.jpg)

**Comment by OlegT911** [comment]
По максимальной дельте выделяется, то же обратился.
https://github.com/SBProX/SBProX-Dev/issues/1036

**Comment by SBProX** [comment]
На данном типе графика выделяет по макс. дельте,а не по объему
