### ISSUE TITLE
Стакан и индикатор VWAP

### ISSUE THREAD

**Issue by Panica777** [SBProX/SBProX-Dev#1017]
1 вопрос Когда в индикатор VWAP добавят отклонения,   2 ой вопрос возможно ли реализовать в вашей платформе стакан.

**Comment by Aleksandr12321** [comment]
Если стакан бы добавили было бы вообще гуд?

**Comment by Panica777** [comment]
Не только стакан, но и ленты принтов не помешало бы добавить.

**Comment by pavloreva** [comment]
Стакан реально нужен! Пока его нет на SBPro, приходится в Волфикс сидеть.

**Comment by SBProX** [comment]
VWAP отклонения - под вопросом.
Стакана точно не будет.
