### ISSUE TITLE
SBPrpo для смартфонов

### ISSUE THREAD

**Issue by Panica777** [SBProX/SBProX-Dev#1019]
SBPrpo для смартфонов, кто за поддержите лайками.

**Comment by Ded-Griboed** [comment]
Для начала хотя бы возможность торговать с компьютера, а уж потом для смартфонов и тд)

**Comment by Aleksandr12321** [comment]
> Для начала хотя бы возможность торговать с компьютера, а уж потом для смартфонов и тд)

Дело говоришь)

**Comment by Alexey316** [comment]
Мне не требуется. Лучше возможность торговать из платформы с компа.

**Comment by SBProX** [comment]
К сожалению для мобильных устройств  мы не планируем делать софт
