### ISSUE TITLE
Отсутствует история за 14.02.2020

### ISSUE THREAD

**Issue by Chekmy** [SBProX/SBProX-Dev#1020]
Добрый вечер! У меня отсутствует история за пятницу 14 февраля, на всех инструментах. Пытался перезагрузить данные с графика. Как можно это исправить?
https://yadi.sk/i/TIigLgE9usOLgA

**Comment by Aleksandr12321** [comment]
По Si тоже нету!!

**Comment by Chekmy** [comment]
Появилась.
