### ISSUE TITLE
Прозрачность индикаторов

### ISSUE THREAD

**Issue by Pavel-111** [SBProX/SBProX-Dev#1024]
Просьба сделать на всех индикаторах функцию прозрачность

**Comment by Pavel-111** [comment]
Просьба сделать прозрачность!!!!!!
На Total Valume прозрачость есть, хотя индикатор в общем то не мешает. А на индикаторах которые наносятся на сам график- как пример Daile Volume Profile- его нет..

**Comment by SBProX** [comment]
Есть, читайте внимательно инструкцию.
Прозрачность устанавливается в настройках цвета (Параметр А)

**Comment by Pavel-111** [comment]
Сложно догадаться. Лучше на главной странице настроек прозрачность сделать.. или прописать что "Параметр А" это прозрачность.
 Спасибо.
