### ISSUE TITLE
Ошибка Цвет фона не на весь экран

### ISSUE THREAD

**Issue by Pavel-111** [SBProX/SBProX-Dev#1025]
![Screenshot_26](https://user-images.githubusercontent.com/50700791/74928498-713de580-53fb-11ea-81a9-09df9a3e67b9.png)
![Screenshot_27](https://user-images.githubusercontent.com/50700791/74928505-73a03f80-53fb-11ea-9387-8993df16f2c4.png)

**Comment by Pavel-111** [comment]
При смене цвета фона цвет меняется не на всем экране

**Comment by Pavel-111** [comment]
Хоть бы ответили..

**Comment by SBProX** [comment]
У вас стоит настройка Chart Grid, это не ошибка вовсе.
Обратитесь в тех поддержку.
