### ISSUE TITLE
Forex пары

### ISSUE THREAD

**Issue by Aleksandr12321** [SBProX/SBProX-Dev#1029]
Добрый вечер, подскажите будет реализация форекс пар в платформе?

**Comment by Panica777** [comment]
Тикер 6E (евро доллара на форексе) 6B (фунт доллар) 6A ( австралийский доллар) Там ведь все написано

**Comment by Aleksandr12321** [comment]
Это мажоры-фьючерсы
Остальные пары будут??

**Comment by OlegT911** [comment]
фьючерсов на кросс пары не существует в природе, ну а  форекс здесь ни к чему

**Comment by Alexey316** [comment]
> 
> 
> фьючерсов на кросс пары не существует в природе, ну а форекс здесь ни к чему

Согласен

**Comment by SBProX** [comment]
Нет, форекса  точно не  будет
