### ISSUE TITLE
Изменения в индикатор или дополнительный индикатор за $

### ISSUE THREAD

**Issue by Search90** [SBProX/SBProX-Dev#1030]
1)Нужно внести дополнительные фильтры в индикатор Daily Delta Profile. 2)Либо отдельно мне написать индикатор за $. Если 2-е,то какова цена ? Индикатор прост в 3 пункта с изменяемыми параметрами.

**Comment by megatronsam** [comment]
проще добавить этот индикатор в виды алертов
а так дельта норм тема

**Comment by SBProX** [comment]
Мы не выполняем работу на заказ. 
Вы можете опубликовать ваши предложения, если они будут интересны, реализуем.
