### ISSUE TITLE
панель меньше можете сделать .

### ISSUE THREAD

**Issue by KingLeo82** [SBProX/SBProX-Dev#1031]
![2020-02-24_16-45-24](https://user-images.githubusercontent.com/56543849/75320222-362f2c80-58a9-11ea-886b-0ccc55baa61f.jpg)

**Comment by traderGoga** [comment]
Нормальная панель. Используйте Full HD и не будет проблем.

**Comment by SBProX** [comment]
Нет, не можем. Будет слишком мелко
