### ISSUE TITLE
Меню обрезается размером окна графика.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#104]
Здравствуйте.
Заметил особенность что если график максимально сужен, то меню (пр. кл. мыши) обрезается на размер окна.

![SBx Menu](https://user-images.githubusercontent.com/20509322/57693157-1d87ba00-767b-11e9-870d-83a52d2ed3ee.jpg)

**Comment by SBProX** [comment]
К сожалению такова техническая особенность платформы.
