### ISSUE TITLE
Динамический профиль. "Исчезаю-появляюсь"

### ISSUE THREAD

**Issue by SDRich** [SBProX/SBProX-Dev#1041]
В режиме ДЕЛЬТА, Линия с макс. бид/аск исчезает и появляется при масштабировании. Доставляет дискомфорт при анализе. Прошу учесть и принять меры. Благодарю.

**Comment by SBProX** [comment]
Уточните на каком инструменте, и вышлите пожалуйста скриншот.

**Comment by SDRich** [comment]
Натяните профиль на свечу, а для лучшей наглядности на свечу D1 и возникнут проблемы с "Линия с макс. бид/аск" в режиме ДЕЛЬТА.
Спасибо.

**Comment by SBProX** [comment]
Пробовали на 6E и на Si - все нормально, никакие линии не пропадают
Необходимо чтобы вы выслали скриншоты, или видео, чтобы мы могли у себя воспроизвести ошибку.
