### ISSUE TITLE
ОИ на Западные инструменты. Опционные уровни с CME.

### ISSUE THREAD

**Issue by SDRich** [SBProX/SBProX-Dev#1042]
Планируется ли активация ОИ на Западные инструменты.
Планируется ли включение в индикаторы Опционных уровней с CME. 

Спасибо.

**Comment by weeclemans** [comment]
вопросы можно задать в телеграм-группе
а тут можете оставить своё предложение, только распишите, как Вы это видите, более детально

**Comment by control63** [comment]
Поддерживаю! А также можно через коннектор рос.опционы в реальном времени

**Comment by SBProX** [comment]
ОИ на западные - нет, потому что ОИ нет в режиме реального времени на западные инструменты.
Опционы тоже нет. Если и будут опционы, то в виде отдельной платформы за отдельные деньги.

**Comment by SDRich** [comment]
Понял. Спасибо.
