### ISSUE TITLE
Разделитель периодов - цвета

### ISSUE THREAD

**Issue by TrickyBear** [SBProX/SBProX-Dev#1043]
Я использую светлую цветовую схему программы. Мне было бы удобно, чтобы полосы отличались друг от друга по цвету незначительно и при этом их цвет вверху и внизу был бы одинаковый. На графиках я рисую горизонтальные уровни-зоны - они являются самым важным элементом после графика цены. Нужно, чтобы разделитель периоднов был виден, но не бросался в глаза. 
Уважаемые разработчики, добавьте пожалуйста цвета для инструмента "Разделитель периодов", сделайте по 2 цвета для каждой вертикальной полосы - верхний и нижний. Кому нужно, сделают разные цвета.
На скрине хорошо видно, что вверху разделители не видны. Делать темнее не хочу, контрастные зоны будут мешать работе.

**Comment by TrickyBear** [comment]
![разделитель](https://user-images.githubusercontent.com/35699492/76775436-69811f00-67b6-11ea-8423-7b662e1f11d6.png)

**Comment by SBProX** [comment]
Просто настройте цвета разделителя близкие к цветам фона графика.
Не видим никакой проблемы в этом.
