### ISSUE TITLE
Настройка по времени RANGE диапазона 

### ISSUE THREAD

**Issue by Panica777** [SBProX/SBProX-Dev#1044]
Настройка по времени RANGE диапазона ( отметил красной линий для примера) Тоесть мне допустим интересен только тот участок . То есть растягиваю RANGE диапазон и задаю в настройках с 29,10.19 начала диапазона. Прилагаю скриншот. Поддержите коментами и лайками чтоб обратили внимание разработчики.
![Screenshot_1](https://user-images.githubusercontent.com/52234138/76938691-aa4d7500-6929-11ea-800a-4b4ba0a997f5.png)

**Comment by control63** [comment]
Поддерживаю!

**Comment by SBProX** [comment]
Можно просто нарисовать прямоугольник с нужного места.
