### ISSUE TITLE
Перемотка / прокрутка графика, с помощью колесика мыши, по оси X (время).

### ISSUE THREAD

**Issue by weeclemans** [SBProX/SBProX-Dev#1045]
Предлагаю добавить сабжевый функционал.

уточнения:
- по умолчанию установить перемотку графика с помошью колесика мыши;
- для ускорения перемотки графика добавить сочетание Ctrl + колесико мыши;
- для приближения / удаления графика использовать Shift/Alt + колесико мыши;

**Comment by SBProX** [comment]
Нам не нравится данная идея.
Перемещать график удобнее мышкой на наш взгляд
