### ISSUE TITLE
Ширина ценовых линий

### ISSUE THREAD

**Issue by yera217** [SBProX/SBProX-Dev#1049]
Не регулируется ширина линий (на кластерном графике), установленных двойным нажатием ЛКМ по ценовой шкале, хотя такой параметр ("Ширина") в настройках линии есть.  Есть ли возможность это исправить, чтобы можно было выставлять ценовые области в несколько тиков, а не только ценовые уровни шириной в один тик.

**Comment by iz0t0pe** [comment]
Ширина регулируется только если выбран свечной\баровый\линейный график и, к сожалению, толщина в пикселях.

**Comment by SBProX** [comment]
Да, верно. Толщина линий на кластерных графиков динамическая, в зависимости от масштаба.
Чтобы выделять ценовые области - есть инструмент Range.
Изучите более внимательно функционал платформы.
