### ISSUE TITLE
Опционные уровни CME.

### ISSUE THREAD

**Issue by weeclemans** [SBProX/SBProX-Dev#1052]
Предлагаю добавить функционал по отображению опционных уровней с использованием отчетов (commitment of traders reports — COT) с CME.
Свежие (предварительные) отчеты, в формате .pdf, выкладываются на ftp://ftp.cmegroup.com/bulletin/
Здесь инструкция по рассчету опционных уровней
https://binguru.net/opcionnye-urovni-cme-4521
http://strike.opentraders.ru/851.html
Там же можно найти ссылку на программу  OptL (для примера).
Ветка, где обсуждается использование опционных уровней в торговле фьючерсами https://forexdengi.com/threads/36446-optl-i-cmedb-programmi-dlya-rascheta-urovney-po-otchetam-cme?p=18138081
там же можно найти скриншоты с графиками на которых нанесены опционные уровни

алгоритм довольно прост:
1. Проверить наличие свежего предварительного отчета, скачать если имеется таковой по инструменту (к примеру CL);
2. Спарсить данные для рассчета опционных уровней;
3. Провести рассчеты;
4. Добавить данные в базу из которой пользовательский терминал будет брать данные для рисования опционных уровней.
и так по кругу, раз в 5-15 минут, в зависимости от того, как часто выкладывают свежие предварительные отчеты

P.S. заинтересованных в данном функционале прошу поддержать комментариями

**Comment by tarassar** [comment]
Поддерживаю, отличное дополнение!

**Comment by yera217** [comment]
Полностью поддерживаю

**Comment by Ravil124** [comment]
Поддержу.

**Comment by gios76** [comment]
++++

**Comment by sakom117** [comment]
поддержу

**Comment by alexgherco** [comment]
+++

**Comment by SBProX** [comment]
Если мы и будем делать анализ опционов, то это будет в виде отдельной платформы.
При текущей стоимости SBPro добавлять еще и анализ опционов - это финансово не выгодно нам.
