### ISSUE TITLE
баг

### ISSUE THREAD

**Issue by Pavel-111** [SBProX/SBProX-Dev#1056]
Сегодня, с начала новой недели цвет графика изменился.. И на других графиках цвет не меняется!!!!!!!!!!!!
![Screenshot_28](https://user-images.githubusercontent.com/50700791/77302644-77352800-6d13-11ea-9df5-be718242cd0f.png)
![Screenshot_27](https://user-images.githubusercontent.com/50700791/77302712-8e741580-6d13-11ea-8ac8-7a0653838136.png)

**Comment by Pavel-111** [comment]
B с каждой свечей он становится шире и шире

**Comment by Pavel-111** [comment]
> 
И с каждой свечей он становится шире и шире

**Comment by Pavel-111** [comment]
![Screenshot_29](https://user-images.githubusercontent.com/50700791/77501267-50910180-6e79-11ea-8a6e-d102b8d90917.png)
Вы решите эту проблему? меняю цвет фона на белый, где график цвет не меняется!!!!!!!!!!!!
решите вопрос...

**Comment by SBProX** [comment]
Напишите пожалуйста в support:

support@sb-professional.com
Telegram: @sbprosupport

**Comment by Pavel-111** [comment]
Я вчера отправлял письмо
в support:
support@sb-professional.com

  
>Четверг, 2 апреля 2020, 20:15 +05:00 от SBPro X <notifications@github.com>:
> 
> 
>Напишите пожалуйста в support:
>support@sb-professional.com
>Telegram:  @sbprosupport
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Павел Рожнов

**Comment by SBProX** [comment]
Скорее всего вы поставили какие-то настройки в платформе. Сам по себе график не может раскашиваться в произвольные цвета. 
Вам в саппорте ничего не ответили?

**Comment by SBProX** [comment]
У вас случайно разделитель периодов не стоит?
Вы просто включили какую-то настройку, и теперь пишете что это баг.
Такого бага просто быть не может.

**Comment by SBProX** [comment]
Связались с тех. поддержкой, нам сказали что у вас был включен разделитель периодов.
Тикет закрываем, будьте внимательнее.

**Comment by Pavel-111** [comment]
Доброе утро! Долго грузятся графики. Комп вроде нормальный

  
>Пятница, 3 апреля 2020, 13:18 +05:00 от SBPro X <notifications@github.com>:
> 
> 
>Closed  #1056 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Павел Рожнов
