### ISSUE TITLE
профиль рынка

### ISSUE THREAD

**Issue by salsa322** [SBProX/SBProX-Dev#1058]
здравствуйте, сделайте так чтобы продлевающийся поинт "динамического профиля" продлевался только до цены которая его коснулась в будущем и дальше не продолжался, чтобы весь график не был забит линиями поинтов и было точно видно где именно происходила отработка поинта. пример на скриншоте!

![profile](https://user-images.githubusercontent.com/46971427/77670041-b3c48600-6f96-11ea-832b-64d4f2a41618.png)

**Comment by SBProX** [comment]
Добрый день.

Мы не может это сделать, это слишком сложно.
Анализировать где рынок коснулся или не коснулся - извините.
