### ISSUE TITLE
Разница в Данных на графике и в Price rating

### ISSUE THREAD

**Issue by Basicprof** [SBProX/SBProX-Dev#1060]
1.Кто может объяснить ,может что не так понимаю. Максимальный объем за период 04,06,2019 - 10,09,19  по 6E  = 147195 по цене 1.1084 в **Price rating** а на графике максимальный **volume Prifile** 81810 =  по цене 1,1274 за тот же период .  Чтож правильно? https://ibb.co/JFYwMmX
https://ibb.co/bK37NXz
2. Price rating = Ставлю период День Дата с 03.06,2019 = по 07.06.2019  Откуда в результатах появляется даты вне этого периода например 2020 .02.19 https://ibb.co/C0yCHkT

**Comment by SBProX** [comment]
Да, действительно есть ошибка, исправим.

**Comment by SBProX** [comment]
Исправили ошибку в Price Rating, будет работать в ближайших обновлениях
