### ISSUE TITLE
Толщина линий уровней на графиках

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#1063]
Здравствуйте! Не меняется толщина линий уровней на графиках западных инструментов: что 1, что 5 - толщина одинаковая. Было бы хорошо, чтобы менялась. На российском рынке всё хорошо - толщина меняется в соответствии с заданным числом. Спасибо!

**Comment by SBProX** [comment]
Какой тип графика при этом стоит? (на котором не меняется)

**Comment by Dmitry1970** [comment]
![2020-03-31_14-09-20](https://user-images.githubusercontent.com/35344271/78265487-2ab8cc00-750d-11ea-889c-7982979a96ed.jpg)

**Comment by SBProX** [comment]
На кластерных графиках толщина линии динамическая, она не настраивается. Толщина меняется при масштабировании графика
