### ISSUE TITLE
Не работает Rating.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#1064]
Здравствуйте.
Не работает Rating в режиме Bid-ask Difference и вкл. режиме Volume rating with bid-ask.

- Параметр Rating в котором меняют размер фигур сбрасывается по дефолту.... т.е. размер кружков (клаудов) при таких настройках всегда одинаковый.

![Безымянный](https://user-images.githubusercontent.com/20509322/78146629-fd184800-7464-11ea-8106-534d1fd1508c.jpg)

**Comment by SBProX** [comment]
Вы не правильно настраиваете рейтинг.
В режиме bid-ask значение рейтинга может быть от 0 до 100 (в процентах).
250 - работать не будет.

**Comment by Fen8fen** [comment]
> Вы не правильно настраиваете рейтинг.
> В режиме bid-ask значение рейтинга может быть от 0 до 100 (в процентах).
> 250 - работать не будет.

1. Включите Bid/Ask Difference
2. Включите Volume rating with bid-ask
3. попробуйте менять значение в поле Rating.

**Comment by SBProX** [comment]
Понятно, извините.
Проверим

**Comment by SBProX** [comment]
Исправлено, будет работать в ближайших обновлениях

**Comment by Fen8fen** [comment]
Здравствуйте. Обновление 4.1.69
Ошибка исправлена?
