### ISSUE TITLE
Индикатор экстремумов дня

### ISSUE THREAD

**Issue by JohnW32** [SBProX/SBProX-Dev#1072]
Доброго времени,
предлагаю сделать индикатор, показывающий экстремумы текущего и вчерашнего дня с постоянным обновлением, чтобы при обновлении ценой экстремума текущего дня данный экстремум перерисовывался на новый.
Форма отображения - простая линия от экстремума до правой части графика.
Также удобно, если поставить сигнал оповещения за несколько пунктов до подхода ценой к линии экстремума.
Благодарю

**Comment by Vegas3737** [comment]
Экстремумы предыдущего дня линиями цветовыми и уровень открытия текущего дня с настройками времени например по бренту на айсе там профиль начинается с 00-00 а мне нужно открытие торговой европейской сесии с 10-00 мск или по америке с 17-30 например

**Comment by SBProX** [comment]
Глазами видно все экстремумы, не видим смысла нагружать платформу не профильным функционалом
