### ISSUE TITLE
Название индикатора. (ошибка)

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#1081]
![image](https://user-images.githubusercontent.com/20509322/78616728-9c936b80-78a7-11ea-9247-8825dbbd1653.png)

![image](https://user-images.githubusercontent.com/20509322/78616849-10357880-78a8-11ea-93b0-5e65953aec3b.png)
- Здравствуйте.
Если сдвинуть индикатор на один слой вверх (скриншот №2), и добавить новый индикатор то случится ситуация как на (скриншоте №1).

**Comment by Fen8fen** [comment]
- Добавлю.

 В ситуации на скриншоте.
- перестает работать знак (глаз) на графике не исчезают фигуры. Только через удаление индикатора.
- индикаторы перестают перемещаться вверх - вниз (стрелки)

**Comment by SBProX** [comment]
Хм, спасибо большое. Завтра обязательно проверим. Досадная ошибка

**Comment by SBProX** [comment]
Исправлено, будет работать с следующих обновлениях
