### ISSUE TITLE
Предлагаю на расмотрение добавить к total Volume 

### ISSUE THREAD

**Issue by Vegas3737** [SBProX/SBProX-Dev#1086]
Предлагаю на расмотрение добавить к total Volume 
функцию
ТОЛЬКО при сигнале фильтра всплеска большого обьема высветить данные по конкретно зафильтровавшейся свече информацию - ВО СКОЛЬКО РАЗ ОБЬЕМ ДАННОЙ СВЕЧИ БОЛЬШЕ ЧЕМ СРЕДНИЙ ОБЬЕМ ПЯТИ ПРЕДЫДУЩИХ СВЕЧЕЙ? 
Либо во сколько раз либо в % отображении к среднему арифметическому сумме 5ти последних свчей  

Описание в скрине    

http://SSMaker.ru/53917128/

**Comment by SBProX** [comment]
Это уже перебор, мы не хотим на такое тратить время программистов, извините
