### ISSUE TITLE
Уменьшить панель рисования. 

### ISSUE THREAD

**Issue by affectus1** [SBProX/SBProX-Dev#1087]
Добрый день! Большая просьба уменьшить панель рисования вдвое для использования малых окон совсем не удобно. Постоянно разворачивать и сворачивать. Либо убрать ее на сам экран в виде кнопки разворота как у волфикса. 
![1](https://user-images.githubusercontent.com/51283220/78864525-f93c8500-7a65-11ea-8a46-84f2268cce2b.png)

**Comment by Vegas3737** [comment]
А пользоваться горячими клавишами не пробовали не открывая эту панель вообще? Я именно так и пользуюсь

**Comment by affectus1** [comment]
Нет но попробую)

**Comment by test-777** [comment]
согласен с предыдущим автором. Использую горячие клавиши - и не открывал эту панель уже месяц точно. Можно не тратить на это время разработчиков и дать им сконцентрироваться на более актуальных задачах.

**Comment by SBProX** [comment]
@affectus1 Панель и так небольшая, делать её ещё меньше не предоставляется возможным.
