### ISSUE TITLE
Как закрасить прямоугольник?

### ISSUE THREAD

**Issue by Panica777** [SBProX/SBProX-Dev#1093]
Как закрасить прямоугольник?
![Screenshot_3](https://user-images.githubusercontent.com/52234138/79061719-0acb9a00-7cbd-11ea-929e-ecaf09839817.png)

**Comment by Quantum-G** [comment]
Выделить объект - редактирование цвета - уменьшить прозрачность

**Comment by Panica777** [comment]
Где вы нашли редактирование цвета? Можно скрин?

**Comment by Quantum-G** [comment]
![image](https://user-images.githubusercontent.com/34577071/79158794-a35a3b00-7ddf-11ea-83bd-2879227ecece.png)

**Comment by SBProX** [comment]
По всем вопросам обращайтесь в техническую поддержку
