### ISSUE TITLE
настройки

### ISSUE THREAD

**Issue by Janna-Janna** [SBProX/SBProX-Dev#1095]
Добрый день.
 
1. Часто, цвет линий не дублируется в линкованных вкладках, то есть, если на часовом графике линия красная, на остальных по умолчанию чёрная. Как исправить?

2.При использовании симулятора, не работает команда «удалить все рисунки». Как исправить?

**Comment by SBProX** [comment]
Добрый день.

1. Опишите подробнее порядок ваших действий, не понятно 

2. Проверим

**Comment by Janna-Janna** [comment]
Добрый день.
*  цвета линий не дублируются на линкованных вкладках разных тайм-фреймов одного актива. Уточню, прошло обновление винды, заработало, но на симуляторе по прежнему не дублирует цвета.
*  Разобралась, «удалить все рисунки» работает, только те что в инструментах, а урони не удаляет, я считала, что уровни тоже рисую поэтому решила, что не работает. Сразу прошу взять на заметку добавление функции «удалить уровни (все уровни)», так как каждый день обновляются уровни, хотя не критично.          
Спасибо. 
>Вторник, 14 апреля 2020, 2:45 +03:00 от SBPro X <notifications@github.com>:
> 
> 
>Добрый день.
>* 
>Опишите подробнее порядок ваших действий, не понятно
>* 
>Проверим
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением Жанна Мин.

**Comment by SBProX** [comment]
Принято

**Comment by Janna-Janna** [comment]
Добрый день.
*  цвета линий не дублируются на линкованных вкладках разных тайм-фреймов одного актива, при использовании симулятора
