### ISSUE TITLE
Долгая загрузка истории! невозможно переключаться между тайм-фреймами

### ISSUE THREAD

**Issue by Kyrylo12345678** [SBProX/SBProX-Dev#1096]
Невозможно переключаться на одной вкладке с дневки на часовик и т.д., никто ведь не анализирет историю в рамках одной недели!. Весь анализ это работа на дневках с последними 10 годами, и нужно при анализе переключаться с дневки на часовик, на одном графике.
Ни на одной платформе нет таких проблем, мт4,5, quik, xtick, 

это история, и она не меняется, зачем ее в течении дня снова и снова подгружать, одно и тоже, глупость и неудобство.
Просьба решить проблему,

**Comment by SBProX** [comment]
SBPro это не метатрейдер с барами, а платформа для анализа объемов.
Не нужно сравнивать разный софт.
При переключении на другой ТФ, данные необходимо перерасчитывать, так как меняются показатели объемов.

Вы можете заранее загрузить и настроить нужный вам графики, и переключаться между вкладками.
