### ISSUE TITLE
Проблема с отображением графика на D1

### ISSUE THREAD

**Issue by BasileNT** [SBProX/SBProX-Dev#11]
Как была проблема с отображением графика D1 в прошлой версии так она и осталась, хотя обещали решить эту проблему. Решите пожалуйста вопрос с часовыми поясами, для корректного отображения информации.

**Comment by SBProX** [comment]
Мы пока не понимаем о какой проблеме идет речь.
На Day отображение корректное, в соответствие с тем часовым поясом, который выбран в платформе для конкретного инструмента.

Опубликуйте пожалуйста скриншот, на котором видна суть проблемы.

**Comment by alex12mosk** [comment]
Базилик, в настройках графика нужно выставить правильный часовой пояс и все будет ок

**Comment by SBProX** [comment]
Вопрос решен? Если да, закройте тикет.
