### ISSUE TITLE
авто передвижение графика

### ISSUE THREAD

**Issue by koroniova** [SBProX/SBProX-Dev#110]
при включенном передвижении графика вперед когда  передвигаешь график мышью  хоть на миллиметр авто передвижение графика вперед отключается. в старой версии отключалось только когда график передвигаешь мышью назад и текущий бар становился не виден на экране.
сейчас чуть мышью дернешь и опять надо нажимать кнопку включения авто прокрутки графика

видео:
https://drive.google.com/open?id=0B8khzpYINaRFd0puWllHOU15QnBnWmxzdGJUREpsdlo1YURZ

**Comment by SBProX** [comment]
Спасибо, завтра проверим.

**Comment by SBProX** [comment]
Исправлено, будет работать в след. обновлении.
