### ISSUE TITLE
Копирование объектов

### ISSUE THREAD

**Issue by valeriandigital** [SBProX/SBProX-Dev#1104]
Просьба сделать нормальное копирование объектов, через alt или ctrl. В настоящее время копирование работает с ошибкой, если нажимаешь ctrl+c и сразу ctrl+v то ничего не вставляется, пока не сделаешь левый клик мыши в раб. область.

**Comment by SBProX** [comment]
В версии которую мы собираемся выложить, все работает нормально. 
Проверите после обновления

[bandicam 2020-05-19 13-47-55-716.zip](https://github.com/SBProX/SBProX-Dev/files/4649895/bandicam.2020-05-19.13-47-55-716.zip)
