### ISSUE TITLE
Выгрузка данных

### ISSUE THREAD

**Issue by e2e4Konstantin** [SBProX/SBProX-Dev#1105]
Можете сделать выгрузку данных? Бывает очень нужно для анализа. 
Например выгрузить тиковых данных по инструменту XX за период 25.01.2020 - 26.02.2020 в файл aaa.xls. может найдете такую возможность? может за небольшую плату?

**Comment by traderGoga** [comment]
Я тоже "за", только не в xls, а в более абстрактный формат, типа CSV или TXT...
Я случайно создал похожую тему. Видимо не зря ))

**Comment by e2e4Konstantin** [comment]
в принципе в системе уже есть отличный механизм "рейтинг цен",  но с этими данными надо еще возиться. программисту надо 20 минут что бы модифицировать уже готовый механизм под выгрузку тиковых данных.
![image](https://user-images.githubusercontent.com/60742420/80181490-a4743f00-860d-11ea-9209-db623555e688.png)

**Comment by traderGoga** [comment]
в рейтинге нет открытия и закрытия свечей, бидов и асков, а это важная информация

**Comment by e2e4Konstantin** [comment]
согласен. но это уже готовый механизм и затраты для нового сервиса минимальны.

**Comment by traderGoga** [comment]
Конечно, это тоже подходит, достаточно добавить более подробную информацию.

**Comment by SBProX** [comment]
Выгрузку или экспорт данный мы делать не будем.
