### ISSUE TITLE
Симулятор доработайте пожалуйста

### ISSUE THREAD

**Issue by Janna-Janna** [SBProX/SBProX-Dev#1109]
Добрый день, при использовании симулятора, цвета линий не дублируются в линкованных  вкладках. Прощу рассмотреть этот вопрос.
![11](https://user-images.githubusercontent.com/63582167/79748657-9da8ac00-832f-11ea-9e18-7f59c7030650.jpg)
![22](https://user-images.githubusercontent.com/63582167/79748662-9ed9d900-832f-11ea-8f44-e03e3a43f58f.jpg)
![33](https://user-images.githubusercontent.com/63582167/79748665-a00b0600-832f-11ea-88e5-7e40e64e3d79.jpg)

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
