### ISSUE TITLE
Сдвиг графиков при корреляции РТС с западными инструментами

### ISSUE THREAD

**Issue by Genallll** [SBProX/SBProX-Dev#1113]
Здравствуйте.
Есть интерес использовать коррелятор.
Основной актив РТС, корреляция с S&P 400 (EMD)
Графики имеют сдвиг на час и по шкале. Сдвиг и в начале дня и автоматически западный график идет с лагом в один час впереди РТС. Подобное расхождение и со многими другими инструментами американского 
![2020-04-09](https://user-images.githubusercontent.com/64131848/79963116-a31e0780-8491-11ea-89b2-76da6c86ed31.jpg)
рынка. Высылаю скрин. Нельзя ли подправить синхронизацию.
Спасибо.

**Comment by Genallll** [comment]
Как вариант решения этой проблемы дать возможность сдвигать любой график по шкале времени в одну или другую сторону ручками в кореляторе. Это разумно потому, что одни пары имеют лаг в час, другие нет. Боюсб что получиться, что в одном месте появиться синхронизация, а в другом расстроиться.

**Comment by SBProX** [comment]
Это явная ошибка, посмотрим в чем проблема.

**Comment by SBProX** [comment]
Спасибо, исправили. 
Будет работать в сл. обновлении.
