### ISSUE TITLE
Ошибка в формировании календаря

### ISSUE THREAD

**Issue by alekskdr** [SBProX/SBProX-Dev#1116]
В форме выбора даты нельзя быстро сменить диапазон годов. Постоянно выводятся года с 2019.
![2020-04-27_16-30-48](https://user-images.githubusercontent.com/574014/80378172-eec31d80-88a4-11ea-914c-bcd4e26c7de6.png)

**Comment by SBProX** [comment]
Календарь мы поменять не можем, это сторонний компонент.
