### ISSUE TITLE
Ошибка отображения на широкоформатном мониторе

### ISSUE THREAD

**Issue by alekskdr** [SBProX/SBProX-Dev#1117]
Если нажать кнопку "Развернуть на весь экран" на широкоформатном мониторе, то обрезается чать окна спарва и снизу. Параметры железа:
Windows 10
Монитор 2560x1080 с масштабированием 100% (при масштабировании 150% всё отображается правильно)
![2020-04-27_16-36-30](https://user-images.githubusercontent.com/574014/80378587-8e80ab80-88a5-11ea-99a4-f39c51a8e52d.png)

**Comment by test-777** [comment]
Тоже бывали такие глюки,  помогает обычно переход в оконный режим.
![изображение](https://user-images.githubusercontent.com/18189627/80384627-cbe93700-88ad-11ea-8c68-d57ee224ac8d.png)

**Comment by alekskdr** [comment]
в оконном режиме всё растягивается как надо, но указал именно на ошибку с разворачиванием на весь экран. в коде явно баг с подгонкой под стандартное расширение 1920x1080

**Comment by SBProX** [comment]
Никакой подгонки нет, окна в SBPro это отдельные компоненты Telerik - будем им писать и выяснять почему так ведут себя окна при разворачивании.

**Comment by SBProX** [comment]
У нас кстати тоже мониторы широкоформатные, но такой проблемы нет

**Comment by alekskdr** [comment]
после обновления проблема исчезла
