### ISSUE TITLE
Будут ли добавлены акции?

### ISSUE THREAD

**Issue by ziplan** [SBProX/SBProX-Dev#1118]
Здравствуйте. Прекрасный софт сильно ограничен невозможностью анализировать акции. Планируется ли ввести акции МБ в программу?

**Comment by OlegT911** [comment]
Обещали сделать
![2020-04-28 01 33 58](https://user-images.githubusercontent.com/60439200/80427423-5e122f00-88f0-11ea-8077-95f7034e8a2f.jpg)

**Comment by Centr27** [comment]
?

**Comment by QuasarCpt** [comment]
В апреле-мае месяце будут подключены акции NYSE (50-100 наиболее ликвидных акций ).
Вот еще в телеграм канале оповещение было

**Comment by Milishnikoff** [comment]
Все очень ждем!!! Сориентируйте по времени хотя бы.

**Comment by SBProX** [comment]
С акциями пока есть загводки определенные, так как нужно под них адаптировать много чего в платформе. Как только сделаем мы сообщим.
