### ISSUE TITLE
Симулятор - профит-фактор

### ISSUE THREAD

**Issue by ProgramGun** [SBProX/SBProX-Dev#1119]
Привет, так как я заметил что разработчики работают с симулятором. 
Хотел бы предложить что бы добавили подсчет профит-фактор.
Также могу предложить и другие параметры как на скрине. 
<img src="https://i.ibb.co/kgC8Lnb/ok1.jpg" alt="ok1" border="0">
Возможно это не такой сложный таск, расчет по формуле - но ооочень полезный.

**Comment by SBProX** [comment]
Уже добавили, будет в сл. обновлении.
