### ISSUE TITLE
Тестер стратегий

### ISSUE THREAD

**Issue by Gaidar1994** [SBProX/SBProX-Dev#112]
Здравствуйте, подскажите пожалуйста есть ли в данной версии программы возможность в тестере переключаться между таймфреймами? К примеру основной таймфрейм у меня М5 но вход я делаю на С10, следовательно хотелось бы когда я увидел какой-либо сетап на М5 перейти на С10 и уже войти по формациям на этом таймфрейме. Если такой возможности переключения между таймфреймами во время тестирования стратегии нет прошу добавить.

**Comment by SBProX** [comment]
Нет переключаться нельзя.
Добавить не можем, так как тайм фрейм зафиксирован после старта симулятора.
Открывайте тогда 2 графика с разными ТФ, это решит проблему.
