### ISSUE TITLE
Симулятор - побарный сдвиг вперед/назад, hotkeys, сдвиг по времени

### ISSUE THREAD

**Issue by implight** [SBProX/SBProX-Dev#1121]
Добрый день! Рассмотрите возможность доработки симулятора со следующим функционалом:
1. Побарное проигрывание вперед и отмотка назад
2. При начале нового дня возможность сдвинуться по времени вперед, например, пропустить азиатскую сессию или вечернюю на фортс
3. Hotkeys на страт/пауза, побарный сдвиг
4. Побарную промотку назад и возможность отмотать время назад, если такое возможно. Иногда бывает какую-то ситуацию проморгаешь и хочется ее еще раз пересмотреть без перезапуска симулятора с самого начала.

**Comment by Vegas3737** [comment]
Поддерживаю друзья сделайте это уже наконец ! У вас отличный симулятор ,но нужно довести до ума

**Comment by alekskdr** [comment]
Поддерживаю, был удивлён отсутствию таких нужных элементов в симуляторе.

**Comment by SBProX** [comment]
Добрый день.

Побарное уже добавили - будет в сл. обновлении.
Hot keys - включим в список на реализацию.

Промотку назад сделать не получится. По сессиям - тоже.
