### ISSUE TITLE
ТЕКСТ  HLOC Не виден  на большой резолюции экрана 3840*2160 43" **портит зрение, не могу работать** 

### ISSUE THREAD

**Issue by kristinmalkin** [SBProX/SBProX-Dev#1122]
Не виден текст HLOC на большой резолюции экрана 3840*2160 43"
Текст не виден, **портит зрение, не могу работать,** 

Просьба опустить текст на нижнюю часть экрана или бара и увеличить текст пропорционально резолюции. Для меня ошибка критическая не могу работать,
![43](https://user-images.githubusercontent.com/64530665/80588292-bfd1b680-8a20-11ea-84e4-aba81476b367.jpg)
![2020-04-29_12-55-54](https://user-images.githubusercontent.com/64530665/80588295-c19b7a00-8a20-11ea-82a6-7df0543c1d90.jpg)

**Comment by kristinmalkin** [comment]
На снимках разница между экранами, на верхней 43" текст не виден, мне нужно приближаться к экрану на расстояние 20см. Что бы увидеть текст. Другого экрана уже нет.

**Comment by Mihaliych** [comment]
плюсую, у меня разрешение 5120×2880, шрифты много где некомфортные по размеру для чтения. При работе на ноуте разрешением 1920х1080 все гораздо приятней в этом плане выглядит

**Comment by Janna-Janna** [comment]
++++ на эту тему я уже писала тикет "HLOC"

**Comment by SBProX** [comment]
Исправили, будет работать в сл. обновлении.
