### ISSUE TITLE
Правописание

### ISSUE THREAD

**Issue by Janna-Janna** [SBProX/SBProX-Dev#1126]
Добрый день.
 В симуляторе ошибка правописания, ВАЖНОСТЬ низкая
![Inked11_LI](https://user-images.githubusercontent.com/63582167/80717935-51bdea00-8b1b-11ea-97d2-122d5b7d395f.jpg)
, но всё же.
 
С уважением Жанна

**Comment by SBProX** [comment]
Добрый день.

Уже исправили, будет в обновлении.
Спасибо
