### ISSUE TITLE
Нет прозрачности.

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#1131]
На скрине видно что при включённой прозрачности гистограмма закрывает график:

![Screenshot_1](https://user-images.githubusercontent.com/33456972/81274043-372ec800-9069-11ea-95f2-082249619c74.png)

При любых настройках прозрачность не работает в данном профиле. В остальных индикаторах с прозрачностью всё нормально. Исправьте, плиз.

**Comment by SBProX** [comment]
Это не ошибка, если значение попадает под фильтр, то прозрачность определяется автоматически, исходят из величины объема. Иначе бы крупные значения были бы такие же прозрачные, как и все остальные, и никак бы не выделялись.
