### ISSUE TITLE
Ошибка отрисовки графика и индикаторов в отдельных панелях.

### ISSUE THREAD

**Issue by alekskdr** [SBProX/SBProX-Dev#1133]
Происходит наложение графика на области индикаторов, хотя по логике график должен скрываться за этими областями. Пример наложений выделил на скриншотах. Тестировала на разных мониторах с разным разрешением экрана.
![2020-05-08_8-41-46](https://user-images.githubusercontent.com/574014/81375326-f5099300-9109-11ea-9f7d-85982e83b7f4.png)
![2020-05-08_8-48-54](https://user-images.githubusercontent.com/574014/81375329-f63ac000-9109-11ea-9567-cdce3f3ad725.png)

**Comment by X-man77** [comment]
Настройки графика -> основные настройки -> прочее -> внизу раздел "Indicators" ставим галку в чек-боксе "Индикаторы над графиком" и будет вам счастье. 

А вообще почаще в мануал заглядывайте и изучайте мат.часть.
