### ISSUE TITLE
Версия не обновляется 

### ISSUE THREAD

**Issue by nopsynops** [SBProX/SBProX-Dev#1136]
Добрый день, подскажите мне пожалуйста, что с моей версией SBProX 4.1.72 не так. Все обновления у меня не появились ну например Fibo без изменений, нет быстрых кнопок (Header Buttons settings), нет новых звуков.

<img width="732" alt="Fibo" src="https://user-images.githubusercontent.com/55189306/81479083-7d2e8c00-9221-11ea-8195-1e1b2853499b.png">

<img width="655" alt="Head Buttons Settings" src="https://user-images.githubusercontent.com/55189306/81479084-828bd680-9221-11ea-885f-388c1a4a1dd8.png">

**Comment by nopsynops** [comment]
Добрый день, подскажите почему у меня нет таких обновлений как на Рис.

<img width="1177" alt="Screenshot_1" src="https://user-images.githubusercontent.com/55189306/82218481-3d9c2a00-991c-11ea-9309-9850845ef826.png">

**Comment by SBProX** [comment]
Добрый день.

Это обновление еще не выложено!
Мы писали на Telegram канале.
