### ISSUE TITLE
Симулятор доработать

### ISSUE THREAD

**Issue by Janna-Janna** [SBProX/SBProX-Dev#1137]
Добрый день. Спасибо за Ваш труд. 
1. Прошу Вас рассмотреть возможность доработки симулятора, в виде добавления возможности отката назад проработанного графика.  Например если проглядел сделку, но заметил это позже, проще откатить чем перегружать график снова, чтобы разобраться в деталях.
2.  Прошу доработать выставление уровня стоп-лосс
![тикет](https://user-images.githubusercontent.com/63582167/81890329-92137280-95c7-11ea-9679-d9a63eb06f5a.jpg)

**Comment by SBProX** [comment]
Добрый день.

Первый пункт сделать невозможно, это сложно.
Второе со временем добавим.
