### ISSUE TITLE
there is a delay on the sbpro of 5 min. so it is not a good thing. I lost a trade because of the sbpro

### ISSUE THREAD

**Issue by Moapsy99** [SBProX/SBProX-Dev#1139]
there is a delay on the sbpro of 5 min. so it is not a good thing. I lost a trade because of the sbpro
![image](https://user-images.githubusercontent.com/52650303/82060526-d25a1a00-96c7-11ea-9ba4-c947185c4bf4.png)

**Comment by test-777** [comment]
Подскажите что за настройки позволяют отображать часть кластеров в сером цвете ? (и по какому принципу действует данная фильтрация)
