### ISSUE TITLE
Save Default

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#114]
Здравствуйте.
Не работает кнопка Save Default. Сохраняю с одними настройками загружает с другими.....
![savedefault1](https://user-images.githubusercontent.com/20509322/57823518-6d28cb80-77ca-11e9-9f62-c0b8a69036cd.jpg)

**Comment by SBProX** [comment]
Исправлено, будет работать в ближайшем обновлении.
