### ISSUE TITLE
Chart Grid не работает на тиковом графике

### ISSUE THREAD

**Issue by pavloreva** [SBProX/SBProX-Dev#1142]
На тиковом графике теряется ощущение времени, поскольку тиковый график отрисовывается по тикам. Иногда за секунду пройдет сотня тиков, а иногда всего один. Хотелось бы иметь привязку тиков ко времени. Постоянно сверятся по шкале времени внизу нереально.
Если бы Chart Grid работал на тиковом графике, то решило бы эту проблему. 

Сделайте, пожалуйста, поддержку Chart Grid на тиковом графике или предложите другой вариант решения.

Спасибо.

**Comment by SBProX** [comment]
Исправили ошибку с ChartGrid на тиковом графике.
Скоро выложим обновление.
