### ISSUE TITLE
Возможность добавить профиль по дельте по таймфрейму

### ISSUE THREAD

**Issue by cress80** [SBProX/SBProX-Dev#1143]
Аналогичная функция уже есть, но только с объемом. Не всегда можно понять что проходит в свече на данном объеме. При добавлении профиль дельта по таймфрейму можно четко отслеживать все изменения, особенно на тенях свечей когда идет работа маркетов против лимиток. И в самих свечах, когда идет поглощение, здесь уже масса вариантов откроется для многих. 
![Screenshot_1](https://user-images.githubusercontent.com/65598178/82314808-050b5780-99d3-11ea-8e8c-f5d4e2b11bf2.png)

**Comment by SBProX** [comment]
В SBProV2 мы не будем добавлять в ближайшее время новые графики или индикаторы
