### ISSUE TITLE
Прозрачность профилей.

### ISSUE THREAD

**Issue by aledzander** [SBProX/SBProX-Dev#1147]
Предлагаю добавить в настройки возможность регулировать прозрачноость профилей (дневной, недельный, динамический) потому что они перекрывают не только друг друга но и ценовой график. На рисунке надеюсь видно.
![пример](https://user-images.githubusercontent.com/65729671/82591436-02ae2680-9ba8-11ea-82d2-3f2703a72dbd.jpg)

**Comment by SBProX** [comment]
Прозрачность можно регулировать в настройках самого цвета гистограммы.
Рекомендуем ознакомиться с инструкцией
