### ISSUE TITLE
разные биржевые данные

### ISSUE THREAD

**Issue by zionist585** [SBProX/SBProX-Dev#1154]
данные в sbproX и sbpro биды, аски различаются в платформах, соответственно дельта также другая считается, коннектор SbproX - Sbpro

![image](https://user-images.githubusercontent.com/18281935/82782276-2b733c00-9e86-11ea-9a31-979158d46993.png)

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by zionist585** [comment]
![image](https://user-images.githubusercontent.com/18281935/83159837-a5c6e900-a130-11ea-95be-b96e516343c2.png)

**Comment by zionist585** [comment]
![image](https://user-images.githubusercontent.com/18281935/83162887-90ec5480-a134-11ea-9dcc-d194eef9b867.png)
