### ISSUE TITLE
Прекращение обслуживания V2!!!

### ISSUE THREAD

**Issue by indianaxxx** [SBProX/SBProX-Dev#1156]
С учётом последнего объявления о предстоящем факте прекращения функционирования платформы V2, и ранее заявлении администрации, что версия V2 продолжит своё существование с последующими обновлениями, ПРЕДЛАГАЮ: для владельцев имеющих одновременно версии SBPro V2 и SBProX с 01 июля 2020 года предоставить бесплатную возможность регистрации ещё одного аккаунта платформы SBProX взамен утраченной V2.  
p.s. За период параллельного существования (функционирования) двух платформ, наличие возможности использования двух платформ в один промежуток времени одновременно зарекомендовала себя с положительной стороны. В моём случае, старшая дочь познаёт азы торговли и анализа. И у меня нет никакого желания с 1 июля начинать с ней делить один аккаунт выбирая между моей реальной торговлей и анализом ради обучения.

**Comment by vitekkz** [comment]
Согласен.какая то компенсация должна быть!!!

**Comment by Highlander264** [comment]
Поддерживаю,это было бы справедливо

**Comment by Quantum-G** [comment]
У меня тоже есть V2, я ей не пользуюсь. Ну и что теперь. Платформа копейки стоит, с бесплатным data. Что вы ворчите, господа?

**Comment by vitekkz** [comment]
> У меня тоже есть V2, я ей не пользуюсь. Ну и что теперь. Платформа копейки стоит, с бесплатным data. Что вы ворчите, господа?

А я пользуюсь у меня слабый ноут и что теперь?

**Comment by NikolaiBogachev** [comment]
> У меня тоже есть V2, я ей не пользуюсь. Ну и что теперь. Платформа копейки стоит, с бесплатным data. Что вы ворчите, господа?

Данный пост поддерживаю руками и ногами если был бы хвост и хвостом тоже :)

**Comment by Ravil124** [comment]
Поддерживаю.
