### ISSUE TITLE
Ошибки в отображении дельты

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1159]
![2020-05-28_17-20-52](https://user-images.githubusercontent.com/18483236/83154831-443f5400-a109-11ea-868f-242e2d0540f7.png)
![2020-05-28_17-24-48](https://user-images.githubusercontent.com/18483236/83154845-473a4480-a109-11ea-8a51-20f0c7862c5f.png)
![2020-05-28_17-29-05](https://user-images.githubusercontent.com/18483236/83154852-4a353500-a109-11ea-8ea0-41152725065e.png)
![2020-05-28_17-31-14](https://user-images.githubusercontent.com/18483236/83154868-4e615280-a109-11ea-8c13-192ec7279914.png)

**Comment by SBProX** [comment]
Принято, в ПН проверим и поправим.

**Comment by SBProX** [comment]
Исправлено, будет работать в обновлении которое выйдет 10 июня
