### ISSUE TITLE
Ошибки отображения фильтрованного графика

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1162]
Стоит фильтр min tick=20. Откуда взялось столько объема сверху?
![2020-05-29_10-17-22](https://user-images.githubusercontent.com/18483236/83232467-e573ec00-a195-11ea-9cdb-0685c38c2081.png)

**Comment by SBProX** [comment]
Принято, исправим

**Comment by SBProX** [comment]
Исправили, будет работать в обновлении которые выйдет 10 го числа.
