### ISSUE TITLE
Уровни сделать примагничивающимися

### ISSUE THREAD

**Issue by vomma-opt** [SBProX/SBProX-Dev#1165]
Добрый день, спасибо за замечательную программу SbproX прошу сделайте уровни магнитными, чтобы при построении когда их подводишь к хай или лоу бара, автоматически уровень примагничивался к high/low бара. Заранее благодарю!
![Магнитные уровни](https://user-images.githubusercontent.com/66114479/83241588-7954b080-a1b4-11ea-92c1-b5e3cb2e3361.jpg)

**Comment by SBProX** [comment]
Добрый день.

Мы на данный момент занимаемся разработкой инструментов для анализа объемов, прочие моменты на втором плане.
