### ISSUE TITLE
Ошибка отображения шага цены.

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1166]
В инструментах, имеющих шаг цены 0,5(6E,6J,6С) - при изменении шага - он неправильно отображается на панели управления. Сам шаг меняется, но отображение - неверное. После смены вкладки - данные обновляются и шаг показывается правильно. То же самое и с ES.

**Comment by SBProX** [comment]
Проверим работу шага цены, вы можете если не сложно записать видео?

**Comment by SBProX** [comment]
Можете выслать скриншот как он у вас отображается?

**Comment by ershner** [comment]
Инструмент 6Е. шаг = 1. Нажимаю на стрелки выбора шага цены вниз 
![2020-06-01_14-25-11](https://user-images.githubusercontent.com/18483236/83404670-bbc7f880-a413-11ea-98da-a6c5bee5f38c.png)

на  панели инструментов шаг НЕ меняется на 0,00005, но при нажатии на эплай, график переходит на шаг=,00005.
![2020-06-01_14-23-44](https://user-images.githubusercontent.com/18483236/83404772-e87c1000-a413-11ea-93d8-fd3af878a23a.png)

При смене вкладки шаг цены начинает отображаться правильно.
![2020-06-01_14-24-07](https://user-images.githubusercontent.com/18483236/83404860-05b0de80-a414-11ea-9193-5f7195e36745.png)

**Comment by SBProX** [comment]
Спасибо, сейчас попробуем воспроизвести

**Comment by SBProX** [comment]
Исправили. Будет работать в обновлении от 10 июня

**Comment by ershner** [comment]
А при увеличении шага, если менять стрелкой вверх, шаг будет подниматься на ,0001. При уменьшении будет меняться на 0,00005, но отображаться  будет неправильно.

**Comment by SBProX** [comment]
Спасибо!

**Comment by ershner** [comment]
Пожалуйста!

**Comment by ershner** [comment]
После обновления некорректно отображается шаг в панели управления. Даже если пересохранить воркспейс с новыми значениями - они сохраняются, но при изменении вкладки сбрасываются на минимальные.

1. Воркспейс прогрузился = отображения шага правильное
![2020-06-08_14-36-49](https://user-images.githubusercontent.com/18483236/84026339-d5c68580-a995-11ea-8a3c-450d3bf63401.png)

2, При смене вкладки = шаг скидывается на минимальный
![2020-06-08_14-38-10](https://user-images.githubusercontent.com/18483236/84026382-e70f9200-a995-11ea-9c17-697b5b48d0ff.png)
