### ISSUE TITLE
Инструменты MOEX

### ISSUE THREAD

**Issue by Rilin** [SBProX/SBProX-Dev#1167]
Добрый день!
Мало инструментов срочного рынка MOEX. Есть ли в плане их добавления, как минимум ликвидные фьючерсы Сбербанка, Газпрома и тд.

Кроме того, если текущие сделки получаем через коннектор QUIK - для построения локальных графиков прошу реализовать возможность выбирать инструменты из своего коннектора.

**Comment by SBProX** [comment]
Добрый день.

Фьючерсы Сбербанка и Газпрома есть, самые ликвидные.

Выбирать инструменты из своего коннектора мы не можем позволить, так как платформа привязана к серверам для получения исторической котировки.
