### ISSUE TITLE
Размер цифр на гистограммах профилей 

### ISSUE THREAD

**Issue by EGOR1972** [SBProX/SBProX-Dev#1168]
Цифр не видно при сжатии графика,на старой было лучше.Исправьте пожалуйста.
![ice_screenshot_20200529-163427](https://user-images.githubusercontent.com/33864838/83266842-0eaf6f00-a1cc-11ea-9b73-7c7f85163759.png)

**Comment by EGOR1972** [comment]
Если сжать график как на старой платформе цифры пропадут.Можно исправить?

**Comment by SBProX** [comment]
Цифры и на старой платформе пропадали.
На вашем скриншотах совершенно разный масштаб.

Исправлять здесь нечего, SBProX другая платформа, и мы не копируем точь в точь все из SBProV2
