### ISSUE TITLE
БОСК ЧАРТ 

### ISSUE THREAD

**Issue by oy-nikolay** [SBProX/SBProX-Dev#1170]
Дорогие разработчики. 
Можете исправить отображение бокс чарта. 
Пример М5 и 4Ч по графику SI. Отображение М5 видно свечи инструмента, на 4Ч графика вообще невидно. бокс полностью закрашен. 

Фото с графиком. 
https://drive.google.com/file/d/1BWuVl8DGybzPRdhHrw4r9_uSL9xO0Pnm/view?usp=sharing
Такая же закраска идет на EU, LKON график не читабельный.

**Comment by SBProX** [comment]
Добрый день.
Спасибо, проверим.

**Comment by SBProX** [comment]
Исправили ситуацию таким образом:

- добавили опцию включения/выключения сетки (именно из-за нее получался такой эффект)
- прорядили частоту рисования сетки при низком масштабе.
