### ISSUE TITLE
При приближении цены к линии - сдвигается лейбл со временем.

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1171]
Стоит параметр Chart to end distance=65. Если установлена линия и цена приближается к ней на расстояние -+ 2 пункта - сдвигается лейбл со временем.
![2020-06-01_18-40-44 (2)](https://user-images.githubusercontent.com/18483236/83426910-8c77b280-a438-11ea-8258-11e23f6ae430.png)
Если линию убрать или цена отходит от нее больше чем на 2 пункта - лейбл встает на свое место.
![2020-06-01_18-40-57 (2)](https://user-images.githubusercontent.com/18483236/83427022-ba5cf700-a438-11ea-8d05-205da2c9d1ab.png)

**Comment by SBProX** [comment]
Лейбл со временем сдвигается спецально, чтобы не накладываться на близлежащую линию.
Так как у вас стоит расстояние 65, то данный лейбл теперь налазит на график при сдвижении.
Рекомендуем поставить 85-90 расстояние.
