### ISSUE TITLE
Умоляю, добавьте индикатор Bollinger Bands !

### ISSUE THREAD

**Issue by PowerUser0** [SBProX/SBProX-Dev#1176]
Это единственный технический индикатор, от которого есть хоть какая-то польза... Очень хотелось бы его видеть в вашей платформе.

**Comment by trades1** [comment]
Поддерживаю!

**Comment by IrinaKob** [comment]
Поддерживаю эту просьбу!

**Comment by SBProX** [comment]
В ближайшее время никаких индикаторов из ТА мы добавлять не планируем.

**Comment by dusha1973** [comment]
Поддерживаю!
