### ISSUE TITLE
Быстрый выбор цвета. (без кнопки "ОК")

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#118]
Здравствуйте. 
В предыдущей платформе можно быстро было выбрать цвет для линии
Предлагаю сохранить эту возможность и в новой версии. Скрыть меню после нажатия на нужный цвет палитры без нажатия кнопки "ОК"
![палитра](https://user-images.githubusercontent.com/20509322/57827880-c6e5c180-77db-11e9-8d76-0513e25bc97c.jpg)

**Comment by SBProX** [comment]
Рассмотрим.

**Comment by SBProX** [comment]
Сделано, будет работать в следующем обновлении.
