### ISSUE TITLE
Условная отрисовка тела свечи на графике кластеров.

### ISSUE THREAD

**Issue by tradingpro-nesterov** [SBProX/SBProX-Dev#1185]
Предложение о визуальном определении бычьего или медвежьего направления  в кластерном анализе  ,такие как - кластера объёма ,профиля, а также в чарт бокс.  Хотелось бы на графике  с левой  стороны кластера  видеть линию ТЕЛА  соответствующего цвета (дублирующую свечку) . Это не большое внедрение дало более четкую картину происходящих движений на графике в кластерном анализе .

Сейчас так : 
![Безымянный](https://user-images.githubusercontent.com/66359979/83625798-31ab9b80-a59d-11ea-827f-925b9328a6e0.png)
А так намного информативнее :
![Безымянный1](https://user-images.githubusercontent.com/66359979/83625818-396b4000-a59d-11ea-9086-7873c3991c1d.png)

**Comment by SBProX** [comment]
Данная настройка давно есть в платформе.
В настройках графика нужно включить направление бара.
