### ISSUE TITLE
Сильное запаздывание котировки при резких движениях!

### ISSUE THREAD

**Issue by Artem074** [SBProX/SBProX-Dev#119]
Сильное запаздывание котировки на 2-4 минутных бара В ОБЕИХ ПРОГРАММАХ!... проблема появляется в начале торговой сессии и при резких движениях. Восстановление (догоняет) порой длится минут 10-20...
Это сервак  у вас такой глючный или сама программа? Не могу пока понять причину, т.к. вы ещё не сделали рабочие коннекторы!

**Comment by Expert-ks** [comment]
проблема может быть в подключении если через вай фай то это нормально если кабельное подключение то проблема в другом. попробуйте подключить через кабель и потестить

**Comment by Expert-ks** [comment]
еще зависит от железа если подключение по кабелю. 1 если открыто несколько терминалов + спб про 2 если обычный хдд механический +слабый проц. Почему так во время открытия приходит премаркет много тиков спб надо успеть из отрисовать на график + залогировать на хдд а если еще и клауд стоит то тогда тут может и оперативы не совсем хватать. опиши подробней что имеешь и как подключен. Ну и если есть фин возможность поставь минимальный ссд

**Comment by Artem074** [comment]
> проблема может быть в подключении если через вай фай то это нормально если кабельное подключение то проблема в другом. попробуйте подключить через кабель и потестить

у меня отличный ПК и кабель... у меня не у одного такие проблемы, а у всей нашей группы в разных городах...

**Comment by Artem074** [comment]
> еще зависит от железа если подключение по кабелю. 1 если открыто несколько терминалов + спб про 2 если обычный хдд механический +слабый проц. Почему так во время открытия приходит премаркет много тиков спб надо успеть из отрисовать на график + залогировать на хдд а если еще и клауд стоит то тогда тут может и оперативы не совсем хватать. опиши подробней что имеешь и как подключен. Ну и если есть фин возможность поставь минимальный ссд

сотрудник СБПРО?

**Comment by Expert-ks** [comment]
нет юзер

**Comment by Artem074** [comment]
> нет юзер

а зачем тогда тут накую ерунду несешь... тут нищебродов вроде нет ))

**Comment by Artem074** [comment]
> > нет юзер
> 
> а зачем тогда тут такую ерунду несешь... тут нищебродов вроде нет ))

**Comment by Expert-ks** [comment]
проблемы разные у всех и такое тоже бывает.

**Comment by Artem074** [comment]
> проблемы разные у всех и такое тоже бывает.

"Почему так во время открытия приходит премаркет много тиков спб надо успеть из отрисовать на график" - прежде чем такое писать, подумай хоть немного... у всех программ Волфикс, Атас норм работает, а тут нет... причем это недавно стало появляться.... недели как 2-3 назад...

**Comment by Expert-ks** [comment]
ок пошел думать

**Comment by SBProX** [comment]
@Artem074 На серверах большая нагрузка во время новостей или волатильного рынка.
Поэтому запаздывание. Учитывая что вы за котировку не платите, то попрошу без претензий.

**Comment by Artem074** [comment]
> @Artem074 На серверах большая нагрузка во время новостей или волатильного рынка.
> Поэтому запаздывание. Учитывая что вы за котировку не платите, то попрошу без претензий.

Да ваши заторможенные котировки даром никому не нужны. Все ждут коннекторы,  чтобы тянуть адекватные данные.
