### ISSUE TITLE
Удаление линий и фигур при смене таймфрейма

### ISSUE THREAD

**Issue by alekskdr** [SBProX/SBProX-Dev#1196]
Если поменять таймфрейм к примеру с m5 на H1, то с графика удаляются все отмеченные уровни и нанесённые фигуры рисования.

**Comment by SBProX** [comment]
Уже исправили, обновитесь.

**Comment by alekskdr** [comment]
объекты рисования остаются на графике, а горизонтальные уровни всё равно исчезают.
![2020-06-08_19-06-02](https://user-images.githubusercontent.com/574014/84054236-c4906f80-a9bb-11ea-9699-f665d99a03aa.png)

**Comment by SBProX** [comment]
Исправили
