### ISSUE TITLE
Проблема с загрузками графиков после запуска программы. Помогает только перезагрузка. 

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#12]
![2019-05-07_9-23-00](https://user-images.githubusercontent.com/35344271/57276330-e5e0a700-70a9-11e9-8375-2b327399657f.jpg)
![2019-05-07_9-26-44](https://user-images.githubusercontent.com/35344271/57276428-440d8a00-70aa-11e9-8ee2-31024669972b.jpg)

**Comment by SBProX** [comment]
Пожалуйста отправьте нам сюда ваш workspace который вы загружаете, проверим.
Такая ошибка возникает именно при первой загрузке workspace?

Опишите детально в каком случае возникает эта проблема.

**Comment by Dmitry1970** [comment]
Ошибка возникает в процессе работы. Графики загрузились, работаю с одним графиком, потом переключаюсь на другую закладку, а там такая картинка. После загрузки график был нормальным.
![2019-05-07_22-02-13](https://user-images.githubusercontent.com/35344271/57326153-79e75880-7114-11e9-8caf-d32f4f89c709.jpg)
[Space.zip](https://github.com/SBProX/SBProX-Dev/files/3154142/Space.zip)

**Comment by SBProX** [comment]
Подскажите, ошибка возникает при выходе из спящего режима, или при новом запуске платформы?
При запуске платформы у нас все загрузилось хорошо, на всех вкладках графики отображаются корректно.
