### ISSUE TITLE
Are you sure want to close SBPro? 

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#120]
Здравствуйте.
В старой версии при закрытии окна и при нажатии в меню "Exit" - появлялись сообщения  
- Are you sure want to close SBPro? 
- Do you want to close this window?
- Do you want to close TAB?

В новой платформе закрытие происходит без сообщений.

**Comment by SBProX** [comment]
Второй пункт работает - когда закрываете окно программа спрашивает.

**Comment by SBProX** [comment]
Сделано, будет работать в следующем обновлении.
