### ISSUE TITLE
Имена окон для всех стали одинаковые

### ISSUE THREAD

**Issue by OlegT911** [SBProX/SBProX-Dev#1200]
Здравствуйте! В обновлённой версии, имена окон теперь одинаковые для всех активов.
![2020-06-08 17 15 34](https://user-images.githubusercontent.com/60439200/84041866-036af900-a9ad-11ea-8902-5fadcf4c9846.jpg)

**Comment by SBProX** [comment]
Добрый день.

Исправим.

**Comment by SBProX** [comment]
Исправили
