### ISSUE TITLE
Отображение вертикального объема

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1203]
При разрешеннии 1280*1024
![2020-06-08_18-34-11](https://user-images.githubusercontent.com/18483236/84051707-31096f80-a9b8-11ea-8ce4-5e7e7a038b6f.png)

При разрешеннии 1920*1080
![2020-06-08_18-46-50](https://user-images.githubusercontent.com/18483236/84051893-7168ed80-a9b8-11ea-995d-6360b2ff7998.png)

При разрешеннии 1920*1080, растянув график
![2020-06-08_18-49-05](https://user-images.githubusercontent.com/18483236/84052196-e89e8180-a9b8-11ea-8852-a4da408bd633.png)

**Comment by SBProX** [comment]
Принято, проверим и исправим.

**Comment by SBProX** [comment]
Исправили, можете проверить
