### ISSUE TITLE
Не работает опция в кастомном графике.

### ISSUE THREAD

**Issue by WebSurfer001** [SBProX/SBProX-Dev#1204]
Здравствуйте! Не работает опция в кластерпрофиле, при включении не пропадает рамка выделения макс объёма, если кластере объём меньше установленного в  фильтре. Хотя в дельтепрофиле работает.

![image](https://user-images.githubusercontent.com/66634368/84052096-c278e180-a9b8-11ea-94bd-f59fa9b2462d.png)

**Comment by ale389** [comment]
О классно ,а как так включить ,что бы с лева кластеры были,а с правы дельта подскажите пожалуйста.

**Comment by WebSurfer001** [comment]
Ответ для  ale389
https://github.com/SBProX/SBProX-Dev/issues/1239

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении
