### ISSUE TITLE
Шаг цены 

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1205]
#1166 После обновления некорректно отображается шаг в панели управления. Даже если пересохранить воркспейс с новыми значениями - они сохраняются, но при изменении вкладки сбрасываются на минимальные.

Воркспейс прогрузился = отображения шага правильное
![2020-06-08_14-36-49](https://user-images.githubusercontent.com/18483236/84053944-4fbd3580-a9bb-11ea-8d4b-9e9cd0a69c9a.png)

2, При смене вкладки = шаг скидывается на минимальный
![2020-06-08_14-38-10](https://user-images.githubusercontent.com/18483236/84054019-6cf20400-a9bb-11ea-9393-723d9fe27f94.png)

**Comment by SBProX** [comment]
Исправили, сегодня выложим обновление.
