### ISSUE TITLE
Ошибка запуска

### ISSUE THREAD

**Issue by aledzander** [SBProX/SBProX-Dev#1208]
После запуска ошибка загрузки настроек.
Перезапуск - та же ошибка.

![error](https://user-images.githubusercontent.com/65729671/84085620-a859f600-a9ee-11ea-9a9d-4bec95de3af8.jpg)

**Comment by aledzander** [comment]
Трассировка проходит без проблем.

![5](https://user-images.githubusercontent.com/65729671/84086141-d55ad880-a9ef-11ea-9d60-7938d5792da0.jpg)

**Comment by WebSurfer001** [comment]
Вам надо скачать новую версию с сайта и установить поверх старой.

**Comment by SBProX** [comment]
В течение дня возможны перебои сегодня, но уже должно работать.

**Comment by SBProX** [comment]
И да, нужно переустановить как написали выше
