### ISSUE TITLE
Не обновляется дата на графиках на сегодняшний день.

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#121]
Загружаю графики утром до начала торгов - загружается предыдущий день. Всё правильно. Но начинаются торги и на графиках ничего не меняется на сегодняшний день. То есть надо на каждой вкладке вручную поменять дату на сегодняшний день и перезагрузить данные с сервера. Как сделать так, чтобы при начале торгов на графиках была актуальная информация?  Т.е. отображалась информация на текущий момент.

**Comment by SBProX** [comment]
Уточните какой именно инструмент?
Загружаете workspace?
Если да, то для workspace стоит "кол-во загружаемых дней"?

Пожалуйста, всегда пишите чтобы мы могли проверить у себя.
Нет никакой конкретной информации.

**Comment by Dmitry1970** [comment]
Все инструменты ФОРТС - РТС, Нефть, Сбербанк, Доллар/рубль. Например, сегодня 16.05 в 7-00 я запускаю программу - открываются вкладки за 15.05 с последним временем 23 часа. А сегодня 16.05. в 10-00 начинаются торги. На графиках ничего не меняется. Дата остаётся 15.05. Руками на каждой вкладке переставляю дату и нажимаю "Перегрузить данные с сервера" и ставлю галочку"все вкладки" После этого графики с обновлённой датой - 16.05 показывают реальные торги.

**Comment by SBProX** [comment]
Спасибо проверим.

**Comment by Dmitry1970** [comment]
Сегодня днем загрузил программу. Половина вкладок загрузилась на 19.05, половина - на 15.05. Есть номерность - все вкладки с дневным таймфреймом загрузились за 15.05. Остальные H1, M5 - часть 19.05,  а часть - 15.05. Речь идёт о фьючерсах РТС, Си, Сбербанк, Нефть.

**Comment by SBProX** [comment]
Требуется время на проверку данной ошибки.
Вы можете сообщить нам ваш логин и название workspace?

**Comment by Dmitry1970** [comment]
логин: badl1970@mail.ru
workspace: X

**Comment by Dmitry1970** [comment]
Только что попробовал загрузиться через сервер QUIK , а не через SB Pro. Всё чётко - загрузилась текущая дата - 22.05, и графики актуальные - на конец вчерашнего дня.
