### ISSUE TITLE
Не запускается программа после последнего обновления

### ISSUE THREAD

**Issue by AlexLesha** [SBProX/SBProX-Dev#1213]
Доброе утро. Не запускается программа после последнего обновления (произошло сегодня) . Вчера все работало без проблем - закрыл приложение, выключил компьютер, ничего не обычного. Сегодня, при первом запуске программа начала обновляться, после чего НИЧЕГО не произошло - никаких окон, ни логина, ни выбора коннекторов - НИЧЕГО! 
.Net 4.5 установлен,  компьютер перезагружал - после запуска ничего не происходит: ни обновления, ни логина.

Решите пожалуйста, или откатите новую версию.

**Comment by AlexLesha** [comment]
Как можно запустить прежнюю версию? Есть предпоследнее обновление в папке, но не могу залогиниться - есть только кнопка Update. Нужен СРОЧНЫЙ ответ пожалуйста.

**Comment by AlexLesha** [comment]
Написал в поддержку в телеграме - в ответ МОЛЧАНИЕ

**Comment by makhitrov** [comment]
Скачай по новому с сайта и переустанови

**Comment by StasON1989** [comment]
тоже самое! только не обновлялась она у меня - просто не запускаеться!!!

**Comment by upeko** [comment]
Подтверждаю программа не запускается также

**Comment by avfinance** [comment]
Поддерживаю. Есть проблема

**Comment by AlexLesha** [comment]
Апдейт. Моя проблема решилась после переустановки основной программы с сайта (https://drive.google.com/file/d/1yvw5ErPxAt11rKuhZpyJhj451BHaMCSi/view) и нескольких перезагрузок. Переустанавливал два или три раза. 
Не знаю что именно повлияло на исход, но после некоторого шаманства, программа просто запустилась как ни в чем не бывало. 
От поддержки - молчание.

**Comment by WebSurfer001** [comment]
Вышла новая версия об этом писали в официальном канале в телеграм.
---------------------------------------------------------------------------------------------------
Сегодня мы выпустили обновление SBProX, которое было ранее анонсировано.

1. Чтобы обновление запустилось, необходимо обязательно скачать платформу с сайта (https://www.sb-professional.com/sbprox) и переустановить ее. При этом ничего удалять не нужно.
______________________________________________

Исправлены ошибки:
1. https://github.com/SBProX/SBProX-Dev/issues/1081
2. https://github.com/SBProX/SBProX-Dev/issues/1089
3. https://github.com/SBProX/SBProX-Dev/issues/1064
4. https://github.com/SBProX/SBProX-Dev/issues/1060
5. https://github.com/SBProX/SBProX-Dev/issues/956
6. https://github.com/SBProX/SBProX-Dev/issues/935
7. https://github.com/SBProX/SBProX-Dev/issues/934
8. https://github.com/SBProX/SBProX-Dev/issues/916
9. https://github.com/SBProX/SBProX-Dev/issues/913
10. https://github.com/SBProX/SBProX-Dev/issues/910
11. https://github.com/SBProX/SBProX-Dev/issues/837
12. https://github.com/SBProX/SBProX-Dev/issues/840
13. https://github.com/SBProX/SBProX-Dev/issues/741
14. https://github.com/SBProX/SBProX-Dev/issues/1122
15. https://github.com/SBProX/SBProX-Dev/issues/1113
16. https://github.com/SBProX/SBProX-Dev/issues/1109
17. https://github.com/SBProX/SBProX-Dev/issues/1142
18. https://github.com/SBProX/SBProX-Dev/issues/1127
19. https://github.com/SBProX/SBProX-Dev/issues/1166
20. https://github.com/SBProX/SBProX-Dev/issues/1162
21. https://github.com/SBProX/SBProX-Dev/issues/1159

Доработан/добавлен функционал:
1. Структуризирован код платформы (Это была основная задача обновления)
2. Доработан Фибоначчи
3. Добавлена верхняя панель быстрых кнопок
4. Добавлено 17 новых звуков
5. Добавлена возможность добавлять свои звуки для алертов
6. Добавлена вкладка Analyzer в симулятор
7. Добавлено сохранение результатов для симулятора и экспорт сделок из симулятора в XLS и PDF
8. Исправлена работа алертов в симуляторе
9. Доработан увеличитель (увеличитель пока НЕ работает на кастомных графиках)
10. Добавлены кастомные кластерные графики с возможностью сохранения конфигурации 
(пока графики сохраняются только локально)
11. Добавлен Delta фильтр для графика Cluster profile
12. Добавлены опции линковки (привязка дат, линий, и действие кнопки Apply/Применить)
13. Добавлена опция включения/выключения времени на Price ticker
14. Добавлены некоторые косметические изменения
15. Исправлено множество системных ошибок

**Comment by StasON1989** [comment]
обновил - теперь ни настройки не загружает ни логиниться - ошибка!!!
![image](https://user-images.githubusercontent.com/62938300/84121534-e21c1280-aa69-11ea-9de6-c275344dd747.png)

**Comment by 7Veles7** [comment]
такая же
![jib,rf](https://user-images.githubusercontent.com/62540720/84122190-ba648480-aa40-11ea-8def-c2d56085fdb9.png)
 беда

**Comment by WebSurfer001** [comment]
Решил перезагрузить комп и  тоже самое что и у вас. хотя только что был в системе и всё работало. Наверно исправляют ошибки.

**Comment by WebSurfer001** [comment]
У меня всё заработало.

**Comment by StasON1989** [comment]
перезагрузил и все работает!)

**Comment by avfinance** [comment]
Скачал по ссылке выше, обновил и полет нормальный. 
Ув. разработчики, спасибо за поддержку!
