### ISSUE TITLE
После обновления 9.06

### ISSUE THREAD

**Issue by OlegT911** [SBProX/SBProX-Dev#1216]
Здравствуйте! После утреннего обновления, программа работает крайне не стабильно, самопроизвольно дёргается, подвисает.

**Comment by vomma-opt** [comment]
подтверждаю, окно зависает, таймер рядом с текущей ценой может зависнуть секунд на 5-6

**Comment by sutr2017** [comment]
так же подтверждаю. программа фризится на пару секунд через каждые ~35 секунд. такое чувство, что на таймере висит какое-то событие, которое периодически нагружает платформу до полной остановки.

**Comment by WebSurfer001** [comment]
Я перезапустил прогу и теперь войти не могу. там что-то делают наверно.

**Comment by alekskdr** [comment]
хотел написать об этой же проблеме, но у меня это проявляется при переключении между вкладками. как только перехожу на другую вкладку, через пару секунд происходит фриз. и так каждый раз, если переключаешься между вкладками.

**Comment by avfinance** [comment]
Народ, может хватит создавать тикеты на одну и ту же тему?? Уверен, что разработчики уже в курсе и давайте не будем им мешать

**Comment by WebSurfer001** [comment]
Просто чат убрали, теперь все здесь.
У меня всё заработало.

**Comment by SBProX** [comment]
Сегодня еще возможны перебои, так как первоначальное обновление сильно загружало сервер.
Сейчас уже выложили фикс.
