### ISSUE TITLE
Запуск в симуляторе контракта без склейки

### ISSUE THREAD

**Issue by AlTuzov** [SBProX/SBProX-Dev#1217]
Добрый день. До обновления, можно было выбрать контракт без склейки (не авто) и запустить его в симуляторе. Теперь, даже если заранее выбераешь нужный контракт, он всё равно выводится в режиме авто со склейкой. 
Например, я хочу прокрутить нефть BR сентябрьский контракт прошлого года, указываю этот контракт на графике и нажымаю применить. Далее добавляю его в симулятор указывая начало торговли с 1 августа а историю с 1 июня, но у меня график подгружается со склейкой и я вижу историю с августовского контракта, что не совсем корректно.
Просьба вернуть этот момент как было до обновления.

**Comment by SBProX** [comment]
Добрый день.

Проверим данную ошибку.

**Comment by SBProX** [comment]
Исправили, сегодня выложим обновление
