### ISSUE TITLE
После обновления пропал звук алертов на индикаторы((

### ISSUE THREAD

**Issue by Dim77485** [SBProX/SBProX-Dev#1219]
После обновления пропал звук алертов на индикаторы((

**Comment by Avadacedavra** [comment]
> После обновления пропал звук алертов на индикаторы((

Да, но не только на индикаторы, а вообще звуки на алерте теперь не проигрываются!

**Comment by Dim77485** [comment]
Да к, а как решить проблему-то ??09.06.2020, 17:57, "Avadacedavra" <notifications@github.com>:

После обновления пропал звук алертов на индикаторы((

Да, но не только на индикаторы, а вообще звуки на алерте теперь не проигрываются!

**Comment by Avadacedavra** [comment]
> Да к, а как решить проблему-то ??09.06.2020, 17:57, "Avadacedavra" <notifications@github.com>: После обновления пропал звук алертов на индикаторы(( Да, но не только на индикаторы, а вообще звуки на алерте теперь не проигрываются! —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Мы никак не сможем, надо ждать, когда разработчики пофиксят ошибки.

**Comment by Dim77485** [comment]
Но как-то разработчикам же нужно эту мысль донести!) Я им в тех поддержку на сайте написал, уж не знаю поняли они или нет.09.06.2020, 18:39, "Avadacedavra" <notifications@github.com>:

Да к, а как решить проблему-то ??09.06.2020, 17:57, "Avadacedavra" notifications@github.com: После обновления пропал звук алертов на индикаторы(( Да, но не только на индикаторы, а вообще звуки на алерте теперь не проигрываются! —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Мы никак не сможем, надо ждать, когда разработчики пофиксят ошибки.

**Comment by SBProX** [comment]
Исправили ошибку со звуком
