### ISSUE TITLE
Предложение по визуализации торговых сессий

### ISSUE THREAD

**Issue by Pavel-111** [SBProX/SBProX-Dev#122]
Предлагаю реализовать подсветку торговых сессий (Азия, Европа, Америка...) внутри дня. 
скрин приложен
  
![Screenshot_15](https://user-images.githubusercontent.com/50700791/57847449-ea1a6c00-77ef-11e9-8c52-1691901b00aa.png)

**Comment by Alkor135** [comment]
Поддерживаю!
Хорошая функция

**Comment by r0b4ik** [comment]
Хотел уже отдельным топиком сделать, а смотрю меня опередили.
Очень нужная функция и несложная в исполнении. Уверен многим пригодится.
Можно сделать это, как функцию в разделителе периодов, а можно, как индикатор, таки образом увеличив их количество.
Народ любит, когда много индикаторов :)

**Comment by ws-keith** [comment]
Поддерживаю, но кнопкой в углу нажал посмотрел отжал, чтобы не мешало графику а не как индикатор

**Comment by bizlis** [comment]
Поддерживаю, так же добавить разделение сессий (дневка/вечерка) и для MOEX
