### ISSUE TITLE
добавить акции РТС

### ISSUE THREAD

**Issue by atusya** [SBProX/SBProX-Dev#1223]
Добрый день! Отличная программа! Особенно, новая версия 5.0.11 - очень нравится! Большое спасибо разработчикам! Хотелось бы еще иметь для анализа акции РТС, хотя бы через коннектор Quik. Понимаю, что не всё сразу - просто, прошу не забывать о страждущих...)) Если это будет реализовано - пожелание, чтобы акции можно было подключать через коннектор квик - независимо от фьючерсов, т.к. у брокера котировки довольно часто отваливаются, поэтому коннектор Sbpro на фьючерс спасает.

**Comment by SBProX** [comment]
Спасибо большое за отзыв. 
Акции мы добавим немного позже.
