### ISSUE TITLE
Не запускается после обновы

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#1224]
Вчера работало, сегодня не обновляется.
1. С сайта качал и устанавливал по новой.
2. Комп перезапускал.
Соединения к серверу размножаются, кол-во скачанных байтов скачет туда-сюда.
![2020-06-09_18-28-29_sbpro](https://user-images.githubusercontent.com/7328803/84168095-87cd8280-aa66-11ea-8b55-a139ff589f9e.gif)

**Comment by ziplan** [comment]
У меня вообще не запускается

**Comment by SBProX** [comment]
Напишите завтра в тех поддержку, вам обязательно помогут.
