### ISSUE TITLE
Опять та же кнопка

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#1235]
Пару дней назад  я писал о неработающей кнопки в правом нижнем углу - "стрелка вправо", не правильно работала фиксация графика по правому краю при включенных комбинированных графиках. В сегодняшнем updates вы исправили этот баг, но похоже не полностью проверили результат исправления. 
Теперь эта кнопка ВООБЩЕ не отключается при любом сдвиге вправо кастомного графика. Отключить кнопку можно только горячими клавишами или ткнув мышью. 
На всех остальных типах графиков кнопка работает штатно. Исправьте , плиз.

**Comment by SBProX** [comment]
Исправили. Сегодня выложим обновление.
Похоже эти графики придется еще не один день дорабатывать.
