### ISSUE TITLE
Ошибка функции увеличитель на графике "Объём дельта профиль"

### ISSUE THREAD

**Issue by indianaxxx** [SBProX/SBProX-Dev#1237]
При просмотре графика "объём дельта профиль" через увеличитель, последний транслирует дельту профиль...
![окно увеличителя](https://user-images.githubusercontent.com/54440183/84263991-e3b50b80-ab39-11ea-82f4-b0cbff5d55dc.jpg)

**Comment by SBProX** [comment]
Исправлено, сегодня будет обновление.

**Comment by indianaxxx** [comment]
Спасибо.
