### ISSUE TITLE
после обновления 13,05,2019 все так же не правильно отображаются мувинги!

### ISSUE THREAD

**Issue by AlexanderStroitelev** [SBProX/SBProX-Dev#124]
![Screenshot_4](https://user-images.githubusercontent.com/36483253/57851626-b8060b80-77e9-11e9-8e79-03585c597c54.png)

**Comment by AlexanderStroitelev** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/36483253/57853323-20ef8280-77ee-11e9-8046-6daa85273752.png)

**Comment by SBProX** [comment]
Исправлено
