### ISSUE TITLE
Опять баги.

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#1241]
После сегодняшнего обновления у меня невозможно нарисовать большую часть граф.фигур. Рисуется только динам.профиль, горизонтальные линии и вертикальные линии. Причём вертикальные линии НЕВОЗМОЖНО УДАЛИТЬ, т.к. на них нет крестика удаления. 
Всё **остальное не рисуется** - при нажатии хоткея курсор меняется или с панели "инструменты", ЛКМ зажимается и тянется, но  дальше ничего не рисуется.

**Comment by X-man77** [comment]
Сегодня заметил - нет OHLC. Вчера кажется было.

**Comment by sutr2017** [comment]
@X-man77 у меня есть OHLC...

**Comment by SBProX** [comment]
С касмотмными графиками поправили. Сегодня будет обновление.
Вертикальные линии удаляются нормально, пожалуйста создайте отдельный тикет со скриншотом или видео.

Спасибо.
