### ISSUE TITLE
Проблемы с симулятором

### ISSUE THREAD

**Issue by DmitrySche** [SBProX/SBProX-Dev#1242]
1. После загрузки истории работает только один день. Потом останавливается. Никак не исправлется.
2. Я открываю несколько окон с разными таймфреймами. При попытке промотки по 1или 2 или 5 баров проматываются бары во всех окнах на всех таймфреймах. То есть когда на м5 я нажимаю +1B также проматывается бар на M15, H1 и т.д.

**Comment by SBProX** [comment]
Первый пункт исправлен.

Второй пункт - позже поправим.

**Comment by SBProX** [comment]
Второй пункт исправили, сегодня выйдет обновление.

**Comment by DmitrySche** [comment]
Чудесно!
Большое Человеческое Спасибо.
