### ISSUE TITLE
Баги в обновлении 5.0.13

### ISSUE THREAD

**Issue by sbprosupport** [SBProX/SBProX-Dev#1243]
1. При загрузке другого инструмента в окне или на другой вкладке окна сохраняется шаг цены предыдущего инструмента. Отображение графика получается некорректным, приходится открывать новое окно графика или вручную изменять шаг цены. 
![Screenshot_1673](https://user-images.githubusercontent.com/50356876/84284185-896d7800-ab44-11ea-958c-969dba49fefa.png)
![Screenshot_1674](https://user-images.githubusercontent.com/50356876/84284187-8b373b80-ab44-11ea-9145-1f0424edb204.png)

2. Если сохранить шаблон графика, а потом загрузить его в новом окне/вкладке - то не обновляются котировки по инструменту реалтайм без нажатия кнопки "Применить"

3. Симулятор работает не совсем корректно. Если выбрать интервал больше 1 дня, то по окончании 1го дня симуляция закончится. Если подождать еще, время между торговыми сессиями - то пойдет следующий день. Особенно это неудобно для инструментов Forts, т.к. ждать нужно с 23:49 предыдущего дня до 10:00 следующего дня.
![Screenshot_1677](https://user-images.githubusercontent.com/50356876/84285321-00574080-ab46-11ea-9d37-5dca04e5b760.png)
![Screenshot_1678](https://user-images.githubusercontent.com/50356876/84285348-09e0a880-ab46-11ea-90e0-c71b951b2b11.png)

**Comment by SBProX** [comment]
Пункт 1 и 2 исправили, сегодня выйдет обновление.
По симулятору будем исправлять на сл. неделе.

**Comment by SBProX** [comment]
3й пункт исправлен в версии 5.0.16
