### ISSUE TITLE
После очередного обновления не запускается программа 

### ISSUE THREAD

**Issue by aaryzhikov1974** [SBProX/SBProX-Dev#1249]
После очередного обновления перестала запускаться программа sbporX. Появляется окно - checking for updates и все.
ОС win8.
При этом sbproV2 запускается без проблем.

**Comment by aaryzhikov1974** [comment]
Кода будет реакция?

**Comment by Vegajav** [comment]
У меня была подобная ситуация. Помогло удаление и полная переустановка программы.

**Comment by aaryzhikov1974** [comment]
Переустановил программу, зааботало
