### ISSUE TITLE
Проблемы с перекрестием на комбинированном графике.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1251]
На комбинированном графике не отображается вертикальная линия у перекрестия. Сама вертикальная линия есть, но она застревает в начале первой даты графика.
![Snap_11 июня 2020 г _16h44m19s_005_](https://user-images.githubusercontent.com/24631570/84354370-1b888580-ac04-11ea-8ddd-8f14b9b44222.png)

**Comment by SBProX** [comment]
Какая у вас версия платформы? 
Мы это вчера исправляли.
