### ISSUE TITLE
Поле лупы на комбинированном графике сдвинуто.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1252]
![Snap_11 июня 2020 г _16h57m00s_006_](https://user-images.githubusercontent.com/24631570/84354761-cb5df300-ac04-11ea-90ed-9e693cbc1b3b.png)
На комбинированном графике поле лупы очень сдвинуто. Курсор указывает на пустоту, а отображаются значения, которые значительно выше того места, куда указывает курсор. Сам курсор у меня на графике не отобразился, но по горизонтальной линии поля лупы видно несоответствие.

**Comment by SBProX** [comment]
Увеличитель не работает (и не будет в ближайшее время работать) на данных графиках.
Мы об этом написали в списке обновлений.
Данный функционал сложен в реализации.
