### ISSUE TITLE
Не сохраняются настройки комбинированного графика.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1253]
![Snap_11 июня 2020 г _17h01m37s_007_](https://user-images.githubusercontent.com/24631570/84355385-de24f780-ac05-11ea-86bc-7643ef2626ca.png)
Как ни пыталсся, кроме первого сохранения настроек комбинированного графика, последующие не сохраняются и игнорируются программой.

**Comment by gengal** [comment]
Следующее сохранение возможно только для другого графика. Такое впечатление, что для одного графика можно сделать только одно сохранение настроек. Кроме этого, уже сохраненная настройка не пересохраняет изменения в параметрах.

**Comment by gengal** [comment]
![1](https://user-images.githubusercontent.com/24631570/84360749-f13bc580-ac0d-11ea-8f83-bb5ff5effe38.png)

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by SBProX** [comment]
В это поле настройки комбинированного графика не сохраняются.
Вы меняете настройки, а потом нужно их сохраниться в этом окне.

![image](https://user-images.githubusercontent.com/16720120/84378992-c04b9880-abed-11ea-9d06-349f95b47083.png)
