### ISSUE TITLE
В режиме комбинированного графика нет точного перехода в начало графика.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1254]
График 1
![Snap_11 июня 2020 г _17h09m07s_008_](https://user-images.githubusercontent.com/24631570/84355717-686d5b80-ac06-11ea-8c6a-a4e2a15bdd12.png)
График 2
![Snap_11 июня 2020 г _17h09m18s_009_](https://user-images.githubusercontent.com/24631570/84355734-74f1b400-ac06-11ea-83e6-d0f84f385aa2.png)
Как видно на первом графике отображается начало графика.
При нажатии на кнопку со стрелочкой перехода в нижнем правом углу графика (график 2), не видно начала графика. Сам график за экраном где то вверху. Пока активна эта кнопка со стрелочкой, невозможно вручную график сдвинуть в нормальное положение.

**Comment by SBProX** [comment]
Какая у вас версия платформы, мы вчера исправляли это.

**Comment by SBProX** [comment]
Проверьте, все должно работать.
