### ISSUE TITLE
На комбинированном графике не регулируется длина уровня.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1255]
![Snap_11 июня 2020 г _17h38m17s_010_](https://user-images.githubusercontent.com/24631570/84358631-c69c3d80-ac0a-11ea-89ff-949096815365.png)
На комбинированном графике невозможно регулировать длину выставляемого уровня. Сразу ставится уровень на всю длину графика.

**Comment by gengal** [comment]
Пробовал на часовом графике выставить укороченную линию уровня, она все таки рисуется, но при этом курсор не совпадает с концом рисуемой линии уровня. Его нужно уводить на левый край экрана, чтобы начала формироваться укороченная линия.

**Comment by gengal** [comment]
![Snap_11 июня 2020 г _18h28m47s_017_](https://user-images.githubusercontent.com/24631570/84363005-707ec880-ac11-11ea-860c-bbc5e7068b49.png)
Дальше линия не ведется, так как курсор уже у левой границы экрана.

**Comment by SBProX** [comment]
Исправили. Сегодня будет обновление
