### ISSUE TITLE
На комбинированном графике не работает натягиваемый профиль.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1256]
![Snap_11 июня 2020 г _18h38m08s_018_](https://user-images.githubusercontent.com/24631570/84363943-c7d16880-ac12-11ea-8f13-4077e8a61d91.png)
Натягиваемый профиль ничего не отображает ни на одной вкладке профиля.

**Comment by gengal** [comment]
На натягиваемом профиле открывается только вкладка Settings

**Comment by SBProX** [comment]
Исправили, сегодня выложим обновление.
