### ISSUE TITLE
Пропали заголовки окон

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1267]
Всё ещё не исправлено, поэтому открываю новый тикет

![image](https://user-images.githubusercontent.com/50357928/84471678-7f579080-ac8e-11ea-9130-e96d3ea910ba.png)

**Comment by sutr2017** [comment]
странно. у меня на семёрке это заработало сразу после апдейта, как написали, что исправили. и сейчас платформа обновилась, всё по прежнему - на окнах есть имена.

**Comment by r0b4ik** [comment]
У меня на Server 2016 такая беда, на Windows10 заработало после обновления. Так и знал, что будет какая то фигня после обновления, не хотел выключать программу, но пришлось. Оставили бы хоть возможность не обновляться и работать на стабильной предыдущей версии. Мне например кастомные графики не нужны.

**Comment by r0b4ik** [comment]
похоже проблема в другом, открыл инфо и вижу, что нет последних обновлений, написал в суппорт 
![image](https://user-images.githubusercontent.com/50357928/84477796-e11cf800-ac98-11ea-9957-955e70bf1ec9.png)

**Comment by r0b4ik** [comment]
можно закрывать тикет, удалось обновиться и всё заработало
