### ISSUE TITLE
Некорректно работает индикатор Daily Volume Profile

### ISSUE THREAD

**Issue by Alexey316** [SBProX/SBProX-Dev#1270]
Дневной маркет профиль должен строиться от границ, указанных стрелочками на скрине.

То есть, от 0:00 до 0:00. В данном же случае он строится до клиринга (15:40).

![Маркет профиль](https://user-images.githubusercontent.com/58070921/84488255-20177180-acca-11ea-8fa5-4e9c3aadf0e8.png)

**Comment by Bambino00777** [comment]
переведи время

**Comment by Alexey316** [comment]
> переведи время

А зачем? Что не так со временем? На графике стоит центральное время США, которое мне и нужно для NQ.

**Comment by WebSurfer001** [comment]
Поставь время Калининград, будет у тебя дневные и четырех часовые свечи правильные и профиль тоже.

**Comment by Alexey316** [comment]
> Поставь время Калининград, будет у тебя дневные и четырех часовые свечи правильные и профиль тоже.

То есть, дневной профиль будет строиться от 0:00 по калиниградскому времени? Если, да, то это совсем не то.

**Comment by WebSurfer001** [comment]
Новый День будет начинаться после клиринга как и должно быть. Почему у них есть внутри дневная моржа и перенос позиции через ночь.

**Comment by SBProX** [comment]
В SBPro профиль строится с 00.00.

По Чикагскому времени торги начинаются в воскресенье, поэтому Вы и видите профиль за этот день.
Это решается только сменой часового пояса для инструмента, как посоветовали выше.
