### ISSUE TITLE
Неправильное отображение цены на 6E

### ISSUE THREAD

**Issue by fallenAngelBad** [SBProX/SBProX-Dev#1275]
![tradingview_гепа_нет_6E](https://user-images.githubusercontent.com/10365262/84539477-26264600-acfc-11ea-8241-3ade914a33ea.jpg)
![геп в терминале SbProX_инструмент_6E](https://user-images.githubusercontent.com/10365262/84539479-27577300-acfc-11ea-9496-faa2b1ac6d60.jpg)

12.06.2020 на графике 6E наблюдается некорректное отображение данных. В программе SbProX есть геп, которого нет в реальности. Использование кнопки "перезагрузить данные с сервера", НЕ решает проблему. Прошу разобраться, т.к. это напрямую влияет на работу с графиком. Подробности на скринах

**Comment by WebSurfer001** [comment]
У вас склейка стоит (AUTO), если выбрать контракт как и в трейдингвью гэпа не будет. Для склейки это норма (такое отображение), на новом контракте цена выше чем на старом.
