### ISSUE TITLE
Симулятор

### ISSUE THREAD

**Issue by ikolenkov** [SBProX/SBProX-Dev#1276]
в новой версии в симуляторе ошибка.
я включаю график 5 мин и график рядом 1 мин.
при переключении 1 бара на на графике 1 мин переключается и автоматически переключаеться на 1 бар впееред на соседнем графике 5 мин.
и уже идет рассинхронизация по времени.
![image](https://user-images.githubusercontent.com/57211682/84548095-94273900-ad0d-11ea-87c8-eb643fcce027.png)

**Comment by SBProX** [comment]
Да, есть такое.
Поправим.

**Comment by SBProX** [comment]
Исправлено, сегодня выйдет обновление.
