### ISSUE TITLE
Предложение по доработке горизонтальной линии которая рисуется на ценовой шкале.

### ISSUE THREAD

**Issue by Kirill5282** [SBProX/SBProX-Dev#1277]
Здравствуйте уважаемые разработчики! Предложение реализовать расширение линии на кластерном графике. Таким образом можно объединить два инструмента рисования в один, тем самым улучшив восприятие графика и разгрузить его от большого количества линий. Как минимум в два раза. Лично моё мнение так было бы гораздо удобнее.
![Screenshot_2](https://user-images.githubusercontent.com/66850042/84551930-d48bb480-ad17-11ea-9616-20ec60cdc3c9.png)
![Screenshot_1](https://user-images.githubusercontent.com/66850042/84551947-e3726700-ad17-11ea-97c7-a59bc933723f.png)

**Comment by SBProX** [comment]
Для данных целей есть инструмент Range.
Посмотрите.

**Comment by Kirill5282** [comment]
> Для данных целей есть инструмент Range.
> Посмотрите.

Да я в курсе, но это инструмент крайне геудобен. На него даже нельзя поставить горячую клавишу, там нет окна с заранее предустановленными цветами. Чтобы нанести его на график и корректно настроить нужно совершить много лишних действий, а это всё время!
