### ISSUE TITLE
(ВАЖНО) Некорректное отображение цены на дневном графике для инструмента 6E

### ISSUE THREAD

**Issue by fallenAngelBad** [SBProX/SBProX-Dev#1278]
![tradingview_6E_день](https://user-images.githubusercontent.com/10365262/84563383-daa78280-ad63-11ea-87e2-557a2cbeec09.jpg)
![sbprox_6E_день](https://user-images.githubusercontent.com/10365262/84563385-dbd8af80-ad63-11ea-9979-9ec51cc841ed.jpg)

В программе SbProX на дневном графике инструмента 6E имеются лишние бары с очень маленькими объемами, данная проблема также была и в прошлой программе SbProV2. Прошу исправить данную проблему, т.к. это не позволяет проводить анализ по данному инструменту в рамках дневного графика, что в свою очередь ведет в кому, что приходится пользоваться разными сервисами для анализа рынка.

**Comment by SBProX** [comment]
Объемы отображаются корректно - это не лишний бары, это воскресенье по Чикаго.
Вы можете установить для данного инструмента другой часовой пояс, например Московский, и тогда будет все ок.
