### ISSUE TITLE
Предложение добавить RSI и AO на 4h

### ISSUE THREAD

**Issue by litensk** [SBProX/SBProX-Dev#1279]
Прошу добавить индикаторы RSI и AO, тк на 4h на них часто видна дивергенция/конвергенция, если это кому-то еще нужно, лайкайте, ставьте плюсы. На данный момент постоянно приходиться нырять в трейдингвью за ними, так же как и вручную прорисовывать линии последних open/close дневок, неделек, месяца, что реализовано в трейдингвью скриптами пользователей при просмотре меньших таймфреймов. С уважением.

**Comment by SBProX** [comment]
Предложений по тех. анализа сразу же отклоняются, мы не будем в ближайшее время делать индикаторы ТА. Это не профиль платформы.
