### ISSUE TITLE
Добавить канал

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#128]
Уважаемые разработчики, добавьте канал в панель рисования.

**Comment by vik62** [comment]
Поддерживаю.

**Comment by SBProX** [comment]
Подумаем.

**Comment by vomma** [comment]
Уважаемые разработчики, поддерживаю не хватает канала, и чтобы по средине была пунктирная линия как 1/2 канала (как на рисунке ниже) Благодарю заранее! Платформа супер!
 
![канал](https://user-images.githubusercontent.com/51166186/59005934-f024cb00-8838-11e9-84c0-4434ec795f44.jpg)
