### ISSUE TITLE
Price levels/Pivots/Initial balance/Round numbers индикаторы добавить

### ISSUE THREAD

**Issue by bdt253** [SBProX/SBProX-Dev#1280]
Идеи для улучшения. Пожалуйста, очень не хватает этих линий на графике, неудобно смотреть их в другом терминале
 
Opening price
Previous day high/low/close
Pivot points как в tradingview
Initial balance high/low c выбором времени
Rounds numbers автоматически выделять ближайшие круглые числа

**Comment by SBProX** [comment]
Предложения по реализации индикаторов ТА или всего что не касается объемной аналитики отклоняются. В ближайшее время мы будет заниматься только инструментами для анализа объемов.
