### ISSUE TITLE
Настройки комбинированного графика... предложение

### ISSUE THREAD

**Issue by indianaxxx** [SBProX/SBProX-Dev#1281]
Прописать в выпадающем окне настроек возможность установки столбца направление бара...было бы гораздо информативнее и появилась бы возможность более сжать график...
![образец 2](https://user-images.githubusercontent.com/54440183/84600293-b3e76a00-ae91-11ea-9f09-a8dce8b18a5d.jpg)

**Comment by Pikad0r** [comment]
+100500, Cool !!!
