### ISSUE TITLE
Перенос окна по экрану.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#1284]
Здравствуйте.
![image](https://user-images.githubusercontent.com/20509322/84626369-8b09b800-af17-11ea-9889-a5fcb2fd67ad.png)
- Желтой стрелкой обозначено область.
Окно программы нельзя перенести курсором мыши за эту область.
У меня часть окон свернуты.
Разворачиваю переношу - сворачиваю.

**Comment by Alexey316** [comment]
Подтверждаю. Тоже столкнулся с этим.

**Comment by SBProX** [comment]
Доработано, сегодня выйдет обновление.
