### ISSUE TITLE
Ошибка в на тестере

### ISSUE THREAD

**Issue by Neophyte666** [SBProX/SBProX-Dev#1285]
заметил ошибку под названием читерский тестер 
В расположении когда  выведен другой график  этого же инструмента с периодом старшего таймфрейма то при нажатии на младшем графике кнопки +1В  (или любое добавление бара ) добавляется 1 бар и младшего и старшего. Старший пероуд  в данном случае день только начался а  отрисовывается полный бар а не текущие данные. Сделайте пожалуйста дополнительную проверку в ходимости данных одного периода в другой и завершения старшего периода этими данными.  Потом идет полная разсинхронизация данных на всех графиках. 
Еще было бы супер если добавили кнопку отмотать обратно 1 бар.

[](url)https://prntscr.com/szzm3i

**Comment by SBProX** [comment]
Уже исправили.
Сегодня выйдет обновление.
