### ISSUE TITLE
Сделайте пожалуйста книгу ордеров в sbpro

### ISSUE THREAD

**Issue by igorzivt** [SBProX/SBProX-Dev#1288]
Возможно ли сделать книгу ордеров как в терминале bookmap? 
![bookmap-feature-screenshot (1)](https://user-images.githubusercontent.com/17834913/84678036-f7e97600-af48-11ea-8666-11a55b3769a8.jpg)

**Comment by trades1** [comment]
Поддерживаю!! Было бы очень полезно

**Comment by bravo1020** [comment]
Похоже на Qscalp, только там уже прошедшие сделки. А здесь крупные заявки можно смотреть что ли?

**Comment by igorzivt** [comment]
> Похоже на Qscalp, только там уже прошедшие сделки. А здесь крупные заявки можно смотреть что ли?

Здесь можно смотреть историю движения лимитников. Они остаются на графике. В qsqalp движение в стакане только в текущий момент. В bookmap все эти заявки остаются на чарте и в зависимости от цвета лимита можно определить какой он силы, чем темнее тем сильнее и значит его труднее пробить

**Comment by trades1** [comment]
Классная тема. Реально помогает, и не нужно гадать, какие были лимитки, в данный период времени.

**Comment by SBProX** [comment]
У нас нет данных по заявкам к сожалению.
Этот вопрос не решаемый в данный момент времени.
