### ISSUE TITLE
Не работает затемнение шрифта в bid/ask profile!

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#129]
![image](https://user-images.githubusercontent.com/50406792/57870902-c4518f00-7810-11e9-8b39-73cf44689a69.png)

**Comment by bizlis** [comment]
так же не работает затемнение на графике объем дельта профиль

**Comment by bizlis** [comment]
После обновления на графике объем дельта профиль так и не работает затемнение
![Screenshot_44](https://user-images.githubusercontent.com/29704362/58498205-fe1e8000-8196-11e9-96f0-997fef557881.jpg)

**Comment by SBProX** [comment]
У вас скорее всего не встало обновление корректно.
Удалите платформу полностью, и переустановите.

**Comment by bizlis** [comment]
вот один и тот же график, но отображается по разному (обновление ставил последнее)
![Screenshot_44](https://user-images.githubusercontent.com/29704362/58569083-e0145680-824e-11e9-8893-1b9a97e3701a.jpg)

**Comment by SBProX** [comment]
Вышлите скришоты настроек для сравнения

**Comment by bizlis** [comment]
Нашел проблему, в одном стоял фильтр 100, в другом 0, поэтому и различались, теперь вопросов нет
