### ISSUE TITLE
16-го июня. Новая версия не работает.

### ISSUE THREAD

**Issue by bravo1020** [SBProX/SBProX-Dev#1291]
Здравствуйте! Сегодня 16-го июня 2020, новая версия не работает. Работает только старая. Подробные скрины прилагаю. Помогите, пожалуйста, разобраться.

![2020_06_16_01](https://user-images.githubusercontent.com/66790463/84756601-adf5a400-afcb-11ea-9abe-afd3a3c7265c.png)
![2020_06_16_02](https://user-images.githubusercontent.com/66790463/84756612-b221c180-afcb-11ea-8d31-ace5e5e25391.png)
![2020_06_16_03](https://user-images.githubusercontent.com/66790463/84756620-b5b54880-afcb-11ea-81fb-8d02cb6770b4.png)
![2020_06_16_04](https://user-images.githubusercontent.com/66790463/84756635-ba79fc80-afcb-11ea-9257-aad18b54be92.png)

**Comment by SBProX** [comment]
Добрый день.

Напишите пожалуйста в тех поддержку.
