### ISSUE TITLE
Сделайте, пожалуйста режим Поверх всех окон (Always on top)

### ISSUE THREAD

**Issue by sp0yler** [SBProX/SBProX-Dev#1292]
Здравствуйте! Сделайте, пожалуйста, в будущих версиях этот простейший функционал.
Полезно для трейдеров с одним монитором (например, 4К).
Заранее спасибо!

**Comment by WebSurfer001** [comment]
отличная идея +

**Comment by SBProX** [comment]
Добрый день.

Сделали, будет работать в версии 5.0.19
