### ISSUE TITLE
Неравномерная подсветка линии

### ISSUE THREAD

**Issue by Quantum-G** [SBProX/SBProX-Dev#1295]
Неравномерная подсветка линии подсветка линии отвлекает, потому что порой создаёт ложное восприятие кластерного фильтра. Просьба исправить.
![Screen Shot 17 06 2020 at 3 24](https://user-images.githubusercontent.com/34577071/84841190-4df21280-b04a-11ea-8ef3-b22eb847f0da.png)

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by SBProX** [comment]
Исправлено. Будет работать в версии 5.0.19
