### ISSUE TITLE
17-е июня. Новая версия программы не работает.

### ISSUE THREAD

**Issue by bravo1020** [SBProX/SBProX-Dev#1297]
16-го июня я уже обращался к вам в тех.поддержку. Первые 3 часа новая версия программы не работала, потом появились бары. Сегодня 17-го история повторилась, работа пошла около 12-ти часов дня. Однако после 17-ти опять всё замерло. Кнопка Применить, чтобы перезапустить подгрузку данных, не помогает. Что делать?

![1](https://user-images.githubusercontent.com/66790463/84930625-424e2c80-b0da-11ea-9c4e-011eac1f883a.png)
![2](https://user-images.githubusercontent.com/66790463/84930648-48440d80-b0da-11ea-91e3-96c31c473f2d.png)
![3](https://user-images.githubusercontent.com/66790463/84930674-5003b200-b0da-11ea-8cc0-7dea3c9760c6.png)

**Comment by SBProX** [comment]
Вопросы касательно таких проблем решает тех. поддержка.
Вероятно вы не корректно настроили коннектор.

Я передам ваш тикет в тех. поддержку, Вам завтра напишут.

**Comment by bravo1020** [comment]
Спасибо!

**Comment by sbprosupport** [comment]
> Спасибо!

Добрый день.

Напишите пожалуйста в тех. поддержку для решения вашей проблемы:
Skype: strategy.builder
Тех. поддержка telegram: @sbprosupport
