### ISSUE TITLE
Не отображается объем за 17.06.2020 для 6E 

### ISSUE THREAD

**Issue by fallenAngelBad** [SBProX/SBProX-Dev#1298]
![2020-06-18_7-34-06](https://user-images.githubusercontent.com/10365262/84978922-d2ba5a80-b136-11ea-9887-49d426c96267.jpg)

Для инструмента 6E на дневном графике не отображается объем за 17.06.2020, при этом для rsED все нормально.

**Comment by SBProX** [comment]
Добрый день.

Данная проблема наблюдается при включении платформы, или она работала через ночь без выключения? Мы только что включили такой же график, объемы на месте.
Необходимо понять при каком сценарии появляется данная ошибка

**Comment by fallenAngelBad** [comment]
сейчас попытаюсь выключить платформу и запустить снова

**Comment by fallenAngelBad** [comment]
проблема ушла. сегодня утром, после обнаружения данной проблемы, первое, что я сделал - это перезагрузил платформу
