### ISSUE TITLE
Переход на новый контракт

### ISSUE THREAD

**Issue by galich2** [SBProX/SBProX-Dev#1299]
Сегодня 18, переход закрытие старого 6.20 на 9.20 должно быть вечером, а у меня уже с начала торгов 9.20
![image](https://user-images.githubusercontent.com/21958015/84988992-0657ad80-b154-11ea-91e2-001f6cf6655a.png)
![image](https://user-images.githubusercontent.com/21958015/84989266-77976080-b154-11ea-94f2-e2fda9955671.png)

**Comment by Alexey316** [comment]
У вас стоит Auto. Выбирайте нужный контракт вручную.
