### ISSUE TITLE
Добавьте пожалуйста инструменты

### ISSUE THREAD

**Issue by day-trade** [SBProX/SBProX-Dev#13]
Здравствуйте! Несколько лет пользуюсь вашей платформой. Очень не хватает основных активов для анализа, таких как СБер, Газпром, USDtom.  Хотя бы их добавьте. При торговле фьючерсами анализируются активы и было бы очень удобно иметь такую возможность в этой платформе. Очень надеюсь, что это будет реализовано.

**Comment by day-trade** [comment]
Здравствуйте! Несколько лет пользуюсь вашей платформой. Очень не хватает основных активов для анализа, таких как СБер, Газпром, USDtom. Хотя бы их добавьте. При торговле фьючерсами анализируются активы и было бы очень удобно иметь такую возможность в этой платформе. Очень надеюсь, что это будет реализовано.

**Comment by day-trade** [comment]
ИНТЕРЕСУЮТ ИМЕННО АКЦИИ, ПОМИМО ФЬЮЧЕРСОВ

**Comment by day-trade** [comment]
Торгуя фьючерсы, трейдеры анализируют активы. И было бы хорошо иметь возможность натягивать тот же профиль объёма на актив.

**Comment by day-trade** [comment]
Конкретно для меня, и думаю, для многих это серьёзный момент.  Без него на платформе по факту предлагаемых функций ничего не изменилось относительно старой версии программы. Сделайте это пожалуйста! Будет огромная польза и КАЧЕСТВЕННОЕ ДОПОЛНЕНИЕ.  Спасибо!

**Comment by day-trade** [comment]
Опять же намного правильнее иметь возможность анализировать кластера АКТИВА фьючерса

**Comment by SBProX** [comment]
Мы добавим инструменты, но это никак не относится к функционалу платформы.
На GitHub публикуются ошибки и предложения по разработке, добавление новых инструментов выходит за рамки GitHub.
