### ISSUE TITLE
Предложение по инструментам

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#130]
Нужно добавить отдельно рисование горизонтальной, вертикальной и по диагонали линии, а то сейчас нарисовать горизонтальную и вертикальную линию чтобы было ровно нужно очень сильно постараться)

**Comment by SBProX** [comment]
Платформа SBPro не для рисования, а для анализа объемов.
Мы как и раньше против нагромождений из серии метатрейдера.

**Comment by WillBegin1** [comment]
![image](https://user-images.githubusercontent.com/50406792/58099461-5af0c800-7be4-11e9-86bb-ff25917827f5.png)
Вот ребята вроде тоже не метатрейдером занимаются, но с инструментами всё нормально
И даёт возможность делать вот такие исследования и прошу заметить совсем не метатрейдерский подход
![image](https://user-images.githubusercontent.com/50406792/58099980-71e3ea00-7be5-11e9-8ebb-b6a366b5e435.png)
И вот такие вещи легко и непринужденно, а с вашей платформой если делать такие исследования, то можно от нервов поседеть)
![image](https://user-images.githubusercontent.com/50406792/58100193-d69f4480-7be5-11e9-917c-971357224b15.png)

**Comment by SBProX** [comment]
Хорошо, сделаем но чуть позже.
