### ISSUE TITLE
Рисованные фигуры

### ISSUE THREAD

**Issue by ws-keith** [SBProX/SBProX-Dev#1304]
Предложение. Просьба реализовать в следующем обновлении дополнительные функции по фигурам 
1. рисованные фигуры отображать на всех ТФ данного инструмента как на линиях (Дублировать на все графики)
2. При входе в рисованную зону срабатывало оповещение 
3. Добавить кнопку СКРЫТЬ все рисунки, по возможности и линии

**Comment by Vponed** [comment]
Полностью поддерживаю.
Также прошу добавить в настройки Сигналов комбобокс "Срабатывать только в зоне". Зону отмечать прямоугольником. Дельты и объемы нужны только в избранных местах графика, иначе они только отвлекают.

**Comment by Quantum-G** [comment]
Поддерживаю. Так же просил сделать реализацию скрытия линий и предлагал варианты

**Comment by Quantum-G** [comment]
https://github.com/SBProX/SBProX-Dev/issues/1070

Вот например

**Comment by WebSurfer001** [comment]
Полностью поддерживаю все предложения этого сильно не хватает.

**Comment by affectus1** [comment]
пункт номер 1 нужен очень. поддерживаю!

**Comment by indianaxxx** [comment]
+1

**Comment by tarassar** [comment]
отличная идея, поддерживаю

**Comment by SBProX** [comment]
Пункты 1 и 2 - этого делать не будем, так как много работы по другому функционалу.
Пункт 3 будет сделан в версии 5.0.19
