### ISSUE TITLE
прошу добавить ещё один временной интервал

### ISSUE THREAD

**Issue by pihot** [SBProX/SBProX-Dev#1305]
Вернее, это не совсем временной интервал. Свечи формируются по заданному количеству тиков в свече. Например, задаём значение 50, рисуется свеча в границах пятидесяти тиков и на 51 тике начинает формироваться новая свеча.... Я использую этот способ в МТ5 с помощью утилиты и было бы здорово добавить объём и дельту от SBProX. С уважением, Олег.

**Comment by indianaxxx** [comment]
https://github.com/SBProX/SBProX-Dev/issues/1173... вам сюда...

**Comment by SBProX** [comment]
В версии 5.0.19 будет данный функционал для тикового графика
