### ISSUE TITLE
Фьючерс rsRTS

### ISSUE THREAD

**Issue by AeraVentis** [SBProX/SBProX-Dev#1307]
В выпадающем списке по rs RTS контракты 3, 5, 7, 9-20, 5 и 7-20 это ошибка. Они должны быть квартальные 3 6 9 (в будущем 12), т. е. экспирация в марте, июне, сентябре, декабре.

**Comment by SBProX** [comment]
Добрый день.

На самом деле это ошибка в платформе, будет исправлено в версии 5.0.19
