### ISSUE TITLE
Импорт открытого интереса с сайта CME

### ISSUE THREAD

**Issue by vito-andolini** [SBProX/SBProX-Dev#1308]
Уважаемые разработчики,хотел бы предложить вам идею по реализации открытого интереса для западных инструментов.
С сайта CME можно попробовать импортировать открытый интерес для валют и не только,там он появляется по закрытию сессии(дня).
https://www.cmegroup.com/market-data/volume-open-interest/fx-volume.html ссылка на открытый интерес.

**Comment by trades1** [comment]
++

**Comment by SBProX** [comment]
Добрый день.

Мы не видим смысла в ОИ по итогу дня, если честно.
Да и пользователи тоже в основной массе, за три года может быть несколько человек просили добавить.
