### ISSUE TITLE
ошибка при коннекте 5.0.8 64

### ISSUE THREAD

**Issue by romanovvv1987** [SBProX/SBProX-Dev#1309]
ошибка при коннекте virtual_machine_error 
установленно на виртуалке виндус 10

**Comment by SBProX** [comment]
Обновитесь до последней версии 5.0.18.

**Comment by romanovvv1987** [comment]
![image](https://user-images.githubusercontent.com/6541829/85232723-d6393480-b409-11ea-9829-4bc4e9f8b724.png)
