### ISSUE TITLE
Weis Wave индикатор

### ISSUE THREAD

**Issue by trades1** [SBProX/SBProX-Dev#1311]
Индикатор WeisWave. Индикатор предназначен для торговли по стратегии Дэвида Вайса (David Weis). Технически данный индикатор состоит из 2-х индикаторов: первый накладывается на график инструмента и рисует последовательность трендовых движений (так называемый зиг-заг) по заданным условиям; второй индикатор располагается в отдельном окне и в виде гистограммы показывает суммарный объем в каждом трендовом движении накопительным итогом. 
Индикатор для определения спроса и предложения на любых рынках. Работает на любых объемах. Показывает суммарный объем в волнах.
Отлично показывает дивергенции, начало или конец тренда, наличие или отсутствие спроса/предложения в тренде.
Формула расчета
В индикаторе строятся цены, если разворот более чем на заданный параметр, то у идет движение в обратную сторону. Пока движение идет в одну сторону, объемы суммируются.
![1](https://user-images.githubusercontent.com/64479728/85208741-e2f35500-b343-11ea-9760-65909b092610.png)
![2](https://user-images.githubusercontent.com/64479728/85208742-e4bd1880-b343-11ea-98df-6a8bbee795ca.png)
<img width="320" alt="3" src="https://user-images.githubusercontent.com/64479728/85208744-e5ee4580-b343-11ea-9f45-0f32089692fb.png">
![21](https://user-images.githubusercontent.com/64479728/85208745-e5ee4580-b343-11ea-8ba1-5ab46fc7ef4c.png)

Прошу поддержать.

**Comment by SBProX** [comment]
Добрый день.

SBPro это платформа для анализа объемов, в ближайшее время мы точно не будем делать ничего из ТА или подобного.

**Comment by trades1** [comment]
А при чем здесь ТА, это не имеет к ТА никакого отношения.
кумулятивный объем это не объемы? Очень странно.
