### ISSUE TITLE
Элементы меню 

### ISSUE THREAD

**Issue by blalorvet** [SBProX/SBProX-Dev#1312]
Добрый день. 
Прошу прощения но цветные[ элементы меню](http://prntscr.com/t3hedb) это прошлый век. 
Если элементы объедены какой-то общей сущностью, в данном случае у нас элементы меню, то тогда они должны быть одинакового цвета размера и шрифта. 
Для меня как для пользователя цвета вообще ни о чем не говорят. Из-за того что пункты меню разного цвета читать их не удобно и это затрудняет навигацию по программе. 
Как пример возьмите меню любого крупного сайт, фейсбук, яндекс да хоть github.com, то увидите что меню всегда одного цвета.  При наведении или клике они меняются, чтобы дать понять пользователю, что действие произошло.  
Большая просьба сделать меню какого-то одного цвета, лучше черного с выделением фона при наведении. 

Спасибо.

**Comment by SBProX** [comment]
Добрый день.

Мы сделали гибкую систему, вы можете менять цвет.
Вот например пример с одним цветом:

![image](https://user-images.githubusercontent.com/16720120/85232413-6164fb00-b407-11ea-97b4-996e11580269.png)

Цвет нужен для подсветку каких то пунктов меню по желанию пользователя.

**Comment by blalorvet** [comment]
Спасибо
