### ISSUE TITLE
Стакан котировок

### ISSUE THREAD

**Issue by scalper02** [SBProX/SBProX-Dev#1313]
Здравствуйте дорогие разработчики! Во-первых хочу сказать Вам спасибо за оперативное решение вопросов по платформе. Теперь вопрос--есть ли возможность сделать стакан котировок на фьючерсах РТС? хотелось бы увидеть реализацию на графике рядом со свечами и в режиме симулятора. Заранее спасибо.

**Comment by SBProX** [comment]
Добрый день.

Спасибо за отзыв. 
Возможности сделать стакан пока что нет.
