### ISSUE TITLE
Проблемы с шаблонами

### ISSUE THREAD

**Issue by outallspaces** [SBProX/SBProX-Dev#1314]
Для того чтобы размножить визуальные настройки на несколько открытых окон прибегаю к следующему приему: сохраняю шаблон нужного окна и загружаю его для остальных окон, при этом при перезагрузке даты в одном окне начинается перезагрузка и в остальных, что не очень удобно и требует гораздо большего времени.

**Comment by SBProX** [comment]
У вас в настройках шаблона включена линковка?

**Comment by outallspaces** [comment]
Добрый день,

Поясните, пожалуйста, что имеется в виду? Я проверю

вс, 21 июн. 2020 г. в 21:34, SBPro X <notifications@github.com>:

**Comment by outallspaces** [comment]
С линковкой разобрался -проблема была в ней. Вопрос снят.

**Comment by SBProX** [comment]
Обращайтесь
