### ISSUE TITLE
Ошибка в симуляторе при нажатии кнопок "+1B", "+2B" и т.д. при нескольких графиках разных ТФ.

### ISSUE THREAD

**Issue by sevrer** [SBProX/SBProX-Dev#1315]
Обнаружена неправильная синхронизация графиков в симуляторе при побарной работе.
Открыть два графика одного инструмента разных таймфреймов.
Запустить симулятор и добавить оба графика
Нажать паузу.
На любом графике любого ТФ нажать кнопку "+1B".
В результате на каждом графике добавиться один бар его таймфрейме и графики потеряют синхронизацию.
![2020-06-21_172423](https://user-images.githubusercontent.com/266359/85227227-d07d2800-b3e4-11ea-9857-7f9c7f6d71d7.png)
![2020-06-21_172559](https://user-images.githubusercontent.com/266359/85227230-d1ae5500-b3e4-11ea-8d38-86612adaa333.png)

**Comment by SBProX** [comment]
Мы исправили данную проблему в версии 5.0.17.

Какая у вас версия?

**Comment by sevrer** [comment]
Вчера раза два скачивал с сайта новую версию и переустанавливал. Каждый раз после переустановки была версия 5.0.9.
Сегодня установилось свежее обновление 5.0.19 и ошибка пропала. Кроме этого, кнопки теперь называются не "+1В", "+2В", а "+1TF", "+2TF" и т.д., что считаю логичным.
Тикет можно закрывать.
