### ISSUE TITLE
Ошибки в агрегированном тиковом графике

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1316]
![image](https://user-images.githubusercontent.com/50357928/85250238-a9fbd300-b45e-11ea-92c1-ee4f4a306008.png)

1. какие то непонятные разрывы, текущие цены не показывает
2. bars volume highlight и bars deta highlight не работают, полностью убирают свечи

**Comment by SBProX** [comment]
Спасибо, исправим. Если нажать Apply то все встанет нормально.

**Comment by SBProX** [comment]
Проверьте пожалуйста, бага быть не должна уже в 5.0.20
