### ISSUE TITLE
Bars delta highlight и bars volume highlight, возможность накладывать индикатор на график кластер/дельта профиль.

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1318]
было бы отлично иметь возможность подсвечивать этими индикаторами полоску направления бара на несвечных графиках

**Comment by SBProX** [comment]
Спасибо за предложение, но нет.

**Comment by SBProX** [comment]
Используйте направление бара и индикатор объема если вам необходимо
