### ISSUE TITLE
не видны значения индикаторов

### ISSUE THREAD

**Issue by koroniova** [SBProX/SBProX-Dev#132]
из-за названия индикаторов не видны значения текущих баров.
значения накладываются на названия индикаторов!

https://drive.google.com/open?id=1mT7f8zYJZ1rrDm7_U-bavJvnM7mUITy6

**Comment by Fen8fen** [comment]
chart settings - general - other - Hide indicator name

**Comment by koroniova** [comment]
спасибо!
