### ISSUE TITLE
Не запускается SBProX

### ISSUE THREAD

**Issue by Alexey316** [SBProX/SBProX-Dev#1326]
![SBProX](https://user-images.githubusercontent.com/58070921/85364594-a85d0880-b54d-11ea-9f4b-e7ff6add355b.png)

**Comment by Alexey316** [comment]
Спустя много попыток программа запустилась. Но не хотелось бы повторения.

**Comment by SBProX** [comment]
С такими вопросами нужно обращаться в тех. поддержку.
Мы программисты, мы не занимаемся решением технических проблем у пользователей.
У нас все работает в штатном режиме.

**Comment by Alexey316** [comment]
Понял. Просто техподдержка в скайпе отвечает через час и даже позже.
