### ISSUE TITLE
Глюк с уровнем

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#1327]
На дневном графике установил уровень и сделал дублирование на все графики
![Screenshot_1](https://user-images.githubusercontent.com/29704362/85371642-0556bf80-b54a-11ea-8fb3-d25e6958fa99.jpg)
Вот как выглядит уровень на четырех часах (выделено красным прямоугольником)
![Screenshot_2](https://user-images.githubusercontent.com/29704362/85371685-1a335300-b54a-11ea-806b-0459ca48015b.jpg)

**Comment by bizlis** [comment]
отредактировал уровень на Н4, линия растянулась на весь график на D1

**Comment by AlTuzov** [comment]
Таже история и с залинкованными уровнями.

**Comment by Vitaly-198** [comment]
Поддерживаю,имеется такой глюк!

**Comment by SBProX** [comment]
Принято, исправим.
