### ISSUE TITLE
Ошибка коррелятора

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1328]
После обновления коррелятор стал прогружаться неправильно
![2020-06-23_10-06-06](https://user-images.githubusercontent.com/18483236/85371714-6033eb00-b539-11ea-98d8-6966ee3567a3.png)

После нажатия аплай - ошибка пропадает
![2020-06-23_10-06-45](https://user-images.githubusercontent.com/18483236/85371751-73df5180-b539-11ea-811c-935da56faddc.png)

**Comment by SBProX** [comment]
Принято, проверяем.

**Comment by SBProX** [comment]
Исправлено, будет работать в версии 5.0.21
