### ISSUE TITLE
Ошибка коррелятора 2

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1329]
После нажатия аплай - через 5 минут вот такие сопли
![2020-06-23_10-10-12](https://user-images.githubusercontent.com/18483236/85372051-ecdea900-b539-11ea-9811-18ff40f2fbeb.png)

![2020-06-23_10-21-46](https://user-images.githubusercontent.com/18483236/85373192-95d9d380-b53b-11ea-96be-9059dfc7e2ca.png)

![2020-06-23_13-36-33](https://user-images.githubusercontent.com/18483236/85394070-aea3b280-b556-11ea-975c-2a55d50f9485.png)

**Comment by SBProX** [comment]
Правильно ли я понимаю, что это уже в процессе работы такое появляется?

**Comment by ershner** [comment]
@SBProX Да - во время работы

**Comment by SBProX** [comment]
Исправлено, будет работать в версии 5.0.21
