### ISSUE TITLE
Неадекватное торможение при загрузке тикового графика после последнего обновления

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1332]
![image](https://user-images.githubusercontent.com/50357928/85382052-3f729200-b547-11ea-97e8-442861ad5b36.png)
512т с периодом 4 дня грузится уже пол часа, вчера загружался нормально, за исключением глюка со временем

**Comment by r0b4ik** [comment]
В итоге так и не загрузились тиковые графики. Infinite loop

**Comment by pihot** [comment]
На тиковом графике, при установке птички на агрегаци и указании количества сделок, SBProX просто виснет и всё.....

**Comment by SBProX** [comment]
Хорошо, проверим.
Можете выслать скриншот настроек которые ставите?

**Comment by SBProX** [comment]
Так же вопрос: были ли на график нанесены ранее какие-то линии или графические объекты?

**Comment by pihot** [comment]
![1111](https://user-images.githubusercontent.com/21319747/85621305-5d361900-b665-11ea-98c9-ef116e82cd3f.png)
Графических объектов ещё никаких нет, просто только начинаю строить тиковый график.Цифра в строке"количество сделок" сути дела не меняет - SBProX замирает на всегда...

**Comment by SBProX** [comment]
Исправлено, будет работать в версии 5.0.21
