### ISSUE TITLE
Ошибка при выводе индикации на график

### ISSUE THREAD

**Issue by WebSurfer001** [SBProX/SBProX-Dev#1335]
Если включить индикатор bars delta highlight то свечи перекрывают индикацию.

![image](https://user-images.githubusercontent.com/66634368/85404141-3396c800-b567-11ea-9f02-4200a685dd9e.png)

**Comment by SBProX** [comment]
Принято, исправим.

**Comment by SBProX** [comment]
Это не ошибка, необходимо расположить индикаторы в правильной последовательности.
Bars Delta Highlight - это тоже индикатор, как и остальные.
Поэтому его нужно переместить в верх списка.

![image](https://user-images.githubusercontent.com/16720120/85684189-8f339380-b6d6-11ea-96ec-5fd9d56271b4.png)
