### ISSUE TITLE
Еще ОШИБКА в симуляторе

### ISSUE THREAD

**Issue by korepanoff90** [SBProX/SBProX-Dev#1339]
Покажу на примере (смотреть по ссылке - https://prnt.sc/t5pupl )
Открыты 2 графика одного инструмента на разных ТФ. Открывая сделки только по одному из графиков проблем нет.
НО!!!  Если открыть сделки, скажем на Н1 и выставить тейки по Д1 (помечены стрелочкой), то это быдут совершенно разные сделки.

 Надо сделать так, чтобы управлять одной сделкой можно было и с консоли графика Н1 и с консоли графика Д1
(т.е. - купил по рынку на графике Н1, выставил стоп и тейк на графике Д1 и эти стоп и тейк были видны на графике Н1 и открытая сделка сработает или по стопу или по тейку)

**Comment by SBProX** [comment]
Добрый день.

Это не ошибка, так изначально было задумано, чтобы на разных графиках можно было торговать разные стратегии одновременно. 
Конечно мы можем сделать синхронизацию, но это не сейчас точно.
