### ISSUE TITLE
Рисовалка

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#134]
Здравствуйте! Можно ли добавить в "Инструменты" элемент рисования - ручка/карандаш? Чтобы можно было рисовать по графику. 
Спасибо!

**Comment by makhitrov** [comment]
Eric Pen, хороший инструмент для рисования и не нужно лишнего

**Comment by SBProX** [comment]
Еще раз хотелось бы повторить, что профиль платформы это не инструменты рисования, а анализ объемов.

**Comment by stason251187** [comment]
Да, согласен. Спасибо!
