### ISSUE TITLE
Изменение инструмента в корреляторе

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1342]
В корреляторе нельзя поменять добавленные инструменты на другие. Только через удаление и добавление.
![2020-06-25_10-25-27](https://user-images.githubusercontent.com/18483236/85675654-948ce000-b6ce-11ea-920f-889bdb5b583d.png)

**Comment by SBProX** [comment]
Да, верно.
К сожалению так и будет пока.
