### ISSUE TITLE
Отображение клаудов на аггрегированном тиковом графике

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1348]
Вот такая сопля из клаудов
![2020-06-25_19-44-36](https://user-images.githubusercontent.com/18483236/85762845-d04e9680-b71c-11ea-8cd3-9ef55e06695a.png)

При отключении отображения клаудов - сопля пропадает
![2020-06-25_19-44-50](https://user-images.githubusercontent.com/18483236/85762984-f3794600-b71c-11ea-84a6-536109aad962.png)

**Comment by SBProX** [comment]
Принято, исправим.

**Comment by SBProX** [comment]
Добрый день.

Исправлено в версии 5.0.22
