### ISSUE TITLE
PRICE TICKER TIME & RULER

### ISSUE THREAD

**Issue by 41of1** [SBProX/SBProX-Dev#1349]
Увеличить размер шрифтов текущего времени и рулетки до размера шрифта перекрестья. # #
![2020-06-25_13-10-34](https://user-images.githubusercontent.com/51477821/85769822-07c04180-b723-11ea-8ecf-fa19fc035cb9.png)

**Comment by SBProX** [comment]
Шрифт линейки исправили, но увеличивать данные шрифты мы не будем.
