### ISSUE TITLE
Автопротягивание фигур

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#135]
https://monosnap.com/file/ncSHLIxFp5QF18tMRaLkvT2VqXGMPq
Уважаемые разработчики, добавьте пожалуйста в окно настройки фигуры галочку "протянуть вправо", при активации которой, фигура бы автоматически протягивалась вправо вслед за графиком. А то не очень удобно тянуть нанесенные зоны руками.

**Comment by WillBegin1** [comment]
Поддерживаю предложение!!! Особенно прямоугольник! Т.к. нет возможности нарисовать уровень как диапазон, либо в линиях на ценовой шкале, что-то придумать типа этого
![image](https://user-images.githubusercontent.com/50406792/57922120-ab47ed00-78a7-11e9-9edd-e6a3edf10729.png)

**Comment by SasasSasas** [comment]
Это очень удобно. Поддерживаю! Сильно не хватает этого функционала.

**Comment by vik62** [comment]
Поддерживаю.

**Comment by Ravil124** [comment]
Поддерживаю.

**Comment by NikolaiBogachev** [comment]
Поддерживаю ,а еще добавить копирование на другие графики как с линиями.

**Comment by bizlis** [comment]
Поддерживаю

**Comment by r35p3ct** [comment]
Я предлагал, они отвергли. Только я предлагал установить дату начала фигуры и окончания, чтобы не сидеть и не тянуть несколько экранов прямоугольник.

**Comment by vasiliyyun** [comment]
Уважаемые разработчики, обратите пожалуйста внимание на данное предложение. Оно существенно облегчит работу с графиками.

**Comment by SBProX** [comment]
Проблема в том, что мы не хотим тратить время на инструменты рисования. Поймите нас правильно.
Это не профиль платформы. Когда закончим с основными инструментами, тогда будем дорабатывать все второстепенное.

**Comment by dmo21749** [comment]
Все таки, очень не хватает данной функции.
