### ISSUE TITLE
Баг с линиями

### ISSUE THREAD

**Issue by NikolaiBogachev** [SBProX/SBProX-Dev#1352]
На недельном графике не ставится линия с начальной точкой а только сплошная. если ставишь ценовую линию с начальной точкой ниже недели то на всех графиках она отображается нормально кроме недельного там она сплошная .

**Comment by SBProX** [comment]
Принято, исправим.

**Comment by SBProX** [comment]
Добрый день.

Исправлено в версии 5.0.22
