### ISSUE TITLE
Cumulative Delta Ошибка

### ISSUE THREAD

**Issue by dmo21749** [SBProX/SBProX-Dev#1354]
У Вас Кумулятивная дельта вообще не правильно отображается, сравнил с Тайгером и ТрейдВив.
А так же не мешало бы сделать выбор Колонок или свечей.
![11](https://user-images.githubusercontent.com/52744561/85842229-cda17f00-b7b8-11ea-9c06-e74995aa39ed.jpg)
![12](https://user-images.githubusercontent.com/52744561/85842256-d85c1400-b7b8-11ea-96d8-f7e8752ea73c.jpg)
![13](https://user-images.githubusercontent.com/52744561/85842264-dc883180-b7b8-11ea-8dd2-ae98a96aeede.jpg)

**Comment by SBProX** [comment]
Почитайте пожалуйста инструкцию.
Необходимо ставить Daily cumulative delta, а не Cumulative delta.

![image](https://user-images.githubusercontent.com/16720120/85872294-33e9ca00-b7d8-11ea-99ea-8d8cd4bdc2a5.png)

**Comment by dmo21749** [comment]
Понял.
Тогда предложение по выбору свечей или колонок остается.
