### ISSUE TITLE
Отображение клаудов на аггрегированном тиковом графике #1348

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1359]
После обновления - если включить клауды на аггрегированном тиковом графике - графики просто не загружаются(грузятся бесконечно)
![2020-06-26_19-25-33](https://user-images.githubusercontent.com/18483236/85879531-3a317380-b7e3-11ea-9e02-3d9ec8c8cef0.png)

**Comment by SBProX** [comment]
Ничего подобного не наблюдается:

![image](https://user-images.githubusercontent.com/16720120/85908867-a29e4600-b81f-11ea-9bc3-3994fad33c75.png)

Вышлите скриншот настройки Cloud пожалуйста

**Comment by SBProX** [comment]
Пробовали включать на любых агрегациях с любыми настройками, никаких проблем нет.

**Comment by ershner** [comment]
![2020-06-30_16-48-11](https://user-images.githubusercontent.com/18483236/86137124-93f0b100-baf5-11ea-98fe-2d2622c60961.png)

**Comment by SBProX** [comment]
Проблема решена в версии 5.0.24
