### ISSUE TITLE
Дублирование и удаление линий

### ISSUE THREAD

**Issue by AlTuzov** [SBProX/SBProX-Dev#136]
У меня настроенно несколько окон и в каждом по нескольку графиков разных ТФ по RI.
При дублировании линий с графика одного ТФ на график этого-же ТФ всё дублируется нормально. При дублировании линий на младший ТФ часть линий пропадает. Возможно это связано с тем что я использую график Кластер профиль и на разных ТФ у меня  установлен разный шаг цены. Хотелось бы это как-то поправить.

При использовании функции "Удалить все линии", линии удаляются на всех графиках выбранного окна. Возможно так и задумано, но хотелось бы иметь возможность удалять все линии только с одного выбранного графика.

**Comment by SBProX** [comment]
Да, это из-за разного шага цены.
Это никак не подправить, если вы копируете линию с ценой 1000, а такой цены нет на другом графике с измененным шагом цены, то как мы ее можем добавить? Это нереально.

**Comment by SBProX** [comment]
По поводу линий - да, это ошибка, исправим.

**Comment by AlTuzov** [comment]
> Да, это из-за разного шага цены.
> Это никак не подправить, если вы копируете линию с ценой 1000, а такой цены нет на другом графике с измененным шагом цены, то как мы ее можем добавить? Это нереально.

А почему нельзя сделать чтобы линия ложилась на ближайший доступный уровень. Например, если линия была на цене 1000 и такой цены нет на другом графике, но есть 1002 и 998, то если линия выше текущей цены, то она бы легла на 998, а если ниже, то на 1002? И всё было бы отлично.

**Comment by SBProX** [comment]
Получаются разночтения.
Копируешь линию с ценой 1000, а вставляется линия с ценой 998.
Тех поддержка не выдержит потока писем по этому поводу.

**Comment by SBProX** [comment]
С удаление ошибку исправили, будет работать с следующем обновлении.

**Comment by AlTuzov** [comment]
> Получаются разночтения.
> Копируешь линию с ценой 1000, а вставляется линия с ценой 998.
> Тех поддержка не выдержит потока писем по этому поводу.

В Волфиксе всё работает. Возможно стоит просто поискать подходящее решение. Иначе дублирование линий имеет смысл только на свечах и барах, а например мне эти графики нужны меньше всего.

**Comment by SBProX** [comment]
Волфикс - это волфикс. Спасибо, мы подумаем.

**Comment by SBProX** [comment]
Сделано
