### ISSUE TITLE
Может сами тоже будете проверять, что "наисправляли"?

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1362]
На тиковом графике опять разрывы, неправильное время, а линию с начальной точкой поставить вообще невозможно. 
Неужели программист не может проверить после себя то, что накодил?!  
Тут первый попавшийся день, любое кол-во тиков и глюк налицо. Тем более, что эту ошибку вроде уже исправляли в предыдущем обновлении.
![image](https://user-images.githubusercontent.com/50357928/85893034-baaf9e80-b7fa-11ea-8a5b-7faf497153b4.png)

**Comment by SBProX** [comment]
У нас никаких разрывов не наблюдается.

![image](https://user-images.githubusercontent.com/16720120/85908715-e5135300-b81e-11ea-9edb-5e38e481634a.png)

**Comment by SBProX** [comment]
Кроме того, в последнем обновлении не было ничего написано про исправления насчет разрывов графика.
Поэтому ваши претензии на данный момент не уместны.

В ближайшее время мы попробуем с вами связаться, и выяснить в чем именно проблема, так как то что отображено на вашем скриншоте у нас никак не воспроизводится. Все работает хорошо.

**Comment by SBProX** [comment]
У вас явно происходит дублирование графика. 
Какой коннектор у вас выбран для западных инструментов?

**Comment by SBProX** [comment]
Напишите пожалуйста в telegram  @sbproofficial во вторник, попробуем разобраться в чем проблема. 

Спасибо.

**Comment by r0b4ik** [comment]
> У вас явно происходит дублирование графика.
> Какой коннектор у вас выбран для западных инструментов?

коннектор SBpro
