### ISSUE TITLE
Ошибка даты указываемой перекрестием.

### ISSUE THREAD

**Issue by Tahir1081** [SBProX/SBProX-Dev#1365]
Дата указываемая перекрестием на дневном графике не совпадает с датой на панели даты и указывает неверные значения.
![Аннотация 2020-06-28 103232](https://user-images.githubusercontent.com/28987359/85941552-4b39cc00-b92c-11ea-8748-12c46fc80ab9.jpg)

**Comment by upeko** [comment]
Подтверждаю тоже самое по всем активам

**Comment by MichMN19** [comment]
По российским бумагам это только на дневках.

**Comment by Hellenk** [comment]
Да тоже

**Comment by SBProX** [comment]
Проблема решена в версии 5.0.24

**Comment by MichMN19** [comment]
...а где посмотреть номер версии в программе? 03.07.2020, 16:59, "SBPro X" <notifications@github.com>: Проблема решена в версии 5.0.24—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tahir1081** [comment]
Правая кнопка-Информация-Logs-Логи приложения
