### ISSUE TITLE
Вертикальная гистограмма

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#137]
Просьба убрать закругление нижних гистограмм или добавить галку чтобы можно было убрать это закругление + ко всему чтобы можно было настраивать цвет шрифта каждой гистограммы отдельно и можно ещё добавить функцию затемнения шрифта, как сделали на фильтры

**Comment by Flawmaster** [comment]
Поддерживаю! Закругления очень режут глаз.

**Comment by Ravil124** [comment]
Да, закругления очень мешают.

**Comment by Artem074** [comment]
Поддерживаю! Закругление убрали в кластерах, уберите у индикаторов!

**Comment by koroniova** [comment]
поддерживаю

**Comment by dvdenic** [comment]
Согласен. Закругление мешает. Так же было бы не плохо добавить регулировку ширины столбцов в гистограммах. Мне кажется, что когда сжимаешь график и исчезает закругление, то это и есть оптимальная ширина для гистограмм (хорошо читаются).

**Comment by vasiliyyun** [comment]
Полностью поддерживаю! Закругление не нужно.

**Comment by SBProX** [comment]
Хорошо, добавим опцию.

**Comment by SBProX** [comment]
Сделано
