### ISSUE TITLE
Лупа на комбинированных графиках должна быть!

### ISSUE THREAD

**Issue by DariaUnique** [SBProX/SBProX-Dev#1371]
Всё в названии. Лупа на комбинированных графиках чрезвычайно необходима. У меня настроены все пары практически только по комбинированным графикам, поскольку расположение и значение дельты и объемов важно по стратегии, а комбинированные графики создают полную картину. Это, помимо прочего, экономит место на мониторах. Постоянно возникает необходимость взглянуть поближе. А лупа, такая необходимая именно в таких ситуациях - отсутствует.

**Comment by ws-keith** [comment]
+

**Comment by ws-keith** [comment]
+

**Comment by Din-sys** [comment]
+

**Comment by indianaxxx** [comment]
+1

**Comment by SBProX** [comment]
К сожалению это технически сложно сделать.
