### ISSUE TITLE
Не загружаются шаблоны и обновления

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#1372]
На втором компьютере программа перестала обновляться и не подгружаются шаблоны
Крайнее обновление 9 июня 2020 г.
Переустановка не помогла. 
Когда программа подгружает сохраненные шаблоны и пространства с сервера, то загрузка останавливается на одном шаблоне и не закончив загрузку до конца разрешает делать подключение.
![Screenshot_1](https://user-images.githubusercontent.com/55657161/86032431-04d59180-ba40-11ea-8049-89b9ba1f23c0.png)

![Screenshot_2](https://user-images.githubusercontent.com/55657161/86032444-0a32dc00-ba40-11ea-8365-7d7d36c1ba4f.png)

На первом компьютере всё с сервера загружается, даже вновь созданные на втором рабочие пространства и шаблоны

**Comment by SBProX** [comment]
Проверьте в версии 5.0.24 должно работать
