### ISSUE TITLE
Рамка МАКС.объёма на комбинированном графике

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#1373]
Не отключается
На дельте без проблем.
![Screenshot_1](https://user-images.githubusercontent.com/55657161/86033829-3cddd400-ba42-11ea-9473-4085137dc3d7.png)

**Comment by e2e4Konstantin** [comment]
Да поддерживаю.
Рамки эти надоели.

**Comment by SBProX** [comment]
Исправили, сегодня выложим обновление
