### ISSUE TITLE
В всплывающие подсказки добавить hotkey

### ISSUE THREAD

**Issue by RoketAnny** [SBProX/SBProX-Dev#138]
Обнаружил что в программе уже работают горячие клавиши, а вот подсказок по ним нет

Добавьте пожалуйста.

![hint](https://user-images.githubusercontent.com/18662109/57931773-e2c39300-78c1-11e9-87b2-b6f17a327641.jpg)
#

**Comment by SBProX** [comment]
Хорошо, добавим.

**Comment by SBProX** [comment]
Сделано
