### ISSUE TITLE
Индикация текущего дня на временной шкале

### ISSUE THREAD

**Issue by EvgenMGN** [SBProX/SBProX-Dev#1382]
При движении мышкой по графику на временной шкале подсвечивается текущий вертикальный период, например день. Номер дня (дата) при этом отображается неправильно, на шкале "30.06", при подсветке отображается "29.06.20".
Пример на скриншотах.

![Screenshot_118](https://user-images.githubusercontent.com/53474049/86434610-4e133300-bd17-11ea-9ae0-4d94e3c8f46f.png)
![Screenshot_119](https://user-images.githubusercontent.com/53474049/86434616-50758d00-bd17-11ea-9b55-bc7f449ca64c.png)

**Comment by SBProX** [comment]
Проблема решена в версии 5.0.24
