### ISSUE TITLE
Продолжение истории с тиковыми графиками.

### ISSUE THREAD

**Issue by anatolev1122** [SBProX/SBProX-Dev#1387]
Писал на почту, присылал видео с отображением безобразия та тиковом графике, причем именно агрегированном по количеству тик, продублирую здесь, определенно их надо докрутить, в таком виде как сейчас пользоваться ими не возможно, при загрузке обычных тиковых с фильтрацией, ни каких проблем не наблюдается.
[2020-07-03 16-04-30.zip](https://github.com/SBProX/SBProX-Dev/files/4869995/2020-07-03.16-04-30.zip)

**Comment by SBProX** [comment]
Добрый день.

Версия 5.0.24?

**Comment by anatolev1122** [comment]
08.07.2020, 19:59, "SBPro X" <notifications@github.com>:
Добрый день.
Версия 5.0.24?

**Comment by anatolev1122** [comment]
Здравствуйте, Даже новее  5.0.2508.07.2020, 19:59, "SBPro X" <notifications@github.com>:
Добрый день.
Версия 5.0.24?

**Comment by SBProX** [comment]
На данный момент проблемы не наблюдается, проверили работу профилей.
Если у вас проблема еще есть - то тогда необходимо чтобы выслали настройки графика, и точные даты на которые такое возникает.
