### ISSUE TITLE
Часовой пояс. Проблема!!!

### ISSUE THREAD

**Issue by Velikodushniy** [SBProX/SBProX-Dev#1389]
![Time](https://user-images.githubusercontent.com/56736314/86493241-2dd08c00-bd8a-11ea-8616-737ca0032c71.jpg)

**Comment by Velikodushniy** [comment]
Время отображается неправильно как на Курсоре Перекрестие, так и на Панели времени.

**Comment by SBProX** [comment]
Эта ошибка была исправлена в версии 5.0.24, у нас все нормально.

**Comment by Velikodushniy** [comment]
Все верно ошибка уже исправлена. Спасибо за оперативность!
