### ISSUE TITLE
Сужение и расширение графика .

### ISSUE THREAD

**Issue by tradingpro-nesterov** [SBProX/SBProX-Dev#1397]
Здравствуйте ! Возможно ли установить реверс на  функцию - сужение и расширение графика, думаю для многих ваша настройка  не привычна  ,так как обычно когда тянешь график направо ,он должен сужаться , у вас же наоборот . Это очень не удобно ,поэтому компромис был бы очевиден ,если в настройках добавить реверс на эту функцию .

**Comment by indianaxxx** [comment]
В SBPro как и в МТ... и никакого дисонанса...

**Comment by tradingpro-nesterov** [comment]
indianaxxx ,это лишь частное мнение, так к приверу  в QUIK  - терминал с которого все начинали ,а так же на многих других платформах управление расширением обратно как в SBPro ,это как вдруг выехать на дорогу с левым движением ,диссонанс высокий , окошко с галочкой для реверса сняло бы все неудобства .

**Comment by indianaxxx** [comment]
...уважаемый, в истории тикетов есть куча действительно нужных и не реализованных предложений и улучшений.... а данное, в моём личном понимании, "косметическое" изменение никак не влияющее качественно на анализ... поэтому и не хочется чтобы ребята-разрабы распылялись по мелочам...
