### ISSUE TITLE
SBProX  - Название индикаторов

### ISSUE THREAD

**Issue by vpaks** [SBProX/SBProX-Dev#14]
Пожалуйста название индикаторов переместите на левую сторону окна, так как в текущем варианте они мешают (отвлекают) смотреть значения данных с индикаторов, при условии, если смещение графиков задать меньше 80. И название самих индикатор сделаны слишком крупно и жирным шрифтом. К примеру: Open Interect_1

**Comment by ershner** [comment]
https://github.com/SBProX/SBProX-Dev/issues/6#issue-440796716

**Comment by SBProX** [comment]
Если отвлекают, вы можете их отключить.
Если данный вариант решения вопроса не устраивает, то тогда мы оставим данный тикет.

**Comment by vpaks** [comment]
Спасибо, отключил. Можно так оставить, если это сложно в реализации

**Comment by SBProX** [comment]
Это не сложно, но не хочется делать лишнюю работу, времени мало до выхода релиза.
