### ISSUE TITLE
Ошибка в симуляторе.

### ISSUE THREAD

**Issue by NikolaiBogachev** [SBProX/SBProX-Dev#140]
При ведении сделок на одном тайм фрейме и при заключении сделки  в другом окне с другим тайм фреймом  сделка не отображается или не фиксируется на графике кривой статистики .

**Comment by SBProX** [comment]
Так и задумано.
Это сделано специально, так как вы можете одновременно на одном инструменте тестирования разные стратегии - например, одновременно купить и продать.
