### ISSUE TITLE
Пропадают сделки на агрегированном тиковом графике

### ISSUE THREAD

**Issue by Mihaliych** [SBProX/SBProX-Dev#1407]
9 июля/16:31:36/RIU При постановке галочки "тиковая агрегация" происходит во такое интересное изменение ОИ. Прошло 3 контракта по аску, а ОИ увеличился на 10. очевидно, что при любом раскладе такого не может быть.

http://pix.academ.info/img/2020/07/09/dbcbfc520743e026d69097012b1bce62.png
http://pix.academ.info/img/2020/07/09/c0c8a381cf2ff2b54b9c24d3d6085233.png

снимаем галочку "тиковая агрегация" и видим, что по аску прошло не 3 контракта, а 5. Впрочем как и по биду до этого прошло не 17 контрактов!

http://pix.academ.info/img/2020/07/09/0654fcef5e340b53b20f9441fc352cb7.png

отсюда вопрос: как работает тиковая агрегация? 
из инструкции: "При включенном режиме “Тиковая агрегация” тики, прошедшие за 1 миллисекунду, будут суммироваться в один кластер".  Мне кажется где-то ошибка: или в инструкции, или при суммировании

ps Так же хотелось бы напомнить о другой ошибке https://github.com/SBProX/SBProX-Dev/issues/1115, где я дал подробный ответ с картинками, но не понял увидели вы его или нет.

**Comment by SBProX** [comment]
Да, действительно есть ошибка с пропаданием сделок.
Сегодня выложим обновление с исправлением.

По поводу ОИ - если проходит сделка, например в 2 контракта, это не значит что и ОИ изменится на 2 контракта.
Посмотрите как в других платформах меняется ОИ
