### ISSUE TITLE
Смещение границ кластера.

### ISSUE THREAD

**Issue by Ravil124** [SBProX/SBProX-Dev#141]
Границы кластера смещены относительно границ профиля и горизонтальной линии.

![1](https://user-images.githubusercontent.com/24837011/57957951-9c008800-7917-11e9-88f9-464c423e8d6d.png)

**Comment by Alkor135** [comment]
Согласен, есть смещение. Причем при сжатии оно может усиливаться.
Вот увеличенная картинка сжатого графика, и на ней видно приличное смещение линии направления бара.
![2019-05-22_203507](https://user-images.githubusercontent.com/50710452/58196104-31ae6580-7cd2-11e9-8e00-d41beb8360bc.png)

**Comment by alexgherco** [comment]
GC, M15, 23 мая 9:15 по бирже.
Кажется - ПРЕДПОСЛЕДНИЙ уровень цены
![image](https://user-images.githubusercontent.com/2143904/58262679-60d0df80-7d83-11e9-9b12-9edcd4d89c61.png)
а вот и нет, это ХАЙ.
![image](https://user-images.githubusercontent.com/2143904/58262766-8bbb3380-7d83-11e9-99c4-dc9873d97051.png)
