### ISSUE TITLE
Тестер встает при переходе на следующий день

### ISSUE THREAD

**Issue by Vponed** [SBProX/SBProX-Dev#1413]
![image](https://user-images.githubusercontent.com/60276844/87330168-cf9d6900-c540-11ea-8fb8-4d9e34a67010.png)
Если нажимать кнопку +1ТФ. При обычном переходе все нормально. Пользоваться очень неудобно.

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении
