### ISSUE TITLE
Не отображается на графике последняя сессия.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1415]
Обратил внимание, что на следующий день при загрузке SBProX не загружается последняя сессия независимо от инструмента. 14.07.2020 это Вторник, а 10.07.2020 это Пятница.
![Snap_14 июля 2020 г _10h43m01s_003_](https://user-images.githubusercontent.com/24631570/87368017-dd460380-c5bf-11ea-8da4-bb1604774805.png)

**Comment by gengal** [comment]
![Snap_14 июля 2020 г _10h56m48s_004_](https://user-images.githubusercontent.com/24631570/87368342-c48a1d80-c5c0-11ea-82e4-5197ba5a8fc8.png)

**Comment by gengal** [comment]
![Snap_14 июля 2020 г _10h58m27s_006_](https://user-images.githubusercontent.com/24631570/87368424-fb603380-c5c0-11ea-8dfa-c57e4f53276b.png)

**Comment by gengal** [comment]
![Snap_15 июля 2020 г _10h57m12s_001_](https://user-images.githubusercontent.com/24631570/87490824-fc10cc80-c689-11ea-8886-a27f92a413c5.png)
Та же картина. Не отображается последняя сессия на следующий день.

**Comment by gengal** [comment]
![Snap_15 июля 2020 г _10h58m29s_002_](https://user-images.githubusercontent.com/24631570/87490891-2793b700-c68a-11ea-9400-48e0ce57cdfb.png)
Но на графике с черным тикером (единственном из всех) всё отображается нормально.

**Comment by gengal** [comment]
Сегодня, 16 июля не отображаются данные за 15 июля на всех графиках, как и в предыдущие дни.

**Comment by e2e4Konstantin** [comment]
я им тоже писал про этотбаг. ответ был: у вас часовой пояс не настроен))

**Comment by gengal** [comment]
Хм, сегодня настроил время на графиках, завтра посмотрим результат.

**Comment by gengal** [comment]
![Snap_17 июля 2020 г _23h35m31s_002_](https://user-images.githubusercontent.com/24631570/87791819-4494d980-c886-11ea-8874-777a8a801b6c.png)

**Comment by gengal** [comment]
![Snap_18 июля 2020 г _11h05m01s_001_](https://user-images.githubusercontent.com/24631570/87841148-9c632d00-c8e6-11ea-8bf1-d036ddeb3e30.png)
С утра выставил график по местному времени (Владивосток). это UTC+10. График после перезагрузки показал последнюю сессию. Те графики, которые выставлены по Московскому времени (по умолчанию) последнюю сессию так и не показывают. Мне не понятно, почему раньше, начиная с предыдущей версии программы, всегда последняя сессия отображалась по Московскому времени, а сейчас после обновления нет? Мне удобно анализировать график по Московскому времени. Почему на следующий день я должен все графики переводить на местное время, чтобы увидеть последнюю вчерашнюю сессию? Что за бред?

**Comment by gengal** [comment]
![Snap_18 июля 2020 г _12h22m08s_003_](https://user-images.githubusercontent.com/24631570/87842660-59f31d80-c8f1-11ea-91cc-3314f295ce15.png)
Сравним получившийся бред с выставлением времени по Владивостоку на графике SBPRo c нормальным графиком на стороннем терминале.

**Comment by gengal** [comment]
Ура, только что опять запустил программу и отобразилась последняя сессия (выставил часовой пояс по Москве)!

**Comment by gengal** [comment]
Сегодня 22 июля в 05:10 по Мск запустил программу, опять на отображается на графиках вчерашняя сессия. :-(

**Comment by SBProX** [comment]
@gengal Очень запутанно, тяжело понять почему не отображается.
Вы можете написать в Telegram @sbproofficial чтобы оперативно посмотреть проблему?

**Comment by SBProX** [comment]
Надеемся что исправили.
Сегодня выложим обновление, сможете завтра проверить.
