### ISSUE TITLE
Значение макс объема на графике.

### ISSUE THREAD

**Issue by Lesdry** [SBProX/SBProX-Dev#1416]
День добрый.
Было бы неплохо если бы Вы поправили такую функцию как "фильтр максимального объема" (настройки- стандартные графики).
![image](https://user-images.githubusercontent.com/68265700/87389803-ea172700-c5c0-11ea-9bf3-472d7ec9cd0a.png)
Так если у этой функции задано значение 1 или больше , то она выдает макс. значение объема на каждом баре где макс объем бара больше 1. Тут все верно. Но.. если задать 0, то макс объем будет подкрашиваться вообще на каждом баре. А как сделать что бы макс объем бара не выводился вообще??? Пусть 0 и будет таким значением.
П.с. тоже самое верно и для функции "первый бокс фильтр" и "второй бокс фильтр", "фильтр дельты"( хотя с дельтой тут еще вопрос. она ведь по факту может быть 0)
П.с. к фильтрам типа значения объема, дельты и др, было бы неплохо прикрутить значение времени. Ведь не новость, что  на разных участках торгового дня один и тот же объем имеет разное значение для торговли...

**Comment by gengal** [comment]
" А как сделать что бы макс объем бара не выводился вообще??? Пусть 0 и будет таким значением." Попробуйте выставить значение максимального объема настолько завышенным, что оно не будет встречаться. Например ели на графике максимальный объем равен 1000, выставьте значение максимального олбъема равным, скажем, 10 000.

**Comment by e2e4Konstantin** [comment]
у них с системным подходом, проблемы. нет общего концепта. поэтому настройки часто по разному работают.
очень слабая постановка задачи программистам для ООП, отсюда все проблемы.

**Comment by SBProX** [comment]
При значении ноль - фильтра нет, это значит что будут отображаться все макс. объемы.
Специальной галочки выключения макс. объема мы не делали.
Во первых чтобы не плодить лишних галочек, во-вторых как сказали выше можно просто поставить огромный фильтр, который никогда не будет встречаться, и этот вопрос решается.
