### ISSUE TITLE
Chart Box

### ISSUE THREAD

**Issue by LevakovMK** [SBProX/SBProX-Dev#1419]
Добрый день.
Тайм фрейм - 30 секунд
Вид - Chart Box
В настройках Chart Setting, Standart Charts, Box Chart, Period Type:
Period type - секунды
FirstBoxPeriod - 30 
Second period - 300
Бокс с клеточками не появляются, только если поменять:
Period Time - минуты
FirstBoxPeriod - 1 
Second period - 5
Только тогда появляются боксы с клеточками.

Можно это как-то исправить?
Спасибо

**Comment by SBProX** [comment]
Добрый день.

Если FirstBoxPeriod 30 секунд, и основной тф тоже 30 секунд, то рамка не будет отображаться, так как это дублирование информации. Здесь нет ошибки.
