### ISSUE TITLE
Инструменты рисования в области индикатора.

### ISSUE THREAD

**Issue by Ravil124** [SBProX/SBProX-Dev#142]
Инструменты рисования ,нанесённые в области графика, отображаются в области индикатора, при активированной функции "индикаторы над графиком". Думаю, это ошибка.

![Рисунок над графиком](https://user-images.githubusercontent.com/24837011/57946185-2683c000-78f5-11e9-92d0-701e38dc2de3.png)

**Comment by SBProX** [comment]
Все просили сделать индикаторы в одной области с графиком.
Мы сделали.
Если вам так не нравится, то можете включить опцию "Индикаторы над графиком"

**Comment by Ravil124** [comment]
На скриншоте опция "индикаторы над графиком" включена.
