### ISSUE TITLE
Ошибка "Удалить везде"

### ISSUE THREAD

**Issue by Quantum-G** [SBProX/SBProX-Dev#1420]
Добрый день. На залинкованых графиках функция "удалить везде", не удаляет линии со всех линкованных графиков одного инструмента.
Проверьте пожалуйста

**Comment by ElizarovSS** [comment]
Точно, уже писал.

**Comment by SBProX** [comment]
Добрый день.

Проверили, запись на видео.
Может быть мы что-то не то проверяем?

[bandicam 2020-07-27 16-01-34-604.zip](https://github.com/SBProX/SBProX-Dev/files/4982141/bandicam.2020-07-27.16-01-34-604.zip)

**Comment by ElizarovSS** [comment]
[Безымянный.zip](https://github.com/SBProX/SBProX-Dev/files/4983145/default.zip)
Вот

**Comment by Quantum-G** [comment]
> [Безымянный.zip](https://github.com/SBProX/SBProX-Dev/files/4983145/default.zip)
> Вот

Именно об этом и речь..

**Comment by Quantum-G** [comment]
> Добрый день.
> 
> Проверили, запись на видео.
> Может быть мы что-то не то проверяем?
> 
> [bandicam 2020-07-27 16-01-34-604.zip](https://github.com/SBProX/SBProX-Dev/files/4982141/bandicam.2020-07-27.16-01-34-604.zip)

На вашем примере удаляется каждая отдельная линия. Это такое себе удовольствие. Ранее можно было удалять сразу все и везде

**Comment by SBProX** [comment]
Сделали.

Сегодня выйдет обновление.
