### ISSUE TITLE
Комбинированные графики

### ISSUE THREAD

**Issue by max7447** [SBProX/SBProX-Dev#1422]
Здравствуйте. Предлагаю в комбинированных графиках добавить регулировку толщины свечей или хотя бы сделать их тоньше в 3-4 раза. Было бы куда смотрибельней.

**Comment by exclim89** [comment]
Поддерживаю, и не только в комбинированных, но и в прочих графиках

**Comment by ElizarovSS** [comment]
Да! Уже было подобное https://github.com/SBProX/SBProX-Dev/issues/1411

**Comment by e2e4Konstantin** [comment]
все должно быть единообразно. все настройки везде. тогда будет стройность.
бары, линии, диапазоны, фибо.... - цвет, толщина, прозрачность.....

**Comment by SBProX** [comment]
Сделано, будет работать в сл. обновлении
