### ISSUE TITLE
Максимальное сжатие графика по горизонтали

### ISSUE THREAD

**Issue by weeclemans** [SBProX/SBProX-Dev#1423]
Предлагаю добавить возможность максимального сжатия графика по горизонтали.
https://www.youtube.com/watch?v=pw4NRMruVZ0

- когда одна свеча или бар меньше одного пикселя на экране монитора
- когда туча свечей/баров помещаются на одном графике
- когда не нужно мотать график туда сюда чтобы точно отследить уровень вливания объёма на секундном или на тиковом таймфрейме
- такое невозможно заменить на смену более старшего таймфрейма

**Comment by Quantum-G** [comment]
Поддерживаю, степени сжатия не хватает.

Но  стоит учитывать специфику SB Pro X, уже на текущем максимально возможно сжатом графике (например 5-15 секундном), график ощутимо тормозит, а на 4К мониторе лучше вообще такое не открывать (но ребята вроде занялись решением вопроса скорости).

**Comment by SBProX** [comment]
Мы решим вопросы с масштабированием когда перейдем на DirectX отрисовку.
Сейчас боюсь это невозможно
