### ISSUE TITLE
Ошибка в программе: При использовании комбинированных свечей не отображает график ATR

### ISSUE THREAD

**Issue by Ed1984-s** [SBProX/SBProX-Dev#1428]
При использовании комбинированных свечей не отображает график  индикатора ATR

Обычные свечи:
![АТР-Свечи](https://user-images.githubusercontent.com/68437592/87808514-83189d00-c862-11ea-8c39-140ebd581b82.JPG)

Комбинированные свечи:
![АТР-комбинированые свечи](https://user-images.githubusercontent.com/68437592/87808580-9f1c3e80-c862-11ea-8760-bdbe56c6e237.JPG)

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении.
