### ISSUE TITLE
Не удаляется рабочее пространство

### ISSUE THREAD

**Issue by Ed1984-s** [SBProX/SBProX-Dev#1429]
У меня в настройках два рабочих пространства. Одно уже старое и не актуально. Я его удаляю через меню (нажатие правой кнопкой мыши пункт: Сохранить/удалить рабочее пространство), но после нового запуска Sb pro оно вновь доступно для выбора.

**Comment by SBProX** [comment]
Напишите пожалуйста имя вашего рабочего пространства и первые 3 символа вашего логина в платформу, проверим на сервере в чем проблема.

**Comment by Ed1984-s** [comment]
Пространство: Futures contract
Три первых символа логина: edg <edgar22091984@gmail.com>

пн, 27 июл. 2020 г. в 16:25, SBPro X <notifications@github.com>:

**Comment by SBProX** [comment]
Исправили, сегодня выложим обновление.
В вашем случае удалить придется два раза, так как у вас там два файла с почти одинаковым названием.

**Comment by Ed1984-s** [comment]
Спасибо!

чт, 6 авг. 2020 г. в 15:23, SBPro X <notifications@github.com>:
