### ISSUE TITLE
Неравномерное расстояние между ячейками кластеров и индикаторов профиль.

### ISSUE THREAD

**Issue by Ravil124** [SBProX/SBProX-Dev#143]
![Неравномерное расстояние между кластерами](https://user-images.githubusercontent.com/24837011/57946955-0e14a500-78f7-11e9-9c71-901d9d27b245.png)

**Comment by SBProX** [comment]
Такие особенности чартинга. Исправить пока не представляется возможным с технической точки зрения, так как у всех разное разрешение и масштабирование экрана, а отрисовка идет по дробным пикселям.
