### ISSUE TITLE
Ошибка с отображением Cloud'ов

### ISSUE THREAD

**Issue by outallspaces** [SBProX/SBProX-Dev#1430]
Cloud'ы, отрисованные в реальном времени (
![2020-07-16_12-11-40](https://user-images.githubusercontent.com/67224044/87810347-84979480-c865-11ea-961b-22a380be20b8.png)
) и Cloud'ы, отрисованные на исторических данных(
![2020-07-16_12-11-59](https://user-images.githubusercontent.com/67224044/87810362-8b260c00-c865-11ea-90fb-9ea20a427a85.png)
) не одно и тоже для интструментов FORTS через Transaq, т.е. если перезагрузить окно, то часть cloud'ов пропадет. На скриншотах rsRTS 15 min. С американскими инструментами такой проблемы незамеченно. Настройки cloud:
![2020-07-16_12-15-22](https://user-images.githubusercontent.com/67224044/87810548-d93b0f80-c865-11ea-9e9c-7fab40ceffed.png)

**Comment by SBProX** [comment]
Спасибо, проверим на Transaq connector почему так происходит.
Ожидайте ответ.

**Comment by SBProX** [comment]
Проблема связана с тем, что у нас на истории есть миллисекунды, а в транзаке их может не быть (скорее всего их нет - во всяком случае у нас их точно нет). Из-за этого разница в подсчете Cloud.
Мы исключили миллисекунды из расчетов Cloud для Transaq коннектора и должно все теперь совпадать.
Обновление выложим сегодня (версия 5.0.29)

**Comment by outallspaces** [comment]
Поясните, пожалуйста, насчет миллисекунд. Правильно ли я понимаю, что в transaq минимальный шаг между сделками по времени секунда? Для моих фильтров важно, чтобы шаг был несколько миллисекунд. Я обновил версию, разница на скриншотах ниже:
Transaq:
![2020-08-06_20-38-49](https://user-images.githubusercontent.com/67224044/89563958-f2abf780-d824-11ea-8581-5aad60f4e822.png)
SBPro:
![2020-08-06_20-40-02](https://user-images.githubusercontent.com/67224044/89563995-03f50400-d825-11ea-9cc7-570e5b80d079.png)
Если правда на SBPro, то я готов пользоваться этим коннектором, но тогда вопрос по временной задержке. На этом коннекторе она достигает 3-5 секунд в моменты активности на рынке
