### ISSUE TITLE
Симулятор

### ISSUE THREAD

**Issue by LevakovMK** [SBProX/SBProX-Dev#1438]
Добрый день, нельзя в симуляторе добавить, чтобы сразу с приказом выставлялся T/P и S/L, а то приходиться делать три приказа друг за другом, что занимает некоторое время (типа, как в VolFix). Спасибо.

**Comment by ikki1561** [comment]
+

**Comment by Lesdry** [comment]
Что бы не постить лишнее... 
почему в симуляторе не учитываются позиции и приказы по одному и тому же инструменту, но на разных тф???
 вместо закрытия позиции, открытой на с10, по стопу выставленному на м1 графике, система открывает мне новую позицию на м1, в противоположном к графику с10 направлении.

**Comment by SBProX** [comment]
@LevakovMK Сделаем со временем.

@Lesdry Так сделано чтобы можно было одновременно торговать разные стратегии на одном и том же инструменте.
