### ISSUE TITLE
Невозможно поставить линию с начальной точкой на тиковом графике

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1440]
![image](https://user-images.githubusercontent.com/50357928/88397282-633a2980-cdcc-11ea-86bb-6a537de17615.png)

**Comment by r0b4ik** [comment]
Причина в неправильном времени свечей 

![image](https://user-images.githubusercontent.com/50357928/88428625-e7f16b80-cdfd-11ea-9aee-98fc376fb6ba.png)

**Comment by SBProX** [comment]
Сегодня выйдет обновление, проверьте пожалуйста как будет.
