### ISSUE TITLE
Баг SBpro X по текущей сессии .

### ISSUE THREAD

**Issue by tradingpro-nesterov** [SBProX/SBProX-Dev#1446]
В 22.40 27.07.2020 зайдя на SBpro X и на Quik  для выполнения прогрузки и  анализа , я 
![БАГ](https://user-images.githubusercontent.com/66359979/88588374-ba076380-d057-11ea-9d79-64db18e6cf7d.png)
не нашёл дневной сессии её просто нет ,а есть только график  последнего часа 22.00 до текущего момента .

**Comment by SBProX** [comment]
Эта проблема должна быть исправлена в версии 5.0.29 которую сегодня выложим.
Если не будет - переоткройте пожалуйста тикет.
