### ISSUE TITLE
Отображение цены на отдельном графике

### ISSUE THREAD

**Issue by ElizarovSS** [SBProX/SBProX-Dev#1447]
Добрый день! Не знаю в чём может быть проблема, но каждое утро такое происходит - инструмент rsSi:
Накануне работаю с основным окном, на дополнительном мониторе выведен дополнительное окно с cluster volume 10 sec. Завершается сессия и выключаю все сохраняя, утром включаю, в дополнительном окне пустота и никакие манипуляции со сменой дат не помогают. Помогает, только принудительное закрытие доп-окна и открытие по новой через загрузку из шаблона.
![Screenshot_25](https://user-images.githubusercontent.com/25759170/88616127-1fd60880-d0b5-11ea-8e66-57e69c192c1f.png)
![Screenshot_26](https://user-images.githubusercontent.com/25759170/88616130-21073580-d0b5-11ea-97e1-e70851b71337.png)
Дополнение 29.07.2020. На 10 сек графике в основном окне стоит 27.07.2020 и никак не хочет показывать 28.07.2020
![Screenshot_3](https://user-images.githubusercontent.com/25759170/88752601-28dddd00-d17c-11ea-8c88-a8f9663a2b46.png)
Update 31/07/2020 Графики с интервалом ниже минуты, показывают то что было 2 дня назад

**Comment by SBProX** [comment]
Эта проблема должна быть исправлена, сегодня выложим обновление.
Если не будет - тогда переоткройте данный тикет. Спасибо.
