### ISSUE TITLE
Магнит для перекрестия.

### ISSUE THREAD

**Issue by Ravil124** [SBProX/SBProX-Dev#145]
В версии SBPro2 перекрестие ходит строго по границам цены и времени. В версии SBProX перекрестие свободно, при сжатом графике, непонятно на какую ячейку кластера или гистограммы объёма попал. Прошу разработчиков, добавить функцию магнит для перекрестия.

![1](https://user-images.githubusercontent.com/24837011/57950483-d27ed880-7900-11e9-989e-f161792ce5d6.png)

**Comment by control63** [comment]
Поддерживаю

**Comment by SBProX** [comment]
В старой версии многие жаловались что перекрестие не совпадает с курсором.
Как раз потому, что была привязка к шагу цены, как вы описываете.
Особенно при низком масштабе.
Поэтому мы сделали жесткую привязку к курсору.
В текущей версии будет работать так как есть, у нас нет возможности переделывать.
