### ISSUE TITLE
Уровень прозрачности цвета шрифтов не сохраняется

### ISSUE THREAD

**Issue by investprognoz** [SBProX/SBProX-Dev#1457]
При рисовании шрифтов прозрачность цвета постоянно сбрасывается на уровень 50 процентов.
Другие уровни прозрачности сохраняются только на одно применение, а потом переводятся на 50%.
[Запись экрана (30.07.2020 12-25-47).zip](https://github.com/SBProX/SBProX-Dev/files/5000325/30.07.2020.12-25-47.zip)

**Comment by ElizarovSS** [comment]
+

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении
