### ISSUE TITLE
Настройка отступа графика от верхней и нижней границы.

### ISSUE THREAD

**Issue by Ravil124** [SBProX/SBProX-Dev#146]
Большая просьба к разработчикам, добавить функцию настройки отступа графика от верхней и нижней границы. На данный момент отступы для меня очень велики, особенно нижний. 

![1](https://user-images.githubusercontent.com/24837011/57951718-52f30880-7904-11e9-9cbc-8e48acbeb4bc.png)

**Comment by SBProX** [comment]
Хорошо, добавим.
