### ISSUE TITLE
Возможность зеркального отображения графиков и индикаторов

### ISSUE THREAD

**Issue by KleschMachine** [SBProX/SBProX-Dev#1466]
Добрый день! Включите, пожалуйста, в возможности программы СБПро зеркально отображать по горизонтальной оси ценовые графики и привязанные к графику индикаторы. Так как у некоторых валютных пар у брокеров и других источников  цена, например, идёт вверх, а на фьючерсе в СБПро вниз, очень трудно бывает адаптироваться к такому расположению, что очень пагубно влияет на эффективность принятия решений во время торговли. Заранее большое спасибо!

**Comment by SBProX** [comment]
Добрый день.
Боюсь пока это невозможно в рамках платформы.
