### ISSUE TITLE
В Line settings баг

### ISSUE THREAD

**Issue by MakcoH22rus** [SBProX/SBProX-Dev#147]
В Laine settings нет возможности добавить или заменить доп. цвет, при выборе серого и попытке его замены на свой дополнительные ячейки так и остаются с цветом по умолчанию. 
 #Необходимо добавить возможность смены цвета ячеек. Возможно добавлением кнопки как указано на скриншоте. 
![Кнопка заменить](https://user-images.githubusercontent.com/19171328/57962346-e4cc3700-793f-11e9-8a83-5459a379cf6c.png)

**Comment by Fen8fen** [comment]
Щелкните правой клавишей мыши по "серой" ячейке - выберите цвет - закрыть - цвет сохранится.

**Comment by SBProX** [comment]
@Fen8fen все правильно, надеюсь разобрались.
