### ISSUE TITLE
Хрипят звуки

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1472]
[Хрип задолбал 6 авг., 18.43.zip](https://github.com/SBProX/SBProX-Dev/files/5036085/6.18.43.zip)

Во время продолжительной работы:
![2020-08-06_18-46-42 (2)](https://user-images.githubusercontent.com/18483236/89553762-9c37bc80-d816-11ea-8c2b-5e1e08b7070f.png)
После закрытия СБпро:
![2020-08-06_18-52-02 (2)](https://user-images.githubusercontent.com/18483236/89553852-bb364e80-d816-11ea-98d3-f8b9cebfe573.png)

**Comment by WebSurfer001** [comment]
Тоже хрипят звуки во время продолжительной работ.
