### ISSUE TITLE
После последнего обновления тиковый график не двигается и показывает неправильное время

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1476]
обновление графика происходит только после нажатия кнопки "применить". Время неправильное в любом случае.
![image](https://user-images.githubusercontent.com/50357928/89571170-ea0cee80-d82f-11ea-8da1-ebf86f37a219.png)

**Comment by StanislavGanzyuk** [comment]
Это просто беда... просьба устранить проблему как можно быстрее.

**Comment by StanislavGanzyuk** [comment]
поправьте пожалуйста или верните деньги

**Comment by artursh** [comment]
Поддерживаю, нужен нормальный тиковый график.

**Comment by anatolev1122** [comment]
Согласен, они и так то плохо работали, а теперь вообще стоят, надо что то сделать

**Comment by koptelovav** [comment]
Поддерживаю

**Comment by tretyak** [comment]
Поправьте, пожалуйста.

**Comment by Nikitian** [comment]
Очень страдаем, было же всё хорошо

**Comment by SBProX** [comment]
Проверяем проблему.

**Comment by SBProX** [comment]
Какая агрегация у вас стоит на тиковом графике? Сколько сделок агрегируется?
Дело в том, что агрегированный тиковый график обновляется только при достижении параметров агрегации.
Поэтому может показаться что он не обновляется в режиме реального времени.

**Comment by SBProX** [comment]
Исправили, сегодня выложим обновление.
