### ISSUE TITLE
Ошибка: После удаления индикаторов из середины списка.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#148]
Здравствуйте.
![cluster search1](https://user-images.githubusercontent.com/20509322/57963468-16043180-7957-11e9-831a-738315d2cda6.jpg)
В панели индикаторов добавлены последовательно 7 "кластер серчей"
Если удалить  из середины 4 "кластер серч" то появится ошибка в виде одинакового названия двух "кластер серчей" с номером 7
![cluster search2](https://user-images.githubusercontent.com/20509322/57963490-6e3b3380-7957-11e9-8bd9-28100b7ece85.jpg)

После этого настроить "кластер серч" не получится. После добавления новых индикаторов Начнут выделяться (зеленой рамкой) сразу два индикатора.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
