### ISSUE TITLE
Добавить возможность  в симуляторе скрыть пунктирные линии сделок (от открытия до закрытия позиции)

### ISSUE THREAD

**Issue by ilexush** [SBProX/SBProX-Dev#1488]
Очень прошу добавить эту функцию. При большом количестве сделок в симуляторе, анализировать график становиться очень сложно.

**Comment by ikki1561** [comment]
+

**Comment by Alex-Prohorov** [comment]
Поддерживаю, при скальпинге сложно разобрать даже на большом мониторе.

**Comment by ilexush** [comment]
> Поддерживаю, при скальпинге сложно разобрать даже на большом мониторе. Если возможно, также скрыть надписи Sell Buy - так же мешают. Оставить одни значки, вполне достаточно, тот, кто тестирует разберется. А то графика не видно.

При открытии окна симулятора есть кнопка "Скрывать текст позиций". Остаются только линии и значки. Но вот линии скрыть не получается.
