### ISSUE TITLE
Изменить цвет всех нарисованных линий.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#149]
Здравствуйте.
У меня предложение добавить возможность как и в предыдущей версии менять цвет нарисованных линий. 
Настоящая опция смены цвета в новой платформе также интересна для новых линий.

Но здорово было бы менять цвета и у "всех" нарисованных ранее линий. 
Получается так что работая с графиком точно не знаешь какой цвет подойдет лучше исходя из фона графика, цвета фона кластера и цвета самих линий. Приходится все линии удалять и рисовать заново.  (хотя можно было бы просто всем изменить цвет. Повторюсь настоящая опция также полезна - смена цвета только у новых линий.)

![color all lines](https://user-images.githubusercontent.com/20509322/57966321-d5221200-7982-11e9-8592-ffa7f2f78d3f.png)

**Comment by SBProX** [comment]
Это уже перегруз по настройкам. Мы против.
