### ISSUE TITLE
Прозрачность Volume Profile

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#15]
![image](https://user-images.githubusercontent.com/50357928/57283390-b46ed800-70b7-11e9-8fcc-8794629425d6.png)

На ДД работает, при переключении на объёмный профиль, прозрачность пропадает

**Comment by SBProX** [comment]
Это не ошибка, **так как для объемного профиля прозрачность устанавливается в настройке цвета, а не в указанном вами поле.**

Попробуйте поменять прозрачность и напишите о результате.

**Comment by r0b4ik** [comment]
Спасибо, работает. Но реализация странная, не интуитивно понятная
