### ISSUE TITLE
Окраска бара

### ISSUE THREAD

**Issue by Venerzet** [SBProX/SBProX-Dev#150]
Можно сделать окраску бара при достижении определённых параметров, например по объёму и дельте?Что бы бар окрашивался в зелёный или красный цвет.

**Comment by WillBegin1** [comment]
В индикаторах есть уже такие называется BARS VOLUME HIGHLIGHT, BARS DELTA HIGHLIGHT

**Comment by Venerzet** [comment]
Они окрашивают если только одно качество реализовано,а я имел ввиду когда по двум качествам одновременно,например по определённому объёму и определённой дельте.И возможность добавления для ОИ стрелочки над(под) баром

**Comment by Dmitry1970** [comment]
Типа как в XTick сделано: там есть возможность окраски бара по нескольким параметрам
![2019-05-20_17-51-53](https://user-images.githubusercontent.com/35344271/58030990-3800de00-7b28-11e9-96bf-ca938b482d5b.jpg)

**Comment by Venerzet** [comment]
Да именно про это я написал выше,окрас одновременно по нескольким параметрам

**Comment by Artem074** [comment]
> Да именно про это я написал выше,окрас одновременно по нескольким параметрам

Писать можно что угодно, но по факту это не работает тут... индикатор по дельте только показывается

**Comment by bizlis** [comment]
Поддерживаю, возможности создания подсветки бара по условиям пользователя, это отличный помощник для анализа

**Comment by Artem074** [comment]
> Они окрашивают если только одно качество реализовано,а я имел ввиду когда по двум качествам одновременно,например по определённому объёму и определённой дельте.И возможность добавления для ОИ стрелочки над(под) баром

у них это невозможно, т.к. индикаторы не могут друг на друга накладываться..... тут нужно либо окрашивание бара по объему + стрелочки по дельте + крестиком по ОИ (над/под стрелочкой ну или типо того)... P.S. лет через 100 сделают ))

**Comment by Venerzet** [comment]
Я знаю что в данном варианте это невозможно, поэтому и написал, что бы добавили индикатор по 2-м и более вариантам.Сделать этот выбор как в Икстике было бы очень хорошо.

**Comment by SBProX** [comment]
К сожалению это можно реализовать только с помощью отдельного индикатора.

**Comment by bizlis** [comment]
Сделайте по типу индикатора пит-бар, как в x-tick

**Comment by Venerzet** [comment]
Можно наверное просто заменить эти 2 индикатора  BARS VOLUME HIGHLIGHT, BARS DELTA HIGHLIGHT - одним сочетающим в себе оба эти настройки
