### ISSUE TITLE
Разделитель периодов в области индикатора.

### ISSUE THREAD

**Issue by Ravil124** [SBProX/SBProX-Dev#151]
На данный момент разделитель периодов отображается в области индикатора, только при не активированной функции “индикаторы над графиком”. Пожалуйста, сделайте чтобы она работала и при включённой функции “индикаторы над графиком”.

![1](https://user-images.githubusercontent.com/24837011/57971081-d3684680-79a2-11e9-99cf-939132c9dbc1.png)

**Comment by SBProX** [comment]
Дело в том, что разделите периода работает только в области графика.
Если вы ставите индикаторы НАД графиком, то логично, что разделитель не отображается.

**Comment by Ravil124** [comment]
А можно сделать, чтобы он работал и в области индикатора?
