### ISSUE TITLE
Индикатор ОИ

### ISSUE THREAD

**Issue by murza2019** [SBProX/SBProX-Dev#1519]
Индикатор Открытого интереса
я правильно  понимаю, что в настоящий момент
данные по ОИ поступают в виде кумулятивной дельты?
и она очень громоздкая...

этот индикатор хотелось бы видеть еще в 2-х вариациях
1 . простая линия
2. свое число на каждой свече
  свое число на каждой свече реализовано  в Qscalp -это очень удобно.

Спасибо за такую чудесную платформу,

**Comment by ElizarovSS** [comment]
Коммулятивная дельта это КД, открытый интерес это совершенно другое - число открытых позиций!!!

**Comment by ElizarovSS** [comment]
Давно, пора уже открытый интерес до ума довести.

**Comment by murza2019** [comment]
ну понятно, что ОИ - это количество открытых позиций.
только индикатор отображает их в виде накопительной кумулятивной дельты.
а интересно было бы, чтобы каждая свеча имела именно свое число, 
так сделано в qscalp - это очень удобно.
Представьте  такой индикатор в форме свечей....
Импульсная свеча ОИ !!!!  - это очень круто)

**Comment by gengal** [comment]
> 
> 
> Коммулятивная дельта это КД, открытый интерес это совершенно другое - число открытых позиций!!!

Согласен. Но согласитесь, тоже хороший индикатор на основе индикатора открытого интереса. Иногда важно не число открытых позиций, а динамика их изменений. Ведь мы в принципе отслеживаем именно динамику изменения открытого интереса.

**Comment by ElizarovSS** [comment]
**Коммулятивная дельта не строится на основе открытого интереса. КД и ОИ совершенно разные объекты!** 
Дельта (Delta) – это разница между покупками и продажами. Если покупок больше – дельта положительная, если больше продаж – дельта отрицательная.
Слово “Кумулятивный” означает “Накопленный”. От английского слова Cumulative – накопленный, интегральный, общий, совокупный, сводный.
Соответственно, накопительная дельта – это индикатор, который суммирует показания дельты за определенный период.
https://atas.net/ru/torgovlya-na-birzhe/kumulyativnaya-delta/

Открытый интерес – это мера (величина) взаимно открытых позиций покупателей и продавцов. Значение открытого интереса транслируется только для срочных рынков

https://atas.net/ru/torgovlya-na-birzhe/indikator-oi-analyzer/
https://atas.net/ru/torgovlya-na-birzhe/otkrytyy-interes/

**Comment by gengal** [comment]
> 
> 
> **Коммулятивная дельта не строится на основе открытого интереса. КД и ОИ совершенно разные объекты!**
> Дельта (Delta) – это разница между покупками и продажами. Если покупок больше – дельта положительная, если больше продаж – дельта отрицательная.
> Слово “Кумулятивный” означает “Накопленный”. От английского слова Cumulative – накопленный, интегральный, общий, совокупный, сводный.
> Соответственно, накопительная дельта – это индикатор, который суммирует показания дельты за определенный период.
> https://atas.net/ru/torgovlya-na-birzhe/kumulyativnaya-delta/
> 
> Открытый интерес – это мера (величина) взаимно открытых позиций покупателей и продавцов. Значение открытого интереса транслируется только для срочных рынков
> 
> https://atas.net/ru/torgovlya-na-birzhe/indikator-oi-analyzer/
> https://atas.net/ru/torgovlya-na-birzhe/otkrytyy-interes/

Внимательно посмотрите исходный код индикатора на картинке, предоставленной мною и задайтесь вопросом, почему индикатор назван OICandle.
В данном индикаторе нет кумулятивной дельты, а есть разница соседних значений индикатора OI (открытый интерес), выраженная в виде свечи. Неужели это не очевидно?
