### ISSUE TITLE
Некорректная обработка сделок в симуляторе.

### ISSUE THREAD

**Issue by VeegoDamask** [SBProX/SBProX-Dev#152]
1. Выставляем в симуляторе два ордера, по ценам 47 и 46,9. При исполнении обоих ордеров получаем среднюю цену 46,95. Первым исполняется ордер по 47, вторым - по 46,9.
![image](https://user-images.githubusercontent.com/29836202/57974073-1df5bd00-79bb-11e9-9bc4-f938c286767d.png)
![image](https://user-images.githubusercontent.com/29836202/57974079-4bdb0180-79bb-11e9-955d-916796db2831.png)
2. Теперь закроем половину позиции по цене 46,97. Биржевое исполнение работает по принципу FIFO, т.е. закроется тот ордер, который был исполнен по 47, таким образом, мы имеем убыток в 3 тика и средняя цена должна измениться на 46,9. Однако, симулятор показывает фиксацию прибыли в 2 тика и сохраняет среднюю цену в 46,95.
![image](https://user-images.githubusercontent.com/29836202/57974122-c86de000-79bb-11e9-882c-89a6207ce7d7.png)
Это не корректно, при таком механизме работы симулятора будут возникать ошибки в тестировании стратегий у тех людей, кто в реальном рынке не работал или работал мало.

**Comment by SBProX** [comment]
Исправили, можете проверять.

**Comment by VeegoDamask** [comment]
Проверил. Теперь все корректно.

**Comment by SBProX** [comment]
Отлично
