### ISSUE TITLE
То что можно улучшить.

### ISSUE THREAD

**Issue by ProgramGun** [SBProX/SBProX-Dev#153]
1) Кнопки регулировки скорости симулятора на панели рядом с другими кнопками. 
И возможность увеличения  скорости на конкретный интервал - пример +50 и – 50 
https://i.ibb.co/mqZw1pp/01.jpg
2) Возможность сохранять статистику симулятора в какой либо из известный формат статистки как в других программах. Например желательно в формат статистики mt4! **Это очень важно**, так как можно проанализировать её в других программах! 
3) По возможности добавить настройку у линий(уровней) как луч! 
Чтобы можно было длину регулировать.

**Comment by SBProX** [comment]
Перепубликуйте пожалуйста в три тикета - в одном тикете три задачи против правил репозитория.
