### ISSUE TITLE
Некорректная работа МА

### ISSUE THREAD

**Issue by finast** [SBProX/SBProX-Dev#154]
Некорректная работа МА на графике 10 сек.
МА рисуется вплотную к барам. Скрин 1
Когда открываю Настройки и нажимаю Применить, то МА заново перерисовывается, уже корректно. Скрин 2
![Скрин5](https://user-images.githubusercontent.com/50439357/58030417-f2e4a800-7b37-11e9-8c90-69ac5f6be791.jpg)
![Скрин6](https://user-images.githubusercontent.com/50439357/58030419-f2e4a800-7b37-11e9-8645-19cb2ab7918c.jpg)

**Comment by SBProX** [comment]
Пожалуйста высылайте полные скриншоты, мы не вилим ни дат, ни инструмента

**Comment by SBProX** [comment]
У вас точно установлено последнее обновление?
От какого числа у вас обновление?

**Comment by finast** [comment]
Хорошо попозже пришлю полный скрин. 
Обновление от 13 мая. Инструмент SBRF на фортс. Таймфрейм 10 секунд.

**Comment by SBProX** [comment]
Извиняюсь. Проблему мы уже исправили, просто не выложили обновление.
Завтра выложим, проверите. Тикет я закрою, если ошибка сохранится, то тогда напишите.
