### ISSUE TITLE
Настраиваемый шаг цены для Profile.

### ISSUE THREAD

**Issue by Ravil124** [SBProX/SBProX-Dev#155]
Огромная просьба к разработчикам, пожалуйста, добавьте в настройки индикаторов Profile функцию изменения шага цены. К примеру, для Daily Volume Profile на фьючерсе rsSi, я использую шаг 50, но при таком шаге пропадает информативность кластер профилей, на которых лучше использовать шаг 10.

![Шаг Профиля](https://user-images.githubusercontent.com/24837011/58041839-8cb94e80-7b52-11e9-941f-526bf593ff8c.png)

**Comment by SBProX** [comment]
К сожалению это невозможно, так как все профили строятся из баров.
