### ISSUE TITLE
Разная толщина линий на графике.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1552]
![Snap_12 сентября 2020 г _01h50m38s_027_](https://user-images.githubusercontent.com/24631570/92990063-41cc0300-f51c-11ea-89a8-1ebb26ce4ea8.png)
Приветствую.
Не знаю у кого как, но у меня почему то на 5-ти минутных графиках толщина линий всегда больше, чем на графиках остальных таймфреймов, например на часовом графике. Хотя размер толщины везде выставлен одинаковым (рисунок вверху). Линии общие для всех графиков.
Вот еще пример, где 5-минутный и часовой графики отдалены:
![Snap_11 сентября 2020 г _19h07m08s_009_](https://user-images.githubusercontent.com/24631570/92990142-0da51200-f51d-11ea-8f6e-19f845eed17e.png)

И вот еще для сравнения 5-ти минутный график (слева) и минутный (справа). Масштаб у графиков почти одинаковый:
![2](https://user-images.githubusercontent.com/24631570/92990284-6f19b080-f51e-11ea-8bda-5aa2bfee95c0.png)

**Comment by gengal** [comment]
Хм, ничего не пойму. Сегодня загрузил на 5-ти минутках линии нормальные.

**Comment by Fen8fen** [comment]
Да есть баг. 
При запуске платформы меняется толщина свечей 

когда выставлен режим отображения кластер а стоят линии (тонкие) как будто стоит график со свечами. 
Помогает перезагрузка через "apply" если не ошибаюсь.
