### ISSUE TITLE
Отображение отсчета времени (таймер закрытия бара)

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#156]
https://monosnap.com/file/EUf3yYd0JUxoHGHYTAKglboCkLrPkv
В текущий момент, отсчет отображения времени до закрытия бара реализован таким образом, что отсчет происходит только при движении котировок. На мой взгляд это не совсем удобно. Ведь не зависимо от того движутся котировки или нет, время идет. Уважаемые разработчики, сделайте пожалуйста так, чтобы отсчет времени до закрытия бара происходил в соответствии с реальным течением времени, а не с движением котировок.

**Comment by SBProX** [comment]
Не находим полезным тратить время на такой функционал в платформе для анализа объемов, по времени и так понятно когда закрытие бара.
