### ISSUE TITLE
Реверсал чарт как в Волфиксе.

### ISSUE THREAD

**Issue by Torgovetsc** [SBProX/SBProX-Dev#1564]
Хочется реверсал чарт как в Волфиксе.
Спасибо.

**Comment by SBProX** [comment]
Reverse chart в volfix это полная чушь.
Даже не предлагайте такое.

**Comment by Torgovetsc** [comment]
Ну значит вы не умеете готовить их.
Реверс для того, что бы видеть скопление объема на определенной цене. Настройки валатильности помогают более точно настроить отображение при изменении валатильности.
Да, можно натягивать профиль на наторговки на временном таймфрейме, но зачем, если можно сделать специальный тайм фрейм.

Ну нет, дак нет.
