### ISSUE TITLE
Лишняя сбпро

### ISSUE THREAD

**Issue by timtrade** [SBProX/SBProX-Dev#1573]
Общего чата пользователей программы нет поэтому пишу здесь. В какой-то мере это и разработчика касается.
Я один из тех кто покупал обе версии сбпро.
Старую версию обновили до Х.
Но зачем мне сейчас две одинаковые версии?
Простаивает только.
Предлагаю приобрести постоянную версию за 80$ вместо 100$ на сайте. 
Перенос аккаунта на вашу почту не проблема.
Просьба к разработчикам не удалять тему.

**Comment by AlTuzov** [comment]
> 
> Перенос аккаунта на вашу почту не проблема.
>
А как вы решаете данную проблему? Очень интересно.

**Comment by Torgovetsc** [comment]
> Общего чата пользователей программы нет поэтому пишу здесь. В какой-то мере это и разработчика касается.
> Я один из тех кто покупал обе версии сбпро.
> Старую версию обновили до Х.
> Но зачем мне сейчас две одинаковые версии?
> Простаивает только.
> Предлагаю приобрести постоянную версию за 80$ вместо 100$ на сайте.
> Перенос аккаунта на вашу почту не проблема.
> Просьба к разработчикам не удалять тему.

Есть

**Comment by timtrade** [comment]
Torgovetsc, как связаться с вами?

**Comment by Torgovetsc** [comment]
> [#1573 (comment)](https://github.com/SBProX/SBProX-Dev/issues/1573#issuecomment-700580987)
> Torgovetsc, как связаться с вами?

torgovetsc@gmail.com или телега @Torgovetsc.
