### ISSUE TITLE
AAPL Chart

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1588]
![2020-10-07_21-16-33](https://user-images.githubusercontent.com/18483236/95371278-a8a5c780-08e2-11eb-8911-89b56aabff97.png)
![2020-10-07_21-16-12](https://user-images.githubusercontent.com/18483236/95371282-a9d6f480-08e2-11eb-9719-fcfa2c4a7a69.png)

**Comment by SBProX** [comment]
Добрый день. 
Перезагрузите данные с сервера пожалуйста.

**Comment by ershner** [comment]
С эплом беда - график нормально отображается только когда нет торгов(((
![2020-10-12_16-44-56](https://user-images.githubusercontent.com/18483236/95753490-5bdb3b80-0caa-11eb-9ae1-5f2697f909a9.png)
