### ISSUE TITLE
Хрипят звуки 

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1590]
#1381 #1472 Перезагружаю программу 3-6 раз на дню. Бесит.

**Comment by WebSurfer001** [comment]
+1

**Comment by SBProX** [comment]
Принято, смотрим.

**Comment by SBProX** [comment]
@ershner Можете пожалуйста написать в telegram @sbproofficial для выяснения деталей проблемы.
Спасибо.
