### ISSUE TITLE
Почему вы игнорируете эту проблему?

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1592]
https://github.com/SBProX/SBProX-Dev/issues/1476

**Comment by SBProX** [comment]
Добрый день.

Мы ничего не игнорируем.
Напишите пожалуйста в telegram @sbproofficial чтобы выяснить детали проблемы.
Спасибо.

**Comment by SBProX** [comment]
Описались в тикет.

**Comment by SBProX** [comment]
Исправили, сегодня выложим обновление.
