### ISSUE TITLE
Фьючерс YM на коннекторе SBpro не обновляется

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#1593]
25.09 последняя дата обновления

**Comment by WebSurfer001** [comment]
Всё работает! Для понимания что у вас не работает прикладывайте скриншоты.

![image](https://user-images.githubusercontent.com/66634368/95426841-4a62fe00-094f-11eb-8bd7-8eaad885f8a1.png)

**Comment by r0b4ik** [comment]
Да, сейчас работает, моя ошибка, не проверил
