### ISSUE TITLE
Добавить Вилы: Эндрюса, Шиффа, Модифицированные Шиффа, Внутрь

### ISSUE THREAD

**Issue by AceFaeton** [SBProX/SBProX-Dev#1599]
Для проведения полного технического анализа нужно прокладывание трендов и контр-трендов с учетом глубины откатов. Для этого существуют инструменты "Вилы".

Прошу добавить в инстурументы "Вилы":
**- Вилы Эндрюса**
**- Вилы Шиффа**
**- Модифицированные вилы Шиффа**
**- Вилы Внутрь**

**Comment by SBProX** [comment]
Добрый день.

SBPro это платформа для анализа объемов, данные индикаторы мы делать не будем.
