### ISSUE TITLE
Построение канала по 3м точкам

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#16]
В чате писали, что скорее всего мы его увидим в платформе.
![3k](https://user-images.githubusercontent.com/7328803/57283670-63abaf00-70b8-11e9-90a1-68f6d8459500.png)

**Comment by Venerzet** [comment]
+Полностью поддерживаю

**Comment by RoketAnny** [comment]
Очень не хватает, канала

**Comment by Cayman131** [comment]
+Полностью поддерживаю

**Comment by Cayman131** [comment]
+ добавить линию 50% канала, тоже очень надо...
