### ISSUE TITLE
Добавьте веер Фибоначи

### ISSUE THREAD

**Issue by Dmitry309** [SBProX/SBProX-Dev#1604]
Уважаемые разработчики!
Огромная просьба добавить веер Фибиначи с (возможностью настроек нескольких лучей по градусам) в инструменты рисования, ну и чтобы как и все другие графические инструменты он примагничивался к Мин Макс баров.
Заранее благодарю!

**Comment by SBProX** [comment]
Мы не будем этого делать, извините. 
Платформа для анализа объемов.
