### ISSUE TITLE
Висит бар загрузки

### ISSUE THREAD

**Issue by KinchBroker** [SBProX/SBProX-Dev#1620]
Здравствуйте! Уже который день после загрузки и начала работы продолжает висеть бар загрузки. Я его, конечно закрываю, или скрываю. У меня в данном Рабочем Пространстве 4 чарта, а пишется о каких-то восьми... По неопытности не могу прикрепить скрин. Картинка в .png, не грузится сюда. Хотя, думаю, и так понятно, о чём речь.

**Comment by ElizarovSS** [comment]
Картинку (файл) нужно просто перетянуть в поле сообщений.

**Comment by KinchBroker** [comment]
Пытался, но безуспешно. Повесил её в вашем суппорте в Телеграмм

  
>Среда, 21 октября 2020, 6:11 +03:00 от ElizarovSS <notifications@github.com>:
> 
> 
>Картинку (файл) нужно просто перетянуть в поле сообщений.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
С уважением,
Константин Манякин

**Comment by KinchBroker** [comment]
Сейчас проверил, всё работает нормально.

  
>Среда, 21 октября 2020, 6:11 +03:00 от ElizarovSS <notifications@github.com>:
> 
> 
>Картинку (файл) нужно просто перетянуть в поле сообщений.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
С уважением,
Константин Манякин

**Comment by SBProX** [comment]
Если работает нормально, тогда тикет закрываем.
