### ISSUE TITLE
Прошу добавить способ отражения "Кластер объем дельта"

### ISSUE THREAD

**Issue by uzziahmogg** [SBProX/SBProX-Dev#1623]
Прошу добавить способ отражения "Кластер объем дельта". То есть аналог "Кластер объем", но с раскраской полосок кластера по дельте. Или как "Объем дельта профиль", но с изображением не в виде профиля, а в виде кластера.

**Comment by Pikad0r** [comment]
поддерживаю, давно попрошайничаю в скайпе
+1

**Comment by uzziahmogg** [comment]
После обдумывания этого запроса понял, что "Кластер объем дельта" эквивалентен "Кластер дельта" - ведь у кластера все полоски одинаковые по длине и отличаются только окрасом. А он может быть в одном из двух вариантах - фильтр по объему и фильтр по дельте  и эти варианты уже реализованы. Так что извиняюсь за беспокойство.
