### ISSUE TITLE
Построит свой алгоритм

### ISSUE THREAD

**Issue by mscrigna** [SBProX/SBProX-Dev#164]
можно ли сделать что-то похожее на xtick что бы построит свой алгоритм?

http://prntscr.com/nrhzyg

**Comment by Fen8fen** [comment]
Использование конструктора условий XPaint
https://www.xtick.ru/guide/xpaint.html

**Comment by vrd096** [comment]
сам хотел написать об этом! только из за этой функции приходится пользоваться xtick, не думаю что это сложно реализовать, но если это появится в сбпро я думаю будет реальный смысл переходить с sbpro2 на sbproX а так особо смысла не вижу.. фибо, линии рисовать.. это не серьезно, куча инструментов есть для этого. А вот алгоритм(с подсветкой сигнала и звуковым сопровождением это отличное решение).

**Comment by vik62** [comment]
Полностью поддерживаю.

**Comment by SBProX** [comment]
Пока что не получится сделать.

**Comment by vik62** [comment]
А в будущем.Есть ли возможность реализовать эту функцию.
