### ISSUE TITLE
USD_RUB_TOM не обновляется в реальном времени

### ISSUE THREAD

**Issue by PowerUser0** [SBProX/SBProX-Dev#1646]
Котировка загружается, и просто висит. Обновлять нужно всё время перезагрузкой. Коннектор SB Pro.

**Comment by SBProX** [comment]
Добрый день. 

У вас не может быть коннектора SBPro для акций и валют Московской биржи, это физически невозможно. 

Чтобы работали акции или валюты с Московской биржи нужно подключать Quik или Transaq. 

В инструкции об этом подробно написано.
