### ISSUE TITLE
Альтернативное представление тикового графика и фильтрация сделок

### ISSUE THREAD

**Issue by andrey3824** [SBProX/SBProX-Dev#1666]
Предлагаю добавить к существующим минутам, секундам и тикам еще один вид графика.
Сразу поясню, что это не ренко-бары. Я не хочу избавиться от рыночного шума, а наоборот, хочу его упорядочить. 
Блоки, как я их назвал, будут строиться по лучшим ценам стакана. Нам не нужны значения объемов на уровнях, только их (бид и аск) положение. Это означает, что для этого не нужны данные Level1. У разработчиков узнал, что использование стакана пока не планируется. В аттаче исходники индикаторов для МТ5 и описание того, что хотел бы видеть. 
[Uploading Блоки.docx…]()

[Uploading MT5_indicatorsl.zip…]()

**Comment by SBProX** [comment]
Спасибо, но у нас нет данных по стакану, плюс в таком случае, котировку стакана нужно хранить на истории, а это очень все сложно и затратно.

**Comment by andrey3824** [comment]
Там не нужны данные стакана. Я все пояснил в описании. Вы же в платформе не используете данные стакана, только бид и аск. Все берется с ленты сделок. Просто сделки распределяются по уровням определенным образом. так называемые «верхние» и «нижние» блоки. Фильтрация и выделение разницы идет по-другому.

  
>Вторник, 17 ноября 2020, 18:47 +08:00 от SBPro X <notifications@github.com>:
> 
> 
>Спасибо, но у нас нет данных по стакану, плюс в таком случае, котировку стакана нужно хранить на истории, а это очень все сложно и затратно.
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Андрей Гладышев

**Comment by andrey3824** [comment]
**"Нам не нужны значения объемов на уровнях, только их (бид и аск) положение. Это означает, что для этого не нужны данные Level1. У разработчиков узнал, что использование стакана пока не планируется."**
Первый пост
