### ISSUE TITLE
Возврат графика в центр при движении цены

### ISSUE THREAD

**Issue by exclim89** [SBProX/SBProX-Dev#1669]
При смещении графика в любую сторону график смещается в исходное положение при движении цены, что очень мешает при прокрутке графика. Помогает только смещение графика влево так, чтобы не было видно текущего дня, после этого график возвращаться в исходное положение прекращается

**Comment by indianaxxx** [comment]
... не совсем до конца  понятно что вы пытались объяснить... возможно у вас просто включена данная кнопка... на скрине...
![Screenshot_2](https://user-images.githubusercontent.com/54440183/99783929-e4b48500-2b3c-11eb-90dd-10013693a508.jpg)

**Comment by exclim89** [comment]
аа, так она еще и включается... Извините, был не прав =)
