### ISSUE TITLE
Задержка времени по серверу Sbpro на российских фьючерсах

### ISSUE THREAD

**Issue by upeko** [SBProX/SBProX-Dev#1672]
Народ подскажите есть у кого задержка по отображению баров чрез сервер Sbpro на наших фьючах? Бывает что до 10-15 секунд задержка  потом быстро начинает отображаться.  А кто сидит с сервера Quik там как,есть подобное?

**Comment by CuJlaMblcJlu** [comment]
Тоже смотрю российский рынок через сервер Sbpro и тоже бывают задержки в несколько секунд

**Comment by SBProX** [comment]
Мы не может гарантировать отсутствие задержки.
По данным вопросам вас могут проконсультировать в тех поддержке.
