### ISSUE TITLE
Не отключается звуковой алерт на установленном индикаторе...

### ISSUE THREAD

**Issue by indianaxxx** [SBProX/SBProX-Dev#1673]
![BarsDeltaHiglight](https://user-images.githubusercontent.com/54440183/98952344-2df14d00-251d-11eb-8266-555468518e40.jpg)

**Comment by WebSurfer001** [comment]
![image](https://user-images.githubusercontent.com/66634368/98985017-05288200-2534-11eb-8ba2-97b4138ebbf4.png)

**Comment by indianaxxx** [comment]
WebSurfer001 ... но текстовые уведомления мне нужны... не вариант убрать галочку с "Активировать"...

**Comment by SBProX** [comment]
Исправлено, будет работать в версии 6.1.0
