### ISSUE TITLE
Сбивается конечная дата (повторяет начальную)

### ISSUE THREAD

**Issue by MrLex33** [SBProX/SBProX-Dev#1674]
Здравствуйте, уважаемые разработчики!

При относительно долгой (2–3 часа) работе платформы сбивается конечная дата. Скриншот:
![Скрин ошибки](https://user-images.githubusercontent.com/74345866/98973234-8f68ea00-2524-11eb-9c72-afe4dce2729c.png)

Получается, что конечная дата повторяет начальную. Причем происходит это после переключения между вкладками. Объясню более подробно: нашел я, допустим, нужный мне участок графика, который хочу проанализировать, на дневном графике. Перехожу на 15-минутный таймфрейм, где провожу нужные мне настройки, в том числе и даты. Стоит мне переключиться между вкладками, и конечная дата дублирует начальную. При этом, как только ошибка появляется, она повторяется на всех открытых графиках.

Отмечу, что происходит это на исторических данных. Когда графики работают в реальном времени, такого не замечал, хотя, возможно, работал на них не так долго.

Перезагрузка платформы не решает вопрос (думаю, мало ли что, зависло — перезагружу). Но по неизвестным мне причинам, если открыть платформу через несколько часов, ошибка уже не наблюдается (до поры до времени, как я уже отметил в самом начале).

По возможности прошу решить проблему.

С уважением.

**Comment by WebSurfer001** [comment]
![image](https://user-images.githubusercontent.com/66634368/98985267-5df81a80-2534-11eb-815f-41d89bc8e25d.png)

**Comment by MrLex33** [comment]
Все дело в линковке линий? Кстати, да, я ее как раз недавно отключил, но она мне не нужна. Много линий наношу на старшем ТФ, потом корректирую их на младших, с включенной линковкой очень неудобно получается.

**Comment by WebSurfer001** [comment]
Надо убрать галочки (с дат и кнопки применить) , оставить только линии если надо. Либо вообще отключить всё.

**Comment by MrLex33** [comment]
> Надо убрать галочки (с дат и кнопки применить) , оставить только линии если надо. Либо вообще отключить всё.

Благодарю.

**Comment by SBProX** [comment]
@WebSurfer001 Спасибо за саппорт.
Если вопрос решен, то тикет закрываю.
