### ISSUE TITLE
Просьба доработать бары

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#168]
![image](https://user-images.githubusercontent.com/50406792/58161387-d3a96000-7c88-11e9-916c-27d2b06e824b.png)
![image](https://user-images.githubusercontent.com/50406792/58161068-4239ee00-7c88-11e9-8eaf-1477ba645775.png)
![image](https://user-images.githubusercontent.com/50406792/58161099-5251cd80-7c88-11e9-844f-32651bfc5060.png)
А у вас сейчас бары меняют свою толщину, а открытие, закрытие остаётся тонким.

**Comment by stason251187** [comment]
Поддерживаю! Давно об этом прошу. А то график зрение режет!

**Comment by vik62** [comment]
Поддерживаю.

**Comment by SBProX** [comment]
Доработали, выйдет в обновлении.
