### ISSUE TITLE
Функции вкладок (последнее обновление)

### ISSUE THREAD

**Issue by Quantum-G** [SBProX/SBProX-Dev#1682]
При нажатии правой кнопки на вкладку - не открывается меню. 
При создании новой вкладки, меню.
![image](https://user-images.githubusercontent.com/34577071/99290634-9a3abc00-284f-11eb-9999-7167996e7cf4.png)

**Comment by WebSurfer001** [comment]
+

**Comment by SBProX** [comment]
Исправили, обновление выложено.
