### ISSUE TITLE
Новый шрифт

### ISSUE THREAD

**Issue by angrystoat** [SBProX/SBProX-Dev#1684]
Новый шрифт неудобен, он стал мельче, и приходится придвигаться ближе к монитору. А еще он как будто "рябит" (разрешение у обоих моих мониторов 1080). Пожалуйста, добавьте возможность менять его размер на ценовой шкале и на линиях ispocline, а еще лучше, если была бы возможность выбрать старый шрифт

**Comment by SBProX** [comment]
Кому то и старый был неудобен. 
У нас новый шрифт выглядит непорядок лучше чем старый. Мониторы 2k и 4k. 
Выбор шрифта мы не можем давать пользователю, есть масса технических нюансов которые сложно реализуются.

**Comment by angrystoat** [comment]
> Кому то и старый был неудобен.
![1123](https://user-images.githubusercontent.com/68894190/99414018-33cda080-2918-11eb-92fc-aed22d02fc41.jpg)
Это опрос в вашем канале, созданный вами же. Может провести еще один опрос по поводу нового шрифта?

**Comment by SBProX** [comment]
Многие за два года просили изменить шрифт. 
Мы выбрали один из топовых, который используется на многих ресурсах в сети - Roboto. Это один из лучших шрифтов по качеству отображения. 

Мы не можем по желанию отдельного пользователя туда-сюда менять шрифты или ещё что-то, это не так просто сделать как кажется. 

Надеюсь что у вас получится адаптироваться к новому шрифту. Если будут массовые жалобы, тогда учтём.
