### ISSUE TITLE
Ввод нужных значений уровням

### ISSUE THREAD

**Issue by qaztrade** [SBProX/SBProX-Dev#1685]
В Сбпро сейчас невозможно внести нужные значения линий (уровням) через редактирование. Цвет, толщину можно изменить, а нужное значение самому выставить недоступно. Просим внести данную опцию в программу.

**Comment by WebSurfer001** [comment]
+1

**Comment by Ardoti** [comment]
Это было бы очень кстати

**Comment by Petrov007** [comment]
+1

**Comment by SBProX** [comment]
Сделано
