### ISSUE TITLE
В окне не помещается последняя буква.

### ISSUE THREAD

**Issue by WebSurfer001** [SBProX/SBProX-Dev#1687]
Не влезает в окно последняя буква

![image](https://user-images.githubusercontent.com/66634368/99380630-47a6e180-28db-11eb-9274-2367b3c45416.png)

![image](https://user-images.githubusercontent.com/66634368/99380771-702edb80-28db-11eb-9cff-1d1eaa1dae68.png)

![image](https://user-images.githubusercontent.com/66634368/99381804-9f921800-28dc-11eb-9816-5dab522e3ebb.png)

**Comment by Hefren** [comment]
И цена сдвинута вверх с этим новым шрифтом, на пиксель ниже надо.
![цена](https://user-images.githubusercontent.com/66305548/99398203-28b54900-28f5-11eb-8de4-164f8952fbb4.png)
Может дело привычки, но старый мне больше нравился. Лучше бы выбор дали, какой шрифт юзать.

**Comment by WebSurfer001** [comment]
Объёмы в рамках (макс объёмы) жмутся к нижней границы, а не по центру как было раньше. Если сузить на один шаг, то на нижнею часть не много заходит рамка, раньше так не было.
 
![image](https://user-images.githubusercontent.com/66634368/99401236-03c2d500-28f9-11eb-9eb3-97941bf31751.png)

**Comment by Hefren** [comment]
> Объёмы в рамках (макс объёмы) жмутся к нижней границы, а не по центру как было раньше. Если сузить на один шаг, то на нижнею часть не много заходит рамка, раньше так не было.
> 
> ![image](https://user-images.githubusercontent.com/66634368/99401236-03c2d500-28f9-11eb-9eb3-97941bf31751.png)

Небольшой офтоп. Подскажите как сделать объём-дельта график, как у вас, со свечой внутри? Я только так смог настроить
![бидаск](https://user-images.githubusercontent.com/66305548/99404120-4afe9500-28fc-11eb-8e8e-86c16996af1f.png)
Т.е. у меня просто полоска направления.

**Comment by WebSurfer001** [comment]
![image](https://user-images.githubusercontent.com/66634368/99408551-67e99700-2901-11eb-9f3b-1867ccfda4a7.png)

**Comment by SBProX** [comment]
Принято, пофиксим в ближайшем обновлении.
