### ISSUE TITLE
Объемы размыты

### ISSUE THREAD

**Issue by Sh-Vadim** [SBProX/SBProX-Dev#170]
Объемы размыты, при мелком масштабе нормальные. Можно сделать прямоугольные. В глаза сильно бросается.
![Объемы размыты](https://user-images.githubusercontent.com/50907656/58163073-c5fdd580-7c9c-11e9-85f4-9cd7b2f9c98a.jpg)

**Comment by WillBegin1** [comment]
Уже решили этот вопрос ранее сказали сделают
