### ISSUE TITLE
Несколько графиков в одной вкладке.

### ISSUE THREAD

**Issue by Disfixed** [SBProX/SBProX-Dev#1700]
Добавьте пожалуйста возможность отображать несколько графиков на одной вкладке, без открытия нового окна/вкладки для каждого графика.

**Comment by ikki1561** [comment]
Поддерживаю. Приходится открывать каждый раз нужное количество окон одного иструмента при запуске программы, или можно  сделать ;сохранение последних изменений" добавить туда количество окон.

**Comment by SBProX** [comment]
Маловероятно что это получится сделать в ближайшее время.

**Comment by SBProX** [comment]
> Приходится открывать каждый раз нужное количество окон одного иструмента при запуске программы

Зачем каждый раз открывать при запуске? Можно просто сохранить рабочее пространство.
