### ISSUE TITLE
Баг с Сигналами

### ISSUE THREAD

**Issue by Hefren** [SBProX/SBProX-Dev#1702]
Настроил сигнал на вертикальный объём. Потом закрыл окно за ненадобностью. А вот сигналы с того окна всё приходят. Я правда не сохранял ещё. Может потом пройдёт. Но тем не менее баг.

**Comment by WebSurfer001** [comment]
Было так тоже, закрыл сбпро и зашёл обратно и всё пропало.

**Comment by SBProX** [comment]
Принято

**Comment by SBProX** [comment]
Исправлено, будет работать в версии 6.1.0
