### ISSUE TITLE
Цвет по умолчанию в ценовых линиях

### ISSUE THREAD

**Issue by Alexey316** [SBProX/SBProX-Dev#1703]
Сделайте пожалуйста возможность выбора цвета по умолчанию для ценовых линий. Ну не нравится этот серый невзрачный цвет. Почему он? Каждый раз выставлять другой цвет - уже раздражает.

**Comment by SBProX** [comment]
Читайте пожалуйста внимательно мануал: https://www.manula.com/manuals/sbprox/sbprox-manual/1/ru/topic/4-2-2
Все это есть.
