### ISSUE TITLE
6A фантастический Bid/Ask дельта профиль

### ISSUE THREAD

**Issue by traderGoga** [SBProX/SBProX-Dev#1704]
Здравствуйте,

Наблюдаю на австралийце невиданную доселе картину. Все зеленое...
Таких дельт просто не бывает на рынке...
Можете проверить пожалуйста?

PS: проверял бид аск через CQG и другую платформу -  там все ок.

![Снимок экрана 2020-11-23 214517](https://user-images.githubusercontent.com/61839747/100008072-a1287800-2dd5-11eb-9427-84b931459266.jpg)

**Comment by traderGoga** [comment]
Вот скрин Multicharts + CQG, сегодняшний день, часовой TF.
Мне кажется, что это более правильный график в данном случае.
![Снимок экрана 2020-11-23 215456](https://user-images.githubusercontent.com/61839747/100008779-8d314600-2dd6-11eb-9999-080dfb61d98c.jpg)

**Comment by SBProX** [comment]
Да, вы правы.
Сейчас посмотрим, но вероятно 99% это проблема с дата фидом.

**Comment by traderGoga** [comment]
Спасибо, главное исправить, чтобы дальше график шел нормально 👍

**Comment by SBProX** [comment]
По остальным инструментам совпадает?

**Comment by traderGoga** [comment]
Вроде бы да, все в пределах разумного.

**Comment by SBProX** [comment]
Как только проблема решится, дам вам знать.

**Comment by SBProX** [comment]
Глюк связан скорее всего с тем, что CME поменяла внезапно шаг цены по данному инструменту.
Боюсь решение проблемы займет не 5 минут.

![image](https://user-images.githubusercontent.com/16720120/100014724-7a6f3f00-2ddf-11eb-90e9-b03f3ecc7003.png)

**Comment by traderGoga** [comment]
Понял, время совсем не проблема. Любой трейдер должен думать головой, а не слепо торговать график. ;)

**Comment by SBProX** [comment]
О решении проблемы известим в телеграмм канале.
