### ISSUE TITLE
Бокс чарт

### ISSUE THREAD

**Issue by Chef-sommelier** [SBProX/SBProX-Dev#1706]
Здравствуйте. После обновления 23.11.2020 бокс чарт стал отображаться не корректно. При увеличении масштаба остаются только рамки старшего таймфрейма и фильтры в пустоте, интервалы младшего таймфрейма исчезают... Корректное изображение возможно только при мелком масштабе. В моём случае таймфрейм 1 минута , бокс чарт 5 минут и 15 минут, инструменты Si и BR на ФОРТС. Надеюсь на оперативное исправление ошибки. Заранее спасибо.

![Image 2](https://user-images.githubusercontent.com/74963304/100091852-3f641e80-2e66-11eb-8365-cda06feb21a0.png)
![Image 3](https://user-images.githubusercontent.com/74963304/100091857-40954b80-2e66-11eb-8a15-d92c588c4029.png)

**Comment by SBProX** [comment]
Добрый день, исправлено, можете обновиться.

**Comment by Chef-sommelier** [comment]
Здравствуйте. Опять не сохранились данные в графиках с предыдущего дня. Вчера была информация в телеграмм канале об исправлении данной ошибки, но сегодня всё повторилось.
