### ISSUE TITLE
Баг в рейтинге цен c размером шрифта

### ISSUE THREAD

**Issue by avfinance** [SBProX/SBProX-Dev#1713]
Здравствуйте! 
Когда скролишь вверх-вниз в окне рейтинга цен, то увеличивается шрифт в столбце "volume"
![Image 1](https://user-images.githubusercontent.com/28949758/100193739-6e7d9d00-2f05-11eb-957a-1c5d970fe265.png)

**Comment by SBProX** [comment]
Исправлено
