### ISSUE TITLE
Добрый день! После недавних обновлений появился баг. Через небольшой промежуток времени, некоторые линии и фигуры самостоятельно удлиняются на протяженность всего графика влево (а иногда и в обе стороны). На картинках отображено….   С уважением, Виктор!

### ISSUE THREAD

**Issue by viktor222bkru** [SBProX/SBProX-Dev#1718]
![1](https://user-images.githubusercontent.com/71009973/100217868-0474f000-2f25-11eb-889c-81a9e0891276.png)
![2](https://user-images.githubusercontent.com/71009973/100217903-0d65c180-2f25-11eb-9299-d2147d7bdb92.png)

**Comment by SBProX** [comment]
Исправлено
