### ISSUE TITLE
ошибка. не грузится часть графика

### ISSUE THREAD

**Issue by mundiz2** [SBProX/SBProX-Dev#172]
ночью не грузится часть графика. но когда запускаю днем,то все нормально отображается. 
![Screenshot_2](https://user-images.githubusercontent.com/30122598/58174113-63f1a000-7c9d-11e9-8518-144236acd90a.png)
![Screenshot_1](https://user-images.githubusercontent.com/30122598/58174114-63f1a000-7c9d-11e9-88b8-bdfd757777cf.png)
![Screenshot_3](https://user-images.githubusercontent.com/30122598/58174127-6a801780-7c9d-11e9-8d6a-41a1d85c80a8.png)

в старой версии нет такой проблемы

![Screenshot_4](https://user-images.githubusercontent.com/30122598/58174150-7b308d80-7c9d-11e9-92e9-00930f91cdcf.png)

**Comment by SBProX** [comment]
Какой инструмент и какой часовой пояс настроен для инструмента?
В какой именно момент времени появляется данная проблема?

Не имея никакой информации, мы не можем ничего проверить.
Скриншоты так же необходимо высылать полные.

**Comment by mundiz2** [comment]
инструмент GC пояс +1UTC . хорошо,завтра все полностью заскриню

**Comment by mundiz2** [comment]
> Какой инструмент и какой часовой пояс настроен для инструмента?
> В какой именно момент времени появляется данная проблема?
> 
> Не имея никакой информации, мы не можем ничего проверить.
> Скриншоты так же необходимо высылать полные.

инструмент GC пояс +1UTC . хорошо,завтра все полностью заскриню

**Comment by mundiz2** [comment]
> Какой инструмент и какой часовой пояс настроен для инструмента?
> В какой именно момент времени появляется данная проблема?
> 
> Не имея никакой информации, мы не можем ничего проверить.
> Скриншоты так же необходимо высылать полные.

инструмент GC пояс +1UTC (проблему вижу кода открываю платформу в 4 утра по европейскому времени . "заново загрузить данные" ничего не меняет. коннектор Sbpro .  когда открываю платформу днем(после 10.00) проблемы нет,и отсутствующий фрагмент котировок загружается,как ни в чем не бывало.так бывает каждый день.следовательно проблема в коде.
![111111](https://user-images.githubusercontent.com/30122598/58222214-8a532200-7d15-11e9-99bc-2fe0a7e79df8.png)
![2222222](https://user-images.githubusercontent.com/30122598/58222221-917a3000-7d15-11e9-86a5-864e4e750220.png)

**Comment by Alkor135** [comment]
Тоже наблюдаю такой трабл.
Инструмент CL, коннектор SBPro, часовой пояс +3(МСК).
![2019-05-23_080651](https://user-images.githubusercontent.com/50710452/58227087-1a06c980-7d32-11e9-9324-912061813931.png)

**Comment by Alkor135** [comment]
При подгрузке данных с сервера, данные за 22.05.2019 заканчиваются свечей 7:55 (на ТФ М5), а данные за 23.05.2019 начинаются с 8:00. Как будто из данных выпали ровно сутки.
Инструмент CL, коннектор SBPro, часовой пояс +3(МСК).
![2019-05-23_150949](https://user-images.githubusercontent.com/50710452/58251842-615e7b80-7d6d-11e9-8e5a-d8d25fd5311f.png)
