### ISSUE TITLE
Ошибка timeline комбинированного графика

### ISSUE THREAD

**Issue by Quantum-G** [SBProX/SBProX-Dev#1724]
На комбинированном графике некорректно отображается или полностью отсутствует  шкала времени.

![image](https://user-images.githubusercontent.com/34577071/100284660-8e05db80-2f80-11eb-83ac-cfcd9d0cdb9d.png)

**Comment by WebSurfer001** [comment]
На 1H  вот такая ошибка.

![image](https://user-images.githubusercontent.com/66634368/100285536-1b95fb00-2f82-11eb-8d99-adcb5ec3f60b.png)

**Comment by SBProX** [comment]
Исправлено
