### ISSUE TITLE
ЗАВИСАЕТ ПРИ ЗАГРУЗКЕ ГРАФИКОВ

### ISSUE THREAD

**Issue by koroniova** [SBProX/SBProX-Dev#1729]
у меня 1 окно и 14 графиков (3 рубля и 11 золота)
![2020-11-27_09-09-09](https://user-images.githubusercontent.com/34831430/100417025-f0e69800-3090-11eb-9941-bfea3c1597d0.jpg)

до обновления от 25.11.2020 (Версия 6.1.2) я нажимал , при загрузке НЕТ (параллельная загрузка графиков) и все загружалось за 2-3 минуты, сейчас все висьнет и даже через 30 минут загружено 3-6 графиков (все выглядит также как на скрине выше и через 30 мин).
![2020-11-27_09-10-35](https://user-images.githubusercontent.com/34831430/100417079-107dc080-3091-11eb-95bf-775f3298480e.jpg)

если выбрать ДА (последовательная загрузка), то все загружается, но за минут 8-10 (т.е. дольше в 2-3 раза чем даже при параллельной загрузке (2-3 минуты ранее)

ПК я не менял и ничего нового не устанавливал....... параметры пк соответствуют требованиям Вашей проги.....(i7,8гб)
видимо это происходит из-за искусственного ограничения нагрузки на ПК, поскольку раньше ПК нагружался так: проц на 30-40%, память 1,5-2Гб-даже до3гб, сейчас проц 2-20%, память не более 0,5Гб. при этом графики двигаются быстрее....

**Comment by affectus1** [comment]
Тоже заметил. У меня обычные свечи 10 графиков максимум каждый по недели открыты. без клаудов. скорость загрузки упала раза в три.

**Comment by X-man77** [comment]
то же самое и у меня

**Comment by SBProX** [comment]
@koroniova @affectus1 @X-man77 

Сообщите пожалуйтса первые три символа ваших аккаутов, и название workspace, проверим у себя как загружается.

**Comment by SBProX** [comment]
Или напишите пожалуйста в telegram @sbproofficial - чтобы выяснить детали проблемы, почему виснет загрузка.

**Comment by koroniova** [comment]
> @koroniova @affectus1 @X-man77 
> 
> Сообщите пожалуйтса первые три символа ваших аккаутов, и название workspace, проверим у себя как загружается.

Аккаунт koroniova
workspace gold

**Comment by SBProX** [comment]
Обновитесь пожалуйста до 6.1.4 - нашли проблему почему так долго загружался workspace.

**Comment by X-man77** [comment]
После апдейта всё заработало штатно. Загрузка в обоих режимах около 40 секунд.
