### ISSUE TITLE
Несколько графиков на одной странице

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#173]
Можно ли разместить несколько графиков на одной странице? Например, один актив на разных таймфреймах.

**Comment by SBProX** [comment]
Если вы имеете в виду в окне, то только вкладками.
На вкладке 2 или более графиков сделать нельзя.

**Comment by Dmitry1970** [comment]
Да, я имел ввиду совмещение нескольких графиков на одной вкладке. Жаль. Может продумаете этот момент? Было бы очень удобно.  Спасибо!
