### ISSUE TITLE
Графики BID и ASK profile - раскраска по дельте

### ISSUE THREAD

**Issue by Petrov007** [SBProX/SBProX-Dev#1734]
Ребята,
сделайте пжл в комбинированных графиках  BID profile и  ASK profile - раскраску по дельте 
очень нужно
![раскараска по дельте](https://user-images.githubusercontent.com/64303270/100498276-9295e400-317a-11eb-90c6-ed7284a6d8bc.png)

**Comment by SBProX** [comment]
Как можно сделать в bid profile и ask profile раскраску по дельте? Это противоречит логике.
