### ISSUE TITLE
Коннектор SBPro для FORTS

### ISSUE THREAD

**Issue by Massashka** [SBProX/SBProX-Dev#1739]
Здравствуйте! 
Приобрела вашу программу SBProX, но у меня отсутствует коннектор SBPro для рынка FORTS. 
Как мне быть?
Спасибо!
![1](https://user-images.githubusercontent.com/75264563/100630110-30d0a800-333b-11eb-8fad-eaea773850bf.jpg)

**Comment by SBProX** [comment]
Мы не предоставляем данных для FORTS.
Перед покупкой на сайте так и написано - чтобы получать рыночные данные, необходимо подключать Quik или Transaq.
