### ISSUE TITLE
Не грузится график при открытой платформе.

### ISSUE THREAD

**Issue by alexgherco** [SBProX/SBProX-Dev#174]
Для получения актуальных котировок необходимо постоянно "reload from server".
Представляю скрины по йене. первый 
скрин 18:27 МСК цена на 09:01 биржи, 
![image](https://user-images.githubusercontent.com/2143904/58189317-f193b680-7cc2-11e9-9961-55fe43403415.png)
через 5 мин - 18:32 - уже на 10:27.
![image](https://user-images.githubusercontent.com/2143904/58189410-1ee06480-7cc3-11e9-8f9c-0e60c566dd56.png)

**Comment by SBProX** [comment]
У вас реал-тайм вообще не идет.
Какой коннектор вы выбрали для американского рынка при запуске платформы?

**Comment by alexgherco** [comment]
всегда грузил без коннекторов, они и не находились
