### ISSUE TITLE
Проблема с отображением объемов на Дневном ТФ

### ISSUE THREAD

**Issue by Alehus2** [SBProX/SBProX-Dev#1749]
![04-12-2020 13-20-30](https://user-images.githubusercontent.com/56960322/101152683-78557d80-3634-11eb-8e58-1dd4b838dce3.jpg)

**Comment by Alehus2** [comment]
Ребята, еще какая-то проблема с отображением заголовков на форуме
Я создаю тему с заголовком:
![04-12-2020 13-29-34](https://user-images.githubusercontent.com/56960322/101153050-edc14e00-3634-11eb-8377-f90580f32636.jpg)
Нажимаю сохранить. И вот что получается
![04-12-2020 13-29-34](https://user-images.githubusercontent.com/56960322/101153093-00d41e00-3635-11eb-816b-7e7a7cc641e2.jpg)
)))

**Comment by WebSurfer001** [comment]
У меня такого нет. Давно прогу обновляли?

![image](https://user-images.githubusercontent.com/66634368/101157757-b3a77a80-363b-11eb-8fc2-158d5f1f7050.png)

**Comment by Alehus2** [comment]
Только с утра программу запустил. Сейчас перезагрузил все нормально стало. Баг какой-то.
