### ISSUE TITLE
Не видно количество лотов под лупой бид аск :(

### ISSUE THREAD

**Issue by goodness25** [SBProX/SBProX-Dev#1750]
Очень неудобно, вся в печали  :( 

![66](https://user-images.githubusercontent.com/73876610/101200501-719c2a00-3677-11eb-8c76-d537ea5e7981.jpg)

![66](https://user-images.githubusercontent.com/73876610/101200733-c5a70e80-3677-11eb-91b1-b71b6b26a92c.jpg)

**Comment by SBProX** [comment]
Принято, поправим максимально быстро.

**Comment by goodness25** [comment]
😀😍😘
Спасибо 😊

**Comment by SBProX** [comment]
Исправлено
