### ISSUE TITLE
Пропали все настройки алертов.

### ISSUE THREAD

**Issue by WebSurfer001** [SBProX/SBProX-Dev#1756]
Возможно исправить или они утеряны?

**Comment by SBProX** [comment]
Добрый день.

Напишите в telegram @sbproofficial - попробую помочь.

**Comment by WebSurfer001** [comment]
Настройки пропали после вот этих обновлений.

![image](https://user-images.githubusercontent.com/66634368/101459602-80b9fb00-3949-11eb-8e90-e9f3c124be25.png)

 А заметил я это только вчера вечером.
Я их уже восстановил из сохранённых шаблонов.

**Comment by SBProX** [comment]
На текущий момент ничего не пропадает?

**Comment by WebSurfer001** [comment]
Нет. Всё ок.

**Comment by SBProX** [comment]
Тогда закрываю тикет. Скорее всего баг был связан с последними обновлениями после 04 числа, но такая мы откатили обратно код, вероятно все исправилось.
