### ISSUE TITLE
Close Workspace is not working!

### ISSUE THREAD

**Issue by kalle171** [SBProX/SBProX-Dev#1757]
Hi,
i can not close my workspace since a few days!
I have to close separately every window.

Is anyone else having this issue?

**Comment by SBProX** [comment]
Try to check it again pls.

**Comment by kalle171** [comment]
Sorry, no it does not work. It is not a big problem for me!
I understand it is a beta, and you are doing a nice job anyway.
Thanks

**Comment by SBProX** [comment]
> Sorry, no it does not work. It is not a big problem for me!
> I understand it is a beta, and you are doing a nice job anyway.
> Thanks

Can you contact us in messengers? (Skype or Telegram)

Skype: strategy.builder
Telegram: @sbproofficial

**Comment by kalle171** [comment]
Problem solved via Teamviever by a Developer on Saturday Night at 10pm.
Thanks a lot!

**Comment by kalle171** [comment]
Done
