### ISSUE TITLE
Не изменяется цвет отображения значений индикатора при наведении перекрестием на бар.

### ISSUE THREAD

**Issue by sbprosupport** [SBProX/SBProX-Dev#1758]
Не изменяется цвет отображения значений индикатора Open Interest при наведении перекрестием на бар, если изменить цвет "Шрифт кластеров" (см. скриншот). Для других индикаторов - данный цвет меняется.
![Screenshot_2770](https://user-images.githubusercontent.com/50356876/101503917-af54c780-3983-11eb-9bc7-afd3408ad398.png)

**Comment by SBProX** [comment]
Принято.

**Comment by SBProX** [comment]
Исправлено в версии 6.2.1
