### ISSUE TITLE
Опаздывает

### ISSUE THREAD

**Issue by mscrigna** [SBProX/SBProX-Dev#176]
https://www.screencast.com/t/VTiugsRyBu

**Comment by Ravil124** [comment]
Да, у меня 3 день рынок РФ запаздывает на 5-7 минут на открытие.

**Comment by Artem074** [comment]
я писал уже... они типо нахер посылают https://github.com/SBProX/SBProX-Dev/issues/119

**Comment by Alkor135** [comment]
> я писал уже... они типо нахер посылают "Учитывая что вы за котировку не платите, то попрошу без претензий."
> Сервер гамно, коннекторов нет - не стоит покупать прогу даже за такие деньги!
> #119

Это вы зря. В общем, хороший продукт. А то, что котировки запаздывают в моменты высокой волатильности, так это как индикатор, нефиг торговать на новостях.

**Comment by Cayman131** [comment]
Который день котировки запаздывают в начале торгов в новой версии сб про...
минут через 20 догоняет график с волфикса и идет нормально

**Comment by vector1207** [comment]
Подтверждаю проблему. Во время сильных движений рынка, цена на графике сильно отстает и потом "догоняет" график квика от нескольких секунд, до нескольких минут. Это караул. Как можно пользоваться алертами например, если они срабатывают с таким временным лагом?

На самом деле терминал СБпро имеет "тормозной" график по умолчанию. Не знаю, с какой скоростью он обновляется, но даже на спокойном рынке неоднократно замечал, что график "пропускает" тики, которые проходят в короткие промежутки времени. Причем дело точно не в скорости интернета или компьютера. И эта проблема присутствует как в версии V2, так и в версии X. Записал на видео как это выглядит в реале — https://youtu.be/4_AmhvAM7VY (В описании к ролику написал что к чему.)

Можете сравнить сами хотя бы рынок ФОРТС. Откройте минутный таймфрейм любого инструмента, и поставьте рядом СБпро и Квик (а еще лучше Метатрейдер, так как у некоторых брокеров квик тоже тормозной).

Раньше я думал, это мне просто кажется, что график в СБпро "вязкий/тормозной", пока не поставил терминалы рядом. Что касается графиков западных инструментов, то там точно такая же проблема. Я пробовал рядом запускать терминал Тайгертрейд, и к нему подключил реальные котировки Rithmic (инструмент CL). Объемы в кластерах совпадают, к ним вопросов нет, но сам график в СБПро "тормозит", т.е. скорость его обновления гораздо ниже, это заметно на глаз.

**Comment by SBProX** [comment]
Все вопросы по поводу нет котировки или нет соединения направляйте в тех. поддержку!
