### ISSUE TITLE
Странности с рамками макс. значений в дельта профиле %.

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#1762]
Заметил сегодня странности в алгоритме маркировки макс значений  в дельта профиле%. Скрин  1:

![Граф дельты%](https://user-images.githubusercontent.com/33456972/101662857-d1c21000-3a6b-11eb-96e8-73c0fe044410.png)

Скрин 2.  Настройки для данного графика:

![Настр 1](https://user-images.githubusercontent.com/33456972/101662960-edc5b180-3a6b-11eb-9913-d72c7d7301a0.png)

Для сравнения Скрин 3:

![Граф дельта профиль](https://user-images.githubusercontent.com/33456972/101663606-bacfed80-3a6c-11eb-8949-54f5ef4754a3.png)

Скрин 4. Настройки. 

![Настр 2](https://user-images.githubusercontent.com/33456972/101663652-c9b6a000-3a6c-11eb-91d9-1344eee1b205.png)

На скрине 4  всё понятно - большее, по абсолюту, значение маркируется рамкой. ОК. 
Но  алгоритм маркировки макс.значения на дельта профиль%  - скрин 1, непонятен абсолютно. 
 
1-й случай (по скрину1); по %-у кластеры равны между собой. Какой, в этом случае, маркировать кластер? Логично наверное тот который больше по абсолюту, ну или оба -  но отмечен почему-то **меньший по абсолюту** кластер. Где логика?

2-й случай (тот же скрин 1): маркирован кластер с **меньшим по %-у** значением, причём **он меньше и по абсолюту**?! Вот по какому принципу он был маркирован? Вообще наобум? 

3-й случай (скрин 1): по %-у больше нижний (62,7%), по абсолюту (49) больше верхний, но с 59%, ещё ниже (стрелкой не отмечен, не заметил его во время) есть кластер со 100% дельтой (но с мелким объёмом и мелким абсолютом 30). Какой из них маркировать? Маркирован верхний кластер, т.е. маркировка шла по абсолюту. Но вообще-то это **профиль дельты  процентный**, причём тут абсолютное значение. Вы скажете  -  у него больший объём. ОК. Тогда почему во 2-м случае маркирован кластер и с меньшим объёмом, и с меньшей дельтой, и с меньшим абсолютом, т.е. не годный для маркировки **ни по одному параметру**?

И это я заметил всего 3 периода (кстати, по скрину в 20:20 маркирован меньший по %-у и по абсолюту кластер, но с большим объёмом).   
В общем вывод такой - для дельта профиля% алгоритм маркировки макс.значений никакой.  Или может я чего не понял? Объясните тогда, плиз. 
Думаю, будет рациональней если народ подтянется и накидает **алгоритм маркировки макс.значения для  дельты профиля%**, ну хотя бы в черне. 
Типа этого (**для обсуждения**):
1) внутри периода маркируются кластера с макс,значением %-а дельты, при этом  исключаются  из маркировки **крайние кластеры со 100% дельтой если**:
        а) в этом кластере аск **или** бид = нулю
        б) если а+б< некоего значения Х (устанавливается в настройках для каждого фрейма отдельно).
        в) если а+б>X кластер маркируется (если в нём макс.значение % дельты в периоде) игнорируя п.1.а)

2) если дельта  **в разных кластерах одного периода** равны между собой, то маркируется кластер с большим абсолютом, при этом учитывая п.I

Дальше надо решить вводить в алгоритм расчёта объём или нет. Поскольку могут быть ситуации как на скрине 1 в случае 3 маркирован кластер с 59% дельты,  абсол.знач 49 и V=83, его конкурент  62,7% дельты, абсол.знач 47, V=75. Ниже там есть кластер с V=121, но меньшим абсолютом и % дельты. Т.е. соотношения %дельты, объёма и абсолютного значения могут быть самыми разными и как тут  приоритеты расставить?   Какие будут предложения? 
  
З.Ы. Чуть не забыл.  Вот здесь https://github.com/SBProX/SBProX-Dev/issues/1731  я просил сделать линию тела свечи. Вы обещали, но пока не сделали? Не забыли?

**Comment by SBProX** [comment]
Да, вероятно есть ошибка, сегодня проверим и исправим.

**Comment by SBProX** [comment]
Исправлено, будет работать в 6.2.1

**Comment by X-man77** [comment]
Можно узнать что конкретно в последнем апдейте исправили? Я что-то изменений в отображении рамок макс. обьёмов дельты профиля% не заметил.  
И что по поводу отображения линии тела свечи на комбографиках?
