### ISSUE TITLE
Ошибка? Акции.

### ISSUE THREAD

**Issue by AvaGreen2rist3000** [SBProX/SBProX-Dev#1763]
Здравствуйте.

В акция (SBER) есть такая проблема, не догружаются данные и свечи. Т.е загрузил максимум данных, оставил комп на 3 часа ( во включенном состоянии), приходишь, всё так и осталось, нажимаешь кнопочку применить, добавляется ещё 3 тех самых недостающих бара. Думается, системная ошибка.

**Comment by SBProX** [comment]
Для начала напишите по этому вопросу в тех. поддержку, если выяснится что это ошибка, то тогда будет рассматривать. А так обычно если данные не обновляются, то проблема в настройке подключения к данным.
