### ISSUE TITLE
ДАТА

### ISSUE THREAD

**Issue by StasON1989** [SBProX/SBProX-Dev#1765]
В графике клоастер дельта указываю дату сегодняшню на начало и конец периода а после загрузки идет дата вчерашня и граффик вчерашнгий

**Comment by SBProX** [comment]
Можете приложить скриншот?

**Comment by StasON1989** [comment]
а нет уже все поправилось само10.12.2020, 17:12, "SBPro X" <notifications@github.com>:
Можете приложить скриншот?
