### ISSUE TITLE
Смещение элементов рисования и ДП на ТФ<2мин при включенном корреляторе

### ISSUE THREAD

**Issue by sbprosupport** [SBProX/SBProX-Dev#1766]
При нанесении элементов рисования (прямоугольник) и динамических профилей на график с ТФ 2мин и ниже, элементы рисования и ДП профили смещаются относительно места нанесения (рисуются не там, где надо). 
При этом на графиках включен коррелятор.
При удалении коррелятора с графика, бага не наблюдается.
![Screenshot_2792](https://user-images.githubusercontent.com/50356876/101750371-f526a280-3adf-11eb-9be3-e8e7c78d6afb.png)

**Comment by SBProX** [comment]
Исправлено, будет работать в 6.2.1
