### ISSUE TITLE
Зависает симулятор, если после изменения скорости в окне платформы нажать Enter

### ISSUE THREAD

**Issue by sbprosupport** [SBProX/SBProX-Dev#1769]
Зависает симулятор, если после изменения скорости в окне платформы (вверху) (НЕ в окне "Симулятор") нажать Enter.
![Screenshot_2802](https://user-images.githubusercontent.com/50356876/101877003-675dbc80-3b9e-11eb-803a-ec2eed52b0f6.png)

**Comment by SBProX** [comment]
Исправлено, будет работать в 6.2.1
