### ISSUE TITLE
Вертикальные линии

### ISSUE THREAD

**Issue by AlTuzov** [SBProX/SBProX-Dev#177]
Пожелание.
Хотелось бы иметь возможность наносить вертикальные линии не только на истории, но и на некоторый промежуток времени в будущем. Например, для 15 мин.ТФ было бы полезно наносить линии на весь период текущего дня. Также было бы полезно иметь возможность выставлять на эти линии сигналы. Например, можно былобы утром выставить линии на все важные события текущего дня и установить на них сигналы.

Также заметил что сейчас нет возможности поменять цвет у вертикальных линий по аналогии с горизонтальными линиями.

**Comment by SBProX** [comment]
В будущем не получится.
