### ISSUE TITLE
Не идут котировки западной нефти "CRUDE OIL"

### ISSUE THREAD

**Issue by day-trade** [SBProX/SBProX-Dev#178]
Котировки западной нефти "CRUDE OIL" стоят на месте. Перезагрузка не помогает. График стоит просто на том месте в какой момент был загружен SB PRO. 
В старой версии SBpro такой проблемы не было.
Пожалуйста, решите этот вопрос!
`
![не идут котировки западные](https://user-images.githubusercontent.com/50354235/58255522-d46bf000-7d75-11e9-8fd3-40ea63a26e16.png)
`

**Comment by day-trade** [comment]
![не идут котировки западные](https://user-images.githubusercontent.com/50354235/58255619-12691400-7d76-11e9-880b-ad0bf2cba759.png)

**Comment by SBProX** [comment]
Все вопросы по поводу нет котировки или нет соединения направляйте в тех. поддержку!
