### ISSUE TITLE
Не работает инструмент "Добавить текст".

### ISSUE THREAD

**Issue by Hefren** [SBProX/SBProX-Dev#1780]
Ну просто не работает. По графику жмёшь что бы разместить, ОК нажимаешь и ничего.

**Comment by SBProX** [comment]
Посмотрите какие настройки прозрачности стоят в цвете.
Перед тем как добавляете текст.

**Comment by Hefren** [comment]
> Посмотрите какие настройки прозрачности стоят в цвете.
> Перед тем как добавляете текст.

Всё верно, прозрачность высокая стояла.

**Comment by SBProX** [comment]
Так или иначе, это ошибка, в версии 6.2.2 будет исправлено
