### ISSUE TITLE
Добрый день! Примерно с 23.12.2020г. при перезагрузке плтформы пропадают нанесенные объекты рисования... 

### ISSUE THREAD

**Issue by viktor222bkru** [SBProX/SBProX-Dev#1799]
**Описание ошибки или проблемы**

**Скриншоты**
Если возможно, приложите видео или скриншот для лучшего понимания

**Если проблема связана с медленной работой платформы**
Напишите Вашу конфигурацию ПК

**Comment by DallasVega** [comment]
тоже самое, компьютер мощный

**Comment by WebSurfer001** [comment]
Только что проверил, всё на месте. Торгую Американский рынок (CME) . Возможна проблема на фортс.

**Comment by kabaev777** [comment]
Да, и настройки при выходе с платформы не сохраняются. Хотя нажимаю Сохранить

**Comment by Evgenii8** [comment]
Да да все слетает а именно 
Начало работы 24.12.20
1. Рисовал прямоугольники, линии на разных инструментах   
2. Ставил ценовые уровни 
3. Динамический профиль 
Закончил работу с сохранением изменений в рабочем пространстве  ххххх 
Открываю программу 25.12.20
Вся проделанная работа 24.12.20 не сохранилось

**Comment by Evgenii8** [comment]
> Да да все слетает а именно
> Начало работы 24.12.20
> 
> 1. Рисовал прямоугольники, линии на разных инструментах
> 2. Ставил ценовые уровни
> 3. Динамический профиль
>    Закончил работу с сохранением изменений в рабочем пространстве  ххххх
>    Открываю программу 25.12.20
>    Вся проделанная работа 24.12.20 не сохранилось

**Работаю на фьчерсе rsBR rsSim**

**Comment by igorkv7** [comment]
тоже самое, не сохраняются изменения. переустановка не помогла.

**Comment by Evgenii8** [comment]
**Не сохраняет !!!!!!!** 
все заново приходится рисовать и настраивать индикаторы все сбрасывает до 22.12.2020

**Comment by Evgenii8** [comment]
**Решил создать шаблоны для каждого инструмента за долбался я каждый день настраивать графики** 
вот что вышло НИчего не вышло 

![10](https://user-images.githubusercontent.com/73286473/103262465-5d361d80-49e8-11eb-9d48-31ec06b311c9.jpg)

![11](https://user-images.githubusercontent.com/73286473/103262468-60c9a480-49e8-11eb-8c6d-5bd438b44ac8.jpg)

![12](https://user-images.githubusercontent.com/73286473/103262478-645d2b80-49e8-11eb-8faf-9fbcd7b25304.jpg)

**Comment by igorkv7** [comment]
Обновление не помогло. так же не сохраняются настройки.

**Comment by Evgenii8** [comment]
Обновление от 29.12.2020 (Версия 6.2.6)
1. Исправлена ошибка сохранения workspace и template на сервере.  👍
**ВСЕ работает только при сохранение нужно сохранить в новом рабочем пространстве**

**Comment by igorkv7** [comment]
Сохраняется новое раб.простр. а дальнейшие измениния в нем, не сохраняются.

**Comment by Evgenii8** [comment]
> Сохраняется новое раб.простр. а дальнейшие измениния в нем, не сохраняются.

Да точно так и есть **ПРОБЛЕМА НЕ РЕШЕНА**

**Comment by SBProX** [comment]
Проверьте пожалуйста, в версии 6.2.7 проблема должна быть решена с сохранением.

**Comment by igorkv7** [comment]
После последнего обновления вроде все сохраняется. Спасибо.

**Comment by SBProX** [comment]
В таком случае тикет закрываем
