### ISSUE TITLE
Не находит обновления при запуске программы

### ISSUE THREAD

**Issue by scalper2901** [SBProX/SBProX-Dev#180]
При запуске программы не находит обновления,а потом пишет вверхнем правом углу, о том что вышло обновление,но при попытке перезагрузить программу обновление не загружается....

**Comment by finast** [comment]
У меня так же было. Всё стало корректно, после того, как сделал по рекомендации здесь: https://github.com/SBProX/SBProX-Dev/issues/106

**Comment by scalper2901** [comment]
Не помогло,так же последние обновление от 13.05 ....

**Comment by finast** [comment]
А что, были новые после 13.05? У меня даже нет сообщений о том, что есть обновления.

**Comment by scalper2901** [comment]
у вас индикаторы скользящих средних(Moving average) нормально отображаются после 5 минуты после установки (не сливаются с закрытием цены?)

**Comment by finast** [comment]
Есть такое. Я писал здесь. Ответили, что исправили и с ближайшим обновлением всё будет корректно.

**Comment by SBProX** [comment]
Последнее обновление от 13.05.

Почему платформа просит обновится не понятно, скорее всего ошибка.
Посмотрим.
