### ISSUE TITLE
Верните как было Ценовой уровень 

### ISSUE THREAD

**Issue by Evgenii8** [SBProX/SBProX-Dev#1800]
**Верните обрано маленький значок крестик Х и линковку L для ценовой линии как раньше**  

**Скриншот**
![213](https://user-images.githubusercontent.com/73286473/103146100-dd117d00-4787-11eb-8517-06a9a4a95d2d.jpg)

**Comment by bushevigor** [comment]
+ На больших мониторах 32"+, где рекомендуемые шрифты 150% стало выглядеть ужасно.
Программа не умеет масштабироваться в режиме высокого DPI.

**Comment by DallasVega** [comment]
раньше был маленький?

**Comment by Evgenii8** [comment]
> раньше был маленький?

Да

**Comment by DallasVega** [comment]
тогда +

**Comment by SBProX** [comment]
На 4k мониторах при масштабировании - раньше, эти значки были крайне малы, на что жаловались многие пользователи.
Сейчас все приведено в порядок. 
На правом скриншоте как раз изображено так, как и должно быть.

На левом - это баг. Который мы исправили.

**Comment by Evgenii8** [comment]
> На 4k мониторах при масштабировании - раньше, эти значки были крайне малы, на что жаловались многие пользователи.
> Сейчас все приведено в порядок.
> На правом скриншоте как раз изображено так, как и должно быть.
> 
> На левом - это баг. Который мы исправили.

Коль так, понял. Спасибо за внимание.
