### ISSUE TITLE
Дублирование всех линий

### ISSUE THREAD

**Issue by dmo21749** [SBProX/SBProX-Dev#1802]
Сделать возможность функцию Дублировать на все графики, с выбором определенного графика.

Т.е. у меня открыто несколько графиков одного инструмента и мне нужно дублировать линию на определенные графики, я во вкладке выбираю на какие графики и они туда и дублируются.
Данный вопрос возник при работе с симулятором, когда работаешь в симуляторе на каком либо инструменте, и открыты рабочие инструменты, копирование происходит и туда то же.
Работа на рабочих графиках становиться невыносимой.

Спасибо.

**Скриншоты**

**Comment by ikki1561** [comment]
поддерживаю.

**Comment by WebSurfer001** [comment]
Коллеги не дублируйте тикеты таких уже создано штук 5, что я видел. История уже старая, есть уже решение со скринами. Почитайте здесь и всё найдёте.

**Comment by dmo21749** [comment]
Я искал, не нашел.

**Comment by dmo21749** [comment]
Все, разобрался.
Закрываю тему.
