### ISSUE TITLE
тиковый график

### ISSUE THREAD

**Issue by salsa322** [SBProX/SBProX-Dev#182]
огромная просьба, сделайте сильное сужение для тикового графика, потому что точки входа на таких активах как NQ невозможно анализировать на графике привязанном к таймфрейму, нужен очень сильно суженный тиковый чтобы можно было выделять профиль объема на каждом участке, в волфиксе например такая функция реализована

**Comment by SBProX** [comment]
Не получится, так как движок графика не позволяет делать размеры элементов менее чем 1 пиксель, как и координаты.
