### ISSUE TITLE
Тормозит платформа

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#183]
https://prnt.sc/nsu4x2

При увеличении волатильности и ликвидности, сразу платформа тормозит.

**Comment by niksav1** [comment]
поддерживаю. Это вчера http://prntscr.com/nsdxcs 
Сегодня картина аналогичная

**Comment by SBProX** [comment]
Серверы не справляются с нагрузкой.
Данные для вас бесплатны, поэтому какие есть.
В ближайшее время будет рассматривать расширение парка серверов.
