### ISSUE TITLE
Индикатор Total Volume - несоответствие направления и цвета

### ISSUE THREAD

**Issue by Dimitrian** [SBProX/SBProX-Dev#1831]
В данном индикаторе Растущий бар часто окрашен как падающий, а падающий иногда как растущий.

Скриншот прилагается.

![сбпро тотал объем](https://user-images.githubusercontent.com/77572690/104840040-fcf31700-58d5-11eb-9960-749e55cf035e.jpg)

**Comment by WebSurfer001** [comment]
Он по другому принципу окрашивается. Посмотрите и найдёте закономерность.

**Comment by Dimitrian** [comment]
Спасибо за коммент, но пока не увидел таких закономерностей.
