### ISSUE TITLE
Графический стакан

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#184]
По возможности, сделайте, пожалуйста, вот такой стакан на графике. Было бы супер-бомба-класс! Спасибо!
http://prntscr.com/nsvr4j

**Comment by alexanflint** [comment]
Поддерживаю!Это не стакан,а глубина рынка.Очень полезная вещь для понимания ожиданий участников рынка.

**Comment by Anton144** [comment]
Поддерживаю!

**Comment by koroniova** [comment]
полностью поддерживаю, только это не стакан а DOM (Depth Of Market) :+1: https://support.orderflowtrading.ru/knowledge-bases/2/articles/352-depth-of-market
я конечно не знаю по какой валюте вы его пользуете, но по GBPUSD смысл в нем крайне редко бывает:  бывает стоит 1400 контрактов и пробивает как нефиг делать, а бывает от 200 контрактов отлетает даже за 5 тиков не доходя!!

а стакан вот: https://support.orderflowtrading.ru/knowledge-bases/2/articles/451-torgovyie-funktsii-stakana-smart-dom

я писал уже про это все ,Разработчики сказали что левел 2 не будут делать:(

**Comment by SBProX** [comment]
Стакана не будет в принципе, мы уже говорили. 
нет возможности пока подключать Level 2
