### ISSUE TITLE
Абсолютно не верно отображаются дневные объемы инструмента 6Е,не возможно работать в принципе ,график и объемы это то ,что должно корректно отображаться ,иначе все остальное просто не нужно!!!

### ISSUE THREAD

**Issue by valkvak** [SBProX/SBProX-Dev#1840]
не верно отображаются объемы тф Д1 инструмент 6Е

![жалоба](https://user-images.githubusercontent.com/77883028/105577433-52ba3a00-5d82-11eb-89a9-92201ef5f4ac.PNG)
![жалоба 2](https://user-images.githubusercontent.com/77883028/105577440-59e14800-5d82-11eb-8aae-eee0dd72cf5a.PNG)

**Comment by WebSurfer001** [comment]
Вам надо выставить часовой пояс одинаковый с биржей по клирингу.

**Comment by valkvak** [comment]
не помогает изменение времени,посмотрите какие объемы 9.12.20 и 10.12.20 в
сравнении с tradingview,в сбпро огни стабильно низкие как не меняй
время,также обстоят дела и с 8-10.09.20
если у вас получается отобразить нормальные объемы продемонстрируйте скрин
пожалуйста.Такое ощущение ,что даются ответы без проверки..

вс, 24 янв. 2021 г. в 16:09, WebSurfer001 <notifications@github.com>:

**Comment by coffeezoo** [comment]
Why do you think Tradingview has the correct volume?

**Comment by WebSurfer001** [comment]
> Такое ощущение ,что даются ответы без проверки.. 

Я вам дал направление куда смотреть... Если в двух программах стоят не одинаковые часовые пояса, объёмы дня разные будут и это логично, может для вас нет. Евро перестал торговать когда ушёл с форекса... Крутить там что специально для вас, я не буду у меня нет времени на это... У меня стоит часовой пояс настроенный на клиринг, какой стоит у вас я не знаю... 

Хотел помочь, но в контексте вашего ответа, желание пропало. 

От темы отписался...

**Comment by valkvak** [comment]
Если бы вы хотели помочь ,то открыли бы график и посмотрели есть ли пиковые объемы в указаные даты, читайте внимательнее, изменение времени ничего не дало(ни один часовой пояс) это баг платформы. Моя критика конструктивна ,а вам пора повзрослеть...

**Comment by valkvak** [comment]
> Why do you think Tradingview has the correct volume?

This is a screenshot from the platform TOS,do you trust TOS?
![тос](https://user-images.githubusercontent.com/77883028/105827244-69eb6880-5fca-11eb-9978-12910ac599b4.PNG)

**Comment by valkvak** [comment]
Хотелось бы услышать комментарий разработчиков, про часовой пояс прошу не писать, все уже пробовал...

**Comment by valkvak** [comment]
Пробовал все часовые пояса, объем указанных дат в платформе SBPro всегда меньше (значительно), что заметно усложняет анализ тф Д1. Выбор часового пояса не может настолько занижать объемы, попробуйте сами и вы убедитесь. Жду ваших комментариев ,спасибо.

**Comment by SBProX** [comment]
@valkvak давайте конкретный день разберем.
Просто сообщите дату по 6E.

**Comment by SBProX** [comment]
Давайте разберем дату например 10 декабря 2020 года.
На tradingview показывает что дневной объем ~362 000 контрактов:

![Screenshot_1](https://user-images.githubusercontent.com/16720120/106403028-21ea9c80-6435-11eb-8030-

994224974d1a.png)

Теперь смотрим тот же день по tradingviewe на таймфрейме 4H:

![Screenshot_2](https://user-images.githubusercontent.com/16720120/106403045-3b8be400-6435-11eb-83ae-5ba8d7224571.png)

Сумма = 91 000 контрактов.

Объясните мне тогда, как может быть дневной объем 362 000, а в сумме по свечка 4H - 91 000?
Вот вам и ответ насчет данных tradingview.

В SBPro объем 86 000 контрактов. Вероятно разница в том, что 4H свечки считаются в tradingview с клиринга до клиринга.
Но уж точно не 362 000.

![Screenshot_3](https://user-images.githubusercontent.com/16720120/106403100-89085100-6435-11eb-9a7b-187512b821f6.png)

**Comment by valkvak** [comment]
Спасибо, я понял ваше разъяснение, не пробовал ,к сожалению, считать сумму контрактов на меньшем тф. У меня возник еще один вопрос по платформе, по отметке начала нового контракта(дата начала контракта разная в режиме авто и 03.21), также объем кол-ва контрактов за 10.12.20 в авто режиме и при выборе 03.21,посмотрите скрины и прокомментируйте пожалуйста.
![6е1](https://user-images.githubusercontent.com/77883028/106462744-28adf980-649f-11eb-9794-855e94b2cf84.png)
![6е2](https://user-images.githubusercontent.com/77883028/106462758-2e0b4400-649f-11eb-89cd-7b3733427cc9.png)

**Comment by SBProX** [comment]
> Спасибо, я понял ваше разъяснение, не пробовал ,к сожалению, считать сумму контрактов на меньшем тф. У меня возник еще один вопрос по платформе, по отметке начала нового контракта(дата начала контракта разная в режиме авто и 03.21), также объем кол-ва контрактов за 10.12.20 в авто режиме и при выборе 03.21,посмотрите скрины и прокомментируйте пожалуйста.
> ![6е1](https://user-images.githubusercontent.com/77883028/106462744-28adf980-649f-11eb-9794-855e94b2cf84.png)
> ![6е2](https://user-images.githubusercontent.com/77883028/106462758-2e0b4400-649f-11eb-89cd-7b3733427cc9.png)

В режиме Auto происходит склейка контрактов:

Все подробно пописано: https://www.manula.com/manuals/sbprox/sbprox-manual/1/ru/topic/6-3-4
