### ISSUE TITLE
Доработка симулятора с загрузкой исторических данных

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#186]
Опишу принцип работы подгрузки необходимого периода дат в симуляторе, как я вижу для оптимальной работы тестирования стратегий:
1. Пользователь открывает необходимое количество ТФ (к примеру Д1, Н1, М5, М1)
2. На каждом ТФ пользователь устанавливает свой период подгрузки графика (к примеру для Д1=год, Н1=3 месяца, М5=неделя, М1=день). Т.е. конечная дата на всех ТФ одна и та же, а начальная дата графика разная. 
3. На всех ТФ настраиваются графики, добавляются индикаторы
4. Выбирается режим симулятор и устанавливается начальная дата, с которого начнется тестирование, т.е. наполнение графика

**При начале тестирования на графиках уже должно присутствовать необходимое количество исторических данных, выбранных для каждого ТФ.**

В итоге мы имеем некоторую подгруженную историю, с необходимыми настройками, на которой проводится предварительный анализ, а запуск теста текущих торгов дает отработку стратегии.

**Comment by Flawmaster** [comment]
Поддерживаю! Было бы очень круто, если бы так сделали.

**Comment by SBProX** [comment]
Уже есть такой тикет.
