### ISSUE TITLE
Отображение Бид-Аск профиля в сжатом виде

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#187]
Уважаемые разработчики, большая просьба доработать график Бид-Аск профиль, в том плане, чтобы при сжатии графика можно было визуально видеть, где находиться максимальный объем в баре.
Привожу пример, как хотелось бы это видеть:
![Screenshot_2](https://user-images.githubusercontent.com/29704362/58369175-25175080-7f10-11e9-9509-a6d13e7170a1.jpg)

**Comment by alexanflint** [comment]
Поддерживаю!

**Comment by bizlis** [comment]
Так же было бы круто, если бы вы добавили к максимальным уровням Бид-Аск профили уровни, которые бы удалялись автоматически при их тестировании
При чем хотелось бы. чтобы уровни были видны, как на несжатом графике, так и на сжатом, пример:
![Screenshot_7](https://user-images.githubusercontent.com/29704362/58372825-d46a1c80-7f3c-11e9-92f5-7d19916c7be4.jpg)

**Comment by SBProX** [comment]
Ничего в этом крутого не видим.
Бид аск профиль не имеет смысла при анализе в сжатом виде.
