### ISSUE TITLE
Отмена выбора цвета

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#188]
Есть небольшая недоработка, при выборе панели смени цветов и выборе какого-либо цвета, нет возможности отменить данное действие (есть только кнопка закрыть и не хватает кнопки отменить), если передумал менять цвет, надо только устанавливать цвет заново, а так как нет панели быстрого выбора цвета, то это становиться небольшой проблемой.
![Screenshot_11](https://user-images.githubusercontent.com/29704362/58372081-f6aa6d00-7f31-11e9-8dae-42983e397174.jpg)

**Comment by Flawmaster** [comment]
Панель быстрого выбора цвета вроде добавили:
https://github.com/SBProX/SBProX-Dev/issues/30

**Comment by SBProX** [comment]
Сделано
