### ISSUE TITLE
Delta GC

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1881]
![2021-02-16_16-11-56](https://user-images.githubusercontent.com/18483236/108068311-f8578500-7072-11eb-8bc8-e61188c578a0.png)
100% ask

После релоада делта поменялась. Это как так то вообще?
![2021-02-16_16-12-31](https://user-images.githubusercontent.com/18483236/108068358-05747400-7073-11eb-92f5-706e1588edd3.png)

до
![2021-02-16_16-13-21](https://user-images.githubusercontent.com/18483236/108068438-2341d900-7073-11eb-9456-9ddcba0167fd.png)

после
![2021-02-16_16-13-51](https://user-images.githubusercontent.com/18483236/108068468-2e950480-7073-11eb-9253-d5ab7795ac3c.png)

**Comment by SBProX** [comment]
Уже исправили, были проблемы со стороны поставщика данных.
