### ISSUE TITLE
Не прогружается GC

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#1883]
![2021-02-17_18-25-10](https://user-images.githubusercontent.com/18483236/108226333-dda60e80-714d-11eb-8065-0eafe5ffdc37.png)
Релоад, удаление данных кэша - не помогает

**Comment by SBProX** [comment]
Только что проверили, график целый
![image](https://user-images.githubusercontent.com/16720120/108458413-4cce5080-727d-11eb-9ab8-55776d5a5f6b.png)

**Comment by ershner** [comment]
@SBProX В тот день данные не прогружались. Как только начался новый день на СМЕ - данные прогрузились.
