### ISSUE TITLE
Range бары для графика бид-аск профиль

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#189]
Знаю, что Range бары вроде пока отложили делать, но прошу рассмотреть возможность сделать Range бары хотя бы для графика бид-аск профиль
![Screenshot_6](https://user-images.githubusercontent.com/29704362/58372521-e5645f00-7f37-11e9-9a1d-deff5ca53055.jpg)

**Comment by Flawmaster** [comment]
Поддерживаю! Очень нужны рэнж бары с дельтой.

**Comment by control63** [comment]
поддерживаю

**Comment by SBProX** [comment]
Пока не можем сделать рендж бары.

**Comment by OlegT911** [comment]
Поддержите новый тикет по рэнж бару #1608
