### ISSUE TITLE
Копирование/дублирование вкладок

### ISSUE THREAD

**Issue by control63** [SBProX/SBProX-Dev#190]
Добрый день. прошу рассмотреть простую доработку, копирование или дублирование вкладок

**Comment by control63** [comment]
http://skrinshoter.ru/i/250519/Za6FlhJj.png

**Comment by bizlis** [comment]
Если такое делать, то добавить возможность копировать/дублировать не только в текущем окне, но в другие окна.

**Comment by SBProX** [comment]
Мы считаем это уже излишество. Лень создать шаблон и загрузить на другой вкладке?
Нам кучу кода нужно написать для этой задачи, пока что - нет.
