### ISSUE TITLE
В симуляторе куда-то пропало пол года

### ISSUE THREAD

**Issue by Milishnikoff** [SBProX/SBProX-Dev#193]
![23 06 16](https://user-images.githubusercontent.com/50336416/58381353-e98a8e00-7fc4-11e9-8e41-5c2bc9c1de31.png)
![03 01 17](https://user-images.githubusercontent.com/50336416/58381357-ee4f4200-7fc4-11e9-9b4b-11072413974e.png)

Не прогружается пол года

**Comment by Milishnikoff** [comment]
Пропуск графика не зависит от симулятора, в реале тоже самое. Так же пропущена половина 2017 года.
![3](https://user-images.githubusercontent.com/50336416/58429654-44001900-80af-11e9-876a-d9d5b3af653a.png)
![4](https://user-images.githubusercontent.com/50336416/58429658-4793a000-80af-11e9-89cf-4a87346157d4.png)

**Comment by SBProX** [comment]
Да просто историю не подкачали.
На неделе подкачаем.

**Comment by Milishnikoff** [comment]
ОК

**Comment by Milishnikoff** [comment]
Историю так и не подкачали?

**Comment by SBProX** [comment]
@Milishnikoff история подкачана
