### ISSUE TITLE
Не меняется прозрачность заливки в индикаторе Daily Cumulative Delta.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#1953]
![1](https://user-images.githubusercontent.com/24631570/117155913-8a646380-ae00-11eb-9829-fee6ef68cced.png)
**Описание ошибки или проблемы**

**Скриншоты**
Если возможно, приложите видео или скриншот для лучшего понимания

**Если проблема связана с медленной работой платформы**
Напишите Вашу конфигурацию ПК

**Comment by SBProX** [comment]
Прозрачность меняется при установке дельта фильтра.
