### ISSUE TITLE
баг

### ISSUE THREAD

**Issue by StasON1989** [SBProX/SBProX-Dev#1958]
**Описание ошибки или проблемы**

Когда загружаю шаблон на 6Е то все номр а когда изменяю TOPXfilter то все становиться как на втором скрине не читаемо - на сотальных инструментах GC CL ES все норма

![image](https://user-images.githubusercontent.com/62938300/117595435-680d7580-b173-11eb-96b6-29365288533b.png)

![image](https://user-images.githubusercontent.com/62938300/117595452-73f93780-b173-11eb-88d0-afb3befaa2bb.png)

**Скриншоты**
Если возможно, приложите видео или скриншот для лучшего понимания

**Если проблема связана с медленной работой платформы**
Напишите Вашу конфигурацию ПК

**Comment by SBProX** [comment]
Вам ответили в тех поддержке.

Необходимо излагать вопросы корректно, и читать инструкцию.
Если вы не понимаете как работает top-x фильтр напишите в тех поддержку, багов тут никаких нет.
Просто вы не разобрались как это работает.

**Comment by StasON1989** [comment]
извинит е бы на взводе)12.05.2021, 23:29, "SBPro X" ***@***.***>:
Вам ответили в тех поддержке.
Необходимо излагать вопросы корректно, и читать инструкцию.
Если вы не понимаете как работает top-x фильтр напишите в тех поддержку, багов тут никаких нет.
Просто вы не разобрались как это работает.
