### ISSUE TITLE
Не корректное отображение объемов и открытого интереса

### ISSUE THREAD

**Issue by dvdenic** [SBProX/SBProX-Dev#196]
![Image 1](https://user-images.githubusercontent.com/50839644/58396247-46d61c00-8065-11e9-9996-af212edd9ef5.png)
![Image 3](https://user-images.githubusercontent.com/50839644/58396253-4e95c080-8065-11e9-9168-3d937ca1b817.png)

**Comment by SBProX** [comment]
С чего вы взяли что неверно?
В ОИ есть галочка специальная внизу, посмотрите внимательно.
