### ISSUE TITLE
Добрый.

### ISSUE THREAD

**Issue by ziplan** [SBProX/SBProX-Dev#1964]
Нужно отображение тотал дельты как свечей. Чтобы видеть хвост и наглядно видеть изменение дельты. Информативность на порядок возрастет.

**Скриншоты**
![2021-05-14_141503](https://user-images.githubusercontent.com/64438718/118249577-00329400-b4bf-11eb-8f99-63c94a039d1a.png)

**Comment by SBProX** [comment]
Уже предлагали подобное в репозитории. Сделаем.
