### ISSUE TITLE
Симулятор 

### ISSUE THREAD

**Issue by OlehKuk** [SBProX/SBProX-Dev#1966]
**Описание**
Sbpro здравствуйте.
Не могли бы вы добавить в семулятор рынка установку времени, так как припустим нужно посмотреть момент который произошёл под вечер и для етого нужно проганять каждый раз целый день.

**Comment by SBProX** [comment]
Нет, мы не можем на текущий момент поменять алгоритм работы симулятора.

**Comment by OlehKuk** [comment]
Здрастуйте!
Не нужно менять алгоритм работы)
Просьба была добавить возможность установить время с которого будет ити
симуляцыя,для того чтобы к примеру
Мне нужно просмотреть интересующий момент который произошёл в 17:00 и для
того чтобы мне его просмотреть мне нужно каждый раз мотать график с 00:00
часов.
Добавьте просто в строку где выбирается дата ещё врема с которого будут ити
котировки и всё))
Спасибо!

вт, 18 трав. 2021, 18:24 користувач SBPro X ***@***.***> пише:
