### ISSUE TITLE
ЕМА индикатор не работает

### ISSUE THREAD

**Issue by Denisey-1** [SBProX/SBProX-Dev#197]
Здравствуйте! Уже больше недели ЕМА индикатор в реальном времени работает не корректно, идёт чётко за ценой, как будто в настройках стоит 1 или 0 а на самом деле ЕМА 50 и ЕМА 200 На истории всё нормально показывает

**Comment by SBProX** [comment]
Это уже исправлено, будет работать в ближайшем обновлении.
