### ISSUE TITLE
Индикатор статистики по открытым позициям физических и юридических лиц MOEX

### ISSUE THREAD

**Issue by OlegT911** [SBProX/SBProX-Dev#1978]
Уважаемые разработчики, есть предложение сделать индикатор открытых позиций по разделению участников
(физических и юридических лиц).
Подписка оформляется на сайте Мосбиржи, в индикаторе только вводится логин и пароль. 
https://www.moex.com/ru/analyticalproducts?futoi
На скрине подобный индикатор для другой платформы.
![28-05-2021, 19'54'52](https://user-images.githubusercontent.com/60439200/120017542-a9fd3f00-bfee-11eb-96fb-ca2d831608bf.png)
![28-05-2021, 19'57'12](https://user-images.githubusercontent.com/60439200/120018095-5c350680-bfef-11eb-871d-73e16ef258f3.png)

**Comment by Den78Spb** [comment]
ПОДДЕРЖИВАЮ
очень толковый инструмент

**Comment by Artem32151** [comment]
Былобы очень хорошо!

**Comment by ikki1561** [comment]
Присоединяюсь к просьбе.

**Comment by Arseniy-Omsk** [comment]
Поддерживаю, только по хорошему это не только с мосбиржи открытый интерес надо внедрить, а как в трейд навигаторе, с сайта www.cftc.gov - все достоверные данные здесь на товарные фьючерсы и прочие инструменты. Собираются со всех бирж мира. У товарных трынков США, там более правильное разделение. так как они собственно и делают цены и реальные поставки, то там есть данные о позициях реальных поставщиков, крупных трейдеров и мелких трейдеров. И это на самом деле ценно, так ковыряться в таблицах можно часами чтобы доставать от туда информацию.

**Comment by Den545** [comment]
Поддерживаю! отличная реализация

**Comment by ferenci** [comment]
Как по мне это бредовая идея не стоящая траты на неё времени. Уверен вы все предполагаете что типа крупняк, типа юр. лица всегда правы. Я уже неоднократно видел как юр.лица с этим открытым интересом неоднократно терпели полный крах. Например, 9 апреля 2018 как сейчас помню юрики были по завязку загружены в шорт по сишке , физики под завязку в лонг, так ещё физики и лотерейки на опциках тарили, а юрики соответственно "пытались продать время". В итоге хз как юрики эти потери вынесли. Тоже самое было относительно недавно по нефти у юриков. После обвала по нефти количество шортовых позиций доходило до 2,5 миллионов, тем не менее цена потихноньку росла и росла и она так ни разу значительно и не упало , непонятно как юрики закрывали свои убытки на нефти. Так что лично моё мнение следить за этим открытым интересом, это засирать себе мозги. По сути какая разница у кого там сколько закуплено, главное это текущий результат. Кто в конкретно взятой ситуации победил покупатель или продавец и всё. Только две силы на рынке: покупатель и продавец. А разделять его ещё и на юриков с физиками это только мозги себе пудрить. Я 9 апреля тоже с сишкой налетел -60% депозита за день. Всё из-за того что тоже в то время засирал себе мозги всей этой хернёй и думал что "ну не могут же юрики ошибиться, это же киты, крупняк, невидимая рука рынка, композит мен и прочая чушь". Теперь я понимаю , невидимая рука рынка и композит мен вовсе не обязательно юрики. Физики тоже могут знатно толкнуть рынок, да так что у юриков не хватит денег сдержать напор. Лучше изучать график и собственное поведение, чем думать о том кто там что закупил. Это обычные манипуляции сознанием и новостным фоном. Тоже тема была недавно с Маском, типа он биткоин нехило закупил, и тут же биткоин улетел. Потом когда биткоин обвалился на 30ку Маск заявил что он больше не принимает битки за оплату за теслу. Ясен пень что Маск не дурак чтобы продавать биток по 30ке, когда можно было продать по 52. Тоже самое было и в самый разгар ковида. Когда вообще всё обвалилось Уорен Баффет заявил что он распродаёт активы своего фонда. Ну тут я сразу подумал , ну не дурак ли Баффет распродавать свой фонд по низам когда уже шортовое движение начинает тормозиться. Понятно что это была разводка, с целью нагнетания паники. Как говорил кто-то известный "покупай когда вокруг паника и льются реки крови, продавай когда самая последняя бабка у подъезда твердит о крутости битка))."  Так помню было с битком в 2017. Я сам помню как бабки у подъезда трещали о нём, ну я и подумал что всё ясно с ним , по 20ке влезали в биток только дураки. Потом когда биток стоил 3к после спада и когда майнеры "проливали реки крови", кто-то его закупил.  Я, например, не планирую в ближайшие пару лет входить в крипту, лучше дождаться пока майнеры опять начнут ныть и "проливать реки крови". Никого не в коем случае не отговариваю от использования этих открытых интересов. Я понимаю что на рынке должны быть не только те кто зарабатывает, но и те кто теряет. Так что дерзайте ))).
