### ISSUE TITLE
Линия с начальной точкой. Убрали совсем?

### ISSUE THREAD

**Issue by SasasSasas** [SBProX/SBProX-Dev#200]
Уважаемые разработчики,  линию ПЛ вы не планируете в новой версии? Это часто основной инструмент для нанесения уровней. Тут уже спрашивали про этот функционал, и смотрю в новом апдейте ее так и нет.. ((( Очень жаль...

**Comment by anatolev1122** [comment]
Отвечу за разработчиков, увидел случайно, на самом деле есть такой функционал, просто он по другому реализован (подозреваю что разработчики стремились максимально минимизировать интерфейс) надо в поле цены щелкнуть левой клавишей мыши, и затем тянуть линию в нужную точку

**Comment by SasasSasas** [comment]
Спасибо! Не догадался )))

**Comment by SBProX** [comment]
Да, @anatolev1122 объяснил корректно, спасибо.
