### ISSUE TITLE
Динамический профиль: прозрачность баров

### ISSUE THREAD

**Issue by anatolev1122** [SBProX/SBProX-Dev#201]
Просмотрел тикеты, нашел похожий, но предлагаемый там вариант изменения прозрачности на самом деле меняет не прозрачность бара, а именно цвет, а прозрачность в варианте отображения профиля объема не поменять, вместо этого меняется только прозрачность линии ПОК  
![Прозрачность профиля 1](https://user-images.githubusercontent.com/33803981/58435708-79663000-80ca-11e9-82df-6cefe25468c1.png)
![Прозрачность профиля](https://user-images.githubusercontent.com/33803981/58435709-79663000-80ca-11e9-872c-77eda1d4e6ba.png)

При этом в варианте отображения дельта все работает.

**Comment by SBProX** [comment]
В каком смысле цвет?
Вы цвет не меняете, меняете только прозрачность в настройках цвета.
По DP мы уже ничего менять не будем, извините. 
Того что есть вполне достаточно для нормальной работы.

**Comment by Flyrine** [comment]
anatolev1122    Прозрачность меняется!.....Настройки профиля,далее цвет бара....и ползунок А(самый нижний).....убавляете его
https://a.radikal.ru/a17/1905/e1/f6d7873688f3t.jpg

**Comment by Flyrine** [comment]
Вот с черным цветом 3 профиля 
https://c.radikal.ru/c07/1905/b8/bd2f0c0215b1t.jpg

**Comment by anatolev1122** [comment]
> anatolev1122 Прозрачность меняется!.....Настройки профиля,далее цвет бара....и ползунок А(самый нижний).....убавляете его
> https://a.radikal.ru/a17/1905/e1/f6d7873688f3t.jpg

Спасибо за подсказку, честно даже внимания не обратил что там еще помимо RGB? есть еще и А которая выходит отвечает за прозрачность, так что Вопрос снят.

**Comment by anatolev1122** [comment]
> В каком смысле цвет?
> Вы цвет не меняете, меняете только прозрачность в настройках цвета.
> По DP мы уже ничего менять не будем, извините.
> Того что есть вполне достаточно для нормальной работы.

Все, разобрался (не без помощи) может это и очевидное решение по настройке прозрачности, засунуть ее в настройки цвета вполне логично, вот только в сравнении с текущей не привычно. А так по DP у меня вопросов больше вопросов нет.

**Comment by SBProX** [comment]
Спасибо.
