### ISSUE TITLE
На М2 график не правильно отображается

### ISSUE THREAD

**Issue by mscrigna** [SBProX/SBProX-Dev#202]
http://prntscr.com/nu2whi

**Comment by mscrigna** [comment]
OI тоже не правильно показуеть! http://prntscr.com/nu2xr4

**Comment by SBProX** [comment]
Что конкретно не так с ОИ?
Высылайте нормальные скришоты, где будет видно и понятно что именно не так. Подобные тикеты мы просто закрываем без рассмотрения.

По поводу баров, все нормально. Вот сравнение с tradingview: http://prntscr.com/nudlww

**Comment by Flyrine** [comment]
Малая ликвидность на самом инструменте
