### ISSUE TITLE
Уведомления быстро исчезают

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#203]
Сделайте пожалуйста скрытие всплывающих уведомлений в ручную по кнопке "ОК", а то при срабатывании уведомления, пока до компа дойдешь, уведомление пропадает и не знаешь о чем тебя уведомили.

**Comment by Flyrine** [comment]
Да не плохая бы фунция была бы....Действительно быстро исчезает....Но,никаких кнопок ОК там не надо,зачем загромождать уведомления....При появлении окна уведомления окно убирать щелком мыши по окну...Спасибо

**Comment by bizlis** [comment]
Согласен, щелчка по уведомлению вполне достаточно для его закрытия

**Comment by bizlis** [comment]
кстати это замечание можно объединить с этим постом [125](https://github.com/SBProX/SBProX-Dev/issues/125)

**Comment by SBProX** [comment]
Было добавлена опция "Автозакрытие уведомлений" которую вы можете отключить
