### ISSUE TITLE
Некоторые странности симулятора после обновления от 27.05.19

### ISSUE THREAD

**Issue by VeegoDamask** [SBProX/SBProX-Dev#204]
Добрый день.

Заметил ряд странностей в поведении симулятора после обновы. Возможно ошибки.

1. При запуске симулятора автоматически включается сдвиг графика на новом баре
![image](https://user-images.githubusercontent.com/29836202/58455113-50c15300-8129-11e9-8ab8-da14aee746e0.png)
Не удобно. Приходится отключать. ИМХО лучше оставить как было - выключенное состояние. Кому надо-включит.

2. В какой-то момент график сам собой переключается на другой тип, при этом в поле типа графика остается cluster volume. Вот скрин до.
![image](https://user-images.githubusercontent.com/29836202/58455405-43f12f00-812a-11e9-8d64-6e21e52d745e.png)
Вот скрин после
![image](https://user-images.githubusercontent.com/29836202/58455470-73a03700-812a-11e9-9787-12d2cb70ac39.png)
Изменение произошло при вводе в ячейку Size объема равного уже открытому лотажу с Num Pad.

**Comment by SBProX** [comment]
1. Это не ошибка, так надо. Иначе график будет улетать за границы.
2. Это ошибка, исправим сегодня.

**Comment by SBProX** [comment]
Исправили
