### ISSUE TITLE
Не устанавливается обновление

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#205]
У меня версия от 13/05 и обновиться не предлагает. По ссылке установочник тоже не новой версии

**Comment by Dmitry1970** [comment]
У меня висит надпись в правом верхнем углу что обновление доступно, Но не загружает его. Сначала пыталось загружаться, но не смогло и написало, что ошибка. Сейчас вообще обновление не грузит при запуске программы, как-будто его нет.

**Comment by Flawmaster** [comment]
Не раз уже писали, что если есть глюки с обновлениями, то нужно удалить программу и заново ее поставить.

**Comment by alex12mosk** [comment]
Спасибо! Переустановка помогла.

**Comment by SBProX** [comment]
> У меня висит надпись в правом верхнем углу что обновление доступно, Но не загружает его. Сначала пыталось загружаться, но не смогло и написало, что ошибка. Сейчас вообще обновление не грузит при запуске программы, как-будто его нет.

Напишите пожалуйста в telegram @sbproofficial , попробуем подключиться и посмотреть.

**Comment by Dmitry1970** [comment]
Переустановил программу. Проблема решена.

**Comment by SBProX** [comment]
Спасибо за информацию
