### ISSUE TITLE
Лже-данные

### ISSUE THREAD

**Issue by FinamSPB2019** [SBProX/SBProX-Dev#2057]
**Описание ошибки или проблемы**
На каждом завершении торгового дня, появляется маленькая свечка секунд за 5 и совершенно космический объём. Это происходит только на американских акциях. Ранее в версии до обновления это происходило каждый вечер, и после включения на следующий день - пропадало. Сейчас (после обновления https://t.me/sbpro_news/387) - таких лже-данных за 1-2-3 свечи, и они не исчезают.

**Скриншоты**
Если возможно, приложите видео или скриншот для лучшего понимания
![image](https://user-images.githubuser
![1](https://user-images.githubusercontent.com/95377107/144294479-a48a2002-837c-4dea-a068-584be33339a8.png)
content.com/95377107/144294263-c9581fec-ee2e-495b-a075-bae6f131b935.png)

**Если проблема связана с медленной работой платформы**
Напишите Вашу конфигурацию ПК

**Comment by SBProX** [comment]
Что это за формулирофка такая, "лже-данные"?

Это пост-маркет торги, а не "лже данные".

Pre-post market сделки можно отключить в платформе, для этого есть соответствующая опция.
