### ISSUE TITLE
Вертикальные гистограммы объема

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#206]
Уважаемые разработчики! Тут недавно был пост про закругляющиеся гистограммы объема. Пришло уведомление, что пожелание по данному посту - реализовано. Однако возможно, я не так понял, но как по мне, речь шла именно по это закругление - https://monosnap.com/file/eNrmuEBOEbbd35rd1F3DstpUhB2aid

**Comment by Flyrine** [comment]
https://radikal.ru/big/o5hp7f7zva5ec

**Comment by Flyrine** [comment]
[https://radikal.ru/big/o5hp7f7zva5ec](url)

**Comment by Flyrine** [comment]
https://a.radikal.ru/a21/1905/aa/e01f78a52df0t.jpg

**Comment by Flyrine** [comment]
https://a.radikal.ru/a21/1905/aa/e01f78a52df0t.jpg

**Comment by SBProX** [comment]
Вам верно, ответил Flyrine
