### ISSUE TITLE
Дублирование ценовых линий

### ISSUE THREAD

**Issue by koroniova** [SBProX/SBProX-Dev#207]
сделайте кнопку ДЛ - Дублирование ценовых линий как в старой версии.
очень не удобно когда каждых раз нужно нажимать правой кнопкой мышь и выбирать дублирование линии везде и также при удалении!
удобно так: нажать ДЛ и везде дублируется и удаляется командой удалить все тоже на всех окнах и графиках+ было бы еще удобнее если нажал ДЛ в одном окне а она работала бы во всех окнах.

**Comment by SBProX** [comment]
Не сделаем. Не будет никаких ДЛ в SBProX.
Нажать правой кнопкой мыши так сложно?

**Comment by koroniova** [comment]
когда торгуешь на  15 сек графике, то уровни меняешь каждые 1-2 минуты......
бывает и чаще...
жаль... очень не удобно:(

**Comment by SBProX** [comment]
Мы сделаем подобную опцию на линковке немного позже, и проблема решится.

**Comment by koroniova** [comment]
ок
спасибо
