### ISSUE TITLE
Тиковые бары

### ISSUE THREAD

**Issue by recwestt** [SBProX/SBProX-Dev#2071]
Здравствуйте уважаемые разработчики спасибо вам за ваш труд и за все что вы делаете. В платформу SbproX V7 вы уже добавили Volume бары и Range бары c указанием произвольного параметра, добавьте пожалуйста ещё и тиковые бары. Что это такое? Все то же самое, как и в случае(Volume, Range) только свечка отрисовывается на графике по заданному количеству тиков. Например при указании 600 тиков в каждом баре на графике будет ровно 600 тиков. Для чего это нужно? Это здорово упрощает визуальный анализ графика, особенно когда активность на рынке спадает, облегчает поиск массивов и ключевых зон поддержки/сопротивления.
С уважением.

**Comment by mockinbirdy** [comment]
Подскажите, что имеете в виду под "Volume бары и Range бары c указанием произвольного параметра" - это что конкретно добавлено в версии v7?

**Comment by recwestt** [comment]
Здравствуйте v7 версии добавили 2 уникальных режима просмотра графика. 1) range бары и volume бары они выбираются там же где и таймфреймы. Про то как они строятся вы можете найти в интернете.
