### ISSUE TITLE
Звуковой сигнал увеличения вертикального объема

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#208]
В обновлении реализовали в вертикальных объемах цвет повышения объема. Возможно ли еще прикрутить звуковой сигнал для повышения объема? Очень был бы признателен.

**Comment by SBProX** [comment]
Не видим смысла в таком алерте.
Есть алерт на вертикальный объем, ставьте нужные вам значения.
На повышение объема - такой алерт будет очень часто сигналить.

**Comment by alex12mosk** [comment]
Алерт на значения абсолютно бестолковая вещь в отличии от алерта на увеличение объема.

**Comment by SBProX** [comment]
ok. Был объем в баре 1000, потом стал 1005. Смысл в таком алерте?
