### ISSUE TITLE
Webhook для алертов $

### ISSUE THREAD

**Issue by timuryan** [SBProX/SBProX-Dev#2085]
Предлагаю добавить функционал webhooks для алертов.

Достаточно задать:
1. задать URL
2. выбор HTTP метода (GET, POST)
3. список HTTP Headers (ключ, значение)
4. стандартный список параметров который будет передаваться (инструмент, индикатор и пр)

Это позволит интегрировать алерты с телеграмом, sms и пр.

Шкурный вопрос - сколько стоит ($) добавить это в список первоочередных фичей? 
sb@adigamov.ca

**Comment by SBProX** [comment]
Нисколько это не стоит, мы не будет делать алерты подобного рода. Извините
