### ISSUE TITLE
в платформе не загружаются фьючерсы (GC, BTC, CL, ES, NQ  и другие) на текущий день

### ISSUE THREAD

**Issue by AlexLesha** [SBProX/SBProX-Dev#2089]
Здравствуйте, в платформе не загружаются фьючерсы (GC, BTC, CL, ES, NQ  и другие) на текущий день. Попытки изменить дату на текущую (02.05) или больше - платформа сама переводит дату в 01.05 и НЕ загружает данные за сегодня (02.05).
Валютные фьючерсы (6A, 6E, и т.д.) работают без проблем - даты меняются, данные загружаются. 
Возможно, что проблема на стороне ваших серверов. 

Пожалуйста, исправьте проблему как можно быстрее. 

Спасибо.

**Comment by SBProX** [comment]
Зачем вы пишете в репозиторий? Тех поддержка есть telegram @sbprosupport
