### ISSUE TITLE
Vvap

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#21]
Нужно добавить периоды индикатора Vwap. Дневной VWAP должен отображаться как в биржевых терминалах - обнуляться каждый день

**Comment by alex12mosk** [comment]
С отображением разобрался - нужно просто время поменять. Добавьте выбор периода: месяц, неделя, день, час, сессия

**Comment by SBProX** [comment]
Создана задача https://github.com/SBProX/SBProX-Dev/issues/22
