### ISSUE TITLE
Симулятор торговли реал-тайм

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#212]
Прошу рассмотреть возможность симуляции торговли в режиме реал-тайм (все тоже самое, что в режиме истории, но на реальных текущих графиках).
Торговля графиков реал-тайм в режиме симуляция сделки, так же помогут отрабатывать навыки, но уже в режиме максимально приближенном к боевым, с учетом всех факторов, включая новости.

**Comment by Flawmaster** [comment]
Был бы очень признателен, если бы сделали так. А то каждый раз приходится другую платформу брать дополнительно, чтобы совершать сделки на демо.

**Comment by Anton144** [comment]
Да было бы круто конечно,я думаю только из-за одной такой опции к вам бы подтянулось множество начинающих!

**Comment by Flyrine** [comment]
Да,так как платформа для анализа и оттачивания торговых навыков такой эмулятор необходим

1.Сейчас конечно разработчики этим заниматься не будут,у них много другой работы...но в ближайшем будущем возможно возьмутся 
2. Чтобы хотелось в нем видеть.....При запуске эмулятора он записывает сделки в историю для статистики торговли и сохраняет при перезапуске программы
3.Выставление профита и стопа...сделать графически так...обьем и пункты...просто и наглядно
https://radikal.ru][img]https://a.radikal.ru/a07/1905/28/37baf42e30c8.jpg
https://radikal.ru][img]https://a.radikal.ru/a15/1905/06/2e229b82dc99.jpg
4.Торговый модуль который можно разместить в меню инструменты
https://radikal.ru][img]https://b.radikal.ru/b03/1905/cc/94bd49d5eaf0.jpg

**Comment by SBProX** [comment]
Мы вас совсем не понимаем? Что значит в режиме реал-тайм?
Сейчас разве не так? Ставите скорость - это кол-во тиков, которое отбирается за одну секунду, и получаете имитацию реал-тайм торговли.

**Comment by Flawmaster** [comment]
Реал-тайм это значит имитация торговли в онлайн режиме. Возможность имитировать торговлю в демо режиме на текущем графике (не на истории). Сделайте, пожалуйста, хотя бы самый простой вариант, возможность ставить ордера, чтобы открывались сделки и показывалась прибыль/убыток, можно даже без сохранения статистики. Допустим, совершенные сделки и прибыль чтобы показывались до закрытия программы(это как пример). Просто для такой торговли в онлайн режиме приходится каждый раз брать волфикс или ниндзю(демо)

**Comment by SBProX** [comment]
@Flawmaster вы сейчас про какую платформу говорите? Про SBProV2?
В SBProX можно торговать и ставить ордера, я абсолютно не понимаю о чем вы говорите.

**Comment by SBProX** [comment]
Я кажется понял о чем вы.
Вы хотите чтобы на текущем рынке можно было торговать как на демо?

**Comment by Flyrine** [comment]
> Я кажется понял о чем вы.
> Вы хотите чтобы на текущем рынке можно было торговать как на демо?

Да..если будет возможность реализовать в будущем было бы отлично

**Comment by SBProX** [comment]
Возможно. Пока что в программу минимум это не входит.

**Comment by dimaan29** [comment]
Очень полезное дополнение - торговля с выставление ордеров в реал-тайме, потому как на истории уже заранее известно куда пойдет цена. Необходим реал - тайм!!!!!

**Comment by dimaan29** [comment]
И прибыль-убыток показывать в рублях для российских инструментов.
