### ISSUE TITLE
Странности работы симулятора с несколькими графиками по одному инструменту.

### ISSUE THREAD

**Issue by VeegoDamask** [SBProX/SBProX-Dev#213]
Добрый день.

При работе с симулятором в режиме двух графиков выявил следующее, возможно, ошибки:

1. Открытая на младшем ТФ сделка не отображается как открытая на старшем ТФ.

![image](https://user-images.githubusercontent.com/29836202/58502956-50a86e00-8190-11e9-9268-3fb34391ea86.png)
![image](https://user-images.githubusercontent.com/29836202/58502993-61f17a80-8190-11e9-8bd0-2f1b54de0e84.png)

2. Открытый P&L в окне в котором не отображается сделка не актуализируется автоматически, а остается в состоянии, в котором он находился при переходе из окна, в котором сделка открыта.

![image](https://user-images.githubusercontent.com/29836202/58503126-aed55100-8190-11e9-8faa-ac080b7896e5.png)
![image](https://user-images.githubusercontent.com/29836202/58503187-d0ced380-8190-11e9-8502-42089228714c.png)

**Comment by SBProX** [comment]
Это так было задумано изначально.
Объясняю.

Например вы хотите тестировать две стратегии по одному и тому же инструменту.
И например, по одной стратегии вам нужно купить, а по второй продать.
Соответсвенно, вы можете это легко делать.
