### ISSUE TITLE
VWAP 

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#214]
VWAP, если выбрать несколько дней в истории, то он все еще перерисовывается.
Еще сделайте возможность добавлять несколько VWAP на график одновременно.(дневной, месячный недельный). Сейчас только один из них можно добавить
![image](https://user-images.githubusercontent.com/50362894/58535257-29848780-81f6-11e9-9246-6d3cd04cd8c2.png)
![image](https://user-images.githubusercontent.com/50362894/58535272-3acd9400-81f6-11e9-9d8b-a342a8794555.png)

**Comment by SBProX** [comment]
Какое тип периода VWAP в данном примере?

**Comment by SBProX** [comment]
Да, есть проблема. Вроде бы исправляли.
Займемся, спасибо.

**Comment by alex12mosk** [comment]
Здесь дневной

**Comment by alex12mosk** [comment]
Если можно еще настраиваемые отклонения VWAP добавить как в ТОС или кластердельта для полноценности данного индикатора

**Comment by SBProX** [comment]
Исправлено
