### ISSUE TITLE
Дублирование линий между залинковаными графиками

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#216]
Уважаемые разработчики, реализуйте пожалуйста дублирование линий на все залинкованые между собой графики. У меня настроено несколько окон, и есть потребность в создании одних и тех же графиков на разных окнах. Было бы очень удобно, когда нанес уровни на один график одного инструмента (Si, например), и затем задублировал их на все графики, которые залинкованы с ним. 
https://monosnap.com/file/X9HNhUto6qYZA2PKKu7uR1LNE4oVmk

**Comment by vasiliyyun** [comment]
Понял как сделать по другому, задача не актуальна.

**Comment by SBProX** [comment]
Вообще задача актуальна, мы как раз хотели это сделать.

**Comment by vasiliyyun** [comment]
Тогда будет еще прикольнее. Хотя я делаю это последовательностью "дублировать все линии" с того графика с которого хочу перенести - "вставить все линии" на том графике куда хочу перенести.

**Comment by SBProX** [comment]
Сделано
