### ISSUE TITLE
Некорректное дублирование линий

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#217]
Уважаемые разработчики. Некорректно работает функция дублирования линий. При выборе пункта "дублировать все линии", и переноса дублированных линий на другой график с помощью пункта "вставить все линии", линии переносятся не в том виде, в котором наносились изначально. Как видно на скрншоте, линии с графика слева (те, что пытаюсь перенести), нанесены не на весь график по вертикали, а имеют начало в определенной точке графика. При переносе (скрин слева), линии ложатся на весь график по вертикали. Можно исправить?
https://monosnap.com/file/CLnlAr73KFNOAdVw2fCddmiDThkkCy

**Comment by vasiliyyun** [comment]
Иными словами нужно сделать так, чтобы линии дублировались ровно в том виде, в котором создавались и присутствуют на графике.

**Comment by Flyrine** [comment]
Да...линии с началом, при дублировании на другом графике превращаются в обычные

**Comment by SBProX** [comment]
Принято, поправим.

**Comment by SBProX** [comment]
Исправлно.
