### ISSUE TITLE
не показывает котировки Сбербанка

### ISSUE THREAD

**Issue by dimaan29** [SBProX/SBProX-Dev#218]
Нет котировок по фьючерсу Сбербанка, последние от 11.05.2019. Исправьте
![Сбер](https://user-images.githubusercontent.com/51146089/58541395-a2e79e80-8225-11e9-8408-052632a7ad0f.JPG)

**Comment by SBProX** [comment]
Что мы должны исправлять? Конечную дату включите текущую, у вас 12 мая стоит.
Просьба быть внимательнее и не писать по таким мелочам в репозиторий, есть тех. поддержка.
