### ISSUE TITLE
Всплывающие уведомления мешают

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#222]
Если цена перешла за сигнальную линию, то отключить сообщение нет созможности т.к. сообщения справа закрывают доступ к настройкам линий.
Было бы удобней их отображать слева или оставить возможность пользователю выбирать.

**Comment by vpaks** [comment]
Присоединяюсь, ранний вариант был лучше

**Comment by r35p3ct** [comment]
Либо дать возможность выбрать с каким периодом создавать сообщения, чтобы сократить их кол-во.

**Comment by SBProX** [comment]
Сделано, можно выбирать положение уведомлений
