### ISSUE TITLE
Еще одна ошибка в дублировании линий

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#223]
Уважаемые разработчики, возникла еще одна ошибка с дублированием линий. При попытке дублировать линию на одном и том же графике, ничего не выходит, линия не дублируется.
https://monosnap.com/file/TyrknJIrMfDHjmy3h1qGNJdJGotNsv

**Comment by SBProX** [comment]
Дублирование предназначено для копирования линий на другие графики.
На текущем вы и так можете поставить линию стандартным способом.
