### ISSUE TITLE
Проблема с масштабированием графика с помощью колесика

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#224]
При масштабировании графика колесиком от самого маленького до того масштаба с которым работал, возврат в рабочий масштаб происходит с несоблюдением изначально отстроенной высоты. Ниже скрины:
https://monosnap.com/file/vu1UgTuvRnnZrmo9vip3ERrJLq8R5X
https://monosnap.com/file/pU8TrrQ0FZ1PL5wjVQluSQbeqBUYfi
https://monosnap.com/file/32ru5pqFHelQoZnIkzZJQsrwv5hkGe

**Comment by vector1207** [comment]
Эта проблема присутствует также в программе версии V2

**Comment by vpaks** [comment]
Очень было бы хорошо, если масштабирование выдерживалось. Поддерживаю!

**Comment by SBProX** [comment]
Исправили, будет с следующем обновлении
