### ISSUE TITLE
Просьба в доработке фибоуровней

### ISSUE THREAD

**Issue by fibo-one-love** [SBProX/SBProX-Dev#225]
Добрый день, огромная просьба сделайте не 4, а 8 фибо уровней... реально очень не хватает.
После того как вы добавили цвета на каждый фибо уровень, стало крайней неудобно, так как нет одной кнопки, чтобы применить ОДИН цвет сразу на все уровни.... приходится выбирать каждый уровень и задавать цвет, что очень неудобно и долго.

**Comment by batonek** [comment]
+

**Comment by batonek** [comment]
+
