### ISSUE TITLE
Быстрота загрузки графиков

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#226]
Мое рабочее пространство имеет два окна с несколькими вкладками в каждом. Период графиков с 01.01.2019 года по текущую дату. За последние пару дней заметно ухудшилась быстрота загрузки графиков при запуске платформы. Данную особенность начал наблюдать именно в последние пару дней, по этой причине исключаю проблемы со скоростью интернета или быстродействия самого компьютера. Дополнительных вкладок с графиками за эти дни не добавлял.

**Comment by vasiliyyun** [comment]
Для уточнения, конфигурация следующая. Два окна, в каждом окне по 4 вкладки с графиками с периодом от 01.01.2019 по текущую дату.

**Comment by SBProX** [comment]
Скорость загрузки мы улучшили в SBProX по сравнению с SBProV2.
Данные считываются с вашего ПК, так как они уже загружены с сервера.
Поэтому если что-то стало медленнее, то это не зависит от состояния сервера.
С сервера загружается только текущий день.
