### ISSUE TITLE
Отображение нового контракта на GC

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#227]
http://prntscr.com/nv8sii
http://prntscr.com/nv8sw2

**Comment by SBProX** [comment]
Какой часовой пояс у вас стоит для GC?

**Comment by stason251187** [comment]
http://prntscr.com/nvdn38

**Comment by SBProX** [comment]
Не корректно рисуетс линия разделителя контракта на Day, исправим.

**Comment by stason251187** [comment]
http://prntscr.com/nvt5gl на сегодняшний день пока так

**Comment by SBProX** [comment]
Перезагрузите данные с сервера

**Comment by stason251187** [comment]
http://prntscr.com/nwyrk0

**Comment by SBProX** [comment]
Проблема решилась?

**Comment by stason251187** [comment]
Да. Спасибо!
