### ISSUE TITLE
Недочет при рисовании линий и преложение

### ISSUE THREAD

**Issue by vomma** [SBProX/SBProX-Dev#228]
1. При выборе цвета линии окно настроек закрывается, например хочешь еще внести настройки, а окно уже закрыто, приходится заново открывать.
![Screenshot_1](https://user-images.githubusercontent.com/51166186/58613894-56a56880-82d0-11e9-8683-16fd0712ab72.jpg)

2. Предложение: Прошу рассмотреть в этом же окне добавить параметр координаты линии, чтобы можно более точно задать уровень линии. Как в квике это реализовано пример на картинке. 
![Screenshot_2](https://user-images.githubusercontent.com/51166186/58614021-ad12a700-82d0-11e9-9a9a-79645a4ef558.jpg)
например так
![Screenshot_3](https://user-images.githubusercontent.com/51166186/58614129-fbc04100-82d0-11e9-9963-e09bc166e20b.jpg)

**Comment by bizlis** [comment]
По редактированию цены для линии, поддерживаю, не хватает этого элемента в платформе.

**Comment by SBProX** [comment]
1. Так просили сделать, мы сделали. Мы же не можем туда-сюда менять код.
2. Редактирование цены осуществляется просто - возьмите линию и передвиньте ее на нужную цену.
Делать какие-то дополнительные поля мы против.
