### ISSUE TITLE
Cloud с параметром "Учитывать размер спреда"

### ISSUE THREAD

**Issue by Samm2019** [SBProX/SBProX-Dev#231]
Cloud, с включённым параметром "Учитывать размер спреда" не появляется (не обновляется) самостоятельно на графике, пока не нажмёшь "Применить".

**Comment by SBProX** [comment]
Скриншот настроек Cloud пожалуйста вышлите

**Comment by Samm2019** [comment]
Настройки очень лёгкие. Сегодня заметил что клауды стали появляться самостоятельно, думал что исправили в последнем обновлении. Но при нажатии "Применить", на графике появилось больше клаудов. Проверял на Евро (6E). Просто накиньте индикатор с минимальными настройками и подождите полчаса. После нажатия "применить", количество клаудов увеличится.
![Настройки](https://user-images.githubusercontent.com/50338402/58978160-b32ee900-87e4-11e9-9a06-164a232441f1.JPG)

**Comment by SBProX** [comment]
Хорошо, в понедельник еще раз проверим.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении
