### ISSUE TITLE
Нет котировок с утра

### ISSUE THREAD

**Issue by Hellenk** [SBProX/SBProX-Dev#233]

**Comment by vector1207** [comment]
подтверждаю. котировки идут вот так — https://imgur.com/zukM8dO

**Comment by bizlis** [comment]
**Сообщали ранее о возможных проблемах:**

В течение нескольких дней будут активные работы по устранению проблемы с зависанием котировки на новостях и открытии рынка.

В течение проведения технических работ будут перебои в работе котировки.
Просьба отнестись с пониманием и не совершать торговых операций в ближайшие дни.

**Comment by vpaks** [comment]
Отсутствие котировок, как понял происходят из-за того, что при запуске QUIK, самопроизвольно, происходит отключение Lua скрипта, приходиться его заново запускать. Прошу обратить на это внимание. Это уже было несколько раз в течении недели.

**Comment by Bolt022** [comment]
> Отсутствие котировок, как понял происходят из-за того, что при запуске QUIK, самопроизвольно, происходит отключение Lua скрипта, приходиться его заново запускать. Прошу обратить на это внимание. Это уже было несколько раз в течении недели.

у тебя норм график через коннектор QUIK показывает? нет раздвоения?

**Comment by Bolt022** [comment]
у меня вроде норм котировки идут

**Comment by Hellenk** [comment]
Добрый вечер !
можно номер кошелька для перечисления денег на х про
не сайт с регистрацией

Regards!

**Comment by SBProX** [comment]
Обратите на sales@sb-professional.com
