### ISSUE TITLE
У кого такой же график по Si через коннектор QUIK ???

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#234]
какое-то раздвоение идёт... в чем дело?

когда нажимаю "Применить" как раз удвоение накладывается
![bandicam_2019-05-31_15-21-13-715](https://user-images.githubusercontent.com/51231827/58699867-030e4a00-83b8-11e9-999c-b4cb4912a702.gif)

**Comment by Bolt022** [comment]
Причем это раздвоение идёт тогда, когда котировка бежит он-лайн... когда день закончился, то всё норм... странная ошибка

**Comment by SBProX** [comment]
Исправляем, спасибо

**Comment by Bolt022** [comment]
> Исправляем, спасибо

серваки висят ваши... свеча через коннектор на 180к из неоткуда ))
![2019-06-03_164931](https://user-images.githubusercontent.com/51231827/58799954-1b809d80-8620-11e9-9b5b-7290cf404709.png)
