### ISSUE TITLE
Разрывы в котировках, перезагрузкой данных с сервера не лечиться.

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#235]
Также не помогает очистка кэша.

![image](https://user-images.githubusercontent.com/50357928/58700045-b4f14a80-83a7-11e9-8925-061ef8218fb6.png)

**Comment by fibo-one-love** [comment]
Может кто-то из разрабов вчера депо слил и теперь не до того? :)

**Comment by r0b4ik** [comment]
Помогла очистка кэша на диске. Но на проблему всё равно надо обратить внимание
