### ISSUE TITLE
Некорректно работает функция реверса в симуляторе. И не только она.

### ISSUE THREAD

**Issue by VeegoDamask** [SBProX/SBProX-Dev#236]
Добрый день. 

Выявил проблему с функцией реверса/ закрытием позиций. Или их сочетанием.

1. Открыли позицию, двумя частями по лоту. Итого 2 лота.

![image](https://user-images.githubusercontent.com/29836202/58730285-53a39880-83f4-11e9-8927-f24b678101ca.png)

2. Цена пошла против, переворачиваемся по кнопке реверса.
![image](https://user-images.githubusercontent.com/29836202/58730424-c57be200-83f4-11e9-8385-06039c62f6bb.png)
Происходит какое-то шаманство, которое можно уловить только в видео записи. В итоге симулятор думает, что был всего один лот ( который был открыт вторым) и кроет его. С убытком, таким образом результат уже неправильный.

3. Пытаемся добрать позицию лимиткой. Не срабатывает. Хотя цена её пробивает на 3 тика 2 раза

![image](https://user-images.githubusercontent.com/29836202/58730568-34593b00-83f5-11e9-8b80-69b28f382e65.png)

4. Пробуем еще раз на новом уровне. Опять облом ( лимитка в симуляторе не срабатывает)
![image](https://user-images.githubusercontent.com/29836202/58730639-6074bc00-83f5-11e9-8cbd-a94259c41215.png)

5. Хрен с ней с лимиткой, даем маркетом. Итого имеем 4 лота в короткую.
![image](https://user-images.githubusercontent.com/29836202/58730685-839f6b80-83f5-11e9-87de-dbdd79aedd79.png)

6.  Делаем частичный фикс на 2 лота по рынку. Обратите внимание, установки корректные, 2 лота.
![image](https://user-images.githubusercontent.com/29836202/58730783-bf3a3580-83f5-11e9-8124-11b8b56b0dbb.png)

7. Результат фикса- закрытие позиции полностью! При этом исчезает часть, которая открывалась в реверсе!
![image](https://user-images.githubusercontent.com/29836202/58730870-f1e42e00-83f5-11e9-9b2f-7075a91ad2ef.png)

**Comment by SBProX** [comment]
Что касательно первого скриншота, то позиция в два лота у вас закрылась правильно - по одному лоту. См. скриншот.
![sim](https://user-images.githubusercontent.com/16720120/58795347-17925280-8603-11e9-86c2-ef22278c2856.png)

**Comment by SBProX** [comment]
По остальному проверяем

**Comment by SBProX** [comment]
Вроде бы все работает.
Проверили. Если проблема будет наблюдаться, пересоздайте тикет.
