### ISSUE TITLE
Дневной VWAP на М1 и М10 отличается. Почему?

### ISSUE THREAD

**Issue by VeegoDamask** [SBProX/SBProX-Dev#239]
![image](https://user-images.githubusercontent.com/29836202/58752961-5075de80-84c0-11e9-9fce-9452f80789ba.png)

![image](https://user-images.githubusercontent.com/29836202/58752966-5d92cd80-84c0-11e9-8f5d-083d4383f520.png)

Разница в 30 центов. Настройка стоит Day и там и там.

**Comment by SBProX** [comment]
К сожалению не можем вопроизвести, у нас совпадает.
Будем проверять

**Comment by bizlis** [comment]
Подтверждаю, есть разница в отображении VWAP на разных графиках с одинаковыми параметрами, после перезагрузки данных с сервера, данные подправляются, но не факт что они одинаковые становятся.
