### ISSUE TITLE
Некорректное отображение по барам и кластерам

### ISSUE THREAD

**Issue by affectus1** [SBProX/SBProX-Dev#240]
1. При сужении кластерного графика с свечами кластера пропадают. 
https://ibb.co/n8Lv66H
2. Смещение уровней на свечном графике и кластерном
https://ibb.co/HdxZ8MF
3. Проблема с баровым графиком цена открытия смещается вправо. 
при сужении бары пропадают.
https://ibb.co/4KVRG3j
4. Неровное расположение кластеров 
https://ibb.co/Fw0vmL8

Хотелось бы чтобы эти вещи исправили перед продажей платформы)

**Comment by affectus1** [comment]
Еще было бы круто доработать линковку чтобы копировались уровни автоматом на все залинкованные графики и графические объекты круги там прямоугольники и.т.д.

**Comment by SBProX** [comment]
1. Так и было задумано, какие кластера вы там хотите увидеть с направлением бара и таким узким масштабом?

2. Из приведенных вами скриншотов ничего не понятно, нужно высылать полные скриншоты

3. Бары не пропадают при сужении. Пропадают риски Open Close, так как они не помещаются.
По поводу смещения цены открытия право - исправим.

4. Ясно
