### ISSUE TITLE
Интересная ошибка в БоксЧарте

### ISSUE THREAD

**Issue by SasasSasas** [SBProX/SBProX-Dev#245]
Если в БоксЧарте, мышкой двигать график, то наполнение кластеров то растут с лева, то пропадают если протянуть в право.
https://yadi.sk/i/nNHGJnAXSfByMw

**Comment by SBProX** [comment]
Это не ошибка, дело в том что ширина профиля строится из видимых баров.
Когда вы двигаете график, то слева появляются большие значения, соответсвенно рейтинг меняется.
