### ISSUE TITLE
Убрать соединение дней/недель у VWAP

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#252]
Можно ли убрать соединение дней у VWAP, чтобы было проще их разделять между днями, особенно, если появятся расширения у этого индикатора.
![Screenshot_8](https://user-images.githubusercontent.com/29704362/58893403-8ce84b00-8709-11e9-8c63-046564e417b8.jpg)

**Comment by SBProX** [comment]
Хорошо, попробуем сделать.

**Comment by SBProX** [comment]
Сделано
