### ISSUE TITLE
бета-тестирование закончилось?

### ISSUE THREAD

**Issue by murza2019** [SBProX/SBProX-Dev#255]
Пробую зайти в новую программу со своим паролем от sbpro V2,
и не могу зайти, 
 хотелось перед покупкой посмотреть на новое обновление от 04 июня,
 Вопрос:    Бета-тестирование закончилось и уже нельзя посмотреть?

**Comment by Flyrine** [comment]
> Пробую зайти в новую программу со своим паролем от sbpro V2,
> и не могу зайти,
> хотелось перед покупкой посмотреть на новое обновление от 04 июня,
> Вопрос: Бета-тестирование закончилось и уже нельзя посмотреть?

Да,запустили продажу

**Comment by SBProX** [comment]
Можете еще сделать демо на 10 дней.
