### ISSUE TITLE
АКЦИИ московской биржи

### ISSUE THREAD

**Issue by murza2019** [SBProX/SBProX-Dev#256]
2 года имею sbpro V2 -  2 года ЖДУ АКЦИИ московской биржи.
Хочу купить новую программу, -
но для меня критично иметь графики АКЦИЙ московской биржи.
В новой программе есть коннектор для КВИКа
Вопрос: 
Этот коннектор позволяет подключать АКЦИИ и другие инструменты московской биржи?

**Comment by Bolt022** [comment]
> 2 года имею sbpro V2 - 2 года ЖДУ АКЦИИ московской биржи.
> Хочу купить новую программу, -
> но для меня критично иметь графики АКЦИЙ московской биржи.
> В новой программе есть коннектор для КВИКа
> Вопрос:
> Этот коннектор позволяет подключать АКЦИИ и другие инструменты московской биржи?

Отвечу за разрабов как пользователь, который тестил уже коннекторы их... 
- коннектор через Квик работает, но показывает кривые графики, 
- через коннектор нет ни акций, ни спота по валютам, как это сделало в ТайгерТрейд (ребята знают толк в этом). 

P.S. Не знаю чем они там думают, давно бы уже сделали прогу через коннекторы и не тратились на котировки для своих серваков и на серваки, и намного шире линейка была бы и народу бы больше приходило, но они видимо, это не понимают, что неудивительно, судя по их отношению и ответам. Красивый интерфейс типо налепили и функций для детишек, а толку... пока не покупаю!

**Comment by murza2019** [comment]
тогда не вижу разницы между старой и новой прогарммой....
в старой версии sbpro V2 - нет индикаторов, -
но индикаторы не помогают прибыльно торговать!
это все глупые игрушки - бесполезные украшения!
фьючерсы и так есть в старой версии...
какой смысл мне покупать новую программу,
если в ней нет самого главного - инструментов ?

Пока в программе нет АКЦИЙ, к вам НЕ придут трейдеры с московской биржи.
