### ISSUE TITLE
Дельта за 4.06

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#257]
На разных инструментах кластер дельта за 4.06 в повышенных значениях
![image](https://user-images.githubusercontent.com/7328803/58934052-fa2fc680-8771-11e9-9c91-74d6f960f6a9.png)

**Comment by Bolt022** [comment]
Она вся красная по дню... ни одного покупочного значения на минутках ))

**Comment by SBProX** [comment]
Уже все исправили, была ошибка в софте на сервере.
Перезагрузите данные с сервера через контекстное меню.
