### ISSUE TITLE
Ошибка при дублировании линий

### ISSUE THREAD

**Issue by NikolaiBogachev** [SBProX/SBProX-Dev#258]
При дублировании ширина не копируется при виде сплошной линии .

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by SBProX** [comment]
Ширина отлично копируется, не понятно что у вас не получается.
Пишите тогда в тех. поддержку.

**Comment by NikolaiBogachev** [comment]
Я ошибка есть тока не так как я сказал в начале . На 30 минутном графике Ширина вообще не меняется соответственно не копирует ширину .

**Comment by SBProX** [comment]
Скриншот можете выслать?

**Comment by NikolaiBogachev** [comment]
Прошу извинения , сейчас пробовал все нормально ширина меняется. Но было когда и не менялась
я перед тем когда написать несколько раз проверил видимо он мерцающий не всегда проявляется поэтому и про видео смело написал.

**Comment by SBProX** [comment]
Тогда если вопрос решен, закроем тикет. Спасибо
