### ISSUE TITLE
Дублирование линий (лишняя буква L)

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#259]
В текущий момент, при дублировании линий, слева от крестика удаления линии стала появляться буква L. До крайнего обновления ее не было, и без нее было куда лучше. На мой взгляд, данная функция не несет никакой пользы, более того, она мешает и загромождает график когда линий много! Уважаемые разработчики, уберите пожалуйста эту букву, пусть будет так, как было раньше.
https://monosnap.com/file/mBSzKLSWFBnIVUG3XPngSrYJUKW6Ww

**Comment by Flyrine** [comment]
Я сначала подумал что так отображаются линии на линкованных (L) графиках...но L появляется и при просто дублировании...действительно и зачем она тогда?

**Comment by Bolt022** [comment]
> Я сначала подумал что так отображаются линии на линкованных (L) графиках...но L появляется и при просто дублировании...действительно и зачем она тогда?

что такое линковка и цвета в проге... не могу понять...

**Comment by Flyrine** [comment]
> что такое линковка и цвета в проге... не могу понять...

Линковка это автоматическое копирование линий и других  каких либо функций,в сбпро линковка  копирует даты на графиках и линии...Линии сейчас не обязательно дублировать с одного графика и вставлять на другой...Включаешь одинаковый цвет на линковке на нужных графиках и они ставятся автоматом

**Comment by SBProX** [comment]
Когда вы дублируете линию на другой график (или графики), то эти линии становятся между собой залинкованными так же, как и в случае если вы включите линковку.

**Comment by vasiliyyun** [comment]
Это понятно, не понятно зачем буква L об этом информирует. Мне по сути не важно задублирована линия или залинкована, главное она там куда я ее нанес (скопировал).

**Comment by Alkor135** [comment]
Как я понял, буква "L" появляется у тех линий, при удалении которых на одном графике, удаляться и на других графиках. На мой взгляд это полезно. К тому же, "L" маленькая и расположена в правом краю, где ходят часы, так что она никак не закрывает график.

**Comment by SBProX** [comment]
Все верно. Если будет сильно критично всем мешать - сделаем опцию отключения.
