### ISSUE TITLE
Перекрытие кластеров линиями

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#260]
Можно ли как-то сделать, чтобы на всех ТФ линии были на заднем фоне и не перекрывали график?
![Screenshot_4](https://user-images.githubusercontent.com/29704362/58947616-b654b580-87a1-11e9-8739-4cc00407ff00.jpg)

**Comment by Flyrine** [comment]
> Можно ли как-то сделать, чтобы на всех ТФ линии были на заднем фоне и не перекрывали график?

Ползунок А в настройке цвета линии...этим регулируется прозрачность линии

**Comment by bizlis** [comment]
> Ползунок А в настройке цвета линии...этим регулируется прозрачность линии
это не то, надо чтобы сама линия была под графиком

**Comment by SBProX** [comment]
А сейчас линия не под графиком?
Линия не должна перекрывать график, и она ПОД графиком. Внимательно посмотрите на ваш скриншот.

**Comment by SBProX** [comment]
Кластеры не перекрываются на профиле, там просто шрифт только, который находится НАД линией.
А линия ПОД шрифтом. Просто из-за того что у вас линия светлая, и шрифт белый, кажется что сливается.
