### ISSUE TITLE
Акции, Спот по валютам и многое другое. ВНЕДРИТЕ!!!

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#263]
**Уважаемые разработчики!**
Предлагаю вам идею наилегчайшую и быстровоплотимую, внедрение которой ждут все трейдеры от любой программы, а тем более вашей.

Есть хороший привод, Qscalp называется, работает только через коннекторы.
Программа ОЧЕНЬ простая, НО в ней можно выбрать практически ЛЮБОЙ инструмент, тянущийся из Квика (скрин во вложении). Жаль только торговая, а не аналитическая.

****Идея в том** , чтобы сделать такую же возможность (как и в приводе) для тех, кто работает через коннекторы**, т.е. вам не нужно покупать эти котировки для своего сервака. Сделайте элементарно вывод окна под список инструментов и готово. Уже все давно внедрили коннекторы в свои программы, т.к. все понимают огромный плюс.... они дают бесплатный доступ  трейдерам к **котировками множества инструментов**, тем самым меньше нагружая серваки разрабов + торговля (но у вас такой функции нет).

**Теперь пофилософствуем и покритикуем...**  а что делаете вы... внедряете какую-то х.рню (извиняюсь за выражение), какие-то затемнения, красивую ерунду, тратя на это своё время, которая большинству зарабатывающих трейдеров вообще не нужна. Прежде чем что-то создавать, исследуйте  рынок для начала... поймите, что нужно трейдерам. _А нам нужно в первую очередь:_ 
- множество инструментов для анализа! Вы же называете свою платформу аналитической.... Как можно анализировать фьючи без спота или акций? Хоть раз задумывались над этим?! Это главное, а не рисовалки и фибоначи деревенские.

**Хотелось бы, чтобы программа жила и развивалась, и радовала пользователей, но порой кажется, что не то вводите в первую очередь** 

_И совет хороший... ниша программ по объемному анализу в 1000р/мес. еще не занята... к вам сразу прибежит часть народа от Тайгера, Волфикса и Атаса. Разумеется, если будет множество инструментов для анализа (хотя бы через коннекторы)_ 

![2019-06-05_182915](https://user-images.githubusercontent.com/51231827/58961043-d4caa900-87c1-11e9-8a96-426fe281cf2a.png)

**Comment by alexanflint** [comment]
Здравое и полезнейшее предложение.Поддерживаю.

**Comment by SBProX** [comment]
Как у вас все просто.
Вы не задумываетесь о нюансах.
А историю откуда брать на эти акции? Нам придется их тоже качать.
Или из квика можно качать тиковую историю?

))

**Comment by Bolt022** [comment]
> Как у вас все просто.
> Вы не задумываетесь о нюансах.
> А историю откуда брать на эти акции? Нам придется их тоже качать.
> Или из квика можно качать тиковую историю?
> 
> ))

**ЗАЧЕМ ВАМ КАЧАТЬ ИСТОРИЮ НА СВОИ СЕРВАКИ?????**

**При подключении Qscalp через коннектор к Квику весь указанный промежуток истории (и тики) загружается сразу! Тоже самое происходит и с вашей  программой, когда входим в неё... только история качается с вашего сервака, а через коннектор - с сервака моего брокера (т.е. тянется с Квика)!** И также можно анализировать объемы, только через Qscalp неудобно это делать.
