### ISSUE TITLE
Глюки с дельтой

### ISSUE THREAD

**Issue by vector1207** [SBProX/SBProX-Dev#264]
Инструмент РТС, дневной таймфрейм.
За 04.06.2019 суммарный объем 501682, суммарная дельта -501682.
Как такое возможно?

версия платформы V2.

![Screenshot (1131)](https://user-images.githubusercontent.com/51026325/58964898-574e6b00-87b8-11e9-9a84-873a0651f950.png)

**Comment by SBProX** [comment]
Да, была такая проблема.
Перезагрузите данные с сервера, еще утром устранили.
![Screenshot_1](https://user-images.githubusercontent.com/16720120/58965787-d2645100-87b9-11e9-8e4d-914ff688bed2.png)
