### ISSUE TITLE
Индикатор максимально объема в баре/свече

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#265]
Сделайте индикатор максимального объема, чтобы на барах или свечках его можно было видеть (линией или еще как-нибудь, не столь важно, главное чтобы было видно где этот максимальный объем находится по отношению к OHLC)
![Screenshot_8](https://user-images.githubusercontent.com/29704362/58976518-174fae00-87e1-11e9-82e4-ac783ddb34cc.jpg)

**Comment by linkoln248** [comment]
Я из этой ситуации вышел, используя индикатор Period Volume Profile, соответственно выставляя его период равным периоду одной свечи. Далее выставил на максимум прозрачность профиля, цвет максимального объема наоборот сделал поконтрастнее. Это не то же самое, о чем Вы просите, но и не сильно то отличается, если не меняете таймфрейм в одной вкладке постоянно.

**Comment by bizlis** [comment]
> Я из этой ситуации вышел, используя индикатор Period Volume Profile, соответственно выставляя его период равным периоду одной свечи. Далее выставил на максимум прозрачность профиля, цвет максимального объема наоборот сделал поконтрастнее. Это не то же самое, о чем Вы просите, но и не сильно то отличается, если не меняете таймфрейм в одной вкладке постоянно.

Да, попробовал, в принципе, как вариант можно использовать.
