### ISSUE TITLE
Выход графика из видимой области

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#267]
Если не включать автомасштабирование графика, то график выход за пределы видимой области. А в конкретно в моем случае если включить автомасштабирование, то график будет в видимой области, но цифры в кластерах пропадут из-за сжатия.
![Screenshot_9](https://user-images.githubusercontent.com/29704362/58979590-cc856480-87e7-11e9-9989-528b4fb1e4d8.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/29704362/58979697-0e160f80-87e8-11e9-8401-daef803e3711.jpg)

**Comment by SBProX** [comment]
Да, цифры пропадают. Они и должны пропадать при сильном сжатии.
В чем здесь ошибка?

**Comment by bizlis** [comment]
Проблема не в пропаже цифр, а в выходе графика за пределы видимости, в версии 2 график ни когда не уходил из видимой области

**Comment by SBProX** [comment]
Ok, принято

**Comment by SBProX** [comment]
Исправлено
