### ISSUE TITLE
ошибка - кумулятивная дельта по CL

### ISSUE THREAD

**Issue by serega1511** [SBProX/SBProX-Dev#268]
неправильный график по кумулятивной дельте по инструменту CL - не совпадает со старой версией, не совпадает с другими источниками, не совпадает с тем, что было раньше, да и просто "бред" нарисован

то есть сами цифры неправильные 

данные за 4 июня 2019 полностью неверны

**Comment by SBProX** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/16720120/59151519-38acd600-8a3d-11e9-9fc9-30d35c840f84.png)

Все совпадает.
Прежде чем писать "бред", и так далее - хотя бы вышлите скриншоты.
4-го числа были проблемы с данными, но мы их решили, попробуйте перезагрузить данные с сервера через контекстное меню.
