### ISSUE TITLE
Невозможно нарисовать стрелку с указанием направления в будуйщем

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#27]
![image](https://user-images.githubusercontent.com/50357928/57300757-222efa00-70e0-11e9-987f-11f09a715f7d.png)

Конец стрелки перетащить за границу текущего времени невозможно. При этом все остальные объекты за границей текущего времени нарисовать можно.

**Comment by r0b4ik** [comment]
Через время стрелку всё таки можно перетащить 
![image](https://user-images.githubusercontent.com/50357928/57306918-4bee1e00-70ec-11e9-97ce-5469eebd7dbc.png)

**Comment by r35p3ct** [comment]
И не только стрелок, хотелось бы иметь возможсть рисования прогнозов на будущее.

**Comment by SBProX** [comment]
Сделано
