### ISSUE TITLE
Запаздывает значение ОИ в SBProX

### ISSUE THREAD

**Issue by vpaks** [SBProX/SBProX-Dev#272]
Открытий интерес (ОИ) в SBProX запаздывает по сравнению с текущим показателем в QUIK

![Снимок1](https://user-images.githubusercontent.com/50356199/59022141-ecc12c00-8898-11e9-89a6-f010d9db71c6.jpg)
![Снимок2](https://user-images.githubusercontent.com/50356199/59022151-ef238600-8898-11e9-8a8a-0e23c851319d.jpg)

**Comment by Bolt022** [comment]
> Открытий интерес (ОИ) в SBProX запаздывает по сравнению с текущим показателем в QUIK
> 
> ![Снимок1](https://user-images.githubusercontent.com/50356199/59022141-ecc12c00-8898-11e9-89a6-f010d9db71c6.jpg)
> ![Снимок2](https://user-images.githubusercontent.com/50356199/59022151-ef238600-8898-11e9-8a8a-0e23c851319d.jpg)

поставь в настройках индикатора галочку "показывать последнее значение" и норм будет... вот так тут у них это реализовано... а я думал, что изначально циферки так показывать будет )

**Comment by vpaks** [comment]
Спасибо, попробую

**Comment by Alkor135** [comment]
Спасибо, за совет. А то я тоже думал, что это глюк. Только не понятно, почему сразу не показывает последние значения.
