### ISSUE TITLE
Поменять принцип загрузки истории для симулятора 

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#274]
Загрузку истории надо сделать по другому принципу, не так как сейчас реализовано (хотя это конечно лучше чем ничего), опишу принцип работы подгрузки необходимого периода истории в симуляторе, как я вижу для оптимальной работы тестирования стратегий:

Пользователь открывает необходимое количество ТФ (к примеру Д1, Н1, М5, М1)
На каждом ТФ пользователь устанавливает свой период подгрузки графика (к примеру для Д1=год, Н1=3 месяца, М5=неделя, М1=день). Т.е. конечная дата на всех ТФ одна и та же, а начальная дата графика разная.
На всех ТФ настраиваются графики, добавляются индикаторы
Выбирается режим симулятор и устанавливается начальная дата, с которого начнется тестирование.

В итоге мы имеем некоторую подгруженную историю, с необходимыми настройками, на которой проводится предварительный анализ, а запуск теста текущих торгов дает отработку стратегии.

Суть в том, что необходимо увидеть как движется цена относительно дня, недели, месяца одновременно, для этого и выбираются разные начальные периоды истории для разных ТФ.

**Comment by Anton144** [comment]
Поддерживаю,идей много хороших,осталось только всё структурировать в одно общее техническое задание.

**Comment by SBProX** [comment]
Скажем честно - спасибо за предложение по истории, но у нас пока нет возможности тратить время на такие вещи, так как это нужно переделывать систему загрузки истории.
И для каждого инструмента - ставить свои даты - это неудобно.

**Comment by Anton144** [comment]
И Вам спасибо за проделанную работу,я думаю всему своё время!

**Comment by SBProX** [comment]
Спасибо за понимание, мы постараемся все сделать в лучшем виде, сейчас главное чтобы все работало и ничего не сбоило.
