### ISSUE TITLE
сделать регулировку прозрачности (Период волиум профиль)

### ISSUE THREAD

**Issue by ws-keith** [SBProX/SBProX-Dev#275]

**Comment by Flyrine** [comment]
Уважаемые разработчики напишу здесь ..В динамическом профиле в режиме объема нет регулировки прозрачности...хотя окошко с процентным значением для этого сделано...прозрачность работает только в режиме дельты и бид/аск это явная ошибка

**Comment by 41of1** [comment]
![2019-06-07_21-15-43](https://user-images.githubusercontent.com/51477821/59124933-9ff95600-8969-11e9-8bba-98c86bdfe682.jpg)
ПРОЗРАЧНОСТЬ РЕГУЛИРУЕТСЯ ВОТ ЭТОЙ ШТУКОЙ

**Comment by Flyrine** [comment]
Да  А регулируется,я и прозрачность линий ей выставляю Просто для динамического профиля изначально была сделана регулировка в процентной строке,но вот работает не во всех режимах

**Comment by SBProX** [comment]
Вам все верно ответили.
Профили объема и дельты имеют разную систему фильтрации, поэтому так сделано.
