### ISSUE TITLE
 Cluster Search

### ISSUE THREAD

**Issue by 41of1** [SBProX/SBProX-Dev#277]
1) Добавить возможность просмотра значений Cluster Search на графике.
2) Постоянно появляется сообщение об обновлении, которого нет.
![2019-06-07_11-09-56](https://user-images.githubusercontent.com/51477821/59124258-ea79d300-8967-11e9-81df-4628732768f7.jpg)

**Comment by Fen8fen** [comment]
http://www.sb-professional.com/sbprox
- Обновите платформу по ссылке.

**Comment by Alkor135** [comment]
> 2\. Постоянно появляется сообщение об обновлении, которого нет.

Попробуйте инсталятор , а в последующем и платформу запустить от имени администратора.

**Comment by SBProX** [comment]
Ошибку с надписью обновления проверим.
По поводу Cluster search - сделаем.
