### ISSUE TITLE
Оптимизировать торговый функционал симулятора

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#278]
Предлагаю оптимизировать торговый функционал симулятора, в плане размещения информационных окон и возможно торговых кнопок, вывести все на на одном экране самого симулятора. 
![Без-имени-1](https://user-images.githubusercontent.com/29704362/59143320-61a07d00-89e3-11e9-89f5-e4e8ff5a8f20.jpg)

**Comment by Flyrine** [comment]
Переключатся между двумя окнами даже для паузы,тоговли и т.д!? И иметь второе окно на пол графика... Не лучшая реализация.В симуляторе все должно быть пол рукой и при этом ничего лишнего ...в Tiger trade вся панель плеера это узенькая полоска места...при этом там и пауза и перемотка и переход на заданное время...сделки запускаются с торгового модуля который также используются в реальном времени,на нем же отобраются и прибыль и лот входа

**Comment by bizlis** [comment]
> Переключатся между двумя окнами даже для паузы,тоговли и т.д!? И иметь второе окно на пол графика... Не лучшая реализация.В симуляторе все должно быть пол рукой и при этом ничего лишнего ...в Tiger trade вся панель плеера это узенькая полоска места...при этом там и пауза и перемотка и переход на заданное время...сделки запускаются с торгового модуля который также используются в реальном времени,на нем же отобраются и прибыль и лот входа

Загромождать графики одним и тем же, тоже не лучший вариант, а вот боковая панель торговли, как в большинстве симуляторов, это было просто отлично.

**Comment by Flawmaster** [comment]
Насчет боковой панели согласен. И еще было бы неплохо сделать автоматическое выставление стопа и тейка. А то очень много времени тратится на это.

**Comment by Flyrine** [comment]
Я предлагал вариант
https://github.com/SBProX/SBProX-Dev/issues/229 
Там график ничем не загроможден,панель баланса не в счет она на свечки/кластера не лезет и бегать по доп панелям не надо,все под рукой.Через несколько дней предложу симулятор с торговым модулем ,кнопок в строчке будет еще меньше,без панели баланса,а возможностей больше

**Comment by bizlis** [comment]
> Насчет боковой панели согласен. И еще было бы неплохо сделать автоматическое выставление стопа и тейка. А то очень много времени тратится на это.

Да, стопа и тейка тоже не хватает, сделать их надо рядом с количеством контрактов

**Comment by SBProX** [comment]
Ваш вариант крайне неудобен.
Мы категорически против. 
Симулятор в плане удостбва еще будет дорабатываться.
