### ISSUE TITLE
Звуковые оповещения от Clouds

### ISSUE THREAD

**Issue by Alkor135** [SBProX/SBProX-Dev#279]
Предлагаю добавить звуковые оповещения в индикатор Clouds, а то приходится извращаться через UOPilot.
![image](https://user-images.githubusercontent.com/50710452/59148607-ca075280-8a13-11e9-8433-cdc479b51d5d.png)

**Comment by Flyrine** [comment]
Alkor135 при включенном индикаторе зайди в вкладку сигналы(на графике правой кнопкой мыши) там список..пара алертов и добавленные индикаторы попробуй там,возможно получится.К сожалению сам посмотреть не могу

**Comment by Alkor135** [comment]
Спасибо за информацию, попробую!

**Comment by Alkor135** [comment]
> Alkor135 при включенном индикаторе зайди в вкладку сигналы(на графике правой кнопкой мыши) там список..пара алертов и добавленные индикаторы попробуй там,возможно получится.К сожалению сам посмотреть не могу

Точно, есть там алерты, а я извращался )))
Осталось только понять, что означает "лимит суммы"
![image](https://user-images.githubusercontent.com/50710452/59148816-03d95880-8a16-11e9-9d20-d2e749e4d53b.png)
Думаю, что можно закрыть тикет.
