### ISSUE TITLE
Индикатор VWAP перерисовывается в реальном времени

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#28]
![image](https://user-images.githubusercontent.com/50362894/57307397-27467600-70ed-11e9-95af-559c435d4474.png)
![image](https://user-images.githubusercontent.com/50362894/57307418-33cace80-70ed-11e9-8116-f3d8d691a5aa.png)

**Comment by alex12mosk** [comment]
после обновления исправляется и снова начинает перерисовываться

**Comment by SBProX** [comment]
Исправлено.
