### ISSUE TITLE
Добавить шкалу значений для нижних индикаторов

### ISSUE THREAD

**Issue by vector1207** [SBProX/SBProX-Dev#280]
Просьба добавить шкалу значений для нижних индикаторов. А также выводить туда текущее значение индикатора. Потому что постоянно наводить мышку на текущий бар, или того хуже — растягивать график в ширину в десять раз, чтобы прочитать числовое значение объема, реально утомляет. Во ВСЕХ терминалах эти шкалы есть, отсутствуют только в вашем.

Да, по индикатору видно, когда появляются большие значения (относительно предыдущих), когда маленькие, но КАКИЕ именно? На глаз это не определить, т.к. максимальная высота гистограммы не имеет привязки к конкретным значениям, а строится относительно видимых баров, и это постоянно вводит в заблуждение.

Спасибо.

![Screenshot (1138)](https://user-images.githubusercontent.com/51026325/59148526-c1fae300-8a12-11e9-86a4-51465be29fe2.png)

**Comment by Bolt022** [comment]
я тоже не понял юмора сначала, почему без значений и шкалы ))

**Comment by Ravil124** [comment]
Поддерживаю. Постоянно приходиться наводить курсор, чтобы узнать значение индикатора.

**Comment by SBProX** [comment]
Рассмотрим возможность по шкале.

**Comment by r35p3ct** [comment]
Проще и компактнее их добавить ниже значений HLOC

**Comment by Ravil124** [comment]
Шкала индикатора более рационально и информативнее.
