### ISSUE TITLE
Ошибка !

### ISSUE THREAD

**Issue by DallasVega** [SBProX/SBProX-Dev#281]
День добрый ! 
вопрос к разработчика : как так получается, что на дневном графике фьючерсе нефти и золота, при пятинедельной торговой недели - шесть дневных баров ??? (Американский рынок)
Обращался в тех. поддержку в скайпе - ничего толком объяснить не смогли.
По факту это корявая обработка данных в совокупности со временем открытия бирж, отсюда появляется лишние дневные воскресные бары, которые при побарном анализе искажают информацию. пример - когда на самой бирже - комекс или наймекс - понедельник заканчивается баром покупок, ТО у СБПРО этот бар - продажный.
Необходимо исправить данный баг, так как это приводит  к искажению контекста рынка и принятию неверных решений, что в конечном итоге отражается на счете.

Смена поясов картину не исправляет. 
Считаю , что платформа должна показывать и отражать действительную информацию от первоисточника - Американские биржи (речь пока только про западные инструменты), а не какойто  алгоритм подсчета платформы.

**Comment by DallasVega** [comment]
![изображение](https://user-images.githubusercontent.com/21984531/59150540-f7f99080-8a2d-11e9-9b40-0849af73e556.png)
на картинке показал - лишние бары
+ непонятно = скрин сделан во вторник - а на дневке еще понедельник)))

**Comment by VeegoDamask** [comment]
С чего Вы взяли, что нефть торгуется 5 дней?

![image](https://user-images.githubusercontent.com/29836202/59150565-43ac3a00-8a2e-11e9-9063-bbc818abf930.png)

**Comment by SBProX** [comment]
> День добрый !
> вопрос к разработчика : как так получается, что на дневном графике фьючерсе нефти и золота, при пятинедельной торговой недели - шесть дневных баров ??? (Американский рынок)
> Обращался в тех. поддержку в скайпе - ничего толком объяснить не смогли.
> По факту это корявая обработка данных в совокупности со временем открытия бирж, отсюда появляется лишние дневные воскресные бары, которые при побарном анализе искажают информацию. пример - когда на самой бирже - комекс или наймекс - понедельник заканчивается баром покупок, ТО у СБПРО этот бар - продажный.
> Необходимо исправить данный баг, так как это приводит к искажению контекста рынка и принятию неверных решений, что в конечном итоге отражается на счете.
> 
> Смена поясов картину не исправляет.
> Считаю , что платформа должна показывать и отражать действительную информацию от первоисточника - Американские биржи (речь пока только про западные инструменты), а не какойто алгоритм подсчета платформы.

Мы не считаем это багом. Это скорее - ваше личное мнение на то, как должно быть по вашему.
Платформа делит дни по календарному времени.
Так как у вас стоит по Чикаго по умолчанию, то присутствует воскресенье.

Вы говорите, что смена пояса не дает результатов?
Вот пожалуйста, CL по московскому времени, со 2-го июня - 5 дней, как Вы и хотели.
![Screenshot_2](https://user-images.githubusercontent.com/16720120/59151295-537d4b80-8a39-11e9-8b18-7eaf51a81420.png)

**Comment by tenalex** [comment]
При смене часового пояса поменялся график со свечами ! Можно ли поменять часовой пояс независимо от графика?

**Comment by tenalex** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/18304997/71373066-0755bb00-25c7-11ea-9d30-d10a8e5e5a4e.png) - это американский часовой пояс

**Comment by tenalex** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/18304997/71373173-54d22800-25c7-11ea-8ba3-3c3fe93377f7.png)
 - это московский часовой пояс

**Comment by SBProX** [comment]
> При смене часового пояса поменялся график со свечами ! Можно ли поменять часовой пояс независимо от графика?

Нельзя, так как графики строятся с 00.00 - когда вы меняете пояс, то и бары на некоторых тф могут быть другими.
