### ISSUE TITLE
Cloud - Bid-Ask Mode - цветовое оформление (заливка) 

### ISSUE THREAD

**Issue by MAXK04** [SBProX/SBProX-Dev#283]
Небольшое предложение на рассмотрение. 
Не могли бы Вы подумать о возможности включения функции применения полупрозрачной заливки фигур выделения вливаний (в виде доп. галочки в меню индикатора Cloud) при выборе функции разделения на Bid - Ask, так как в режиме общего фильтра все прекрасно визуализировано. _Желательно, чтобы была также возможность изменения прозрачности такой заливки._ 

Скрин при светлом оформлении более четко показывает "проблемку" в визуализацией 
![01](https://user-images.githubusercontent.com/51521568/59154061-dc24d780-8a8b-11e9-8876-1cdd49130328.png)

**Comment by Ravil124** [comment]
Поддерживаю.

**Comment by MAXK04** [comment]
@SBProX  Да, огромное спасибо - стало очень удобно, **небольшой дополнительный вопрос** (не думаю, что нужно новый тикет открывать) - **_Есть какая-то проблема с заливкой фигур треугольник в Cloud?_**

**Comment by SBProX** [comment]
@MAXK04 треугольник пока не заливается, но попробуем сделать.
