### ISSUE TITLE
Рисование - создание трендового канала 

### ISSUE THREAD

**Issue by MAXK04** [SBProX/SBProX-Dev#285]
Возможно ли создание функции построения трендового канала? Было бы лучше с возможностью построения 50% (центральной) линии (галочка?)

**Comment by bizlis** [comment]
уже есть такая задача https://github.com/SBProX/SBProX-Dev/issues/16

**Comment by SBProX** [comment]
Не дублируйте пожалуйста одно и тоже.
В репозитории не так много тикетов, не сложно с ними ознакомиться.
