### ISSUE TITLE
Возможность настоящей торговли из программы, а не из квика

### ISSUE THREAD

**Issue by dimaan29** [SBProX/SBProX-Dev#286]
Будет ли возможность подключения настоящей торговли прямо из программы, а не из квика. А то неудобно иметь множество мониторов: часть для квика, часть для сбпро. И уж очень неудобно перерисовывать в квик все линии и зоны. Куда проще сделать привод, и торговать напрямую из сбпро. (не путать с симулятором).

**Comment by bizlis** [comment]
> Будет ли возможность подключения настоящей торговли прямо из программы, а не из квика. А то неудобно иметь множество мониторов: часть для квика, часть для сбпро. И уж очень неудобно перерисовывать в квик все линии и зоны. Куда проще сделать привод, и торговать напрямую из сбпро. (не путать с симулятором).

А зачем все перерисовывать в другие терминалы, анализируйте все в СБ, а другие терминалы используйте только для открытия/закрытия сделки...

**Comment by dimaan29** [comment]
Так и делаю в данный момент: анализирую в сбпро, а ордера в квике. Но может быть было бы удобней делать все из одной программы. Если большинству пользователей это понравится, думаю вы можете рассмотреть возможность такой функции.

**Comment by SBProX** [comment]
Торговый функционал мы делать не будем, уже об этом сообщали.
