### ISSUE TITLE
Фон фильтров перекрывает рамку кластера

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#287]
При смене цвета фильтров у кластерных графиков, фон фильтра перекрывает цвет рамки кластера, не особо критично конечно, но как-то не очень красиво эти обрывы смотрятся
![Screenshot_13](https://user-images.githubusercontent.com/29704362/59155943-b1974680-8aac-11e9-8235-e53c54198661.jpg)

**Comment by vector1207** [comment]
Я писал об этом еще несколько месяцев назад в телеграм-канале бета-тестирования, пока он существовал. Наверно меня не услышали. Проблема в том, что сетка кластеров криво расположена по горизонтали и вертикали.

![Screenshot (1076)](https://user-images.githubusercontent.com/51026325/59157385-70099a00-8ab2-11e9-8bd0-8241c51b6228.png)
![Screenshot (1075)](https://user-images.githubusercontent.com/51026325/59157386-70099a00-8ab2-11e9-9a50-6906553c88b2.png)

**Comment by bizlis** [comment]
вот пусть сейчас разработчики и обратят на это внимание

**Comment by SBProX** [comment]
Исправили, будет в следующем обновлении.
