### ISSUE TITLE
Динамический профиль: режимы по умолчанию

### ISSUE THREAD

**Issue by 220vlt** [SBProX/SBProX-Dev#29]
**Проблема:** При накладывании **Динамического профиля** на график постоянно приходиться его выделять и менять режим(V, D, BA, VD, VBA) на необходимый.

**Цель:** Реализовать возможность выбора **Режим по умолчанию** для **Динамический профиль** в "**Настройки динамического профиля**".

![image](https://user-images.githubusercontent.com/31524209/57315406-2b2dc480-70fc-11e9-949d-e60ecac088cd.png)

**Comment by SBProX** [comment]
Исправлено.

**Comment by AlTuzov** [comment]
Не сохраняются настройки динамического профиля по умолячнию. Раньше работало, но перестало.
