### ISSUE TITLE
График - "Наименование инструмента" (Оформление)

### ISSUE THREAD

**Issue by MAXK04** [SBProX/SBProX-Dev#291]
Уважаемые разработчики, хочу предложить Вам внести возможность добавления пользователем НАИМЕНОВАНИЕ инструмента прямо на график. 
Возможные функции:
1. Местоположение - центр, левый верхний угол, правый верхний угол
2. Размер шрифта
3. Цвет
4. Прозрачность
Очень удобная вещь при работе (Пример NT8, MR Indicator)
![SBProX 3](https://user-images.githubusercontent.com/51521568/59198520-beec2800-8bb5-11e9-8612-5b23f7f0f917.png)

**Comment by r35p3ct** [comment]
Прозрачность меняется в настройках цвета

**Comment by MAXK04** [comment]
> Прозрачность меняется в настройках цвета

Удалил. про фигуры Забыл, там же параметр "А" есть. Спасибо.

**Comment by SBProX** [comment]
Что такое указатель инструмента?

**Comment by MAXK04** [comment]
@SBProX Наименование инструмента

**Comment by SBProX** [comment]
@MAXK04 наименование инструмента пишется в заголовке окна.
Зачем делать мешающую надпись в области графика?

**Comment by MAXK04** [comment]
@SBProX У меня 4К, честно говоря мелковаты надписи, зато график шикарен - ну и не нужно глазами водить никуда - сразу в центре видно ненавязчивую надпись, можно к названию добавить еще и ТФ (пример SBProX) 
![01](https://user-images.githubusercontent.com/51521568/59278499-e7425800-8c83-11e9-91f2-6ea8f7382194.png)

PS Если Вам не сложно, сделайте - кроме благодарности никто ничего не скажет. Гарантирую. Тем более будет функция "Вкл" "Выкл"

**Comment by SBProX** [comment]
@MAXK04 В заголовке окна на вашем скриншоте все отлично видно.
Если мы на каждую мелочь будем делать галочки вкл/выкл то платформа превратится в помойку из кучи настроек.
Поймите правильно.

**Comment by MAXK04** [comment]
@SBProX Вам решать, я только предложил

**Comment by SBProX** [comment]
Спасибо, подумаем.

**Comment by MAXK04** [comment]
@SBProX Вам спасибо огромное, ребята!
