### ISSUE TITLE
История

### ISSUE THREAD

**Issue by Milishnikoff** [SBProX/SBProX-Dev#293]
Историю так и не подкачали☹️

**Comment by Flyrine** [comment]
Если в симуляторе то она есть...дата начала истории -дата начала торговли на симуляторе -конечная дата торговли ...все в втором окошке симулятора

**Comment by Milishnikoff** [comment]
С какого года смотрите?

**Comment by SBProX** [comment]
Если вы про ФОРТС - то на этой неделе подкачаем.

**Comment by Milishnikoff** [comment]
Да, про ФОРТС. Понял, спасибо.
