### ISSUE TITLE
Создание/редактирование индикаторов

### ISSUE THREAD

**Issue by TERROR770** [SBProX/SBProX-Dev#294]
Здравствуйте, уважаемые разработчики. 
Будет ли добавлена возможность редактировать логику имеющихся индикаторов (включая натягиваемые на область профили) или создание совершенно новых?
Готов даже поковыряться с кодом низкого уровня, чтобы получить нужную мне реализацию динамического профиля :(

**Comment by SBProX** [comment]
В следующем году мы хотим открыть API платформы, тогда можно будет писать.
Пока что это невозможно.
