### ISSUE TITLE
Добавить уровни для вертикального объема и дельты

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#297]
Добавьте пожалуйста возможность установки уровней (в нижней части в поле самих индикаторов) для вертикального объема и дельты, а так же возможность установки алертов на эти уровни.
![Screenshot_3](https://user-images.githubusercontent.com/29704362/59347221-7eafb580-8d2d-11e9-90de-c74c98dc12f6.jpg)

**Comment by SBProX** [comment]
Не добавим. Не предусмотрено архитектурой графика.
Алерты есть.
