### ISSUE TITLE
Объем бидов на графике "Бид-аск профиль", таймфрейм 1 минута, при условии объем больше тысячи, плохо читается.

### ISSUE THREAD

**Issue by uzziahmogg** [SBProX/SBProX-Dev#298]
Объем бидов на графике "Бид-аск профиль", таймфрейм 1 минута, при условии объем больше тысячи, плохо читается - единицу на позиции "тысяча" плохо видно.

На скриншоте ситуации указаны стрелками - в первом случае объем 1406 а не 406, во втором - 1122, а не 122.

![rsSi 1 мин BidAskProfile Real-Time Data_ 57478 ticks 2019-06-14 11 33 14](https://user-images.githubusercontent.com/39528065/59496591-6e691900-8e9a-11e9-8d08-10781b0eb4d9.png)

**Comment by SBProX** [comment]
Исправлено
