### ISSUE TITLE
Выбор цвета: добавление часто используемых цветов

### ISSUE THREAD

**Issue by 220vlt** [SBProX/SBProX-Dev#30]
**Проблема:** в **Выбор цвета** приходится в ручную менять цвета по RGB/HEX.

**Цель:** добавить **Часто используемые** цвета. 

![image](https://user-images.githubusercontent.com/31524209/57316758-36362400-70ff-11e9-9bec-ff806dd38126.png)

**Comment by Flawmaster** [comment]
По-моему проще добавить выбор цвета как в прошлой версии.

![colors](https://user-images.githubusercontent.com/50398637/57358845-fa42a380-717e-11e9-8d00-676f4bb05df8.png)

**Comment by SBProX** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/16720120/58170780-15440600-7c9d-11e9-8fd5-0c6623e450c1.png)

Сделали возможность выбора палитры. Надеемся так будет лучше.
