### ISSUE TITLE
Фильтры для дельты

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#301]
Уважаемые разработчики! Добавьте, пожалуйста, фильтры в настройки графика кластер дельты. Имеется ввиду 3-4 фильтра по биду и также по аску, чтобы можно было свои цвета настраивать.

![дельта](https://user-images.githubusercontent.com/50398637/59550082-3f70a700-8f6f-11e9-848b-a6ace824bbe3.png)

**Comment by SBProX** [comment]
По биду и аску уже добавили, будет в обновлении.

**Comment by Flawmaster** [comment]
Я имел ввиду на графике дельты, а не бид-аск графике. Или фильтры тоже будут на графике кластер дельты?
