### ISSUE TITLE
Описка в настройках индикатора Total Volume

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#302]
В настройках цветов индикатора Total Volume написано "цвет покупокок" вместо "цвет покупок"

![2019-06-14_12-27-20](https://user-images.githubusercontent.com/50398637/59550126-e1908f00-8f6f-11e9-9647-c8e733bf9446.png)

**Comment by Bolt022** [comment]
тут я на такое уже не обращаю  внимание ))

**Comment by SBProX** [comment]
> в этой проге я на такое уже не обращаю внимание ))

Как это понимать?

**Comment by SBProX** [comment]
> В настройках цветов индикатора Total Volume написано "цвет покупокок" вместо "цвет покупок"
> 
> ![2019-06-14_12-27-20](https://user-images.githubusercontent.com/50398637/59550126-e1908f00-8f6f-11e9-9647-c8e733bf9446.png)

Спасибо, исправим.

**Comment by Bolt022** [comment]
> > в этой проге я на такое уже не обращаю внимание ))
> 
> Как это понимать?

Много таких ошибок в пунктуации находил...

**Comment by SBProX** [comment]
> > > в этой проге я на такое уже не обращаю внимание ))
> > 
> > 
> > Как это понимать?
> 
> Много таких ошибок в пунктуации находил...

Да, у нас занимался переводом человек который делал ошибки.
Надеемся такого больше не будет повторяться.

**Comment by SBProX** [comment]
Исправлено
