### ISSUE TITLE
Толщина линий на баровом графике не запоминается

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#303]
Если открыть баровый график и нанести линию, а потом отредактировать ее толщину, то при нанесении следующей линии толщина не запоминается. Это очень не удобно, когда работаешь в основном на баровом графике. Уважаемые разработчики, сделайте, пожалуйста, чтобы настройки запоминались.

![толщина_линий_не_запоминается](https://user-images.githubusercontent.com/50398637/59550294-9aa39900-8f71-11e9-9059-84b9602cf367.gif)

**Comment by SBProX** [comment]
Хорошо.

**Comment by SBProX** [comment]
Сделано. Толщина линии запоминается в пределах работы платформы.
