### ISSUE TITLE
Лента сделок... не вижу...

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#304]
Добрый день!

Зашел на сайт проги, увидел инфу и не могу найти эту ленту сделок, о которой пишут...
![2019-06-16_114954](https://user-images.githubusercontent.com/51231827/59560533-0565da80-902d-11e9-8419-b696986c82ed.png)

**Comment by vector1207** [comment]
Ленты нет.

_Оффтоп._ Что самое странное, нигде прямым текстом не указано, что в терминале отсутствует напрочь торговый функционал. Так как некоторые люди, увидев в шапке сайта информацию о наличии коннекторов (Quik и Transaq), совершенно справедливо будут предполагать, что он есть. Особенно учитывая наличие симулятора торговли.

**Comment by Bolt022** [comment]
> Ленты нет.
> 
> _Оффтоп._ Что самое странное, нигде прямым текстом не указано, что в терминале отсутствует напрочь торговый функционал. Так как некоторые люди, увидев в шапке сайта информацию о наличии коннекторов (Quik и Transaq), совершенно справедливо будут предполагать, что он есть. Особенно учитывая наличие симулятора торговли.

...коннекторы то были бы еще рабочими, а то кривые графики показывают.

**Comment by SBProX** [comment]
@Bolt022 - Cloud. 
Это и есть лента, которая отображается на графике.
Стандартной ленты в виде списка пока нет, мы ее не делали.

**Comment by SBProX** [comment]
И неплохо было бы такие вопросы задавать тех. поддержке.
