### ISSUE TITLE
Будет ли версия пограммы под Mac os?

### ISSUE THREAD

**Issue by dimaan29** [SBProX/SBProX-Dev#305]
Планируете ли вы делать версию программы под другую ОС, в частности Мак ос? Любопытно то, что нет ни одной торговой программы под всемирно известную Мак ос)))

**Comment by X-man77** [comment]
МакОС  ивсемирно известная по своему интересная, но малоиспользуемая (не знаю почему) в народе ось. Потому и делать под  неё что-либо боьшого смысла нет, имхо.

**Comment by dimaan29** [comment]
Жаль, а то был бы прорыв в мире трейдинга, тогда глядишь и Квик на Мак ось сделали бы. Просто зачастую в командировке имеется с собой макбук, и как всегда появляются торговые сценарии в этот момент, а компа на виндовс нет под рукой, вот бы спасло появление Сбпро на Мак оси для анализа, а сделку можно делать и с телефона.

**Comment by SBProX** [comment]
Нет, не будет версии под Mac.
Под Mac можете запускать платформу под виртуальной машиной.

**Comment by weeclemans** [comment]
dimaan29, добавить Windows на Macbook и загружать как вторую OS?
