### ISSUE TITLE
SBProX не грузит RTS

### ISSUE THREAD

**Issue by bushevigor** [SBProX/SBProX-Dev#309]
<img width="960" alt="SBPro" src="https://user-images.githubusercontent.com/50689618/59564527-a1eda400-9050-11e9-8727-026de63d8804.png">
<img width="960" alt="SBProX" src="https://user-images.githubusercontent.com/50689618/59564528-a1eda400-9050-11e9-990b-991e0d142b34.png">

**Comment by SBProX** [comment]
Данный подкачиваем.
Скоро будут доступны.
