### ISSUE TITLE
Сделайте удобную панель!!!!

### ISSUE THREAD

**Issue by kiev1979** [SBProX/SBProX-Dev#311]
Добрый день!
10-кой доволен. Но есть одно мощное НО! Тратится сильно много времени чтобы взять профиль и натянуть его на график. Это самый популярный инструмент! Вынесите его на панель, чтобы он всегда был открытый. Сделайте как в старой версии!!! Было очень удобно! Теперь жесть!!!! Спасибо разрабам за работу!

**Comment by kiev1979** [comment]
Очень просится!

**Comment by Flawmaster** [comment]
Есть же горячие клавиши. На "d" как раз профиль натягивается.

**Comment by kiev1979** [comment]
А потом еще надо выбрать нужный. Мега неудобно. В старой же было нормально. В мт4 тоже сверху все инструменты разные. Зачем лишнии клики? Если я по 5 профилей за минуту натягиваю.

**Comment by SBProX** [comment]
> А потом еще надо выбрать нужный. Мега неудобно. В старой же было нормально. В мт4 тоже сверху все инструменты разные. Зачем лишнии клики? Если я по 5 профилей за минуту натягиваю.

Мы стараемся поддерживать минималистичный интерфейс.
Поэтому лепить кнопки мы никуда не будем.

Вы можете пользоваться горячими клавишами, а переключить на нужный тип профиля не составляет труда, кроме того можно установить настройки по умолчанию, чтобы не переключать.
Платформа не должна сама все за вас делать.
