### ISSUE TITLE
Использовать закругление никак не влияет на кластерный график

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#313]
Уважаемые разработчики! Галочка "использовать закругление" в кластерном графике никак не влияет на график. Как я понимаю, должны убираться закругления с рамок максимальных объемов - закругленные рамки остаются в любом случае (стоит эта галочка или нет).

![закругления_на_макс_объемах](https://user-images.githubusercontent.com/50398637/59595961-7d9cd080-90ff-11e9-84f8-eb7c8a086769.gif)

**Comment by Flyrine** [comment]
![кластера](https://user-images.githubusercontent.com/51110220/59755981-92a96900-9291-11e9-9fdc-2ca00ea18580.jpg)

**Comment by Flawmaster** [comment]
Это график "кластер профиль". И да, я знаю, что эта настройка влияет на эти закругления - в FAQ об этом написано. Хотелось бы, чтобы в обычном кластерном графике убирались все закругления - даже с макс объемов.

**Comment by SBProX** [comment]
Ок, пропишем.

**Comment by Flawmaster** [comment]
Спасибо!

**Comment by SBProX** [comment]
Сделано
