### ISSUE TITLE
Разрывы котировки после выхода их режима hibernate

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#314]
Каждое утро я должен удалять C:\SBProData\tickdata и C:\SBProData\cachedata, после этого пройтись по каждой вкладке, нажать перезагрузить данные с сервера, и только после этого могу получить не рваную котировку. 
Исправьте, пожалуйста, эту ошибку, она очень мешает!

**Comment by SBProX** [comment]
Принято.

**Comment by SBProX** [comment]
Надеемся что исправили.
