### ISSUE TITLE
Плавное масштабирование ( zoom-in, zoom-out )

### ISSUE THREAD

**Issue by weeclemans** [SBProX/SBProX-Dev#319]
Просьба сделать масштабирование более плавным (прокрутка колёсиком мыши), сейчас оно скорее дёрганое.

https://www.youtube.com/watch?v=4NUknwtv8VY
смотреть с 13й минуты
смотреть с 16й минуты (плавное масштабирование в VolFix)

**Comment by Flyrine** [comment]
Давно хотел написать о этой проблеме,ну хоть кто то написал )
https://youtu.be/4NUknwtv8VY?t=486
Вот нужное время видео

**Comment by vpaks** [comment]
Для меня тоже - невозможно использовать графики дельта профиль и т.п.  Очень бы хотелось бы что бы именно эту проблему решили, что в старой так и в новой версии. Остальные фишки можно было бы отложить

**Comment by Flyrine** [comment]
При вертикальном масштабе изменения особенно резкие

**Comment by test-777** [comment]
+

**Comment by weeclemans** [comment]
продублировали тут
https://github.com/SBProX/SBProX-Dev/issues/330

**Comment by norbertas-gaulia** [comment]
+1

**Comment by weeclemans** [comment]
да, теперь стало намного лучше, но стоит ещё поработать над масштабированием по вертикали, это очень заметно на footprint-графиках
