### ISSUE TITLE
Почему не совпадают объемы в кластерах на реальном графике и в симуляторе?

### ISSUE THREAD

**Issue by Vyura** [SBProX/SBProX-Dev#32]
![Безымянный3](https://user-images.githubusercontent.com/50382776/57333513-aeafdb80-7125-11e9-99ae-2f95a10e07ed.png)
![Безымянный4](https://user-images.githubusercontent.com/50382776/57333518-b3748f80-7125-11e9-98e3-fcd3a0f5da7f.png)

**Comment by SBProX** [comment]
Исправлено.
