### ISSUE TITLE
Склейка контрактов

### ISSUE THREAD

**Issue by CTAPbIu** [SBProX/SBProX-Dev#320]
Добрый день. 
Спасибо за Ваш продукт, и за Ваш труд. 
Все супер, но есть пара моментов: 
-Склейка контрактов, это как-то лечится штатными средствами? Можно по другому? В NT8 все отлично, хочется чтобы у нас было лучше.
Спасибо.
![img-2019-06-19-03-10-21](https://user-images.githubusercontent.com/51973235/59720384-88ab4a00-9240-11e9-9a15-c4f6e3eddc5d.png)
![img-2019-06-19-03-11-56](https://user-images.githubusercontent.com/51973235/59720493-d627b700-9240-11e9-9bf4-4127b198d26e.png)

**Comment by SBProX** [comment]
Добрый день.

Мы уже миллиардный раз объясняем одно и тоже по склейке.
Ну не может быть склейки без разрыва и без искажения котировки.
В NT котировка склеивается путем подгонки, мы такого делать не будем.

**Comment by CTAPbIu** [comment]
Спасибо, ясно.

**Comment by CTAPbIu** [comment]
Кстати, если снести папки с инструментом в расположениях: C:\SBProData\cachedata и C:\SBProData\tickdata, при выключенном терминале, а потом перегрузить получится вот так
 
![image](https://user-images.githubusercontent.com/51973235/59946092-593c4d80-948b-11e9-9891-8b8d754a8151.png)
Лучше чем было.
