### ISSUE TITLE
Magnifier

### ISSUE THREAD

**Issue by CTAPbIu** [SBProX/SBProX-Dev#321]
Можно как-то подсветить уровень текущей цены в увеличителе графика?

![img-2019-06-19-03-35-43](https://user-images.githubusercontent.com/51973235/59721737-d1b0cd80-9243-11e9-9045-2d0549c6c9a8.png)

**Comment by r35p3ct** [comment]
Поддерживаю, а то не всегда понятно где увеличитель находится.

**Comment by SBProX** [comment]
Уровень цены у вас подсвечен - это серая горизонтальная линия.
Или объясните подробнее, что вы хотите чтобы подсвечивалось?

**Comment by Bolt022** [comment]
> Уровень цены у вас подсвечен - это серая горизонтальная линия.
> Или объясните подробнее, что вы хотите чтобы подсвечивалось?

он имеет ввиду, чтобы линии отображались в Магнифире, т.е. в увеличенном окне

**Comment by CTAPbIu** [comment]
> он имеет ввиду, чтобы линии отображались в Магнифире, т.е. в увеличенном окне

Точно

**Comment by zhivik007** [comment]
...ЭТО ПРОСИЛИ, и НАМ ОБЕЩАЛИ ДВА ГОДА НАЗАД!!!, осталось чуток...

**Comment by SBProX** [comment]
Вы слишком много хотите от увеличителя, это очень тяжело реализуемо технически.
Mag нужен просто чтобы посмотреть какие объемы были на графике в сжатом виде и только.
