### ISSUE TITLE
Даты графиков приходится переставлять вручную

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#322]
Не решилась проблема с автоматической перестановкой даты на графиках на текущую дату. Утром загружаю графики - они грузятся за вчерашний день. Но когда начинаются торги, то графики также остаются на вчерашнем числе. Приходится вручную переставлять даты на сегодняшнее число и перезагружать данные с сервера.

**Comment by vpaks** [comment]
Попробуйте задать количество рабочих дней, нужно поставить галочку и поставить нужное количество дней

**Comment by dimaan29** [comment]
В старой Сбпро такой ошибки не было, там каждый день график нормально работал и не отставал, а здесь нельзя сделать нормально, чтобы не отставало и было на автомате?

**Comment by SBProX** [comment]
Да, мы знаем о проблеме. В ближайших обновлениях она будет решена.

**Comment by SBProX** [comment]
Проблема наблюдается на российских инструментах или на западных?

**Comment by Bolt022** [comment]
> Проблема наблюдается на российских инструментах или на западных?

на ФОРТС точно есть проблема

**Comment by Dmitry1970** [comment]
Да, на ФОРТС российских такая проблема давно. Установка на определённое кол-во дней при настройках графика "Кол-во дней для раб. пространства" не помогает. Проблема осталась.

**Comment by CTAPbIu** [comment]
На западных тоже

**Comment by SBProX** [comment]
Ошибку надеемся что исправили.
