### ISSUE TITLE
подергивания при перетаскивании окна

### ISSUE THREAD

**Issue by weeclemans** [SBProX/SBProX-Dev#323]
При перетаскивании окна заметны подёргивания.
https://www.youtube.com/watch?v=0p8ihPqAd3g

**Comment by weeclemans** [comment]
заметил следующую особенность - если у Вас 4К монитор, но масштабирование (Scale) в настройках ОС выставлено в 200% или больше, то проблема себя не проявляет

**Comment by SBProX** [comment]
Только что проверили на Win8 и Win10, с масштабированием и без.
Все нормально. Скорее всего какая-то локальная особенность на вашей машине, и найти причину этого невозможно. Если бы было не только у вас - тогда да.
