### ISSUE TITLE
Не совпадение

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#325]
На скрине не совпадение кластеров на графике кластер профиля и индикатора Period Volume Profile. Такая картина наблюдается на всех возможных фреймах и графиках.

![Не совпадение](https://user-images.githubusercontent.com/33456972/59779297-71686d00-92d1-11e9-82b3-aaeafbfeedbd.png)

При определённом увеличении графика глаз восринимает это как не сфокусированное изображение и инстинктивно пытается сфокусировать зрение, что в данном случае невозможно. И это приводит к очень большой нагрузке на глаза и ухудшению зрения. Исправьте, плиз, как можно быстрее, пожалейте наше зрение.

**Comment by SBProX** [comment]
Добрый день.

Спасибо, исправим. Еще не дошли руки)

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
