### ISSUE TITLE
Volume Profile

### ISSUE THREAD

**Issue by 11-12** [SBProX/SBProX-Dev#329]
Добрый день! 
В SBPro v.2 при установке Volume Profile, если сделать высокую прозрачность, линии границ VA все равно были хорошо видны, прозрачность на них не влияла, на мой взгляд это было удачное решение, единственное не хватало еще, чтобы линия РОС тоже не бледнела, но это не на столько важно, а в SBProХ линии VA становятся плохо различимы, если повышать прозрачность.
Предложение: реализовать настройку таким образом. чтобы линии границ VA и линия РОС  всегда были высокой контрастности, не зависимо от настройки прозрачности.

**Comment by SBProX** [comment]
Это не правда, VA имеет свой отдельный цвет.
Как и цвет профиля - тоже отдельный. И прозрачность настраивается отдельно.
Может платформа не обновлена?

**Comment by SBProX** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/16720120/59848201-39af0300-936d-11e9-8d73-bb514611bcbd.png)

**Comment by 11-12** [comment]
Прошу извинить, наверное я не совсем корректно описал ситуацию. Прикрепляю скрины.
![Screenshot_1](https://user-images.githubusercontent.com/52030059/59853889-77665880-937a-11e9-953f-b476cc248e5c.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/52030059/59853903-7b927600-937a-11e9-9536-03058c5104b5.jpg)

**Comment by SBProX** [comment]
Вы поставили серый цвет и прозрачность на 30% - само собой результат будет таким.
