### ISSUE TITLE
Сделайте историю торгов в симуляторе

### ISSUE THREAD

**Issue by Venerzet** [SBProX/SBProX-Dev#33]
Сделайте пожалуйста историю торгов в симуляторе,что бы можно было провести анализ стратегий по результатам,итог профит/лосс и экспорт сделок.

**Comment by Venerzet** [comment]
В симуляторе невозможно пользовать динамическим профилем,так как его перекрывает таблица с информацией,можно ли как то инструменты перенести в правый верхний угол или таблицу симулятора перенести в правый верхний угол?

**Comment by Milishnikoff** [comment]
Профиль можно кнопкой D открывать, а вот история в симуляторе нужна, а то мотать устанешь.

**Comment by RoketAnny** [comment]
Тоже очень жду историю, и  смену баров по горячей клавише

**Comment by SBProX** [comment]
Сделано
