### ISSUE TITLE
Более плавное расширение графика по шкале цен и времени

### ISSUE THREAD

**Issue by test-777** [SBProX/SBProX-Dev#330]
Добрый день, хотелось бы видеть большую плавность при растягивании шкалы цен и времени. В текущем варианте при зажатой левой кнопкой мыши - сначала шкала цены растягивается не быстро а затем происходит быстрое расширение.

Хотелось бы наоборот - чем дольше растягиваешь шкалу - тем плавнее и медленнее она должна изменяться.

**Comment by SBProX** [comment]
Посмотрим что можно сделать

**Comment by test-777** [comment]
спасибо

**Comment by weeclemans** [comment]
дубль тут 
https://github.com/SBProX/SBProX-Dev/issues/319

**Comment by weeclemans** [comment]
теперь стало намного лучше, но стоит ещё поработать над масштабированием по вертикали, это очень заметно на footprint-графиках

**Comment by SBProX** [comment]
@weeclemans пишите пожалуйста более конкретно, над чем нужно поработать.

**Comment by SBProX** [comment]
масштабирование доработано.
