### ISSUE TITLE
Баг с шириной нарисованных элементов 

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#331]
После использования инструмента "текст", ширина прочих элементов рисования (например, прямоугольника) становится равной размеру текста, т.е. если размер текста был 10, то ширина последующих прямоугольников тоже будет 10. Уважаемые разработчики, поправьте, пожалуйста, данный баг.

![Баг_с_рисованием](https://user-images.githubusercontent.com/50398637/59861138-f2367000-9388-11e9-97cf-ef069899d3dd.gif)

**Comment by SBProX** [comment]
Спасибо, исправим.

**Comment by SBProX** [comment]
Исправлено
