### ISSUE TITLE
Недостаток в свечном графике

### ISSUE THREAD

**Issue by Flyrine** [SBProX/SBProX-Dev#332]
При добавлении прозрачности в свечах внутри тела видна линия
![Новый точечный рисунок](https://user-images.githubusercontent.com/51110220/59959640-c250af00-94e5-11e9-9ab5-a2b5c1f29d5b.jpg)

**Comment by bizlis** [comment]
Я тоже этот недостаток обнаружил, но решил его очень просто, одноцветный фон и заливка свечи по цвету фона
![Screenshot_2](https://user-images.githubusercontent.com/29704362/59961653-13679f80-94f4-11e9-8afa-27e1bf33ad44.jpg)

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
