### ISSUE TITLE
Отрисовка линии РОС

### ISSUE THREAD

**Issue by 11-12** [SBProX/SBProX-Dev#335]
Уважаемые разработчики, проверьте, пожалуйста настройку динамического профиля.
При установленной галочке на панели настроек, линия РОС не рисуется.
![Screenshot_10](https://user-images.githubusercontent.com/52030059/59962597-43ad3f00-94f0-11e9-8926-ce1c5e2ade57.jpg)

**Comment by X-man77** [comment]
Странно, но у меня всё отрисовывается как положено. Может какие-то общие настройки не те. 
Попробывал сымитировать и получилось если только снять галочку > применить > продолжения нет > поставить галочку без "применить" продолжение линии нет.

**Comment by 11-12** [comment]
X-man77 спасибо, линия появилась.
