### ISSUE TITLE
"0" вместо пропусков на footprint-графиках

### ISSUE THREAD

**Issue by weeclemans** [SBProX/SBProX-Dev#336]
Почему бы не помечать пустые места как "0"?

<img width="1430" alt="2019-06-22 13_33_13-Chart" src="https://user-images.githubusercontent.com/5346038/59962798-d353ed00-94f2-11e9-94e4-6a06076bfc5e.png">

**Comment by romanp55** [comment]
Здравствуйте, а как вывести такой наглядный футпринт с цифрами?

**Comment by SBProX** [comment]
Потому что нули это не наглядно. Когда пропуск - лучше видно что это пропуск
