### ISSUE TITLE
`Volume density` отключает другие настройки

### ISSUE THREAD

**Issue by norbertas-gaulia** [SBProX/SBProX-Dev#337]
после включения Volume density перестает работать эти  настройки:
-Dark font
-Labels with filters
-Max frame with filter

Top-x на симуляторе не работает.

![iNwNhwy](https://user-images.githubusercontent.com/1586492/59963345-6fcdbd80-94fa-11e9-8320-5c2819b359b8.png)

**Comment by SBProX** [comment]
Исправлено
