### ISSUE TITLE
VWAP Лента сделок и стакан

### ISSUE THREAD

**Issue by goldman7777** [SBProX/SBProX-Dev#34]
Добрый день! Для профессионального трейдинга необходимо, чтобы в VWAP были разные периоды (Дневной, Недельный, Месячный), так же для VWAP используются отклонения например -2 +2, такой функции у Вас нету.
Лента сделок - необходима лента сделок не в виде клауда, а в виде потока ордеров, чтобы можно было детально рассматривать заявки на бирже.
Стакан цен - тоже необходимая информация для отслеживания заявок Маркетмейкеров.

Данные улучшения будут незаменимы. Всё, что описал используется во всех профессиональных платформах (Volfix, Thinorswim, Transaq и т.д.) Если Вы хотите, чтобы клиенты полноценно пользовались Вашим продуктом, то эти примочки необходимы, иначе клиент будет искать чтото еще для анализа и к вашей платформе будет относиться не серьезно. Спасибо!

**Comment by alex12mosk** [comment]
поддерживаю

**Comment by vpaks** [comment]
Что касается моего мнения - это ни к чему, так как усложнить программу и будет не стабильно работать. Есть аналог Volfix, вот и работайте с ней. Лента сделок вам ничего не даст. Сидеть и до дыр высматривать крупные заявки, ну это только для садо-мазохистов

**Comment by SBProX** [comment]
Для каждой задачи необходимо создавать отдельный тикет.
По Vwap уже сделано, скоро будет обновление.

**Comment by Pasha5729** [comment]
Я тоже поддерживаю тему.

**Comment by SBProX** [comment]
https://github.com/SBProX/SBProX-Dev/issues/42

**Comment by SBProX** [comment]
Стакан, к сожалению, мы добавить не можем в ближайшем будущем.
