### ISSUE TITLE
Возможность менять порядок индикаторов

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#341]
В данный момент для этого нужно удалить, потом добавить и снова перенастроить индикаторы. 
А хочется просто их в списке индикаторов переместь и чтобы внизу они тоже изменили порядок отображения на графике.
Спасибо.

**Comment by SBProX** [comment]
Да, это будет сделано обязательно.

**Comment by bizlis** [comment]
хотелось бы еще иметь возможность временно включать/выключать индикаторы без их удаления, при чем отключать/включать каждый индикатор по отдельности, а не все скопом.

**Comment by bizlis** [comment]
Дополнение, как я это вижу для реализации: 
1. возможность временно включать/выключать индикаторы по отдельности без их удаления через окно "Индикаторы"
2. возможность временно включать/выключать сразу все индикаторы с панели или через "Инструменты"
