### ISSUE TITLE
Загрузка графика гэпами

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#344]
Обнаружилась следующая проблема. Платформа стала зависать при загрузке любого браузера, при этом зависает намертво. После закрытия браузера, программа оживает, но подгружает график гэпами. Гэп появляется в той части графика, где началось зависание.

**Comment by SBProX** [comment]
Платформа никак не связана с браузерами. 
Ищите проблему у себя на ПК в windows.
