### ISSUE TITLE
Клауды на недельных графиках.

### ISSUE THREAD

**Issue by CTAPbIu** [SBProX/SBProX-Dev#349]
Уважаемые, добрый день.
Подскажите, пожалуйста, у мня у одного клауды "стоят в сторонке" на недельном графике?
Спасибо.
![image](https://user-images.githubusercontent.com/51973235/60393236-cad36600-9b33-11e9-9ae6-99d984603246.png)

**Comment by SBProX** [comment]
Исправили, будет работать в следующем обновлении
