### ISSUE TITLE
Ошибка в индикаторе VWAP

### ISSUE THREAD

**Issue by DmitryKambarov** [SBProX/SBProX-Dev#35]
При резком скачке цены, VWAP также резко начинает идти за ценой. Помогает только постоянное нажатие кнопки применить, тогда VWAP сглаживается. Была бы возможность прикрепить бы видео ошибки, а так не понимаю как это тут сделать.

**Comment by SBProX** [comment]
Добрый день, уже есть тикет с данной ошибкой.
