### ISSUE TITLE
Вышел QUIK 8, в SBProX через коннектор перестали поступать котировки

### ISSUE THREAD

**Issue by vpaks** [SBProX/SBProX-Dev#351]
Возможно, что причиной стало: Выполнен переход на 64-разрядную архитектуру (х64). Следствием перехода является прекращение поддержки ОС Windows XP и экспорта в системы тех. анализа Omega TS и MetaStock. Кроме того, становится невозможным использование 32-разрядных DLL, подключаемых через LUA-скрипты. Пользователям требуется самостоятельно найти их аналог, реализованный в архитектуре х64. При использовании ODBC-экспорта, необходимо повторно настроить DSN-источник в Администраторе источника данных ODBC 64-разрядной версии.

**Comment by Bolt022** [comment]
кинь ссылку на QUIK 8... в финаме не вижу пока обновы

**Comment by vpaks** [comment]
ftp://ftp.quik.ru/public/updates/8.0/

**Comment by 63vova** [comment]
В обеих платформах фьючи тормознулись на 11:34 (((

**Comment by Bolt022** [comment]
> В обеих платформах фьючи тормознулись на 11:34 (((

ну да... сидим ждём чуда  )))

**Comment by Bolt022** [comment]
> ftp://ftp.quik.ru/public/updates/8.0/

благодарю

**Comment by romanp55** [comment]
и почему служба поддержки молчит?

**Comment by SBProX** [comment]
Никто не молчит.
Просто каждый считает нужным написать что котировка не работает, и пока все ответишь проходит время. Ждем решения вопроса, подводит поставщик. Иногда такое случается
