### ISSUE TITLE
Добавление акций и валюты MOEX

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#356]
Уважаемые разработчики, ПОЖАЛУЙСТА! Добавьте акции и валюту мосбиржи! Анализ фьючей без анализа спотовых инструментов бессмыслен, для тех кто торгует давно и зарабатывает, это мега важно! Все остальные пожелания можно реализовать после добавления акций и валюты. Из-за отсутствия этих инструментов, приходится пользоваться иными платформами, это очень неудобно. Подобные просьбы уже звучали здесь, что подтверждает крайнюю актуальность данного вопроса. Прислушайтесь к своим пользователям! Добавьте для начала, хотя бы акции первого эшелона и спот валюты USDRUB_TOM и EURRUB_TOM, это основное чем торгуют трейдеры на мосбирже.

**Comment by Bolt022** [comment]
> Уважаемые разработчики, ПОЖАЛУЙСТА! Добавьте акции и валюту мосбиржи! Анализ фьючей без анализа спотовых инструментов бессмыслен, для тех кто торгует давно и зарабатывает, это мега важно! Все остальные пожелания можно реализовать после добавления акций и валюты. Из-за отсутствия этих инструментов, приходится пользоваться иными платформами, это очень неудобно. Подобные просьбы уже звучали здесь, что подтверждает крайнюю актуальность данного вопроса. Прислушайтесь к своим пользователям! Добавьте для начала, хотя бы акции первого эшелона и спот валюты USDRUB_TOM и EURRUB_TOM, это основное чем торгуют трейдеры на мосбирже.

это доп.расходы... а с учетом того, что у них фиксированная, то не дождемся вовсе.

**Comment by romanp55** [comment]
у ТайгерТрейд тоже фиксированная пожизненная, но там акции есть

**Comment by romanp55** [comment]
Можно разделить на 2 пакета: фьючерсы и фьючерсы+акции и повысить цену, либо для тех, кто хочет акции, ввести небольшую помесячную оплату (очень конкурентоспособную). Я тоже хотел бы анализировать акции в СБПро, а не пользоваться дополнительно ХТиком

**Comment by vasiliyyun** [comment]
Важны не только акции, но и спотовые инструменты валютной секции. Я тоже готов за это доплатить и не использовать другие платформы. А то получается ералаш из платформ, что дополнительно нагружает систему.

**Comment by vasiliyyun** [comment]
Уважаемые разработчики, мы ждем ваши комментарии!

**Comment by romanp55** [comment]
> Уважаемые разработчики, мы ждем ваши комментарии!

мне прямо ответили, что это планируется, но не в этом году

**Comment by Sin123123** [comment]
Можно реализовать на основе конекторов. Если это накладно и можно ли вообще?!.

**Comment by SBProX** [comment]
@Sin123123 на базе коннекторов можно, НО - тогда теряется привязка к нашим серверам.
Это очень большой риск того, что если платформу взломают (такие эпизоды были), то тогда мы потеряем полностью контроль на софтом и платформа пойдет по рукам.

Чтобы подключить акции, нам необходимо помимо коннекторов, арендовать еще серверы, подключать источники данных и записывать историю по всем этим инструментам.
Пока что мы этот вопрос отложили на будущий год.

**Comment by maxcdklub** [comment]
Я тоже за добавление USDRUB_TOM, USDRUB_TOD

**Comment by gvmn** [comment]
Уважаемые разработчики! Напишите, пожалуйста, примерные (в каком месяце) сроки добавления инструмента USDRUB_TOM на Московской бирже. Мне это необходимо знать, чтобы понять, стоит ли ждать или рассматривать возможность перехода на другую платформу . Спасибо!
