### ISSUE TITLE
Добавить у элементов рисования в настройких значения, цены и времени

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#36]
Например для прямоугольника. Чтобы не тянуть его через несколько экранов добавить параметры цены и времени. Чтобы не продлять его вручную, ввести будущую дату и он бы сам автопротягивался с каждым днем.
У линий тоже было бы удобно вводить значение цены, а не на глаз. 

ПС Не вижу, где добавить категорию запроса.

**Comment by SBProX** [comment]
Поймите, платформа для анализа объемов а не для рисования.
Базовое рисование мы сделали, и этого на наш взгляд достаточно.
Это все усложняет и отнимает время.

**Comment by vik62** [comment]
Прямоугольником мы выделяем объем,который остается в прошлом.Не возможно выделять объем вытягивая его мышкой,так как не видя объем в прошлом допускаем ошибку по цене. А добавив параметры цены и времени решается эта проблема.
