### ISSUE TITLE
Глюк на линиях

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#360]
Заметил сегодня вот это:

![Наложение](https://user-images.githubusercontent.com/33456972/60675695-5f242c80-9e96-11e9-955d-96af89f831a5.png)

Получилось это так: поставил линию > настроил свойства (цвет, текст, и.т.д.)  > ОК в свойствах >  дублирую линию через меню > линия везде стоит как на исходном > через пару минут решил уточнить формулировку текста на линии > в свойствах поле "текст" добавил слово  > ОК. И по логике, после этого изменения в поле "текст" **должны добавиться на всех окнах и вкладках** где стоит **эта** линия поскольку это одна линия по сути. Но(!) в др. окнах, вкладках нет изменений, т.е. **осталась старая формулировка** .  Опять делаю дублирование и получаю то что на скрине на всех фреймах и окнах с этой линией. Там получилось **2-е линии**.  Ув. разработчики, я заметил, что у вас дублированные линии отмечаются значком  так сделайте его **признаком\триггером определяющим изменения на всех дублях данной линии** (во всех окнах, вкладках) причём **на каком бы дубле изменения не были бы внесены**

**Comment by SBProX** [comment]
Спасибо за подробное объяснение ошибки, исправим.

**Comment by SBProX** [comment]
Исправлено
