### ISSUE TITLE
Индикаторы BarsVolumeHighlight и BarsDeltaHighlight совместно не работают

### ISSUE THREAD

**Issue by Blackem007007** [SBProX/SBProX-Dev#363]
Включаешь один , другой перестает работать,

**Comment by X-man77** [comment]
Вся проблема в том как закрасить **один бар в разные цвета**. 
Предположим на баре сработали условия для закраски его и по объёму и по дельте и в какой цвет его красить? Как совместить 2-а разных цвета на одном баре? 
А вот если условия сработали на разных барах, то тогда вопрос закономерен.

**Comment by Blackem007007** [comment]
тут проще из двух один слепить, добавить индикатору BarsVolumeHighlight фильтр по дельте и все.

**Comment by SBProX** [comment]
X-man верно говорит - бар один, а цвета два.
Пока что совместить данные индикаторы никак.

**Comment by Blackem007007** [comment]
а добавить BarsDeltaHighlight фильтр по Volume нельзя? а BarsVolumeHighlight фильр по дельте и пусть преподаватель сам выбирает цвета?
