### ISSUE TITLE
4 вопроса к программистам по срокам реализации предложений в следующих тикетах:

### ISSUE THREAD

**Issue by 63vova** [SBProX/SBProX-Dev#366]
1.	Коррелятор #295 
![image](https://user-images.githubusercontent.com/24702380/60770153-a4d43580-a0e0-11e9-8798-b2f8908e1d26.png)

2. Кумулятивная дельта свечами, а не гистограммой #352
![image](https://user-images.githubusercontent.com/24702380/60770180-df3dd280-a0e0-11e9-99c6-50994e6ea0fc.png)

В продолжении    поста «КУМУЛЯТИВНАЯ ДЕЛЬТА #105»
![image](https://user-images.githubusercontent.com/24702380/60770212-4a87a480-a0e1-11e9-8a01-a1875e445870.png)

3.  Предложение по изменению индикатора открытый интерес #318
![image](https://user-images.githubusercontent.com/24702380/60770227-6d19bd80-a0e1-11e9-85b3-9135e55b1111.png)

4. Предлагаю новый профиль DV #358
![image](https://user-images.githubusercontent.com/24702380/60770247-ad793b80-a0e1-11e9-9375-aaab54e0a078.png)

И, наконец, вопрос:  когда ожидать появление  описание языка для программирования собственных индикаторов

**Comment by SBProX** [comment]
Мы не устанавливаем сроков реализации.
Мы собираем предложения, и по мере возможности из выполняем.
