### ISSUE TITLE
Увеличение размера шрифта на индикаторе вертикального объема

### ISSUE THREAD

**Issue by vector1207** [SBProX/SBProX-Dev#367]
Добрый день.

Вы не могли бы увеличить размер шрифта в индикаторе вертикального объема? Трудно разобрать цифры. В приведенном примере максимальный объем — 4 знака. Правее последней цифры есть еще много места куда можно расширить. 
В индикаторе дельты при такой же ширине столбцов влезает тоже четыре знака, но шрифт при этом гораздо крупнее.

Спасибо.

![Screenshot (1160)](https://user-images.githubusercontent.com/51026325/60772714-ebd32280-a102-11e9-84c2-9ea22381d39d.png)

**Comment by SBProX** [comment]
Это репозиторий для платформы SBProX

**Comment by vector1207** [comment]
> Это репозиторий для платформы SBProX

А куда в этом случае писать пожелание? На форум нельзя, т.к. он закрыт. Вы же сами писали, что платформа будет поддерживаться и дорабатываться.

**Comment by SBProX** [comment]
Да, но это репозиторий по SBProX.
По SBProV2 тоже будет репозиторий, немного позже.
