### ISSUE TITLE
Горячая клавиша на прямоугольник не работает

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#369]
После обновления на "R" не выбирается инструмент "прямоугольник". С остальными инструментами все хорошо - горячие клавиши работают.

**Comment by SBProX** [comment]
Ок, проверим.

**Comment by SBProX** [comment]
Исправлено, можете перезапустить платформу.

**Comment by Flawmaster** [comment]
Спасибо!
