### ISSUE TITLE
Отзыв

### ISSUE THREAD

**Issue by KonstantinCrazy** [SBProX/SBProX-Dev#37]
Добрый день. Поюзав новую обновленную платформу, ничего интересного для себя не увидел. Могу выделить три плюса. Это из календаря убрали выходные, теперь нет пробелов между выходными и клирингами. Второй, изменение интерфейса.Третий это индикатор claster serch, но у него есть недостаток, нельзя выставить минусовую дельту. Индикаторы: open interest, и cumulative delta, не информативны.  Сделайте их как в Atase или Tiger trade. Тогда можно будет рассматривать покупку обновленной платформы. 
Многие трейдеры в России сидят на платформе Atas, после того как платформа Tiger trade, скопировала платформу Atas, и сделала цену гораздо дешевле, люди начали переходить на нее. Для себя как уже написал выше, покупку рассматривать не собираюсь. Так как другие платформы более информативнее. Для новичков, ваша платформа не плохая, не более.
 Это сугубо мое субъективное мнение. Никого не хотел оскорбить!

**Comment by SBProX** [comment]
В репозитории публикуются ошибки и задачи, и его читают программисты, мнение вы можете написать нам на sales@sb-professional.com
