### ISSUE TITLE
Не работает перетаскивание элементов рисования, после обновления

### ISSUE THREAD

**Issue by Blackem007007** [SBProX/SBProX-Dev#370]

**Comment by Blackem007007** [comment]
Перестает работать после того, как торговый канал пытаешься расширить, помогает только перезагрузка

**Comment by SBProX** [comment]
Что такое торговый канал?

**Comment by X-man77** [comment]
По всей видимости имелся в виду трендовый канал. У меня с ним тоже непонятки - кидаю на график > двойной клик выделил> пытаюсь растащить линии  -  не получается, работает только верхняя линия если тянуть её за концы, середина линии не работает. 2-я линия, с выделением только посередине вообще никак не тянется. В результате, нужный инструмент невозможно поставить на нужное место.

**Comment by r35p3ct** [comment]
Да, трендовый канал не расширяется.

**Comment by Blackem007007** [comment]
После неудачной попытки расширить трендовый канал , перестает работать перетаскивание элементов рисования на графике

**Comment by SBProX** [comment]
Исправлено, можно перезапустить платформу - должна обновиться.
