### ISSUE TITLE
Как скрыть цифры шкал индикаторов?

### ISSUE THREAD

**Issue by DmitryKambarov** [SBProX/SBProX-Dev#372]
Добрый день, после последних обновлений появилась ненужная информация, которая мешает восприятию графиков цены и индикаторов, а именно цифры шкал индикаторов. Подскажите как их скрыть?
![image](https://user-images.githubusercontent.com/50403696/60788449-73517d80-a165-11e9-980c-7dddb4638141.png)
![image](https://user-images.githubusercontent.com/50403696/60788481-89f7d480-a165-11e9-9f98-2ead1476defa.png)

**Comment by SBProX** [comment]
Пока никак, добавим опцию.

**Comment by Bolt022** [comment]
> Пока никак, добавим опцию.

это называется "шкала индикаторов"?? либо уберите вообще, либо сделайте нормально...
