### ISSUE TITLE
Трендовый Канал

### ISSUE THREAD

**Issue by AlexandrBik** [SBProX/SBProX-Dev#377]
При построении трендового канала, вторая линия не перемещается. Можно ли сделать построение по трем точкам, последовательно нажимая на две нижних и одну верхнюю между ними при восходящем канале!?

**Comment by SBProX** [comment]
Как не перемещается? Все работает. Объясните понятно.
Мы не будем делать иных вариантов, SBPro не платформа для рисования и тех. анализа.

**Comment by AlexandrBik** [comment]
Все уже отлично работает, переустановил, судя по всему обновления не устанавливались.

**Comment by SBProX** [comment]
Спасибо за информацию
