### ISSUE TITLE
Урони фибо после обновления от 08.07.2019

### ISSUE THREAD

**Issue by kanckiy** [SBProX/SBProX-Dev#381]
Отрицательные значения уровней фибо,после обновления, стали натягиваться только в одну сторону. Можно сделать так как они работали до обновления...
![2019-07-08_23-55-54](https://user-images.githubusercontent.com/52637534/60842145-1e9d1980-a1dc-11e9-813d-03ddd20bca39.png)

**Comment by u1ysses** [comment]
+ после обновления линия "100%" всегда сверху, как ни крути, сделайте пожалуйста как было.

**Comment by SBProX** [comment]
Этот баг исправим.
Этот тикет закроем, так как есть аналогичный, чтобы не дублировалось.
