### ISSUE TITLE
Канал

### ISSUE THREAD

**Issue by AlexandrBik** [SBProX/SBProX-Dev#382]
Можно ли сделать большим, расстояние между линиями при построении канала. При отдалении от графики на больших таймфреймах они стоят слишком близко, чтоб перетащить одну из них. Понимаю что платформа не для рисования. Но данный инструмент базовый и всегда должен быть под рукой. Возможно удастся изменить механизм построения канала. Вам профессионалам виднее как это реализовать.

**Comment by r35p3ct** [comment]
По поводу канала хотелось бы в будущем реализации построением по 3м точкам и возможностью продолжения в бесконечность.

**Comment by SBProX** [comment]
Расстояние да - подправим.

**Comment by SBProX** [comment]
И не дублируйте тикеты **пожалуйста**, уже есть такой: https://github.com/SBProX/SBProX-Dev/issues/379
