### ISSUE TITLE
Зумирование

### ISSUE THREAD

**Issue by ws-keith** [SBProX/SBProX-Dev#385]
при зумировании графика до видимости объемов в виде цифр, вместимость в 2 раза меньше кластеров на графике чем на V2 http://prntscr.com/ocj2tj

**Comment by SBProX** [comment]
Шрифт сделали как можно меньше, уже давно был такой тикет и всех все устроило.
Куда еще мельче: http://prntscr.com/ocl1gq ?

**Comment by ws-keith** [comment]
согласен, просто на брент в кластере до 1000 к и ранее не торговал данный инструмент, спасибо

>Вторник,  9 июля 2019, 14:50 +03:00 от SBPro X <notifications@github.com>:
>
>Шрифт сделали как можно меньше, уже давно был такой тикет и всех все устроило.
>Куда еще мельче:  http://prntscr.com/ocl1gq ?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
WS

**Comment by SBProX** [comment]
Не за что.
