### ISSUE TITLE
ОИ в бэкграунд и крестик

### ISSUE THREAD

**Issue by mscrigna** [SBProX/SBProX-Dev#386]
Можно сделать чтобы при отображении индикатора открытого интереса появлялась еще горизонтальная линия? (образовывался крест)

**Comment by mscrigna** [comment]
https://www.screencast.com/t/e8Cw0Zyvz

**Comment by SBProX** [comment]
Не понятно о чем идет речь

**Comment by mscrigna** [comment]
Когда индикатор (в этом случае ОИ) позади, не отображается горизонтальная линия (не получается крест) а только вертикальная

**Comment by SBProX** [comment]
Не понятно для чего вам нужна эта горизонтальная линия, она не дает никакой смысловой нагрузки.
