### ISSUE TITLE
Перемещение и масштабирование графика с клавиатуры

### ISSUE THREAD

**Issue by vector1207** [SBProX/SBProX-Dev#387]
Добрый день.

Хотелось бы иметь возможность перемещать и масштабировать график с использованием клавиатуры. В некоторых ситуациях это может быть гораздо более удобным, чем использовать мышь (например для побарного анализа). Настраивая масштаб с клавиатуры можно добиться максимально точного и комфортного соотношения сторон, чтобы больше его не менять колесиком мыши.

В качестве примера могу предложить как это реализовано в VolFix:

Стрелка влево/вправо —  сдвиг графика влево/вправо на один бар
Shift + стрелка влево/вправо — сдвиг влево/вправо на 10 баров

Стрелка вверх/вниз — сдвиг графика вверх/вниз на один кластер
Shift + Стрелка вверх/вниз — сдвиг вверх/вниз на 10 кластеров

Ctrl + стрелка вверх/вниз — увеличение/уменьшение вертикального масштаба графика на один шаг масштаба
Ctrl + стрелка влево/вправо — уменьшение/увеличение горизонтального масштаба графика на один шаг масштаба

На видео записал как это выглядит — https://youtu.be/mGDb_fAwA0w

Спасибо.

**Comment by weeclemans** [comment]
+ на видео нет жестких подергиваний графика при масштабировании

**Comment by vector1207** [comment]
> * на видео нет жестких подергиваний графика при масштабировании

не совсем понял, что вы имеете ввиду. Более "плавное" масштабирование в волфиксе происходит оттого, что там больше шагов масштаба (и более мелкий шаг по вертикали и горизонтали). Но вроде как разработчики SBPro говорили, что это будут допиливать. Но удобства масштабирования такой как скажем в Tradingview, в волфиксе все равно нет.

В идеале конечно, еще не хватает функции блокировки пропорций масштаба (такое есть в Tradingview и SierraChart). То есть один раз настроил себе удобные пропорции по ширине и высоте, а дальше масштабируешь, не опасаясь что случайно собьешь пропорции. Но это уже оффтоп для этой темы.

**Comment by SBProX** [comment]
Пока мы против делать масштабирование с кнопками.
