### ISSUE TITLE
Горизонтальная линия не работает прозрачность

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#389]
На сколько я понимаю этот инструмент задумывался как для отображения линий, так и областей в том числе, у данного инструмента не работает прозрачность, совсем, а хотелось бы чтобы прозрачность регулировалась.
![Screenshot_1](https://user-images.githubusercontent.com/29704362/60911837-86ffff80-a29d-11e9-9a0c-ea2d46db4957.jpg)

**Comment by SBProX** [comment]
Принято, исправим.

**Comment by Ivarti** [comment]
Толщина линий тоже не доделана. Меняешь значения и ничего не меняется.

**Comment by SBProX** [comment]
Толщина не меняется на кластерных графиках.

**Comment by SBProX** [comment]
Сделано, сегодня выйдет обновление.
