### ISSUE TITLE
Fibo уровни

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#39]
Добавили уровни 5,6,7,8 - пытался в них ввести положительные значения. Уровни на графике не отображаются. Видны на графике только уровни с 1 по 4.
![2019-05-08_15-40-45](https://user-images.githubusercontent.com/35344271/57376681-515d6e00-71a9-11e9-9983-57097c67a085.jpg)

**Comment by SBProX** [comment]
Вы не правильно настраиваете, нижние 4 поля - это для отрицительных значения фибо.

**Comment by Dmitry1970** [comment]
Можете добавить возможность добавления дополнительных положительных уровней Фибо?

**Comment by Dmitry1970** [comment]
Можно сделать аналогично tradingview.com. У них есть важные кнопки- получается не добавить положительные значения а иметь возможность перевернуть
![2019-05-10_8-23-51](https://user-images.githubusercontent.com/35344271/57504632-e3768b00-72fd-11e9-821f-5310dc756941.jpg)
![Clip2net_190510152653](https://user-images.githubusercontent.com/35344271/57504634-e6717b80-72fd-11e9-9a9d-6e750f9a003d.png)

, Рассмотрите, пожалуйста, такую возможность.

**Comment by SBProX** [comment]
Цвета добавили - больше пока не будем ничего делать по Fibo.
