### ISSUE TITLE
Уведомления UAC при запуске программы

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#393]
Контроль учетных записей Windows ругается на SBpro при каждом запуске. Это происходит потому, что система не видит данных об издателе приложения. Можете это поправить? 
Из всех установленных приложений на моем компе, только у СБпро вот такая вот приставка к ярлыку 
![image](https://user-images.githubusercontent.com/50597350/61030271-b6119080-a3c5-11e9-97ae-b1b43487b593.png)
А если отключить уведомления UAC то я не буду получать уведомления при запуске не только от сбпро, но и от других приложений, что не есть гуд.
Подскажите пожалуйста, как мне быть? Просто реально раздражает это всплывающее окно при каждом запуске

**Comment by SBProX** [comment]
Нет, дело не в данных об издателе.
Приложение принудительно запускается от имени администратора, поэтому вы всегда видите окно UAC. Изменить это мы не можем, так как права администратора нужны.

**Comment by vasiliyyun** [comment]
А вы можете подсказать как это исправить?

**Comment by SBProX** [comment]
Что именно? Мы специально сделали так. Чтобы программа запускалась от имени администратора.

**Comment by vasiliyyun** [comment]
Ну Вы говорите, что изменить этого не можете, так как нужны права администратора. А что именно можно изменить, может это смогу сделать я по Вашей инструкции?
