### ISSUE TITLE
Горячие клавиши на "линейку" 

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#394]
Уважаемые разработчики! Предлагаю ввести дополнительно комбинацию горячих клавиш для инструмента "линейка", т.к. когда измеряешь множество движений, то не совсем удобно это делать на колесико мыши. Например, Ctrl+F, как в Metatrader, и "линейка" становится активна (меняется курсор на перекрестие, как при рисовании) до тех пор пока не произойдет клик мышкой. Т.е. нажимаем Ctrl+F, курсор меняется, затем кликаем мышкой и меряем движение; как только левая клавиша мыши отпускается - курсор меняется на обычный, работа с "линейкой" закончена.
Либо другой вариант по вашему усмотрению, но с возможностью активировать "линейку" с клавиатуры.

**Comment by vasiliyyun** [comment]
Так есть же уже горячая клавиша "J"

**Comment by vasiliyyun** [comment]
![image](https://user-images.githubusercontent.com/50597350/61082154-8d26e500-a431-11e9-9bdd-be6edb18a90a.png)

![image](https://user-images.githubusercontent.com/50597350/61082120-8009f600-a431-11e9-927e-4607abb374ad.png)

**Comment by Flawmaster** [comment]
Спасибо, был не в курсе.
