### ISSUE TITLE
Примагничивание линий

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#395]
Уважаемые разработчики, добавьте пожалуйста возможность примагничивания линий к минимумам/максимумам свечей (баров). Было бы здорово если такая функция появилась у всех линий, не только тех, что вызываются кликом на полях, но и линий из раздела "инструменты". Порой очень важно отметить на графике лоу или хай, приходится немного изловчиться, чтобы сделать это в текущих условиях, а при примагничивании это бы существенно упростило работу с графиками.

**Comment by vasiliyyun** [comment]
И еще одна просьба, сделайте возможным самостоятельно комбинировать горячие клавиши.

**Comment by X-man77** [comment]
> И еще одна просьба, сделайте возможным самостоятельно комбинировать горячие клавиши.

Если вы имеете ввиду изменение горячих клавиш, то такая возможность есть.

**Comment by SBProX** [comment]
Мы не будем делать примагничивание линий к high low.
Извините, выставляйте руками.

**Comment by vasiliyyun** [comment]
Но ведь это очень удобно! Навел линию в область хая, а она сама к нему примагнитилась.
