### ISSUE TITLE
Танцы с бубном или как правильно обновлять программу

### ISSUE THREAD

**Issue by Ivarti** [SBProX/SBProX-Dev#396]
Последние три обновы, сообщения о возможности их установки висят но не обновляются. Теперь каждый раз нужно программу переустанавливать для обновления версии?
Еще после последней переустановки слетели графики. Было 6 в рабочем пространстве, стало 2

**Comment by weeclemans** [comment]
не наблюдал таких проблем, а в последним обновлением формат файлов шаблона изменился

**Comment by SBProX** [comment]
Просто перезапускайте платформу - она сама обновится.
Что касательно рабочих пространств, то мы сделали систему резервных копий.
Об этом написано в последнем обновлении.
