### ISSUE TITLE
Показывать время выделенного промежутка для профиля

### ISSUE THREAD

**Issue by weeclemans** [SBProX/SBProX-Dev#397]
было бы неплохо показывать количество времени выделенного промежутка для профиля
объём же показан, а вот за какое он время ...

**Comment by SBProX** [comment]
Когда вы натягиваете профиль (если имеется в виду это), то очевидно вы и так видите, за какое время измеряется объем.
Точные показатели времени натягивающегося профиля имеют какое-то практическое значение?
