### ISSUE TITLE
Классический временной профиль

### ISSUE THREAD

**Issue by Kovunec** [SBProX/SBProX-Dev#398]
Когда будет внедряться классический профиль? Это был бы для платформы огромнейший шаг вперед и много новых клиентов

**Comment by Kovunec** [comment]
Если нужно собрать определенное количество заявок или подписей в пользу того, чтобы внедрили классический профиль – могу организовать. Человек 50-100 будет достаточно?

**Comment by control63** [comment]
Давайте организуем! Я за.

**Comment by SBProX** [comment]
Если вы про market profile - то на него требуется лицензия CME.

**Comment by control63** [comment]
Ну можно же не буквами обозначать, а цветом или другими вариантами, которые не попадают под лицензию. Я не думаю, что они запотентовали гистограмму цены по распределению по блокам времени

**Comment by weeclemans** [comment]
TPO запатентован?

**Comment by tarassar** [comment]
Очень хорошая идея, поддерживаю!
