### ISSUE TITLE
НЕУЖЕЛИ ТАК СЛОЖНО!!!

### ISSUE THREAD

**Issue by makhitrov** [SBProX/SBProX-Dev#40]
Да сделайте вы уже наконец в старой и в новой версии, чтобы можно было рисовать за пределами графика, сколько уже можно надеяться и ждать

**Comment by SBProX** [comment]
Все тикеты с негативным содержанием будут закрываться, имейте уважение к разработчикам.

Кроме того такой тикет уже есть, зачем дублировать одно и тоже?

**Comment by makhitrov** [comment]
Извините, вы правы08.05.2019, 17:30, "SBPro X" <notifications@github.com>:Все тикеты с негативным содержанием будут закрываться, имейте уважение к разработчикам.
Кроме того такой тикет уже есть, зачем дублировать одно и тоже?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
-- С уважением, хитров максим79525355719
