### ISSUE TITLE
Линии при разных типах графиков.

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#402]
Уважаемые разработчики, убедительная к Вам просьба. Сделайте так, чтобы линии не масштабировались при масштабировании графика, а также при переключении графика с обычного на кластерный. А то получается вот так вот. 
![image](https://user-images.githubusercontent.com/50597350/61297688-624be080-a7e5-11e9-8deb-14c816b5a7dc.png)

**Comment by vasiliyyun** [comment]
Да, и еще такой момент. при отключении закругления, рамка с макс объемом в кластере, все равно закругляется.
![image](https://user-images.githubusercontent.com/50597350/61298553-19952700-a7e7-11e9-85ea-bb42bb471a5a.png)

**Comment by SBProX** [comment]
По рамке исправили.
По линиям - линии при кластерам имеют свою толщину, так задумано.
Пока что мы это менять не можем.
