### ISSUE TITLE
не обновляются графики после выхода из спящего режима, разрывы по времени

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#403]
Не обновляются графики после выхода из спящего режима, появились разрывы по времени в графиках, когда ноутбук был закрыт. 
![2019-07-16_8-39-06](https://user-images.githubusercontent.com/35344271/61350840-8e14a800-a871-11e9-9ea3-1f8d410454f8.jpg)

**Comment by SBProX** [comment]
Перезагрузка графика не помогает?

**Comment by SBProX** [comment]
Мы прописали чтобы после спящего режима графики перезагружались автоматически.
Вероятно еще нужно тестировать.

**Comment by r0b4ik** [comment]
Скорее всего имеется в виду выход из режима hibernate, в этом случае графики не обновляются.
Проблема уже описана https://github.com/SBProX/SBProX-Dev/issues/314 
При этом последнее обновдение её не исправило

**Comment by Dmitry1970** [comment]
Да, все правильно написал r0b4ik.

**Comment by SBProX** [comment]
Мы рады исправить ошибку, но не можем ее вопроизвести.
Вы можете описать порядок действий, которые привели к ошибке?
Важно знать когда вводили в спящий режим и выводили.

**Comment by SBProX** [comment]
Ошибку нашли, исправили и проверили, надеемся что все будет ок - ожидайте обновления.

**Comment by r0b4ik** [comment]
Теперь всё работает, спасибо!

**Comment by SBProX** [comment]
Супер!
