### ISSUE TITLE
график не разворачивается на экран

### ISSUE THREAD

**Issue by alexgherco** [SBProX/SBProX-Dev#404]
Доброго времени!
График в полноэкранном режиме не разворачивается на весь экран (дисплей 1920х1080_landscape). По сторонам остаются не заполненные области.
![image](https://user-images.githubusercontent.com/2143904/61403730-9e16a100-a8de-11e9-8eb7-85be5bfb48d9.png)
может это штатное функционирование?
------------------------------------------------

**Comment by SBProX** [comment]
Такого быть не должно, у нас все разворачивается.
Нажмите на иконку вверху - она у вас на скриншоте в неактивном состоянии максимизации.
