### ISSUE TITLE
Мидикатор боленджер

### ISSUE THREAD

**Issue by SunMrAngel** [SBProX/SBProX-Dev#406]
Можно ли сделать на платформу боленджер которы можно было бы настраивать. Экспаненто Симпл. Взвешаный, добавлять уровни.

**Comment by SBProX** [comment]
Нет, мы не будем добавлять больше индикаторы ТА

**Comment by SunMrAngel** [comment]
Очень жаль только по боленджеру можно торговать и не плохо.

Отправлено с iPhone
