### ISSUE TITLE
Закругления в динамическом профиле

### ISSUE THREAD

**Issue by AlexandrBik** [SBProX/SBProX-Dev#410]
Было бы не плохо убрать закругления не только индикаторов, но и в самом динамическом профиле. А также по раннее заданным параметрам установив галочку сделать его прозрачным.

**Comment by SBProX** [comment]
Прозрачность регулируется в настройках цвета профиля (для объема).
У дельты или bid-ask своей прозрачности нет, так как она высчитывается в зависимости от фильтра.

Закругления = ok.

**Comment by SBProX** [comment]
С закруглениями исправлено, будет работать в сл. обновлении
