### ISSUE TITLE
Текущая дата

### ISSUE THREAD

**Issue by SBProX** [SBProX/SBProX-Dev#412]
Напишите пожалуйста в комментариях, нормально ли у вас переключается дата на текущий день после спящего режима, или после загрузки workspace.

Спасибо.

**Comment by r35p3ct** [comment]
Поставил на разных графиках разную будущую дату, где след. неделю, где след. месяц. 
Перезагрузил и везде отображается текущая 20.07

**Comment by SBProX** [comment]
Да, конечная дата везде будет текущим днем.
Это так специально сделано.

**Comment by Fen8fen** [comment]
Здравствуйте.
Появилась ошибка при дублировании даты через стрелки (см. скрин)
![1sbdateerror](https://user-images.githubusercontent.com/20509322/61697666-55da0180-ad6a-11e9-8767-611e7eaeeb0d.jpg)
Если я хочу поставить одну дату за 18 число 
- нажимаю стрелку копировать в соседнюю ячейку
 дата копируется в соседнюю ячейку 18 число - 18 число

(Раньше грузился один день. )

- При нажатии Apply
- Загружаются все даты включая настоящую дату 23 число
- итого загружаются все дни  с 18 числа по 23 число.

**Comment by SBProX** [comment]
@Fen8fen Исправили, спасибо.

**Comment by Fen8fen** [comment]
Здравствуйте.
В SB_X нет данных (фортс) за 24 число.
в SB_Pro данные за 24 число есть.
Идут тех. работы?
