### ISSUE TITLE
Вопрос по котировкам (не совпадают биды и аски)

### ISSUE THREAD

**Issue by vector1207** [SBProX/SBProX-Dev#413]
Добрый день.

У меня есть терминал SBPro и MultiCharts от брокера AMP. В мультичартсе подключены котировки CQG. Сегодня я сравнивал кластерные графики фьючерса NQ и заметил, что данные не совпадают. Суммарные объемы в кластерах в 99% случаев совпадают, но есть места, где они отличаются (см. скрин).

![Screenshot (1183)](https://user-images.githubusercontent.com/51026325/61583316-2eebb780-ab3f-11e9-97d1-cc366adfcbbc.png)

Но помимо этого **очень** сильно различаются данные по бид-аск (скрин ниже). Они различаются не в некоторых местах, а практически везде.

![Screenshot (1184)](https://user-images.githubusercontent.com/51026325/61583335-825e0580-ab3f-11e9-897e-02404e1aeb59.png)

В связи с этим два вопроса:
1. как такое может быть?
2. по какому принципу СБпро делит сделки на бид-аск?

В мультичартс есть два варианта:
- Ask vs Bid Traded Delta
- Up vs Down Tick Delta.

Но ни тот, ни другой вариант не имеют ничего общего с тем, что я вижу в СБпро.
Хотелось бы разобраться с этим вопросом. Спасибо.

P.S. Друзья, если у вас есть на руках другие терминалы, в которых есть биржевые котировки, сравните пожалуйста с вашими данными. Конкретно на этих скринах график сентябрьского фьючерса E-mini NASDAQ 19 июля 2019 года 8:25-8:30 (время по бирже).

**Comment by SBProX** [comment]
@vector1207 

Как раз Вам и нужно предоставить доказательства некорректности данных, если Вы так считаете.
И для этого нужно сравнить данных хотя бы с двумя сторонними платформами.

Ниже скришот с volfix.

![volfix1](https://user-images.githubusercontent.com/16720120/61593372-5ac27800-abe7-11e9-890a-db76d2909521.png)

**Comment by SBProX** [comment]
Судя по всему, в мультичартсе 5 контрактов попали в новый бар из соседнего бара.
Посмотрите внимательно - в SBPro и volfix - 160 контрактов на той же цене в предыдущем баре, а в мультичартс - 155.

**Comment by vector1207** [comment]
> Судя по всему, в мультичартсе 5 контрактов попали в новый бар из соседнего бара.
> Посмотрите внимательно - в SBPro и volfix - 160 контрактов на той же цене в предыдущем баре, а в мультичартс - 155.

Благодарю за ответ. На счет этих пяти контрактов я понял.

Не нужно принимать мои вопросы в штыки, я не прошу вас предоставить доказательства "правильности" ваших котировок, и не обвиняю, что ваши данные неверные. Абзац в конце после "P.S." был вообще адресован не разработчикам, а пользователям платформы (уверен, что кто-то из них параллельно пользуется и другими терминалами).

У меня нет никакого другого терминала на руках, чтобы сравнить с чем-то еще. Раньше я ориентировался только на данные из вашей программы, поэтому этот вопрос и не возникал. Но раз заметил расхождения, то хочется понять причину. Если проблема на стороне CQG, то буду писать брокеру.

Насколько я понимаю, то на вашем скрине в волфиксе в настройках стоит Delta side by Aggressor, т.е. по идее это тоже самое что и "Ask vs Bid Traded Delta" в мультичартс. Можете ли вы сравнить график бид-аск СБпро и Волфикс?

Спасибо.

**Comment by SBProX** [comment]
> > Судя по всему, в мультичартсе 5 контрактов попали в новый бар из соседнего бара.
> > Посмотрите внимательно - в SBPro и volfix - 160 контрактов на той же цене в предыдущем баре, а в мультичартс - 155.
> 
> Благодарю за ответ. На счет этих пяти контрактов я понял.
> 
> Не нужно принимать мои вопросы в штыки, я не прошу вас предоставить доказательства "правильности" ваших котировок, и не обвиняю, что ваши данные неверные. Абзац в конце после "P.S." был вообще адресован не разработчикам, а пользователям платформы (уверен, что кто-то из них параллельно пользуется и другими терминалами).
> 
> У меня нет никакого другого терминала на руках, чтобы сравнить с чем-то еще. Раньше я ориентировался только на данные из вашей программы, поэтому этот вопрос и не возникал. Но раз заметил расхождения, то хочется понять причину. Если проблема на стороне CQG, то буду писать брокеру.
> 
> Насколько я понимаю, то на вашем скрине в волфиксе в настройках стоит Delta side by Aggressor, т.е. по идее это тоже самое что и "Ask vs Bid Traded Delta" в мультичартс. Можете ли вы сравнить график бид-аск СБпро и Волфикс?
> 
> Спасибо.

CQG дает корректные данные, им писать нет смысла.
Напишите в мультичартс, и покажите им скриншот с волфикса и с платформы мультичартс.
SBPro у них не будет аргументом, так как на западе нас пока никто не знает.

**Comment by SBProX** [comment]
Проблема не на стороне CQG, - просто вероятно некорректные расчеты в мультичартс.
