### ISSUE TITLE
Рисование прямоугольника.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#414]
Здравствуйте.
Заметил что при рисовании прямоугольника он стал отображаться на одну клетку больше.
Из за этого приходится его поправлять (т.е. уменьшить)

![1указатель](https://user-images.githubusercontent.com/20509322/61708733-13bbba80-ad80-11e9-9dd7-13e92a842f4a.jpg)

На скриншоте указатель - если его отпустить (указатель) то прямоугольник расширится до размеров желтой зоны. 
А должен зафиксироваться в синей зоне.

Видно что при смещении указателя (указатель находится на одну клетку дальше от прямоугольника) рисование сверху - вниз.

Если рисовать прямоугольник снизу вверх то прямоугольник нарисуется нужных размеров и его не нужно поправлять

**Comment by Flawmaster** [comment]
Данная проблема не встречается только на баровом и свечном графиках. На всех остальных графиках прямоугольники приходится перечерчивать постоянно, т.к. рисую от настоящего в прошлое. Как раз хотел сюда написать об этом.

**Comment by r35p3ct** [comment]
А вот если бы сделали у прямоугольника координаты по времени и цене, как я просил, то подобные проблемы стали не актуальны и можно было выделять зоны и они сами бы продлялись при установке будущей даты.

**Comment by SBProX** [comment]
Проверим, спасибо

**Comment by CuJlaMblcJlu** [comment]
И ещё тело прямоугольника перестало окрашиваться , осталась только рамка по периметру
![25 07](https://user-images.githubusercontent.com/53310098/61889964-c1f16c80-af06-11e9-8d59-c9eddd270e0c.png)

**Comment by SBProX** [comment]
@CuJlaMblcJlu У вас скорее всего прозрачность стоит в настройках цвета.
Проверьте.

**Comment by CuJlaMblcJlu** [comment]
Да действительно , спасибо за оперативность .
Не знаю где, спрошу здесь - Индикатор вертикального объёма можно ли в отдельном окне указать ?

**Comment by SBProX** [comment]
@CuJlaMblcJlu вы можете включить настройку 
![Screenshot_1](https://user-images.githubusercontent.com/16720120/61900814-0e4ca480-af27-11e9-9929-419ad8d36c66.png)

**Comment by CuJlaMblcJlu** [comment]
Включил но почему то линии и прямоугольники из прошлого т.е. с левой стороны графика идут поверх окон с индикаторами , это очень мешает . Может есть какое то решение этой проблемы ?
![26 07](https://user-images.githubusercontent.com/53310098/61940973-cf563780-af96-11e9-8d2b-9aa07be6df8f.png)

**Comment by Bolt022** [comment]
> Здравствуйте.
> Заметил что при рисовании прямоугольника он стал отображаться на одну клетку больше.
> Из за этого приходится его поправлять (т.е. уменьшить)
> 
> ![1указатель](https://user-images.githubusercontent.com/20509322/61708733-13bbba80-ad80-11e9-9dd7-13e92a842f4a.jpg)
> 
> На скриншоте указатель - если его отпустить (указатель) то прямоугольник расширится до размеров желтой зоны.
> А должен зафиксироваться в синей зоне.
> 
> Видно что при смещении указателя (указатель находится на одну клетку дальше от прямоугольника) рисование сверху - вниз.
> 
> Если рисовать прямоугольник снизу вверх то прямоугольник нарисуется нужных размеров и его не нужно поправлять

тоже сегодня заметил проблему

**Comment by SBProX** [comment]
С высотой прямоугольника исправили, сегодня будет обновление поздно ночью.
