### ISSUE TITLE
масштабирование

### ISSUE THREAD

**Issue by vitekkz** [SBProX/SBProX-Dev#415]
Добрый вечер.а можно сделать так как в старой версии,когда на водишь на график то колесиком график сразу начинает масштабироваться,а не так что надо каждый раз щелкать мышкой чтобы он опять начало колесо работать.очень не удобно.в старой версии поработал по шкале вертикали горизонтали навел на график и крутишь сразу колесо,тут надо обязательно обратно щелкать мышь каждый раз чтобы активировалось колесо мыши

**Comment by SBProX** [comment]
Это защита от случайных действий.
