### ISSUE TITLE
дневной график динамического профиля

### ISSUE THREAD

**Issue by OulmesCode** [SBProX/SBProX-Dev#417]
![2019-07-23_20-06-00](https://user-images.githubusercontent.com/14151241/61755497-c9d5d300-ad85-11e9-8b22-d0fa01d1e787.gif)

пожалуйста, исправьте. задачи рисование и перемещение динамического профиля на дневном графике

**Comment by SBProX** [comment]
Принято, проверим.

**Comment by OulmesCode** [comment]
такая же проблема возникла в 12h, 8h и 6h

**Comment by SBProX** [comment]
В понедельник исправим и выложим обновление.

**Comment by SBProX** [comment]
Исправлено
