### ISSUE TITLE
нет регулировки прозрачности

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#419]
![bandicam 2019-07-24 12-59-18-417](https://user-images.githubusercontent.com/50406792/61784797-08659f00-ae13-11e9-850b-0979772d217f.jpg)

**Comment by r35p3ct** [comment]
Прозрачность в самих цветах регулируется

**Comment by WillBegin1** [comment]
почему тогда в месячном профиле есть отдельно регулировка прозрачности? С цветами я знаю, что можно регулировать, спасибо за совет, но хотелось бы увидеть регулировку прозрачности всего профиля.

**Comment by SBProX** [comment]
В месячном профиле параметр прозрачности по ошибке, уберем.
Прозрачность практически везде настраивается в настройках цвета.
Это более гибко, так как вы можете задать прозрачность любому цвету.
