### ISSUE TITLE
Привязка перекрестия

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#425]
Обратил внимание на такую вещь. Данная функция работает корректно не на всех графиках. Например, на графике CL в принципе при любом масштабе (кроме сильно сжатого) функция работает хорошо, но на графике сбера или сишки, функция работает некорректно. Перекрестие привязывается к свечам при передвижении курсора по горизонтали, но нет привязки при передвижении по вертикали (хотя как написал, на CL работает и так, и так). Раз уж Вы отказались делать примагничивание линий, то хоть это спасало бы ситуацию, но работает не на всех графиках.

**Comment by SBProX** [comment]
Вышлите скриншот графика, чтобы понимать.
Если будет сильное сжатие, графика, или же большой интервал - то плотность цен очень высокая, и поэтому эффекта привязки вы не замечаете. Мы с этим ничего сделать не можем.
