### ISSUE TITLE
Оповещение: Программа уже запущена.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#427]
Здравствуйте.

Предложение - добавить оповещение о том что программа уже запущена. 

При нажатии кнопки (Close SBPro) в разных окнах - будет предложено сохранить разные workspace

Close SBPro
Do you want to close SBPro **(в одном окне **если workspace empty**)**
Do you want to save changes in workspace "name_Х" ? **(в другом окне)**

Если программа подвиснет с одним workplace и попытаться запустить вторую версию платформы без закрытия первой. Начнут работать две платформы (та что зависла и новая активная) Workspace могут перезаписать друг друга.....

и тут хочу уточнить возможно нужно хранить workspace двух последних запусков...... 
(reserve copies 1 version)
(reserve copies 2 version)

**Comment by SBProX** [comment]
Добрый день.
Добавим, спасибо.

**Comment by SBProX** [comment]
Сделано, будет работать в следующем обновлении.
