### ISSUE TITLE
ошибка в загрузке данных

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#428]
Здравствуйте, почему-то нет вчерашнего дня?
![bandicam 2019-07-26 08-03-14-335](https://user-images.githubusercontent.com/50406792/61927090-fce1b780-af7b-11e9-95e9-288274d6d86a.jpg)
![bandicam 2019-07-26 08-05-11-690](https://user-images.githubusercontent.com/50406792/61927106-1aaf1c80-af7c-11e9-95a8-298faabe1599.jpg)

**Comment by SBProX** [comment]
Добрый день.

Сообщите пожалуйста ваш логин в платформе, название workspace и когда именно вы запускали платформу по времени мск.

**Comment by SBProX** [comment]
Попробуйте выставить корректные даты, загрузить графики - сохранить workspace - и попробовать на следующий день загрузиться в это же время.

**Comment by SBProX** [comment]
Сегодня вечером выйдет обновление, надеемся что исправили ошибку.

**Comment by Bolt022** [comment]
с утра не прогружается вчерашний день (по данным на 9:27 Ект)... такое же наблюдал вчера... но потом появляется, после 11:00 точно (программу перезапускал)

**Comment by Bolt022** [comment]
> Сегодня вечером выйдет обновление, надеемся что исправили ошибку.

тоже заметил такое... на 9:27 (Ект)  утра не прогрузилась пятница, такое и вчера было с четвергом... но после появляется предыдущий день (после 11:00 точно, в это время перезапускал программу вчера).

**Comment by SBProX** [comment]
Исправлено, сегодня выйдет обновление.
