### ISSUE TITLE
ошибка отображения текста при линковке

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#429]
Не видно часть текста

![bandicam 2019-07-26 08-14-59-939](https://user-images.githubusercontent.com/50406792/61927505-9cec1080-af7d-11e9-8388-ad00dd3f7838.jpg)

**Comment by Fen8fen** [comment]
- У меня предложение при дублировании линий изменить "X" значок на знак "L"
(без добавления дополнительного значка.)

**Comment by SBProX** [comment]
Исправлено, сегодня выйдет обновление.
