### ISSUE TITLE
Не возможно сменить путь установки програмы

### ISSUE THREAD

**Issue by Naviador** [SBProX/SBProX-Dev#43]
Не позволяет сменить место установки.
И от администратора запускал и в англиской версии тоже.
А разрешает установить только в С: Диск. А програмы с торговлей у меня в другом диске находятся!

![Eliminar](https://user-images.githubusercontent.com/26739991/57400576-10c71a00-71d4-11e9-8587-fdeac5c168bf.png)

**Comment by SBProX** [comment]
Да, так и задумано.
