### ISSUE TITLE
Новая фигура в CLOUD

### ISSUE THREAD

**Issue by Samm2019** [SBProX/SBProX-Dev#430]
Предлагаю добавить в список фигур Cloud линии. С рейтингом, чем больше объём тем больше длина линии. Желательно что бы толщину линии тоже можно было менять.

**Comment by alexanflint** [comment]
и в cluster search тоже было бы неплохо добавить.

**Comment by SBProX** [comment]
Мы против этого предложения. Непонятна что это будет за визуализация в виде кучи линий на графике.
