### ISSUE TITLE
Стрелки start-end time 

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#434]
Здравствуйте.
Если включить внутри сессии стрелку **start time** (см. скрин.) то из за того что торговая сессия онлайн при первой же сделке экран прыгает в **end time**
Приходится выключать end time (статус: зеленая окрашивает в серый) и затем нажимать стрелку start time.

![Strelki nach konec grafika](https://user-images.githubusercontent.com/20509322/61994856-a88d2380-b0b2-11e9-9aab-2204b51ea01f.jpg)

**Comment by SBProX** [comment]
Принято, очень позорная ошибка.
Исправим.

**Comment by SBProX** [comment]
Исправлено. Обновление будет сегодня.
