### ISSUE TITLE
Alerts: Notification color

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#435]
Здравствуйте.
Не появляется окно выбора цвета для Notification color. 
При нажатии на первый индикатор (notification color) окно выбора цвета будет.
Далее переключаем на второй индикатор (cluster_search_2) окно не появится

![1sbnotification alert](https://user-images.githubusercontent.com/20509322/61994936-6b299580-b0b4-11e9-958f-e07164445841.jpg)

**Comment by SBProX** [comment]
Спасибо, исправим.

**Comment by SBProX** [comment]
Исправлено. Обновление будет сегодня.
