### ISSUE TITLE
Сломали симулятор в части агрегации

### ISSUE THREAD

**Issue by VeegoDamask** [SBProX/SBProX-Dev#437]
Добрый день.

При запуске симулятора не срабатывает агрегация по нестандартным шагам цены.

1. Вот как выглядит график H1 CL с включенным симулятором и агрегацией 0,05

![image](https://user-images.githubusercontent.com/29836202/61998064-fb66db00-b0b2-11e9-95ee-f542f2508f4c.png)

2. Он же, с выключенным симулятором и агрегацией 0,05.

![image](https://user-images.githubusercontent.com/29836202/61998074-18031300-b0b3-11e9-9ae8-bd8d58d512d3.png)

Объемы фильтруются через cluster search

**Comment by SBProX** [comment]
Исправлено. Обновление будет сегодня.
