### ISSUE TITLE
Небольшая проблема с гор. линиями

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#440]
Здравствуйте, не могу постоянно зайти в настройки горизонтальных линий так чтобы выставленные линии не сместились с места, приходится постоянно их корректировать обратно, очень неудобно работать с выставлением гор. уровней. Можно что-то придумать с этим, например, вход в настройки нажатием колесика мышки или что-то ещё)
[bandicam 2019-07-29 14-35-35-972.zip](https://github.com/SBProX/SBProX-Dev/files/3441840/bandicam.2019-07-29.14-35-35-972.zip)

**Comment by SBProX** [comment]
Принято, исправим.

**Comment by WillBegin1** [comment]
ок, при много благодарен)

**Comment by SBProX** [comment]
Исправили, будет работать в следующем обновлении.
