### ISSUE TITLE
Проблема отображения котировок на разных ТФ

### ISSUE THREAD

**Issue by fxNil** [SBProX/SBProX-Dev#441]
Здравствуйте.
На инструменте GC на разных ТФ обнаружился гэп и, соответственно, разные котировки.
Перезегрузка графика и перезапуск платформы не помогли.

![Screenshot_6](https://user-images.githubusercontent.com/6092809/62024664-842e6580-b1de-11e9-9954-7ec43e7cf714.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/6092809/62024668-885a8300-b1de-11e9-9d36-f3615df78f7e.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/6092809/62024670-8a244680-b1de-11e9-962c-95734e630da7.jpg)

**Comment by SBProX** [comment]
Во сколько вы запускали ваш workspace? Нужно точное время.
Судя по скриншотам, то включился новый контракт (что конечно же ошибка).
Попробуйте перезагрузить платформу, на данный момент все в порядке.

**Comment by fxNil** [comment]
Первый запуск сегодня был в 8.30 МСК.
Примерно в 9.00 МСК я перезагрузил компьютер и отображение котировок нормализовалось.
На данный момент тоже всё в порядке.

**Comment by SBProX** [comment]
Понятно, если повторится, сделайте reopen тикета

**Comment by fxNil** [comment]
Сегодня опять гэп на GC. Только теперь уже на всех ТФ. Перезапуск платформы делал раза три. Один раз компьютер перезагружал - не помогло.
![изображение](https://user-images.githubusercontent.com/6092809/62122868-5d039100-b2cf-11e9-8cad-3a8f4023847c.png)

**Comment by SBProX** [comment]
@fxNil Это уже не ошибка - это новый контракт 12-19.
