### ISSUE TITLE
Не работает затемнение графика при плотности объема

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#443]
Обычный график кластер объем
![Screenshot_1](https://user-images.githubusercontent.com/29704362/62044382-40f2e780-b21c-11e9-818f-65371c53ff54.jpg)

При включении плотности объема, затемнение пропадает
![Screenshot_2](https://user-images.githubusercontent.com/29704362/62044411-523bf400-b21c-11e9-888c-ffc63d158d47.jpg)

**Comment by bizlis** [comment]
и еще замечание, при включенной плотности, не работают минимальные объемы

**Comment by SBProX** [comment]
> и еще замечание, при включенной плотности, не работают минимальные объемы

Плотность объемов имеет приоритет над другими фильтрами.
Мы изначально отказались от идеи совмещать плотность и другие фильтры, так как будет венегрет на кластерах, и в этом по нашему мнению нет смысла.

Что касательно затемнения шрифта, то поправим.

**Comment by SBProX** [comment]
Исправили, будет работать в следующем обновлении.
