### ISSUE TITLE
В симуляторе 

### ISSUE THREAD

**Issue by bushevigor** [SBProX/SBProX-Dev#448]
В симуляторе перестали отображаться значки купли,продажи  (треугольники) при масштабировании после обновления.

**Comment by SBProX** [comment]
Принято, проверим и сегодня исправим

**Comment by finast** [comment]
И некоторые рисунки при масштабировании меняют свой размер.

**Comment by SBProX** [comment]
@finast что такое "рисунки"?

**Comment by SBProX** [comment]
С симулятором исправлено, сегодня выйдет обновление.

**Comment by finast** [comment]
Извините, недооформил - торопился. Прилагаю два скрина, где одна сторона прямоугольника (обозначена красной стрелкой) в разных масшатабах перемещается по графику.
![1](https://user-images.githubusercontent.com/50439357/62120745-a063fc80-b2db-11e9-85df-5139fedc65ae.jpg)
![2](https://user-images.githubusercontent.com/50439357/62120746-a0fc9300-b2db-11e9-8635-0b79ec4122e8.jpg)

**Comment by SBProX** [comment]
@finast Исправлено, спасибо

**Comment by finast** [comment]
Да, сейчас всё корректно. Спасибо!
