### ISSUE TITLE
Неправильное обозначение таймфрейма в названии графика

### ISSUE THREAD

**Issue by exclim89** [SBProX/SBProX-Dev#449]
В симуляторе и в обычном графике, в названии графика пишется неправильный таймфрейм, нежели указан на графике в действительности.

![rsBR 1 мин BoxChart 2019-07-30 14 57 29](https://user-images.githubusercontent.com/53253572/62104781-76123f00-b2db-11e9-8ec6-34b091d774b0.png)
![rsBR 1 мин BoxChart 2019-07-30 14 56 17](https://user-images.githubusercontent.com/53253572/62104783-76aad580-b2db-11e9-8442-200d0a35b7c2.png)

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by SBProX** [comment]
Можете сообщить ваш логин и название workspace?
Мы не можем у себя воспроизвести ошибку.

**Comment by exclim89** [comment]
Логин exclim@mail.ru, workspace Work

**Comment by exclim89** [comment]
Может быть в истории дело? У меня открыт фьючерс нефти марки Brent рынка Фортс за сентябрь 2018 года

**Comment by SBProX** [comment]
Ошибку нашли, исправляем.
