### ISSUE TITLE
Изменить место открытия окошка настроек инструментов

### ISSUE THREAD

**Issue by Abrikotin** [SBProX/SBProX-Dev#456]
Сделайте пожалуйста, чтобы окошко настроек инструментов открывалось рядом с курсором, чтобы не было лишних движений мышкой.

**Comment by SBProX** [comment]
Не получится, так как панель длинная, и ее можно разместить только в левом углу.

**Comment by Abrikotin** [comment]
Вы не поняли. Вот скрин.
![Окошко настроек инструмента Текст](https://user-images.githubusercontent.com/53471671/62141008-939fd280-b2f4-11e9-9a9c-f26ddd0e82ab.jpg)

**Comment by Abrikotin** [comment]
Чуть двинул мышкой и ты уже в окошке настроек инструмента.
