### ISSUE TITLE
Группировка окон в одно

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#458]
Использую несколько мониторов, на одном мониторе открыт один инструмент - это 3-4 окна, если на одном мониторе в таком режиме открыть еще один инструмент, то в дальнейшем возникает проблема открытия этих окон по одинаковым инструментам.
![Screenshot_1](https://user-images.githubusercontent.com/29704362/62156200-f2c90b80-b323-11e9-8fe0-ef6bab5114c9.jpg)

Можно ли как-то сделать в новых версиях, чтобы окна связать - слинковать в один блок, чтобы можно было по одному клику мыши сразу открывать этот блок, а не каждое окно в отдельности (в Атасе вроде такую идею смогли сделать, видел в каком-то ролике. но сам не проверял, т.к. им не пользуюсь)?

**Comment by r0b4ik** [comment]
О дааа, это моя мечта. Идеальный вариант модальные окна, но это явно в версии X не реализовать

**Comment by alexanflint** [comment]
очень нужная вещь,поддерживаю.

**Comment by vasiliyyun** [comment]
Поддерживаю!

**Comment by SBProX** [comment]
Мы не сможем это сделать, платформа проектировалась в формате окно-вкладки.
