### ISSUE TITLE
При включенном Bars Delta Highlight не видно других индикаторов.

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#459]
![image](https://user-images.githubusercontent.com/50357928/62190099-3ac64d80-b379-11e9-8a41-fbb3bedfe2f8.png)

возможно просто стоит сделать возможность сортировать индикаторы, т.к. они явно накладываются слоями в порядке очереди

**Comment by SBProX** [comment]
Спасибо за замечание, займемся.

**Comment by SBProX** [comment]
Сортировка индикаторов сделана
