### ISSUE TITLE
Графики неправильно отображаются после выхода ноутбука из спящего режима на всех вкладках

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#46]
![2019-05-09_8-47-41](https://user-images.githubusercontent.com/35344271/57430215-ab0c7980-7237-11e9-8d95-cfa7bcfb9e84.jpg)
![2019-05-09_8-46-13](https://user-images.githubusercontent.com/35344271/57430220-af389700-7237-11e9-8730-5559965a9d2c.jpg)
![2019-05-09_8-53-16](https://user-images.githubusercontent.com/35344271/57430333-09395c80-7238-11e9-8e18-52fce6a17fb8.jpg)

**Comment by Dmitry1970** [comment]
![2019-05-09_16-36-21](https://user-images.githubusercontent.com/35344271/57457691-a87e4400-7278-11e9-9756-0473f41b9a88.jpg)

**Comment by SBProX** [comment]
Сделали полную перезагрузку графиков после спящего режима.
Будет в ближайшем обновлении.
Если проблема не решится, то сделайте reopen тикета.
