### ISSUE TITLE
Масштаб по вертикали

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#461]
После обновления вернулась старая проблема. При масштабировании графика (при этом не обязательно до макс/мин масштаба), например, при небольшом уменьшении масштаба, а затем возврате графика в прежний масштаб, он стремится сузиться по вертикали. Если такую манипуляцию произвести несколько раз, то график сплющивается. Приходится заново настраивать масштаб по вертикали. 
Кроме того, раньше, для того чтобы увеличить или уменьшить график, нужно было меньше крутить колесиком, так как масштабирование осуществлялось довольно быстро. Теперь из-за плавности, это стало ощутимо медленнее, т.е. приходится больше крутить колесико.

**Comment by vasiliyyun** [comment]
Уважаемые разработчики, появилась такая мысль. Можно ли сделать так, чтобы масштаб по вертикали стал сжиматься только после максимального сжатия по горизонтали? Это решило бы проблему. Либо сделайте новую систему масштабирования опциональной. Она возможно удобна тем кто использует кластера, я использую программу в режиме свечей, и мне нововведения не удобны. Поэтому было бы здорово, если бы в меню появился бы пункт с включением/выключением нового режима масштабирования.

**Comment by SBProX** [comment]
Спасибо, поправим.

**Comment by vasiliyyun** [comment]
Уважаемые разработчики, здравствуйте еще раз! У меня появился такой вопрос. В комментариях к описанию обновления от 29.07, Вы сообщили, что плавное масштабирование останется, так как его многие просили. А что если, Вы реализуете некую горячую клавишу (например, LeftCtrl+колесико мыши). В этом случае, при зажатом LeftCtrl и прокручивании колесиком мыши, график бы уменьшался/увеличивался быстрее. Допустим, если при обычном прокручивании колесиком мыши мы имеем масштабирование с шагом 1, то при зажатом LeftCtrl и прокручивании этот шаг становился бы равном 3. Такое возможно реализовать?

**Comment by Bolt022** [comment]
в версии 2 идеально масштабируется туда-обратно без потери по горизонтали и вертикали! можно сделать как там.

**Comment by SBProX** [comment]
Сделано равномерное масштабирование колесом мыши, с сохранением пропорций по осям.
Будет работать в следующем обновлении.
