### ISSUE TITLE
Регулировка ширины у горизонтальной линии мышкой

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#462]
Большая просьба сделать по возможности регулировку ширины горизонтальной линии мышкой с графика, как у фигуры прямоугольник, вместо числового значения и как вариант можно переименовать этот элемент в область или зону, это мне кажется более логичнее, чем линия, т.к. все линии ставятся с боковой панели, это внесет меньше путаницы для новых пользователей платформы.

**Comment by r35p3ct** [comment]
Я предлагаю сделать вернее значение цены и нижнее, установил и забыл, чтобы толщину не подбирать.

**Comment by SBProX** [comment]
Инструменты рисования мы больше дорабатывать не будем в ближайшее время.
У нас нет времени на это.
