### ISSUE TITLE
Не идут котировки западных инструментов

### ISSUE THREAD

**Issue by Artem-Br** [SBProX/SBProX-Dev#464]
Здравствуйте.

SBProX подключен через коннектор SBPro. Российские котировки идут без проблем. В западных - график не перерисовывается автоматом, только по зеленой кнопке "Применить".
Пример по нефти: 
![rsBR 5 мин Candle Real-Time Data_ 5059 ticks 2019-07-31 18 43 30](https://user-images.githubusercontent.com/43574390/62217700-8baf6380-b3c4-11e9-8487-75e2443e4fae.png)

**Comment by Artem-Br** [comment]
PS. Писал в поддержку в Skype - тишина.

**Comment by SBProX** [comment]
@Artem-Br Спасибо, проверим.
Подскажите, какие часовые пояса стоят на инструментах?

**Comment by Artem-Br** [comment]
CL - (UTC-06:00) Центральное время (США и Канада)
rsBR - (UTC+03:00) Москва, Санкт-Петербург

**Comment by SBProX** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/16720120/62290651-80af0e80-b46a-11e9-914b-d6d2de4c1652.png)

В Skype вам вчера ответили.

**Comment by SBProX** [comment]
Спасибо, будем проверять.

**Comment by Artem-Br** [comment]
Странно, в скайп до сих пор ничего не пришло. Но сейчас увидел, что коннектор для US не был настроен. Спасибо за помощь.
