### ISSUE TITLE
Баг с сигналами

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#465]
Была следующая ситуация - по инструменту SI были сигнал за сигналом, прямо зашкаливало, я сигналы отключил и инструмент этот удалил, но теперь по другому инструменту при срабатывании сигнала (изменение DPOC) пишет, что сработал сигнал по инструменту SI, а его у меня нет, по факту сигнал срабатывает на нефти. Вот такой баг обнаружился.

**Comment by bizlis** [comment]
Путаница с сигналами продолжается, теперь у меня открыт РТС, а сигнал якобы по нефти идет.

**Comment by SBProX** [comment]
Спасибо, проверим на днях.

**Comment by SBProX** [comment]
Пока что не удается воспроизвести ошибку.
При удалении вкладки, алерты с удаленной вкладки никак не могут срабатывать.

**Comment by bizlis** [comment]
возможно просто неправильно отображался символ инструмента, поэтому и была путаница

**Comment by SBProX** [comment]
Возможно. Сейчас такой проблемы не наблюдается?

**Comment by bizlis** [comment]
последнее время мало торговал, но вроде пока такого не наблюдал больше

**Comment by SBProX** [comment]
Хорошо, тогда тикет закрываем.
