### ISSUE TITLE
Фильтры кластеров перевернуты

### ISSUE THREAD

**Issue by TonyGerson** [SBProX/SBProX-Dev#468]
Приложил скриншот.
Возможно так задумано, но это довольно странно. Градация должна быть наоборот.
У первого фильтра значение должно быть меньше, чем у последующих, а сейчас наоборот. И чтобы отображение фильтров было корректным, нужно настраивать как на скриншоте.
![фильтры кластер профиля](https://user-images.githubusercontent.com/53541400/62249211-8f59df00-b3f2-11e9-9f0f-5ace83813bdc.png)

**Comment by SBProX** [comment]
Да, так задумано.
