### ISSUE TITLE
Доработка функционала симулятора.

### ISSUE THREAD

**Issue by zelezomen** [SBProX/SBProX-Dev#47]
В текущем виде симулятор не особо пригоден для использования, он как бы формально есть, но пользоваться им по назначению неудобно. 
1) Добавить возможность загрузить данные с одной даты, но воспроизведение начать с другой. Например, я хочу отработать 3 апреля, но мне для построения торговой идеи и полноценной торговли нужны чарты за предыдущие две недели, чтобы я мог понять где мы вообще находимся, что с ценой, какие уровни или зоны и т.п. 
2) Добавить возможность начинать с определённого времени. Я торгую америку и каждый раз отматывать на скорости начиная с 00:00 сильно неудобно. Если нужно отработать один день, то можно пережить, но если требуется прогнать идею на паре месяцев, то это не годится.
3) Возможность промотки воспроизведения как в видеоплеере. Выбираешь интервал, скажем 10 минут и жмёшь кнопку, история перескочила на 10 минут вперёд. Опять же, если есть необходимость отработать много сессий, то без этой функции всё сильно растягивается во времени.

**Comment by bizlis** [comment]
Поддерживаю, действительно симулятору этого не хватает

**Comment by Anton144** [comment]
Присоединяюсь ко всему изложенному,и конкретно к 3 пункту добавлю, может быть повторюсь! Хотелось бы в процессе торговли видеть процесс наполнения самого бара,свечи т.е в разных визуализациях (кластера и профиля),а то бар появляется один за другим и непонятно как он формировался внутри,как цена и объём гуляли в нём!

**Comment by Anton144** [comment]
Присоединяюсь ко всему изложенному,и конкретно к 3 пункту добавлю, может быть повторюсь! Хотелось бы в процессе торговли видеть процесс наполнения самого бара,свечи т.е в разных визуализациях (кластера и профиля),а то бар появляется один за другим и непонятно как он формировался внутри,как цена и объём гуляли в нём!

**Comment by Anton144** [comment]
Присоединяюсь ко всему изложенному,и конкретно к 3 пункту добавлю, может быть повторюсь! Хотелось бы в процессе торговли видеть процесс наполнения самого бара,свечи т.е в разных визуализациях (кластера и профиля),а то бар появляется один за другим и непонятно как он формировался внутри,как цена и объём гуляли в нём!

**Comment by Anton144** [comment]
Присоединяюсь ко всему изложенному,и конкретно к 3 пункту добавлю, может быть повторюсь! Хотелось бы в процессе торговли видеть процесс наполнения самого бара,свечи т.е в разных визуализациях (кластера и профиля),а то бар появляется один за другим и непонятно как он формировался внутри,как цена и объём гуляли в нём!

**Comment by SBProX** [comment]
> Присоединяюсь ко всему изложенному,и конкретно к 3 пункту добавлю, может быть повторюсь! Хотелось бы в процессе торговли видеть процесс наполнения самого бара,свечи т.е в разных визуализациях (кластера и профиля),а то бар появляется один за другим и непонятно как он формировался внутри,как цена и объём гуляли в нём!

Ну как же! Вы когда выставляете скорость в симуляторе, то он работает потиково.
Хотите видеть прямо как в реал-тайме, как формируется бар - ставьте низкую скорость.

**Comment by ferenci** [comment]
Хотел уже было подобную тему открыть ещё одну, но поднапрягся и нашёл эту. В целом поддерживаю то что написал zelezomen, я примерно тоже самое хотел предложить, ведь без истории никак. Можно, например, сделать чтобы история загружалась как и обычно с той даты, которую мы указываем в основном окне. И ещё не по теме: обязательно нужно сделать чтобы можно было рисовать справа от графика.

**Comment by SBProX** [comment]
Историю уже добавили.
Насчет остального - пока что мы это делать не будем, пожалуйста создайте отдельные тикеты по пункту 2 и 3
