### ISSUE TITLE
Симулятор в режиме онлайн

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#472]
Возможно ли сделать симулятор в режиме онлайн? Т.е. включить симулятор и торговать в режиме онлайн самого графика сегодня/сейчас?
Спасибо!

**Comment by SBProX** [comment]
Сделать возможно все, но мы этого делать не планируем.

**Comment by WillBegin1** [comment]
А было бы неплохо)

**Comment by Flawmaster** [comment]
Да, было бы классно. Очень многие ждут этой функции. Можно даже хотя бы самый простой - просто постановка и открытие ордеров, без запоминания истории (до первого закрытия терминала). Т.е. хотя бы в течение дня торговать на "демо".

**Comment by WillBegin1** [comment]
И учитывая тот факт, что во всех известных платформах эта функция доступна)
