### ISSUE TITLE
HLOC закрывает показания рулетки в верхней части графика.

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#473]
При попытке измерения рулеткой с нижней части графика до самых верхов графика, не возможно считать показания рулетки, т.к. они закрываются показаниями HLOC
![Screenshot_18](https://user-images.githubusercontent.com/29704362/62320325-589acc00-b4b9-11e9-8b29-0ba3a5e96da4.jpg)

**Comment by WillBegin1** [comment]
И цвет показаний рулетки сделайте, чтобы можно было изменить

**Comment by finast** [comment]
Извиняюсь за вопрос не в тему, но подскажите, пожалуйста, где можно найти эту самую рулетку? Вроде все инструменты просмотрел, но не нашёл.

**Comment by bizlis** [comment]
> Извиняюсь за вопрос не в тему, но подскажите, пожалуйста, где можно найти эту самую рулетку? Вроде все инструменты просмотрел, но не нашёл.

Нажимаете колесико мыши и удерживая тянете

**Comment by finast** [comment]
> > Извиняюсь за вопрос не в тему, но подскажите, пожалуйста, где можно найти эту самую рулетку? Вроде все инструменты просмотрел, но не нашёл.
> 
> Нажимаете колесико мыши и удерживая тянете

Спасибо. Так просто, я а голову ломал ))))))

**Comment by vasiliyyun** [comment]
На самом деле, было бы очень удобно, если бы HLOC показывался только при наведении курсора на свечку (как это реализовано во многих терминалах).

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении
