### ISSUE TITLE
Очередной баг в симуляторе.

### ISSUE THREAD

**Issue by VeegoDamask** [SBProX/SBProX-Dev#479]
Ребята, наймите плиз тестировщика, чтобы он делал элементарный регресс, ну это же пипец. Как ни сажусь за работу - не получается, потому, что вы катите релиз с багом, который ломает то, что работало ранее и делает работу невозможной.

1. Запускаем симулятор. Оставляем шаг цены по умолчанию. Всё красиво.

![image](https://user-images.githubusercontent.com/29836202/62417065-75690800-b64f-11e9-8ff8-a7e107764258.png)

2. Теперь ставим рабочий шаг цены на часовике - 0,05. Более ничего не меняем. Перезапускаем симулятор. Смотрим, что происходит на М10. 
![image](https://user-images.githubusercontent.com/29836202/62417091-08a23d80-b650-11e9-9a17-097a76bd8ebe.png)

Функционал отрисовывает как бы шаг 0,01, но объемы внутри бара берет с шагом 0,05, в результате чего все фильтры и индикаторы объема по цене отрабатывают не корректно.

**Comment by VeegoDamask** [comment]
Можно как-то поднять приоритет у вопроса? Это блокирующая проблема для меня.

**Comment by SBProX** [comment]
@VeegoDamask ожидайте обновлений, баг проверим и исправим.
У нас нет большого штата программистов и тестировщиков чтобы делать все и сразу.

**Comment by SBProX** [comment]
Исправили, можете проверить.
