### ISSUE TITLE
Не обновляются графики после включения платформы

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#48]
http://prntscr.com/nmb2cx
http://prntscr.com/nmb2n6

**Comment by Artem074** [comment]
есть такая беда... но она появляется тогда, когда перед этим сам ручками дату двигал... и она соответственно к этой дате и прилипает.

**Comment by Artem074** [comment]
уже был такой тикет https://github.com/SBProX/SBProX-Dev/issues/8

**Comment by SBProX** [comment]
Тикет уже был
