### ISSUE TITLE
Баг с ClusterSearch на тиковом графике

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#498]
ClusterSearch на тиковом графике при изменении масшатба или перетаскивании графика то появляется, то пропадает
![image](https://user-images.githubusercontent.com/50357928/62823749-4269cb80-bb9d-11e9-9164-64134abe0bdf.png)

![image](https://user-images.githubusercontent.com/50357928/62823753-57465f00-bb9d-11e9-8996-794e23cd4bf4.png)

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении
