### ISSUE TITLE
Баг уровней на тиковом графике, залинкованном к минутному

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#499]
Есть 2 графика, которые залинкованы. Тиковый и минутный, наношу уровни с  начальной точкой и тамм и там. отображаются нормально. 
После добавления клауд на минутный график и изменения периода, на тиковом у уровней пропадает начальная точка, линии превращаются в бесконечные. При этом на минутном графике они по прежнему отображаются нормально, а на тиковом уже невозможно создать уровень с начальной точкой, линия идёт всегда от начала до конца.  
![image](https://user-images.githubusercontent.com/50357928/62847776-ba8cda00-bce0-11e9-8ac8-d83db44390e2.png)

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении.
