### ISSUE TITLE
Индикатор VWAP все еще глючит

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#50]
Индикатор VWAP после обновы все равно некорректно отображается пока не нажмешь применить.

**Comment by alex12mosk** [comment]
![image](https://user-images.githubusercontent.com/50362894/57435805-fd08cb80-7246-11e9-8f9c-93547be5f25a.png)
![image](https://user-images.githubusercontent.com/50362894/57435830-0eea6e80-7247-11e9-9fb8-9accada9960d.png)

**Comment by SBProX** [comment]
Исправлено
