### ISSUE TITLE
Не работает связка LeftCtrl + E

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#503]
Заметил, что не работает "развертывание графика" с помощью горячих клавиш. Комбинация LeftCtrl + E просто увеличивает график, но не разворачивает окно графика, как это было раньше. Исправьте пожалуйста.

**Comment by SBProX** [comment]
LeftCtrl+E отвечает за увеличение графика, а не окна.
Это не ошибка вовсе.
