### ISSUE TITLE
Индикатор VWAP

### ISSUE THREAD

**Issue by Panica777** [SBProX/SBProX-Dev#504]
Здравствуйте, скажите пожалуйста когда вы уже добавите отклонения в индикатор VWAP ? Ведь технически это не так сложно сделать разве нет? Во всех известных платформах есть отклонения в этом индикаторе. Я бы сказал это одна из очень важных особенностей этого индикатора. А в вашей платформе этот замечательный индикатор напоминает простой мувинг не более того.

**Comment by Panica777** [comment]
Друзья помогите лайками, чтоб разработчики обратили свое внимание на этот пост

**Comment by Vyura** [comment]
+

**Comment by Panica777** [comment]
А лучше конечно коментариями, Отпишитесь кто вообще что думает по этому поводу? Эта платформа позиционирует себя побольшей степени к объемному анализу рынка, VWAP напрямую относиться к объемному анализу, это один из основных биржевых индикаторов. Да и вообще странно честно говоря что нет отклонений,  VWAP без отклонений это не VWAP

**Comment by WillBegin1** [comment]
+

**Comment by SBProX** [comment]
У нас масса задач, мы не можем разорваться.
Тикет такой есть, значит будем делать.

**Comment by gios76** [comment]
здравсвуйте. В SBProX в индикаторе VWAP в настройках только FULL, WEEK и DAY таймфреймовый вариант. не смогли бы добавить ещё низкие периоды, конкретно часовой и 15 минутный
