### ISSUE TITLE
Ошибка в отображении OI

### ISSUE THREAD

**Issue by 63vova** [SBProX/SBProX-Dev#505]
На текущей свече открытый интерес в SB показывает значение закрытия открытого интереса в Квике предыдущей свечи.
[[image](https://user-images.githubusercontent.com/24702380/62867411-dd88af80-bd1b-11e9-9bb8-c38cd9710054.png)](url)
[[image](https://user-images.githubusercontent.com/24702380/62867468-001ac880-bd1c-11e9-813a-738c05db5ea4.png)](url)

**Comment by SBProX** [comment]
В настройках ОИ индикатора есть галочка - показывать последнее значение.
Вы можете ее включить или отключить в зависимости от того, что вы хотите видеть.

**Comment by 63vova** [comment]
Спасибо.

ср, 14 авг. 2019 г. в 16:34, SBPro X <notifications@github.com>:
