### ISSUE TITLE
Оптимизация рабочего пространства

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#507]
Уважаемые разработчики, есть одна просьба. Дело в том, что когда на одном мониторе открыто несколько окон (в приведенном примере 4 окна), то графику немного не хватает пространства. Было бы здорово, если появилась бы горячая клавиша, с помощью которой можно было бы скрыть панели сверху и снизу. Привожу скрин с пояснениями:
![image](https://user-images.githubusercontent.com/50597350/62875836-660f4c00-bd2c-11e9-8e56-3e3d9aecc237.png)

**Comment by 63vova** [comment]
Мне не хватает уже 2 мониторов ) Пора покупать еще один . . .

**Comment by vasiliyyun** [comment]
Ага, такая же фигня=))

**Comment by alex12mosk** [comment]
Было бы еще неплохо сделать горячую клавишу для вызова/скрытия панели "инструменты"

**Comment by SBProX** [comment]
Что вам даст скрытие эти двух панелей?
Принципиально же ничего не изменится. 
Для удобной работы с графиками нужны большие мониторы.
Такие полу-меры по сути ничего не изменят, а работы нам добавит.
