### ISSUE TITLE
Предложение админу

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#508]
На данном форуме накопилось уже несколько сотен тикетов\веток, пошли уже и повторения. Прочитать новым юзерам всё это весьма трудно, отсюда предложение админу - сгруппировать основную массу веток в группы, если конечно движок форума это позволяет. Например группы: симулятор и торг.модуль, линии, индикаторы, графики, и.т.д. на ваше усмотрение. Так будет гораздо легче искать нужную тему и по количеству тикетов в группе  вам легче будет анализировать какая тема наиболее горячая и что надо исправлять\дополнять.

**Comment by 63vova** [comment]
Поддерживаю

**Comment by Komostos** [comment]
Да, это уже стало необходимостью. +1

**Comment by SBProX** [comment]
К сожалению на GitHub нет такого функционала.
Тикеты будем разгребать, сейчас мы немного отдыхаем перед сентябрем.
