### ISSUE TITLE
Видимость направления баров в режиме ПРОФИЛЬ

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#511]
Можно ли включить "видимость" баров (открытие и закрытие) при формате Профиль Дельты/Объёма? 
http://prntscr.com/os8a00

**Comment by Samm2019** [comment]
![Направление бара](https://user-images.githubusercontent.com/50338402/63005032-27e16c00-be95-11e9-8637-ca848b980a7e.JPG)

**Comment by stason251187** [comment]
Супер. Спаибо!
