### ISSUE TITLE
Ошибка в заголовке окна

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#513]
При создании нового окна и загрузки шаблона, заголовок окна не меняет название инструмента. 
А на дневном графике вообще не отображается название инструмента и ТФ.
![Screenshot_1](https://user-images.githubusercontent.com/29704362/62998128-f57b4300-be83-11e9-91d6-e60fe3a64335.jpg)

**Comment by bizlis** [comment]
после перезапуска программы вообще везде пропадают заголовки окон
![Screenshot_1](https://user-images.githubusercontent.com/29704362/62999504-180f5b00-be88-11e9-94e7-ba24f73ae612.jpg)

**Comment by SBProX** [comment]
Внесли изменения. Ожидайте пожалуйста обновления.

**Comment by SBProX** [comment]
Проверьте пожалуйста.
У нас все работает.

**Comment by bizlis** [comment]
> Проверьте пожалуйста.
> У нас все работает.

сейчас все нормально работает!

**Comment by bizlis** [comment]
Только надпись Real_time Data немного забивает глаза
![Screenshot_1](https://user-images.githubusercontent.com/29704362/63114352-18097b00-bfae-11e9-9392-537f559e7fcf.jpg)
