### ISSUE TITLE
Технические работы!

### ISSUE THREAD

**Issue by SBProX** [SBProX/SBProX-Dev#514]
Добрый день.

Сообщаем Вам о том, что с сегодняшнего дня будут выполняться технические работы на серверах для SBProX, для устранения проблемы с задержкой данных.

Работы могут продлиться несколько дней.
Просим Вас воздержаться от торговли с помощью SBProX.

Мы сообщим об окончании работ.

**Comment by Ravil124** [comment]
Здравствуйте. Большая просьба, предупреждайте, пожалуйста, о технических работах до начала торгов.
