### ISSUE TITLE
Настройки динамического профиля по умолчанию

### ISSUE THREAD

**Issue by AlTuzov** [SBProX/SBProX-Dev#520]
Перестали сохраняться настройки динамического профиля по умоляанию. Раньше работало.

**Comment by SBProX** [comment]
Спасибо, проверим сегодня.

**Comment by AlTuzov** [comment]
Хочу оточнить. Не сохраняется тип профиля, а цвет бара и рамки, макисмальный фильтр сохраняются. Остальные элементы не проверял.
