### ISSUE TITLE
Проблема со склейками фьючерса Si

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#523]
Сегодня обратил внимание, что склейки на дневном графике фьючерса rs Si (SIU9) отличаются от склеек на графике Московской биржи и терминала Альфа-Директ. Можно как-то изменять склейки, чтобы графики на московской бирже и в терминале SBPro X совпадали?
Вот скриншоты:
![Snap_19 августа 2019 г _11h12m25s_003_](https://user-images.githubusercontent.com/24631570/63233602-7cf5f700-c274-11e9-9ab0-37e560e3bf91.png)
![Snap_19 августа 2019 г _11h13m07s_004_](https://user-images.githubusercontent.com/24631570/63233611-8a12e600-c274-11e9-800f-f9b2c97e49aa.png)

**Comment by SBProX** [comment]
@gengal У вас на графике Альфа-директ или на втором скриншоте - это не склейка, а отдельно взятый контракт с большим куском неликвидной истории.

Сами сравните вертикальные объемы, на ваших скриншотах.

**Comment by gengal** [comment]
Я хочу уточнить: 1) в терминале SBProX на дневном графике получается склейка из трех последних месяцев текущего и предыдущих контрактов, а в Альфа-Директ и на графике мосбиржи просто отдельный контракт, верно? 
2) Подскажите как в таких случаях ориентироваться на уровни больших таймфреймов? В пределах последних 3-х месяцев текущего контракта уровни в обоих случаях (на приведенных выше графиках) совпадают, но если они определяются по времени больше 3-х месяцев, идет сильное расхождение. Это видно на приведенных выше графиках. Я просто в растерянности, на какие уровни тогда ориентироваться, если они определены на диапазоне больше 3-х месяцев? Смотреть на уровни отдельно взятого контракта с куском неликвидной истории или ориентироваться на уровни 3-х месячные склейки?

**Comment by gengal** [comment]
> 
> 
> Я хочу уточнить: 1) в терминале SBProX на дневном графике получается склейка из трех последних месяцев текущего и предыдущих контрактов, а в Альфа-Директ и на графике мосбиржи просто отдельный контракт, верно?
> 2) Подскажите как в таких случаях ориентироваться на уровни больших таймфреймов? В пределах последних 3-х месяцев текущего контракта уровни в обоих случаях (на приведенных выше графиках) совпадают, но если они определяются по времени больше 3-х месяцев, идет сильное расхождение. Это видно на приведенных выше графиках. Я просто в растерянности, на какие уровни тогда ориентироваться, если они определены на диапазоне больше 3-х месяцев? Смотреть на уровни отдельно взятого контракта с куском неликвидной истории или ориентироваться на уровни 3-х месячных склеек? Как обычно поступают профессионалы?

**Comment by SBProX** [comment]
1. Да, все правильно

2. На что ориентироваться решать Вам, и тот и тот вариант во своему корректны.
