### ISSUE TITLE
динамический профиль дополнительная свеча

### ISSUE THREAD

**Issue by OulmesCode** [SBProX/SBProX-Dev#524]
если, например, вы выбрали только 3 свечи, то по какой-то причине динамический профиль включает в себя четвертую свечу без ее выбора

![IMG - 0004 8-18-2019 9 27 16 PM](https://user-images.githubusercontent.com/14151241/63233788-1df69a80-c200-11e9-9c22-a3226b6d2170.png)

![IMG - 0003 8-18-2019 9 26 53 PM](https://user-images.githubusercontent.com/14151241/63233789-2222b800-c200-11e9-9cb4-7652db4a2ab5.png)

**Comment by Fen8fen** [comment]
- Подтверждаю.
- Если поднести профиль и поставить перед свечой то в профиле отобразятся значения......

**Comment by SBProX** [comment]
Принято, проверим.

**Comment by SBProX** [comment]
Исправлено
