### ISSUE TITLE
Алерт на уровень

### ISSUE THREAD

**Issue by Ermak1243** [SBProX/SBProX-Dev#527]
Здравствуйте. Добавьте, пожалуйста, возможность устанавливать сигнал на событие "достижении ценой определенного ценового уровня". То есть: если цена будет равна уровню 1.5734, то - сигнал.

**Comment by Samm2019** [comment]
![Сигнал](https://user-images.githubusercontent.com/50338402/63371458-947ccf00-c39d-11e9-8f1a-e039066a56b3.JPG)

**Comment by Ermak1243** [comment]
Samm2019, спасибо.
