### ISSUE TITLE
По какому принципу считается Tick Aggregation? 

### ISSUE THREAD

**Issue by Olegglasstrader** [SBProX/SBProX-Dev#53]
Вопрос к разработчикам. По какому принципу происходит аггрегация тиков на тиковом графике?
![Screenshot_22](https://user-images.githubusercontent.com/22243672/57458516-2d1d9200-727a-11e9-81fb-54b4d8212211.jpg)

**Comment by SBProX** [comment]
Агрегируются сделки прошедшие в одной миллисекунде, с одной ценой

**Comment by Olegglasstrader** [comment]
Будет ли в терминале "перетиковая" аггрегация?
![Screenshot_23](https://user-images.githubusercontent.com/22243672/57584979-50e70f00-74ea-11e9-9be3-1dd1776bb4bf.jpg)

**Comment by MakcoH22rus** [comment]
Давно прошу о реализации агрегации потока в количественном значении, т.е. учёт чистых прошедших тиков по порядку, если набирается количество тиков указанного в фильтре, то образуется новый бар,бокс, и т.д.. Что и является эмуляцией чистого потока ордеров в зжатом виде, т.е. если мы не можем уменьшить тиковый график и при этом сохранить читабельность этого графика нам поэтому и требуется именно количественная агрегация, не имеет значения какой объем прошел в самом тике важен именно учет последовательности тиков чистого потока, а объем покажут такие индикаторы как total delta и total bid/ask кому как удобней. 
![sbpro x 1 tick](https://user-images.githubusercontent.com/19171328/57607294-ee971880-7594-11e9-9bfb-14dd4a0b25bd.png) Поток в 1 тик из sb pro x.
![comx10tick](https://user-images.githubusercontent.com/19171328/57607360-14242200-7595-11e9-9b9b-c7c7e85e6375.png) Поток с последовательной агрегацией в 10 тик.

**Comment by SBProX** [comment]
Секундных графиков не достаточно для этих целей?

**Comment by MakcoH22rus** [comment]
> Секундных графиков не достаточно для этих целей?

В том то и дело что секундный график не отображает объективных данных, т.к. сам поток зажат во временной фрейм потому что за 1сек. может пройти тиков как 0 так и какое-то количество, к примеру 100, а в этих 100 прошедших тиках можно увидеть то чего не увидишь в секунде. 
Да мы можем видеть некоторое поведение участников, но что бы видеть более детальную картину т.е. микроконьюктуру, а так же и поведение алгоритмов, нужно корректное отображение потока ордеров. 
Я о том что в потоке можно разглядеть интересные ситуации именно с проявлением заинтересованных участников.
![зл](https://user-images.githubusercontent.com/19171328/57784976-0d470c00-775b-11e9-9932-1c445a960a41.png)

Вот один из примеров так же тиковая агрегация, соответственно понимая контекст это очень хорошая ситуация для совершения операции с минимальным потонциальным убытком.
