### ISSUE TITLE
Доработка линковки

### ISSUE THREAD

**Issue by Toska13** [SBProX/SBProX-Dev#530]
Сейчас линкуются только линии и периоды, очень не хватает линковки графических фигур, хотя бы прямоугольника. Чтобы чертить зону прямоугольником на одном графике и она автоматом выделяется на всех остальных.

**Comment by bizlis** [comment]
очень необходимая функция

**Comment by affectus1** [comment]
Уже было) Тоже за!

**Comment by bizlis** [comment]
как вариант, сделать хотя бы возможность копирования прямоугольника с графика на график (к примеру на часовике нарисовал и на пяти минутку скопировал по тем же координатам), но линковка это будет лучший вариант.

**Comment by SBProX** [comment]
Вы можете скопировать объект.
Ctrl+C -> Ctrl + V

**Comment by Toska13** [comment]
Если так рассуждать то я могу и линии без линковки заново провести. Мы же говорим про удобство работы, а каждый раз делать контрол ц и потом на все остальные графики контрол в неудобно.
