### ISSUE TITLE
Трендовый канал

### ISSUE THREAD

**Issue by AlexandrBik** [SBProX/SBProX-Dev#533]
При построении трендового канала, при среднем отдалении графика, верхняя и нижняя лини, находятся очень близко, и для того чтобы их растянуть нужно приближать график, растягивать их и потом отдалять, что не очень удобно. Могли бы вы сделать так, чтоб при первом его построении, линия которая отодвигается была изначально на хорошем расстоянии от другой.

**Comment by r35p3ct** [comment]
На дневке rsMOEX его построить нет возможности:
![image](https://user-images.githubusercontent.com/7328803/63410630-69759800-c3fc-11e9-84e1-80fea7afb94f.png)

**Comment by AlexandrBik** [comment]
пусть линии дальше друг от друга стоят при первом построении

**Comment by CuJlaMblcJlu** [comment]
Поддерживаю, на дневном таймфрейме не возможно провести трендовый канал !

**Comment by SBProX** [comment]
Исправили, будет работать в следующем обновлении.
