### ISSUE TITLE
Баг режима невидимости индикатора

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#534]
При включении режима невидимости индикатора на графике, его значение все равно продолжает отображаться на графике
![Screenshot_1](https://user-images.githubusercontent.com/29704362/63447783-0f092580-c456-11e9-802a-d2f45cbd8efc.jpg)

**Comment by Ravil124** [comment]
Просьба к разработчикам оставить данный баг как опцию.

**Comment by SBProX** [comment]
Исправлено, ожидайте обновления на этой неделе.
