### ISSUE TITLE
По тексту.

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#536]
1. ***В настройки каждой вкладки*** добавьте кнопку **полного** отключения **текста на графике**. **Включил мелкие объёмы**, в дополнение в обычным, **и текст** в общем стал не нужен и даже **очень мешает воспринимать график** (скрин не стал делать поскольку и так понятно). Пытался изменить  цвет шрифта, дабы он был менее видимым, но тут **изменился и цвет шрифта в индикаторах объёма, дельты, бид-аска** внизу окна, т.к. это одна настройка. Но на индикаторах текст желателен, отсюда необходимость разнести настройки шрифта на графике и на вышеуказанных индикаторах. Лучше всего в настойках индикаторов добавить  пункт "текст"  с выбором цвета.

2. Теперь по поводу соотношения размера шрифта и размера кластера.
![Соотношение 2](https://user-images.githubusercontent.com/33456972/63536502-2ebf4d00-c52d-11e9-841f-126bdc806e6a.png)
На данном скрине видно в общем нормальное  соотношение размеров.  
Теперь следующий:
![Соотношение размеров](https://user-images.githubusercontent.com/33456972/63536728-9bd2e280-c52d-11e9-8572-fb4bf1ded383.png)
Здесь размер кластера раз в 5-7 превышает размер шрифта. Вы скажете - ну дык сожми график по оси Х. Сжимал. Даже при не большом сжатии шрифт вообще пропадает, хотя размеры кластера всё ещё позволяют его отображать. На 2-м скрине фаза баланса и просматривать её в таком растянутом виде довольно не удобно, фаза может не уместиться на экране.

**Comment by SBProX** [comment]
Насчет размера шрифта поправим.
