### ISSUE TITLE
Динамический профиль: некорректное отображение

### ISSUE THREAD

**Issue by indianaxxx** [SBProX/SBProX-Dev#537]
![01](https://user-images.githubusercontent.com/54440183/63590186-8fe62f80-c5c4-11e9-9e08-86e0558a4fe3.jpg)
![02](https://user-images.githubusercontent.com/54440183/63590187-8fe62f80-c5c4-11e9-869e-31bda633e262.jpg)
Динамический профиль некорректно захватывает лишнюю свечу за границей профиля.

**Comment by SBProX** [comment]
Только что проверили, все нормально работает.
Цепляет ровно столько сколько нужно.
Можете продемонстрировать на видео?

**Comment by SBProX** [comment]
Все, нашли ошибку.

**Comment by SBProX** [comment]
Исправлено
