### ISSUE TITLE
Индикатор полос Боллинджера

### ISSUE THREAD

**Issue by indianaxxx** [SBProX/SBProX-Dev#538]
Рассмотрите возможность добавить в терминал данный индикатор. Кто читал книгу или проходил семинар Строкатова по нему это оценят. Один из немногих индюков имеющий практическую ценность в плане определения волатильности инструмента в моменте времени, развития и затухания импульса.

**Comment by alexgherco** [comment]
Если бы индикатор имел хоть КАКУЮ-ТО ценность - большинство бы уже стало миллионерами

**Comment by Panica777** [comment]
Единственный индикатор который имеет ценность это VWAP это основной индикатор который имеет прямое отношение в объемному анализу рынка, напоминаю это не синтетика, это именно  биржевой индикатор которые используют  финансовые институты, хедж фонды, в том виде который он представлен в этой платформе это не VWAP,  этот индикатор отлично помогает с позиционированием цены, где цена находиться на данный момент относительно контракта, относительно предыдущей недели, и предыдущего дня, но для этого используются всем известные отклонения этого замечательно индикатора, есть 2 основные стратегий на основе этого индикатора, 1 стратегия по тренду то есть покупается актив  только выше средневзвешенной или только  продается ниже средневзвешенной  ну и конечно же нужно комбинировать с боковой гистограммой ( профиль рынка) то есть в объемном анализе нет уровней как в техническом анализе рынка, есть диапазон о котором говорит наш профиль рынка. именно 30% праторговка всего профиля, это и будет диапазон сопротивления или же поддержки .  2 стратегия контр трендовая то есть рассматриваются продажи или покупки   на оклонениях индикатора VWAP но важно чтоб на этих оклонениях были диапазоны сопротивления и поддержки естественно,( то есть тест объема будет ли там защита диапазона со стороны крупных операторов рынка ) ну и конечно же нужно учитывать дельту в этом диапазоне на чьей она стороне,+ стакан,+ лента, + корреляция инструмента и много чего еще нужно знать прежде чем открыть сделку. Но основное я сказал.

**Comment by indianaxxx** [comment]
> Если бы индикатор имел хоть КАКУЮ-ТО ценность - большинство бы уже стало миллионерами

Так про любой можно сказать, если не знать с какой стороны к нему подойти...

**Comment by X-man77** [comment]
**Любые математические** индюки с **любыми параметрами** в тот или иной **момент\фазу\состояние\фрейм рынка** дают правильные подсказки, **НО** **_равновероятно_** и **обратное**! 

Весь вопрос в том **как определить текущей(-ую) момент\фазу\состояние\фрейм рынка** и какие **параметры под это дело нужны здесь и сейчас?**  Проще говоря  - **какие параметры данного индюка соответствуют данному моменту\фазе\состоянию\фрейму рынка?**  И кроме этого надо ещё знать и какие параметры будут соответствовать ближайшему будущему - до получаса. **Вы это можете сделать и как?** Кто-нить вообще это может сделать? 
Как говорил один известный персонаж - "человек не просто смертен, он ещё бывает и внезапно смертен". Так вот это не только о человеке, но и про рынок в том смысле что "рынок не просто изменчив, но ещё и внезапно изменчив".  И при таком изменении **все индюки** при любых параметрах начинают показывать цену на дрова позапрошлой зимой. Как в этом случае вы будете подбирать\определять их параметры? И кстати, то самое "масло которое Аннушка уже пролила" и есть **все** математические индюки.

Ошиблись с определением параметров - поймали лосёнка\лося. 

Попали близко - в шоколаде или в масле. 

Вам нужно это гадание на кофейной гуще?  

Сам **несколько лет** безуспешно пытался работать с индюками пока один умный чел не открыл мне глаза - результат потеря около 5 лет. Не повторяйте моих ошибок. 
 Единственно реальная технология анализа и понимание рынка это горизонтальные и вертикальные объёмы, профили. Надо просто правильно их понять и интерпретировать. Думаю эти технологии   были придуманы именно для ухода от вышеперечисленных неопределённостей индюков. Но если вы мне не верите - то флаг в руки. 
Изложил своё понимание, в дискуссию вступать не вижу смысла.

**Comment by Panica777** [comment]
Единственный индикатор на который стойт обратить внимание это VWAP, именно он имеет не посредственно прямое отношение к объемному анализу рынка, напоминаю. это не СИНТЕТИКА как все 99 % индикаторов, это именно биржевой индикатор который по сей день используют в хэдж фондах, в крупных финансовых компаниях и.т.д  В том виде который он представлен в этой платформе это не VWAP, хотя разработчики по всей видимости полагались на то что одной средневзвешенной будет достаточно, исходя общепринятой стратегий на основе этого индикатора, то есть рассматривать только покупки когда цена выше средневзвешенной, и продажи ниже средневзвешенной ( то есть торговля по тренду, ) Но у этого индикатора есть 1 особенность так называемые отклонения,  2 ая стратегия контр трендовая тобиш на этих отклонениях (, а также эти отклонения помогают для позиционирования цены, то есть где цена находиться относительно текущего контракта, относительно предыдущей недели, или же предыдущего дня.  Но этот индикатор используется только исключительно с профилем рынка ( боковой гистограммой) Примечание: в техническом анализе рынка используют уровни, В объемном анализе рынка используют диапазоны сопротивления и поддержки, для этого и используют профиль рынка, именно 30% проторговку НЕ БОЛЕЕ. Комбинация отклонений VWAP и профилем рынка дадут вам преимущества в торговле, но также нужно не забывать о таких вещах как стакан, лента принтов, дельта,  корреляция с другими инструментами для того чтоб так сказать зайти качественно и ювелирно в сделку.  (Стакан и лента принтов для тех у кого есть доступ к этим вещам в других софтах к примеру ) В сбпро этого нету.

**Comment by SBProX** [comment]
Мы не будем делать ничего из ТА, простите.
