### ISSUE TITLE
Рисование при скрытом перекрестии мыши

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#54]
Суть бага: когда рисуешь с активным перекрестием - все хорошо. Но, если перекрестие отключить, то рисование начинает глючить - рисуется с задержкой, а то и вовсе на 3й клик мыши (а не на 2й). Прикладываю видео.

[bug_crosshair.zip](https://github.com/SBProX/SBProX-Dev/files/3163640/bug_crosshair.zip)

**Comment by SBProX** [comment]
Исправлено
