### ISSUE TITLE
Связь между SBProX и mt4

### ISSUE THREAD

**Issue by Spekulyant** [SBProX/SBProX-Dev#540]
Здравствуйте Уважаемые разработчики.

Прошу рассмотреть мое предложение по улучшению качества продукта и облегчения торговли.

Поинтересовался у ребят с которыми торгуем и у которых есть SBPro. Как бы они отнеслись к тому, если бы в программу добавили такую замечательную вещь как открытие позиций через SBpro в mt4 (ну и у других ходовых терминалов). Идея была воспринята на ура.

Понимаем что брокеры в основной массе кухни, разные котировки. Но свечи в принципе одни и те же. Бывают заносы в редких случаях 2-5 тиков, но это не критично, но бывает что и не доходит к примеру до пока:-) обидно.

Пришли к выводы, что облегчило бы нашу торговлю, простое открытие маркетом через SBPro в ручную (кнопочки например справа - buy и sell, а лотаж например тот же самый который стоит в mt4) и моментальное выставление стоп лосса указанное в настройках. Также простая отложка в SBpro при подходе цены, открывает маркетом у брокера и тот же самый автоматический указанный стоп лосс.

Даже готовы купить такую фичу как дополнения в SBPro, а не простое нововведение в программу.

Надеюсь такое будет реализовано и хорошо воспринято.

С Уважением.

**Comment by SBProX** [comment]
@Spekulyant мы не планируем делать торговую платформу, это не входит в наши планы.
