### ISSUE TITLE
Профиль по времени

### ISSUE THREAD

**Issue by Rachidbenzhair** [SBProX/SBProX-Dev#542]
пожалуйста, вы можете добавить время начала и окончания
![2019-08-26_18-51-13](https://user-images.githubusercontent.com/15898370/63708222-1f454a00-c834-11e9-9a81-617b7b10cbc7.jpg)

**Comment by SeregaTS22** [comment]
да я тоже за, чтобы можно было посмотреть профиль за сессию к примеру

**Comment by Ravil124** [comment]
Присоединяюсь к просьбе.

**Comment by SBProX** [comment]
Для чего тогда DP? Натягивайте куда угодно профиль.
