### ISSUE TITLE
Ошибка инструмента "Рисовать горизонтальную линию"

### ISSUE THREAD

**Issue by vallida2003** [SBProX/SBProX-Dev#545]
Нажимаю на этот инструмент, справа подсвечивается значение, скажем 58.8. Отпускаю кнопку мыши и линия выше 58,8

 Хочу выставить 58.8. 1. Щёлкаю левой кнопкой мыши в вкладке Инструменты "Рисовать горизонтальную линию". 2. Помещаю курсор мыши на значение 58.8 (это значение отображается справа по вертикальной оси. 3. Щёлкаю мышью. 4. Отображается горизонтальная линия.
Эта линия должна быть напротив числа 58.8, а она отображается выше (смотри рисунок выше). Не выставишь линию по тому значению как хочешь
![Screenshot_3](https://user-images.githubusercontent.com/48010630/63767357-16a55000-c8d6-11e9-880e-6e42604c24e2.png)

**Comment by SBProX** [comment]
Опишите проблему понятно пожалуйста. Где что подсвечивается не ясно

**Comment by vallida2003** [comment]
Хочу выставить 58.8. 1. Щёлкаю левой кнопкой мыши в вкладке Инструменты "Рисовать горизонтальную линию". 2. Помещаю курсор мыши на значение 58.8 (это значение отображается справа по вертикальной оси. 3. Щёлкаю мышью. 4. Отображается горизонтальная линия.
  Эта линия должна быть напротив числа 58.8, а она отображается  выше (смотри рисунок выше). Не выставишь линию по тому значению как хочешь

**Comment by SBProX** [comment]
Принято, поправим.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении

**Comment by vallida2003** [comment]
Супер. Спасибо

чт, 5 сент. 2019 г. в 16:03, SBPro X <notifications@github.com>:
