### ISSUE TITLE
Использование памяти, стабильность работы

### ISSUE THREAD

**Issue by jjMick21** [SBProX/SBProX-Dev#546]
С самого начала работы (~2 месяца) наблюдается следующее (как например сегодня):
10-00 MSK - запуск программы, использование памяти ~500Mb;
11-00 MSK - использование памяти 700Mb;
17-00 MSK - использование памяти 3Gb;
17-13 MSK - использование памяти 3,2Gb, начинается перезагрузка данных с сервера, программа вылетает. Системных сообщений никаких, просто вываливается и все.
Цифры не всегда именно такие, но сценарий один и тот же каждый день. Если в середине дня перезагрузиться, то все начинается с начала и тогда можно дотянуть без вылетания до конца дня (~23 MSK).
Открыто 2 окна, каждое соответствует одному инструменту. В каждом окне по 5 вкладок, соответствующих различным таймфреймам. В каждой вкладке, кроме D1, используется по 5 индикаторов Cloud с различными настройками для разных временных периодов, а также по одному индикатору ClusterSearch.  Компьютер Core i3, оперативная память 8Gb.

Не призываю разбираться в моем конкретном случае, но интересно, происходит ли что-то подобное еще у кого-нибудь.

**Comment by vasiliyyun** [comment]
У меня тоже скачет значение оперативной памяти. Но максимум до 2Гб доходило. Но у меня не вылетает программа. Оперативка 4 Гб. Использую 4 окна, в каждом по 3 вкладки

**Comment by r35p3ct** [comment]
![image](https://user-images.githubusercontent.com/7328803/63832803-3ee68a80-c97a-11e9-880e-868a0eefa3d7.png)
Работает чуть больше суток.

**Comment by SBProX** [comment]
@jjMick21 Вероятно это происходит из-за большого количества Cloud - так как Cloud использует тиковые данные, которые много весят. Посмотрим, как это можно оптимизировать.

**Comment by jjMick21** [comment]
@SBProX Да, похоже на то. Если Cloud-ы убрать, то никаких проблем, конечно же, нет. Еще замечено, что если помимо SBPro открыть, например, браузер и начать там активно действовать - открывать несколько окон, содержащих ресурсоемкий контент, то это заметно ускоряет развитие проблемы. И наоборот, если кроме SBPro ничего лишнего не открывать, то до вываливания из программы дело, как правило, либо вообще не доходит, либо это происходит значительно позднеее. Вот сегодня, например, хотя использование памяти и дошло с 400М до 2Гб, но пока  ничего не вылетело.
