### ISSUE TITLE
Нанесение линий на high/low свечей

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#547]
Уважаемые разработчики, приветствую Вас! Спасибо за Вашу работу, платформа с каждым обновлением становится все лучше и лучше! У меня к Вам огромная просьба. Я уже писал тут об этом, но предложение было отклонено Вами, возможно по причине того, что я не совсем понятно изъяснил свои мысли. Попробую еще раз. В функционале программы крайне не хватает простой функции "примагничивание линий" к high/low свечей. Поясню что я имею ввиду. Моя ТС, предусматривает работу с high/low свечей, поэтому линии на графике я наношу именно на эти значения (те линии, что вызываются нажатием на поле с ценой, справа от графика). Было бы крайне удобно, если при нанесении линии, а именно ровно в тот момент когда подводишь курсор с линией к high/low свечки, линия автоматом бы примагничивалась к high/low (простите за тавтологию). И если скажем нужно нанести линию не на эти значения, то при удалении линии от high/low это примагничивание теряло бы силу. Иными словами, нужно чтобы примагничивание срабатывало только тогда, когда линия подводится к high/low свечки. Это было бы крайне удобно. Дело в том, что из за отсутствия такой, казалось бы, незначительной, но крайне полезной функции, приходится тратить очень много времени, чтобы точно нанести линию на high/low. С этой функцией, работа с графиком стала бы намного удобнее. Я думаю, что полезность такого улучшения оценят многие трейдеры использующие Вашу платформу. Заранее благодарю!
P.S. Коллеги, если вы также считаете это улучшение полезным, пожалуйста, поддержите данный пост!

**Comment by SBProX** [comment]
Поймите что мы не можем делать функционал по потребности конкретного пользователя.
Кроме того, сделать примагничивание это тонна кода и откровенно говоря геморрой, который непонятно зачем нам нужен.
Выставляйте линии в ручную пожалуйста.
