### ISSUE TITLE
Режим курсора - горячие клавиши

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#55]
Уважаемые разработчики! Добавьте, пожалуйста, в контекстное меню пункт - "курсор", где можно будет быстро отключать и включать перекрестие. И, желательно, ввести для этого горячие клавиши. Для того, чтобы было более понятно, что от вас требуется, прикладываю скриншот сравнения с NinjaTrader.

![cursor](https://user-images.githubusercontent.com/50398637/57481935-fc565080-72ab-11e9-89a4-62db437323f3.png)

**Comment by SBProX** [comment]
В это меню мы не сможем добавить, так как нет места.
Горячую клавишу сделаем.

**Comment by Flawmaster** [comment]
Спасибо!

**Comment by SBProX** [comment]
Done
