### ISSUE TITLE
Ошибка сортировки по столбцу "Price" в окне "Price rating"

### ISSUE THREAD

**Issue by uzziahmogg** [SBProX/SBProX-Dev#550]
При попытке отсортировать таблицу с результатом выдачи по столбцу "Price" в окне "Price rating", таблица показывает результат, осортированный по столбцу "Price" (см скриншот "Price rating -- 1.png"), через 2 секунды самостоятельно переключается на сортировку по столбцу "Volume" (см скриншот "Price rating -- 2.png").

![Price rating -- 1](https://user-images.githubusercontent.com/39528065/63856796-25aa0200-c9ab-11e9-9db7-e85f25185103.png)
![Price rating -- 2](https://user-images.githubusercontent.com/39528065/63856794-25116b80-c9ab-11e9-924e-6a85476217e9.png)

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении
