### ISSUE TITLE
Индикатор Claster search

### ISSUE THREAD

**Issue by Pro-metey** [SBProX/SBProX-Dev#552]
Предлагаю в индикаторе  Claster search сделать объединение ценовых уровней по выбранному значению. Пример: меня интересует сумма горизонтального  объема на трех уровнях.
Данная функция реализована в платформе ATAS.

**Comment by Expert-ks** [comment]
плюсом будет если еще и прикрутят выбор диапазона значений

**Comment by SBProX** [comment]
Мы не будем усложнять плаформу, извините.
