### ISSUE TITLE
Баг в последовательной загрузке вкладок

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#556]
Уважаемые разработчики, обнаружился баг в последовательном алгоритме загрузки вкладок.
![image](https://user-images.githubusercontent.com/50597350/64108199-e9005100-cd84-11e9-827e-b24dbd23c197.png)

Кроме того, после обновления, при параллельном алгоритме загрузки страниц , платформа стала загружаться ощутимо дольше. С чем это может быть связано?

**Comment by SBProX** [comment]
@vasiliyyun Проверим

**Comment by SBProX** [comment]
Исправили, сегодня выйдет обновление.

**Comment by SBProX** [comment]
Можете сообщить ваш логин и имя workspace, чтобы мы могли проверить.

**Comment by SBProX** [comment]
Проверьте сейчас
