### ISSUE TITLE
Баг в отображении High и Low бара.

### ISSUE THREAD

**Issue by sbprosupport** [SBProX/SBProX-Dev#558]
Баг с отображением High и Low бара присутствует. Пропадает High и Low бара при масштабировании графика по временной и/или ценовой шкале. Более явно заметно на более волатильных инструментах, типа NQ, а также на больших таймфреймах.

![Screenshot_862](https://user-images.githubusercontent.com/50356876/64124845-d3088580-cdb0-11e9-8ab4-7b4eb95f6117.png)
![Screenshot_864](https://user-images.githubusercontent.com/50356876/64124846-d3088580-cdb0-11e9-957e-287f749cfc19.png)

**Comment by SBProX** [comment]
Наверное Вы имели в виду Open-Close.
Исправили, спасибо. Можете обновиться.
