### ISSUE TITLE
Ошибка в отображении баров в последнем обновлении

### ISSUE THREAD

**Issue by Toska13** [SBProX/SBProX-Dev#559]
Уважаемые разработчики. В результате последнего обновления и устранения ошибки в отображении открытия/закрытия баров теперь при уменьшении масштаба вообще не отображаются цены открытия и закрытия - график просто невозможно смотреть, так как это просто набор палок. Исправьте пожалуйста.

**Comment by Toska13** [comment]
<img width="1920" alt="2019-09-02_20-16-00" src="https://user-images.githubusercontent.com/54317515/64128331-abb8b500-cdbe-11e9-8c8a-0eac58aa59db.png">

**Comment by SBProX** [comment]
Так уже исправили. Обновитесь.
