### ISSUE TITLE
Ошибка в отображении баров

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#561]
Здравствуйте, вместо баров OHLC, отображаются только HL
https://gyazo.com/02f141d98663b684872ac214fb72d43f

**Comment by SBProX** [comment]
Это уже было исправлено в последнем обновлении

**Comment by SBProX** [comment]
У вас обновление от какого числа?
![Screenshot_5](https://user-images.githubusercontent.com/16720120/64175244-95b10000-ce63-11e9-8dc5-dc765e82d90f.png)

**Comment by SBProX** [comment]
Если у вас проблема не исчезла, откройте тикет заново.
Пока что будем считать что проблема решена.
