### ISSUE TITLE
Баг в режиме "кластер профиль"

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#563]
Уважаемые разработчики. Заметил, что при масштабировании графика в режиме кластер-профиль, на начальном* масштабе цифры в кластере как бы обрезаны по верхам. 
*Под начальным масштабом, я имею ввиду увеличение на один шаг от масштаба при котором цифры еще не видны. Привожу скрины для наглядности.
![image](https://user-images.githubusercontent.com/50597350/64165418-be2dff80-ce4d-11e9-92df-da4669025490.png)
![image](https://user-images.githubusercontent.com/50597350/64165493-e61d6300-ce4d-11e9-84e5-3a7fe69bd541.png)

**Comment by SBProX** [comment]
Можете сохраниться template/шаблон в таком виде - назвать нам ваш логин в платформе и название шаблона. Мы загрузим ваш шаблон с сервера и проверим.
У нас на масштабе +1 от масштаба при котором не виден текст такой результат:
![Screenshot_6](https://user-images.githubusercontent.com/16720120/64339747-5b736a00-cfed-11e9-9cfe-9eed24c7cfc4.png)

**Comment by vasiliyyun** [comment]
vasiliy.yun@yandex.ru
Название шаблона CL M5

**Comment by SBProX** [comment]
Подправили как смогли, проверите в сл. обновлении.
