### ISSUE TITLE
Обращение в разработчикам. Крик души!=)

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#564]
Коллеги, приветствую! Можно поинтересоваться логикой порядка выпускаемых обновлений? Дело в том, что на форуме огромное количество действительно полезных предложений, а также замечаний по работе платформы (например, косяки с масштабированием графика). Т.е. есть огромное количество замечаний по работе платформы, которые реально мешают и создают неудобства при ее использовании. Вместо того, чтобы работать над этими улучшениями, уже два-три обновления выходят с непонятными доработками, которые и раньше не оказывали никакого неудобства в работе с платформой. Я не спорю, они тоже нужны, но ведь они не настолько приоритетны. Я, как торгующий трейдер, который использует Вашу платформу как незаменимый инструмент позволяющий в том числе зарабатывать, искренне недоумеваю, зачем было тратить столько времени на изменение логики загрузки страниц. Какая вообще разница как они загружаются?? Как мне это поможет улучшить свою торговлю, заработать больше???? Вместе с тем, например, я использую более 4 инструментов, мне не хватает цветов для их линковки (такое предложение есть), я работаю c high/low свечей, и мне хотелось бы упростить нанесение линий на эти значения (такой пост тоже есть #547). Т.е. в целом хотелось бы, чтобы в первую очередь выходили обновления с улучшениями/исправлениями того функционала, который реально нужен в торговле, чтобы иметь пусть небольшое, но преимущество в рынке. Пожалуйста, сделайте что-нибудь с этим. Я больше месяца назад писал о том, что у Вас сломалась прежняя логика масштабирования графика, вот это мне реально мешает работать с платформой. Мне абсолютно безразлично как поздно будут улучшены эстетические моменты платформы, потому как это никак не поможет мне заработать денег. Но зато мне крайне важно наличие в платформе дополнительных инструментов для анализа (акции и валюта). 
Извините за столь эмоциональный комментарий, но думаю мое мнение разделят многие трейдеры, которые используют Вашу платформу для заработка, а не рисования в ней.

**Comment by affectus1** [comment]
Согласен! И поддержу. Сам предлагал увеличить кол-во параметров в боксах т.к торгую по боксам и.т.д. Но обновления которые выходят вгоняют в ступор((( например опция отключения/включения закруглений на динамических профилях(((

**Comment by SBProX** [comment]
Вы смотрите только со своей точки зрения, мы же смотрим со стороны всего проекта.

1. Глобально, приоритет на данный момент - это исправление ошибок и каких-то недочетов.
Из репозитория отбираются ошибки и замечания, и исправляются. Порядок решаем мы, учитывая технические моменты, нет смысла это объяснять вам как пользователю.

2. После того как основная масса ошибок и недочетов будет исправлена, и не будет существенных нареканий - будут уже реализовываться предложения из репозитория.
Очередность их выполнения будет зависеть от сложности реализации и от степени "интереса" к тому или иному предложению.

Не раньше этого.

### Теперь касательно вашего основного тезиса:

> Я не спорю, они тоже нужны, но ведь они не настолько приоритетны.
**Это для вас не приоритетны.** А для нас - наоборот. Так как есть много пользователей, у которых много окон, в каждом окне очень много вкладок, потом еще на каждой вкладке куча индикаторов (например Cloud, который рассчитывается из тяжелых тиковых данных), и при этом, **у пользователей не много оперативной памяти.**
При обычной загрузке платформа у таких пользователей просто вылетала из-за нехватки операвной памяти.
**_Почему это не должно быть приоритетной проблемой для нас?_**
Поэтому мы и сделали алгоритм поочередной загрузки графиков, чтобы платформа не вылетала.

Второй момент - у нас нет армии программистов, поэтому мы делаем все постепенно.
Не нужно нас ругать за то, что что-то там не делается - если задача есть в репозитории и она нам одобрена - значит будет сделана.

**Comment by SBProX** [comment]
> Согласен! И поддержу. Сам предлагал увеличить кол-во параметров в боксах т.к торгую по боксам и.т.д. Но обновления которые выходят вгоняют в ступор((( например опция отключения/включения закруглений на динамических профилях(((

Читайте комментарий выше.

**Comment by SBProX** [comment]
Тикет закрываем, и пожалуйста больше не создавайте подобных, чтобы не разводить тут негатив.
Мы сами знаем как, что и когда нам делать.
Спасибо за замечения.

**Comment by SBProX** [comment]
@vasiliyyun Еще касательно вашего сообщения: мы видим общую картину по проекту, и пока что для нас важно чтобы у всех пользователей платформа РАБОТАЛА идеально. Имеется в виду - без ошибок. Пока что это наша цель, а не сделать примагничивание линий к High Low.

Вы же видите только то, что интересно вам - это логично, и понятно.
Но вы не видите тех проблем которые есть при сценариях использования, которые отличаются от ваших. И поэтому мы хотим довести платформу до такого состояния, чтобы при ЛЮБЫХ сценариях использования, платформа хорошо работала и не было сбоев. В том числе и на серверной части, которая так же важна.

Надеемся что дали развернутый ответ.

**Comment by vasiliyyun** [comment]
Спасибо за развернутый комментарий! Очень надеюсь, что Вам удастся исправить все недочеты в самое ближайшее время.
