### ISSUE TITLE
Вопрос по загрузке

### ISSUE THREAD

**Issue by dennndy** [SBProX/SBProX-Dev#565]
При загрузке разных таймфреймов заметил такую особенность, все графики грузятся из кеша, а недельку тянет с тиков, что значительно увеличивает нагрузку на проц и время загрузки самого графика
![sb](https://user-images.githubusercontent.com/52349547/64183000-d1eb5d00-ce71-11e9-8530-fe6c878212c7.PNG)
![sp_w](https://user-images.githubusercontent.com/52349547/64183010-d3b52080-ce71-11e9-9cba-1c10dd56dc93.PNG)
И еще, если графики залинкованы, то при изменении и применении изменения на одном графике , почему-то меняет начальную дату загрузки графика, на ту с какого были применены изменения. Очень неудобно если меняешь что--то на дневке и при этом 
подгружается год на тиковый график.

**Comment by SBProX** [comment]
Значит у вас на недельке стоят какие-то индикаторы или фильтры, которые используют тиковые данные.

**Comment by SBProX** [comment]
При линковке даты меняются, это функционал линковки. Все залинкованные графики имеют одинаковые даты.

**Comment by dennndy** [comment]
> 
> 
> Значит у вас на недельке стоят какие-то индикаторы или фильтры, которые используют тиковые данные.

действительно перекопал все настройки, в результате стояло значение мин тика...
