### ISSUE TITLE
Мелочи по учшению

### ISSUE THREAD

**Issue by dennndy** [SBProX/SBProX-Dev#566]
На горизонтальных линиях шрифт цены почему-то меньше чем на самой ценовой шкале.
![line](https://user-images.githubusercontent.com/52349547/64188868-e3d1fd80-ce7b-11e9-9fc3-1338a57707f2.PNG)
Если увелить толщину линии она сливается с текстом описания, неплохо было-бы поднимать текст над линией при увеличении толщины линии.
![texy](https://user-images.githubusercontent.com/52349547/64188980-1e3b9a80-ce7c-11e9-82e3-4f0c37baf28d.PNG)

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении
