### ISSUE TITLE
Горизонтальная линия - исчезает.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#567]
Здравствуйте.

При нанесении горизонтальной линии 28 числа - для того чтобы видеть эту горизонтальную линию необходимо чтобы было всегда открыто 28 число.

Если открыть start_29 end_29 число линия исчезнет.
Если открыть 27 число и предыдущие числа - линия останется.

![image](https://user-images.githubusercontent.com/20509322/64226531-5b526c00-cf12-11e9-85f8-d1ddf3ee5d44.png)

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
