### ISSUE TITLE
Изменение толщины линий при масштабе графика

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#568]
Уважаемые разработчики, приветствую! В пику темы мелких недочетов, заметил такую вещь. При одинаковом масштабе графика в режиме свечей и кластер-профиль, толщина линий разнится. Так, в режиме свечей, изначально заданная толщина линий не меняется при любом масштабе, а вот в режиме кластер-профиль, изначально заданная толщина линий увеличивается при увеличении масштаба графика. Ниже приведены скрины. Масштаб графика в режиме свечей и режиме кластер-профиль одинаковый, обратите внимание на толщину линий. 
![image](https://user-images.githubusercontent.com/50597350/64247520-b9358280-cf17-11e9-8e7a-7cc31b648b60.png)
![image](https://user-images.githubusercontent.com/50597350/64247542-c3578100-cf17-11e9-80d5-ab3b09e2b831.png)

**Comment by vasiliyyun** [comment]
Вопрос. Можно ли сделать так, чтобы при любом масштабе и в любых режимах графика, изначально заданная толщина линий оставалась неизменной?

**Comment by SBProX** [comment]
Сделали все линии одинаковые, вне зависимости от типа графика.
Будет работать в сл. обновлении.

**Comment by Fen8fen** [comment]
![image](https://user-images.githubusercontent.com/20509322/65652973-284d5500-e046-11e9-863f-1712144987eb.png)

SbPro здравствуйте.
Посмотрите на скриншот с линиями. 
Я против такого обновления. 
Если раньше в зону линии попадал объем и его спокойно можно рассмотреть  то сейчас с шириной линии 10 линия заполняет кластер наполовину. если выбрать яркий цвет то становится не читаемым значение кластера......

**Comment by Fen8fen** [comment]
Я готов от обновления откатиться лишь бы таких линий не было....

Эту опцию с одинаковыми линиями для всех типов графиков нужно тогда сделать опционально.
Я за логически комфортную работу платформы. 
А не за то чтобы говорить тут узкие там толстые линии да еще и наполовину кластер закрывают.

**Comment by Bolt022** [comment]
> Я готов от обновления откатиться лишь бы таких линий не было....
> 
> Эту опцию с одинаковыми линиями для всех типов графиков нужно тогда сделать опционально.
> Я за логически комфортную работу платформы.
> Если например была бы возможность выбрать значение 20 и это заполнит кластер с линией полностью то тогда проблема будет решена, или в chart settings - general - line - добавить галочку full cluster line как в предыдущем обновлении.

согласен... тепер график кривущий с.ка... линии с кластерами не совпадают еще больше! пзд

**Comment by SBProX** [comment]
> Я готов от обновления откатиться лишь бы таких линий не было....
> 
> Эту опцию с одинаковыми линиями для всех типов графиков нужно тогда сделать опционально.
> Я за логически комфортную работу платформы.
> Если например была бы возможность выбрать значение 20 и это заполнит кластер с линией полностью то тогда проблема будет решена, или в chart settings - general - line - добавить галочку full cluster line как в предыдущем обновлении.

Ок, вернем в виде галочки.

**Comment by Flawmaster** [comment]
Я думаю, что народ просил сделать линии одинаково широкими, т.е., чтобы и на баровом графике, например линия была ровно 1 тик. А в таком виде как сейчас поменяли - линии стали бесполезны, т.к.  из-за того, что непонятно где чертится линия, то приходится постоянно уточнять на другом графике. Кстати, на сильно сжатом кластерном графике очень большое несовпадение кластера, линий и прямоугольников. Иногда кажется, что это несовпадение доходит до 1 тика. Визуально некрасиво и постоянно сбивает с толку. Если необходимо выложу скриншот. Уважаемые разработчики, исправьте, пожалуйста линии, а также несовпадения (как линий с кластерами, так и прямоугольников), т.к. на данный момент это самые раздражающие аспекты в программе.

**Comment by SBProX** [comment]
@Fen8fen @Flawmaster Только что откатили обратно, можете обновиться.

**Comment by SBProX** [comment]
@Bolt022 

Согласны, много недочетов.
Работаем, будем стараться тестировать тщательнее.
Спасибо.

**Comment by Flawmaster** [comment]
Спасибо!

**Comment by r35p3ct** [comment]
Только обрадовался адекватности размерности линий, как откатили обратно :(

**Comment by SBProX** [comment]
@r35p3ct мы не можем подстроиться под всех, к сожалению.
Нам лично первый вариант больше нравится, и мы не одни такие.
