### ISSUE TITLE
Link не работает если больше 10 вкладок в workspace

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#569]
Здравствуйте.

Уважаемые разработчики проверьте пожалуйста опцию Link.

Откройте два графика - активируйте Link (закрасится кружок) в двух окнах - нажмите Exit - Tools bar развернут- снова запустите платформу.

- Link все еще будет активным но, кружки не будут закрашены. 
- Посмотрите логику работы окон в таком режиме.
у меня в выборе инструмента вместо РТС поставился 6А инструмент.

**Comment by Fen8fen** [comment]
Update:

Проблема с Link начинается после того как вкладок становится больше 10 (появляется окно о последовательной загрузке) и во всех окнах link становятся не активны кружки.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении
