### ISSUE TITLE
График: масштабирование

### ISSUE THREAD

**Issue by 220vlt** [SBProX/SBProX-Dev#57]
**Проблема:** при масштабирование (**прокрутке средней кнопки мышки**) от самого приближенного масштаба до самого отдаленного масштаба не соблюдается пропорция по высоте.

Приближенный:
![Screenshot_1](https://user-images.githubusercontent.com/31524209/57494855-fd9b7380-72d3-11e9-83f0-b6ae62331266.jpg)

Отдаленный:
![Screenshot_2](https://user-images.githubusercontent.com/31524209/57494867-0d1abc80-72d4-11e9-8e04-f48c1fb028cb.jpg)

Регулировка **Шкала цены** для нормализации графика:
![Screenshot_3](https://user-images.githubusercontent.com/31524209/57494900-2e7ba880-72d4-11e9-9b31-12e9f27b0547.jpg)

**Comment by Artem074** [comment]
Да, тоже заметил такое... постоянно крутить-вертеть приходиться.

**Comment by vasiliyyun** [comment]
Поддерживаю, такой момент наблюдается и со свечным графиком. При масштабировании колесиком от самого маленького до того масштаба с которым работал, возврат в рабочий масштаб происходит с несоблюдение изначально отстроенной высоты. Ниже скрины
https://monosnap.com/file/vu1UgTuvRnnZrmo9vip3ERrJLq8R5X
https://monosnap.com/file/pU8TrrQ0FZ1PL5wjVQluSQbeqBUYfi
https://monosnap.com/file/32ru5pqFHelQoZnIkzZJQsrwv5hkGe

**Comment by SBProX** [comment]
Исправили.
