### ISSUE TITLE
Некорректно работает фильтр объема в кластер-профиле

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#570]
Уважаемые разработчики, заметил такую вещь. В настройках графика кластер-профиль, мной установлен фильтр на объем 5000 и подсветка желтым цветом. Однако подсвечивается данный объем через раз. С чем это может быть связано?
![image](https://user-images.githubusercontent.com/50597350/64324705-8058e480-cfcf-11e9-8227-32cd277c062a.png)
![image](https://user-images.githubusercontent.com/50597350/64324749-9797d200-cfcf-11e9-9ae7-2a54359a3ce8.png)
![image](https://user-images.githubusercontent.com/50597350/64324777-a8484800-cfcf-11e9-8ad7-bd8cfc0b872b.png)

**Comment by SBProX** [comment]
Добрый день.

1. Фильтры необходимо указывать в порядке убывания. Сначала 10000 потом 5000.

2. На последнем скриншоте у вас не закрашен объем фильтром, так как он является максимальным. Чтобы фильтры перекрывали макс. объемы нужно установить галочку "Фильтры над максимальным объемом".

Все это описано в инструкции https://www.manula.com/manuals/sbprox/sbprox-manual/1/ru/topic/3-2-2
