### ISSUE TITLE
Max V внутри профилей.

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#572]
Max V внутри профилей играет свою роль при ловле лучшей точки, на мелких фреймах, открытия позиции, с точки зрения уменьшения просадки, поэтому его видимость, в тактическом плане, весьма актуальна. Как он отображается в платформе?
Вот max V внутри профилей (кстати, этот же скрин хорошо показывает как текст "забивает"\скрывает мелкие объёмы, их тут видно очень плохо, это к тикету 536 [п.1](https://github.com/SBProX/SBProX-Dev/issues/536))
![Max объёмы](https://user-images.githubusercontent.com/33456972/64323967-ef8a0500-cfde-11e9-8da2-279ab909ca69.png)
 
Но почему при сжатии графика **max V внутри профилей исчезают вместе с текстом**: 
![Нет мax объёмов](https://user-images.githubusercontent.com/33456972/64324073-1ba58600-cfdf-11e9-96a8-3bcca5bde986.png)
Почему отображение max V внутри профилей **привязано** к отображению текста? 
Понятно что при определённом сжатии графика текст отображать просто нет смысла поскольку он становится нечитаемым, но при чём тут показ max V внутри профилей?  При таком сжатии как на 2-м скрине вполне можно показывать max V внутри профилей, хотя текст там уже не читался бы.

**Предлагаю сделать видимость max V внутри профилей при как можно большем сжатии, по оси времени**, не в ущерб читаемости графика и независимо от показа текста. Тут надо будет найти некую "золотую середину." 

То же самое надо сделать и при сжатии по оси цены.
![Screenshot](https://user-images.githubusercontent.com/33456972/64326052-b2277680-cfe2-11e9-8220-f13ef6c0efcc.png)
Вот пример когда график на весь экран монитора но, max V внутри профилей не показаны, хотя размер кластеров вполне позволяет их отобразить. При том что текст, в этом случае, был бы нечитаем.

**Comment by X-man77** [comment]
Забыл на писать - в режиме **box chart** также **необходимо видеть max V внутри профилей!**

**Comment by SBProX** [comment]
Скрывается только рамка, а не макс. объемы.
Макс. обьемы никуда не пропадают, у вас на скриншотах так фильтры настроены.

Вот пожалуйста:
![Screenshot_1](https://user-images.githubusercontent.com/16720120/65618779-8edf5e00-dfc7-11e9-9d91-bc7efbbb15c9.png)

Макс. объемы на месте.
А рамки не рисуются, так как при низком масштабе они будут очень мелкие и будут захламлять график.
