### ISSUE TITLE
Очень важный инструмент 

### ISSUE THREAD

**Issue by Evgen955218** [SBProX/SBProX-Dev#574]
Меня волнует инструмент 10-Year T-Note Futures Quotes (Казначейские облигации) , скажите пожалуйста сможете ли Вы их добавить в аналитическую платформу ,и когда ??? ОЧЕНЬ НЕ ХВАТАЕТ в анализе и настроения рынков !)

**Comment by SBProX** [comment]
Пока что не можем добавить, сначала мы исправим все ошибки, потому будем заниматься добавление новых инструментов.
