### ISSUE TITLE
Критическая ошибка в отображении графика через коннектор QUIK

### ISSUE THREAD

**Issue by ghost** [SBProX/SBProX-Dev#58]
Добрый день!
На протяжении всей торговой сессии появляется критическая ошибка с отображением данных через коннектор QUIK (что-то типо дублирования свечей.....если загружу программу в середине сессии, то продублируется половина первой сессии. т.е. до того момента как была загружена программа). Тем самым искажается информация по объемам, дельте и другим параметрам.

![2019-05-10_120234](https://user-images.githubusercontent.com/50441291/57509116-de750400-731c-11e9-8e6f-ffe975595bdf.png)
![2019-05-10_121042](https://user-images.githubusercontent.com/50441291/57509117-de750400-731c-11e9-9399-71ffb41466fe.png)

**Comment by Artem074** [comment]
Проходит чуть больше времени, нажимаю "Применить" и снова дублирование... только уже той части, после которой нажал "применить".
![2019-05-10_121525](https://user-images.githubusercontent.com/50441291/57509301-54796b00-731d-11e9-9d42-9779facc29f8.png)

**Comment by Artem074** [comment]
Исправьте проблему, а то ваш сервак порой сильно тормозит!

**Comment by Artem074** [comment]
Ну и пример с середины сессии... котировка идёт при подключении, НО дубляж данных остаётся...
![2019-05-10_150030](https://user-images.githubusercontent.com/50441291/57519623-2b64d480-7335-11e9-8374-e4d58e0efcc1.png)

**Comment by Artem074** [comment]
Добавлю ещё один момент... как только подключился через коннектор Quik, котировка нормально идёт, дубляж виден и он остаётся, НО только той части, которая была до подключения... потом нет дублирования, но по левой шкале искажение инфы идёт, как и писал ранее! Это происходит на графиках вплоть до дневных баров (не включительно!).
![2019-05-13_130541](https://user-images.githubusercontent.com/50441291/57605752-cd2c3180-7580-11e9-9a50-98b931c85480.png)

**Comment by Artem074** [comment]
> Ну и пример с середины сессии... котировка идёт при подключении, НО дубляж данных остаётся... Разница есть с вышеуказанными картинками (что дублируется), т.к. в текущем случае, я заново загружал программу, а не нажимал "Применить".
> ![2019-05-10_150030](https://user-images.githubusercontent.com/50441291/57519623-2b64d480-7335-11e9-8374-e4d58e0efcc1.png)

только странно, что на этой картинке из середины сессии только одно начало котировки, на остальных начало дублируется и их 2, т.е. тут дублируется с середины...

**Comment by makhitrov** [comment]
Объясните пожалуйста кто нибудь, какой смысл подключаться через коннектор, если торговля в терминале все равно не доступна?

**Comment by Artem074** [comment]
> Объясните пожалуйста кто нибудь, какой смысл подключаться через коннектор, если торговля в терминале все равно не доступна?

Выше причина была указана.

**Comment by Bolt022** [comment]
заметил тоже самое

**Comment by SBProX** [comment]
Следующие обновления будут посвящены исправлению данных багов, и других.
