### ISSUE TITLE
некорректная работа профиля на графиках типа Line

### ISSUE THREAD

**Issue by weeclemans** [SBProX/SBProX-Dev#580]
![2019-09-07 10_04_47-6E Tick Line Real-Time Data_ 0 ticks](https://user-images.githubusercontent.com/5346038/64470636-c50f8780-d157-11e9-8310-b26d7fa61759.png)

при выделении необходимого участка профиль берется с самого первого тика на графике

**Comment by SBProX** [comment]
Спасибо, исправим.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении
