### ISSUE TITLE
Функция торговли с помощью  quik и transaq

### ISSUE THREAD

**Issue by Pasha5729** [SBProX/SBProX-Dev#582]
Здравствуйте. Во первых хотел поблагодарить за функцию в симуляторе начало истории, я не знаю потому ли, что я просил добавить или вы сами так решили, но я просил, хотя сказали, что делать не будут.  Спасибо огромное. Хотелось бы, если можно, функцию торговли с помощью  quik и transaq (мне лично transaq  нужен).

**Comment by WillBegin1** [comment]
Поддерживаю

**Comment by Bolt022** [comment]
> Поддерживаю, transaq connector. Я даже уверен в том, что после реализации данной возможности очень много людей торговали бы через вашу платформу!

Qscalp 5 в помощь... работает шустро через транзак конектор, быстрей даже чем через QUIK.

**Comment by X-man77** [comment]
Поддерживаю торгоый модуль через QUIK. В принципе торг.модуль есть в симуляторе, надо только малёхо допилить его (что именно надо есть тикеты) и дописать скрипт подключения для передачи ордеров. Всего делов.

P/S/ **Bolt022** как можно связаться с тобой по e-mail. Личных сообщений здесь, увы, нет.

**Comment by WillBegin1** [comment]
> > Поддерживаю, transaq connector. Я даже уверен в том, что после реализации данной возможности очень много людей торговали бы через вашу платформу!
> 
> Qscalp 5 в помощь... работает шустро через транзак конектор, быстрей даже чем через QUIK.
> Из привода сделки в PirateTrade (журнал сделок) и готово ))
> Да и пока не стал бы доверять этой проге торговлю из-за постоянных сбоев серверов. Для анализа годится.

Зачем же pirate trade есть Статистика Трейдера http://marketstat.ru/partner/willbegin

**Comment by SBProX** [comment]
Мы не будем делать торговый функционал в платформе, это 100%.
