### ISSUE TITLE
Некорректная работа увеличителя графика при добавлении линии

### ISSUE THREAD

**Issue by AlTuzov** [SBProX/SBProX-Dev#583]
Добрый день!
Заметил баг в работе увеличителя графика.
При добавлении линии и включенном увеличителе графика, увеличитель перемешается только по горизонтали, вертикально движение увеличителя не работает. Видео с багом в архиве.
[Video_2019-09-07_171026.zip](https://github.com/SBProX/SBProX-Dev/files/3586680/Video_2019-09-07_171026.zip)
.

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении.
