### ISSUE TITLE
Вкладки с графиками в одном окне

### ISSUE THREAD

**Issue by UrfinJus** [SBProX/SBProX-Dev#584]
Необходимо следить за несколькими графиками сразу, для этого есть "Новое окно графика", но:
Во-первых, новые окна отделены от рабочего пространства(рп) и если не сохранил шаблон или правильно не закрыл РП, то при следущем запуске эти окна просто не загружаются;
Во-вторых, можно ли сделать как в квике - в одной вкладке несколько окон с графиками?
Скрин: https://yadi.sk/i/vQ68IMyc0jSHHQ
В-третьих, текущая система с "Новое окно графика" не удобна тем что плодит много вкладок на панели. Да, можно их сгруппировать, но когда перекрывается одно из нужных окон потом его затруднительно найти.
Скрин: https://yadi.sk/i/okW5sDSJceQB5Q
В-четвертых, при выходе из программы надо закрывать каждый график отдельно, причем сначала созданные окна и в конце РП, без сохранения настроек, иначе при следующем запуске они автоматически не загрузятся...

Возможно у вас уже есть эта функция, однако в мануале ничего кроме "Новое окно графика" не нашел. В остальном программа просто супер!

**Comment by Mimilun** [comment]
Могу подсказать как правильно сохранять. Нажимаете правой мышкой в любом окне и выбираете "выйти из SB-Pro" и на вопрос про изменения в РП нажимаете ДА. Все окна и вкладки в них сохраняться со всеми изменениями.

**Comment by UrfinJus** [comment]
> 
> 
> Могу подсказать как правильно сохранять. Нажимаете правой мышкой в любом окне и выбираете "выйти из SB-Pro" и на вопрос про изменения в РП нажимаете ДА. Все окна и вкладки в них сохраняться со всеми изменениями.

О, чудо чудесное, спасибо за совет!
