### ISSUE TITLE
Смещение текста  у времени бара

### ISSUE THREAD

**Issue by RoketAnny** [SBProX/SBProX-Dev#585]
можно сместить текст чтобы он не накладывался на квадратик линии. Отслеживал 10 ТФ и цена топталась на этом уровне, постоянно скрывая текущее время

![image](https://user-images.githubusercontent.com/18662109/64515334-11dc9500-d2f5-11e9-8a87-a4a6685be2b1.png)

**Comment by vpaks** [comment]
Поддерживаю, сильно раздражает.

**Comment by SBProX** [comment]
Поправим.

**Comment by SBProX** [comment]
Куда именно сместить? 
По центру - странно.
Слева - тогда будет накладываться на профайл графики.

**Comment by RoketAnny** [comment]
Может вот так
![image](https://user-images.githubusercontent.com/18662109/65662113-123a9700-e03c-11e9-9400-b4679dc3861b.png)

**Comment by SBProX** [comment]
Сделано
