### ISSUE TITLE
Симулятор доработать. Смена шага  во время воспроизведения симулятора

### ISSUE THREAD

**Issue by Pasha5729** [SBProX/SBProX-Dev#586]
Из-за того что меняется волатильность свечей от сессии к сессии, изо дня в день, использовать кластерпрофиль и тому подобное крайне проблематично, надо менять шаг цены, чтобы свеча не была, то фиг знает где, за пределами дисплея, или необходимо шаг уменьшить потому, что свечи маленькие теперь. При частой смене волатильности очень тяжело так торговать. Сделайте, пожалуйста, чтобы можно было находу менять шаг в плеере, чтобы график, на котором меняется шаг, снова загружался до той секунды, которая была, за одно очень неплохо было бы смену таймфрейма также реализовать.

**Comment by SBProX** [comment]
К сожалению технически это не возможно, график строится по тому шагу, который был установлен до старта симулятора. На ходу менять не получится, будут куски графика с разным шагом цены.
