### ISSUE TITLE
Добавление в платформу торговых инструментов

### ISSUE THREAD

**Issue by linkoln248** [SBProX/SBProX-Dev#588]
Добрый день! 

Возможно ли добавление в новую платформу дополнительных торговых инструментов? Интересует в частности не особо популярный за пределами США фьючерс с тикером ZB (30 Year US Treasury Bond), торгуемый на бирже ECBOT. Спасибо за ответ.

**Comment by SBProX** [comment]
На данном этапе невозможно.
