### ISSUE TITLE
Сигнал для комбинации баров

### ISSUE THREAD

**Issue by Labama** [SBProX/SBProX-Dev#590]
Просьба реализовать сигнал на настраиваемую комбинацию баров.

Пример  условия для  сигнала:
1. Бар закрывается, его направление вверх. Максимальный объем бара ниже середины. 
2. Предыдущий бар направлен вниз. Максимальный объем ниже или равен цены закрытию.
3. Бар перед предыдущим направлен вниз. Максимальный объем ниже середины.

**Comment by r0b4ik** [comment]
Сильно сомневаюсь, что в ближайшее время в СБ таку. функцию реализуют. Есть готовая система сигналов, которая делает это. Если интересно - пиши в телеграм @discretionary_trader

**Comment by SBProX** [comment]
@r0b4ik правильно сомневаетесь, пока делать не будем, нет желания усложнять софт.
