### ISSUE TITLE
ГОРИЗОНТАЛЬНЫЕ ЛИНИИ УЛУЧШЕНИЕ

### ISSUE THREAD

**Issue by SeregaTS22** [SBProX/SBProX-Dev#593]
Здравствуйте, хочу предложить вам реализовать такую идею, вы добавили ширину 10 в горизонтальных линиях, мне кажется гораздо удобнее что бы ширина линии мерялась в тиках как в волфикс а не в пикселях или что там, получается когда наносим горизонт линию у нас есть возможность сделать из нее зону ну скажем шириной в 10 тиков а вторую шириной  5 тиков к примеру, а то сделал 10 ширину и ее не видно на футпринте какая там ширина только на свечах, а наносить линии шириной 5 тик потом зону строить слишком долго и не удобно

**Comment by 11-12** [comment]
Уменьшить бы еще количество действий при расцвечивании линий. Например убрать кнопку Ок, Сейчас, к примеру, чтобы поменять цвет линии, нужно произвести кучу действий, после выбора цвета нужно его подтвердить - зачем? Потом еще нужно щелкать по самой линии, чтобы снять выделение. Это излишне и утомительно.

**Comment by SeregaTS22** [comment]
ну да есть такое для какого то несложного действия нужно проделать сложные манипуляции хотелось бы проще

**Comment by SBProX** [comment]
Мы придумаем как реализовать диапазоны для линий, то точно не так как вы предлагаете.
Линия это линия, со своей ценой. Зона это другое.
