### ISSUE TITLE
Настройки индикатора Cloud

### ISSUE THREAD

**Issue by 11-12** [SBProX/SBProX-Dev#594]
Уважаемые разработчики, в настройках индикатора Cloud не работает функция изменения прозрачности фигур, выделяющих максимальные объемы. Исправьте, пожалуйста.
И еще просьба сделать цвет нулевой дельты, в этом же индикаторе, регулируемым или просто ярче.

**Comment by SBProX** [comment]
Какие максимальные объемы в cloud?
Поясните пожалуйста на скриншоте.

**Comment by 11-12** [comment]
Здравствуйте! Скрин во вложении.


-- 
С уважением, Могилевич Игорь

**Comment by 11-12** [comment]
![Screenshot_65](https://user-images.githubusercontent.com/52030059/65125566-42f84c00-d9fe-11e9-90db-12c67b406c92.jpg)

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
