### ISSUE TITLE
Толщина линий по умолчанию

### ISSUE THREAD

**Issue by iz0t0pe** [SBProX/SBProX-Dev#597]
1. Предлагаю во вкладке Линии добавить пункт **Толщина линий по умолчанию**.
2. Дать возможность увеличить толщину больше, чем в 10 п. (хотя бы до 100), чтобы рисовать области одним кликом.

Скорее всего этот момент уже поднимался, но толстые линии показываются только на графике со свечами\барами и на линейном графике.
https://prnt.sc/p5m2t0
https://prnt.sc/p5m37h

**Comment by SBProX** [comment]
На кластерах толщина линий автоматическая.
Нельзя сделать толщину больше чем высота ячейки кластера!
