### ISSUE TITLE
Название гистограмм мешают их чтению

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#6]
Сделать возможность отключать название
![2019-05-06_16-24-36 (2)](https://user-images.githubusercontent.com/18483236/57241894-c3637500-703a-11e9-85cb-063d5163a49f.png)
![2019-05-06_16-43-54 (2)](https://user-images.githubusercontent.com/18483236/57241904-cbbbb000-703a-11e9-90a4-40f73a2e86a7.png)

**Comment by Ravil124** [comment]
Да, очень мешают.

**Comment by SBProX** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/16720120/57245435-8e0f5500-7043-11e9-9b9e-3fca0e0c1de5.png)

**Comment by SBProX** [comment]
Если вопрос решен, можете закрывать тикет.

**Comment by ershner** [comment]
Ok. Спасибо.
