### ISSUE TITLE
Программа некорректно работает через TRANSAQ Connector!

### ISSUE THREAD

**Issue by ghost** [SBProX/SBProX-Dev#60]
Другие программы коннектятся, а ваша - нет.
![2019-05-10_122111](https://user-images.githubusercontent.com/50441291/57509675-4bd56480-731e-11e9-8792-9f969923c418.png)

**Comment by Artem074** [comment]
Volfix нормально коннектится... и никаких серверов и портов не нужно указывать (только логин и пароль).
![2019-05-10_124152](https://user-images.githubusercontent.com/50441291/57510877-3f9ed680-7321-11e9-8c20-b5f81cf5c134.png)

**Comment by Artem074** [comment]
в Tiger Trade тоже коннектится и идут котировки...
![2019-05-10_143401](https://user-images.githubusercontent.com/50441291/57518444-7204ff80-7332-11e9-9f0a-565a5632fee2.png)

**Comment by Artem074** [comment]
Заметил разницу между настройками подключения вашей программы и другими... у них есть строка "Лог" или "System"... базово выбирается "стандартный"... может в этом проблема?!

**Comment by Artem074** [comment]
Проблему с подключением решил... нужно сначала отключиться от связки в другой программе, а то не пускает в параллельную... Но котировки стоят!!! Они не идут он-лайн!

**Comment by SBProX** [comment]
Спасибо, проверим все на следующей неделе.

**Comment by Bolt022** [comment]
аналогичная ситуация
