### ISSUE TITLE
Не удаляется текст

### ISSUE THREAD

**Issue by iz0t0pe** [SBProX/SBProX-Dev#600]
Если выбрать в тулбаре текст, нанести на график, но в в диалоговом окне сразу отменить создание, то на графике остается "Text", который никак не выделяется и не удаляется (даже через delete all drawing). Удалить можно если вновь повторить процедуру создания текста и при этом добавить на график.

**Comment by SBProX** [comment]
Спасибо, исправим.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении
