### ISSUE TITLE
Как включить сетку?

### ISSUE THREAD

**Issue by ragodnar** [SBProX/SBProX-Dev#601]
Добрый день!
Подскажите,как включить сетку на графике? (как в квике)
купил по 2 дня назад, не могу найти сетку
Разработчику респект

**Comment by iz0t0pe** [comment]
Никак. Максимум вертикальные линии дневные и вот такое вот короче https://prnt.sc/p61bio

**Comment by ragodnar** [comment]
эх...
спасибо 

> Никак. Максимум вертикальные линии дневные и вот такое вот короче https://prnt.sc/p61bio

**Comment by SBProX** [comment]
@ragodnar Это не место для тех поддержки, пишите на support@sb-professional.com
