### ISSUE TITLE
БАГ! При сужении графика вертикальные линии исчезают!!!

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#603]
![2019-09-15_112554](https://user-images.githubusercontent.com/51231827/64917633-f4ec0a00-d7ab-11e9-8021-41db80e35e7b.png)

**Comment by Bolt022** [comment]
...но когда наносишь новую линию, она еще пока остаётся...

**Comment by SBProX** [comment]
Линии остаются, проверили, ничего не пропадает.
Сообщите ваш логин и имя workspace, проверим.

**Comment by Bolt022** [comment]
> Линии остаются, проверили, ничего не пропадает.
> Сообщите ваш логин и имя workspace, проверим.

Разобрался, линии исчезают, если стоят на 10:00 (время), в остальных случаях они остаются при сужении графика.

**Comment by SBProX** [comment]
Проверим.
