### ISSUE TITLE
Как открыть несколько окон программы?

### ISSUE THREAD

**Issue by ragodnar** [SBProX/SBProX-Dev#604]
не вкладки, а окна чтоб были рядом, несколько графиков

**Comment by RoketAnny** [comment]
@ragodnar Меню - Новое окно графика

**Comment by ragodnar** [comment]
> @ragodnar Меню - Новое окно графика

ура!!!
спасибо

**Comment by SBProX** [comment]
Для вопросов у нас есть техническая поддержка support@sb-professional.com
