### ISSUE TITLE
Связанные вкладки

### ISSUE THREAD

**Issue by koreeichik** [SBProX/SBProX-Dev#607]
Хочу предложить сделать улучшение.
В каждом окне есть вкладки одного инструмента но с разными таймфреймом или видом
При нажатии на одном окне вкладке допустим РТС на других окнах также переключались на те же вкладки. Сделать эту функцию настраиваемой кому не надо не пользуется.

**Comment by SBProX** [comment]
Как это "переключались на те же вкладки"?
Вкладок может быть много одно и того же инструмента и одновременно в окне может быть только одна вкладка. Это как минимум не реализуемо, и не понятно зачем это нужно

**Comment by koreeichik** [comment]
Кто написал тому понятно, для чего и зачем. 
У меня в окнах распределения в одном окне 5 минут в другом окне 1 час 3 окно 1 день.
Чтобы не бегать по окнам и не переключать на один и тот же инструмент, а нажал и на одном окне остальные окна подчинили.
Я конечно не программист, но нет ничего не реализуемого.
