### ISSUE TITLE
В диалоге подтверждения удаления вкладки кнопка "Отмена" лишняя

### ISSUE THREAD

**Issue by uzziahmogg** [SBProX/SBProX-Dev#609]
В диалоге подтверждения удаления вкладки кнопка "Отмена" и кнопка "Нет" дублируют функциональность отмены удаления вкладки

![Confirm 2019-09-16 13 05 43](https://user-images.githubusercontent.com/39528065/64975744-6618e380-d8b8-11e9-8631-ad978a649719.png)

**Comment by SBProX** [comment]
Исправлено
