### ISSUE TITLE
Возможность регулирования прозрачности окна настроек симулятора

### ISSUE THREAD

**Issue by Pasha5729** [SBProX/SBProX-Dev#610]
Экран симулятора постоянно спереди, сжимается он до определенного минимума, у меня  19 дюймов экран. Два окна, фон и рабочий таймфрейм. И симулятор постоянно спереди, из-за него график фона очень плохо видно, я  часто нажимаю паузу, потому что скорость симулятора большая, а скорость секунду ставить я не собираюсь,я не хочу целый день сидеть. Пожалуйста, сделайте возможность регулировки прозрачности окна симулятора, а то он реально мешает, не видно нормально.

**Comment by SBProX** [comment]
Мы вынесем кнопки управления симулятором, но делать прозрачность окна - это слишком, и звучит не особо. Скорость симулятора измеряется в тиках.
