### ISSUE TITLE
Перемотка назад в симуляторе

### ISSUE THREAD

**Issue by Pasha5729** [SBProX/SBProX-Dev#611]
Бывает ситуация, ставлю на м1 скорость в 60, подходит цена к уровню, 3 секунды цена подошла к уровню и улетела далеко уже, во первых в симуляторе хотелось бы изучать, как формируется свеча возле уровня, а ставить скорость секунду и ждать когда там дойдет до уровня или экстремума в тренде,, легче застрелиться, поэтому скорость высокая у меня, иногда сигнал, не иногда, а часто пропускается, ну и не всегда закрытия свечи надо ждать, а иногда и раньше входить, как бы цену, а не свечи торгуем. Поэтому функция перемотки прекрасная вещь, зря вы ее не сделали. Сделайте, пожалуйста, эту функцию.  Я  попросил линковку в симуляторе ранее, вы сделали. Спасибо.

**Comment by SBProX** [comment]
Скорость измеряется не в секундах, а в тиках (трейдах).
Если стоит 60 - значит каждую секунду отбирается 60 трейдов.
Если хотите симуляцию как в реальном времени, можете выбрать 5-10-20.
Перемотку мы пока делать не будем, извините, есть другие задачи.
