### ISSUE TITLE
!!!!!!!!!!!!!ИНСТРУМЕНТЫ РИСОВАНИЯ !!!!!!!!!!!

### ISSUE THREAD

**Issue by SeregaTS22** [SBProX/SBProX-Dev#615]
![bandicam 2019-09-16 23-48-22-342](https://user-images.githubusercontent.com/54494083/64993499-e7836c80-d8de-11e9-99c1-000fdc478521.jpg)
бывает запаришься и все снесешь с графика сделайте пожалуйста дополнительный запрос на удаление, я думаю где удаление там должен быть этот запрос неважно что удаляется.

**Comment by X-man77** [comment]
Желательно опционально - где-нить в инструментах поставить чек-бокс -> галка стоит -> выходит запрос. Нет галки не запроса.

**Comment by SeregaTS22** [comment]
можно и так

**Comment by SBProX** [comment]
Лишние окна подтверждения - не удобно. 
Тяжело представить ситуацию, когда можно случайно нажать на кнопку удаления объектов.
Делать галочки - теперь для каждой мелкой функции галочку?
Вы же понимаете, что это галочек будет миллион.
Принципиально отклоняется, если такие случаи будут частые - тогда сделаем.
