### ISSUE TITLE
Ширина на ценовых горизонтальных линиях для красоты?

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#616]
![bandicam_2019-09-17_09-14-54-927](https://user-images.githubusercontent.com/51231827/65011260-533ff680-d92c-11e9-9caf-9bad8f3f3cce.gif)

**Comment by Bolt022** [comment]
Разобрался, толщина линии меняется только на графике со свечами\барами и на линейном графике. Это прикол такой что ли??? На одном графике работает, на другом нет. Дурдом.

**Comment by iz0t0pe** [comment]
> Разобрался, толщина линии меняется только на графике со свечами\барами и на линейном графике. Это прикол такой что ли??? На одном графике работает, на другом нет. Дурдом.

Че бомбишь то, если "Платформа имеет статус Beta и на данный момент проходит стадию тестирования и исправления ошибок."?

**Comment by SeregaTS22** [comment]
это хорошо что на стадии ИСПРАВЛЕНИЯ ОШИБОК про эту ошибку я писал уже два раза и что то все никак, ну будем надеяться на чудо что исправят и хотелось бы что б ширины добавили хотя бы до 30

**Comment by iz0t0pe** [comment]
чекайте https://www.sb-professional.com/servicepolicy. 


> это хорошо что на стадии ИСПРАВЛЕНИЯ ОШИБОК про эту ошибку я писал уже два раза и что то все никак, ну будем надеяться на чудо что исправят и хотелось бы что б ширины добавили хотя бы до 30

в любом случае, последнее слово за разрабами - захотят сделают, нет - нет.

**Comment by SeregaTS22** [comment]
> чекайте https://www.sb-professional.com/servicepolicy.
> 
> > это хорошо что на стадии ИСПРАВЛЕНИЯ ОШИБОК про эту ошибку я писал уже два раза и что то все никак, ну будем надеяться на чудо что исправят и хотелось бы что б ширины добавили хотя бы до 30
> 
> в любом случае, последнее слово за разрабами - захотят сделают, нет - нет.
не понимаю где в наших сообщениях негатив, это по поводу ссылки, а по поводу последнего слова разработчиков ни кто не спорит с этим, мы указали на ошибку (по нашему мнению)  ведь для этого создавался данный ресурс, что бы мы высказывали свое мнение и предложения

**Comment by SBProX** [comment]
> это хорошо что на стадии ИСПРАВЛЕНИЯ ОШИБОК про эту ошибку я писал уже два раза и что то все никак, ну будем надеяться на чудо что исправят и хотелось бы что б ширины добавили хотя бы до 30

Вы же сами видите сколько тикетов в репозитории, что нам теперь разорваться на части?
Все делаем постепенно.

**Comment by SBProX** [comment]
> Разобрался, толщина линии меняется только на графике со свечами\барами и на линейном графике. Это прикол такой что ли??? На одном графике работает, на другом нет. Дурдом.

Вы бы сначала разобрались.
На кластерных графиках линия имеет автоматическую толщину, равной ячейке кластера.
Чтобы когда вы ставите линию, все было симетрично. Если на кластерных графиках линия будет иметь толщину в 1-2-3 пикселя например, или настраиваемую, то это будет выглядеть довольг убого.
