### ISSUE TITLE
Инструменты рисования - на "линиях" не работает прозрачность!

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#617]
В инструментах рисования прозрачность для "горизонтальной линии" меняется, а я для "линии" нет! это так задумано?
![bandicam_2019-09-17_09-16-15-301](https://user-images.githubusercontent.com/51231827/65011292-7c608700-d92c-11e9-9c78-e73408eb9522.gif)

**Comment by SBProX** [comment]
Там у нас была какая-то загвоздка с этой прозрачность, перепроверим

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении.
