### ISSUE TITLE
Ошибка в меню линии

### ISSUE THREAD

**Issue by RoketAnny** [SBProX/SBProX-Dev#619]
в посте #118  реализована быстрая смена цвета
но при создании новой линии и и добавлении на неё текста и алерта, а потом цвета
применяется только цвет а текст и алерт слетают.
приходится ее повторно открывать меню линии и заполнять эти параметры,
или сначала выставлять их, нажимать ок, а потом переоткрывать окно  и выбирать цвет линии.

Поправьте пожалуйста.

**Comment by Fen8fen** [comment]
- Здравствуйте.
- Большая просьба оставить возможность быстрого выбора цвета.....
совместив выбор (клик по ячейке с цветом) с кнопкой "ОК"

**Comment by SBProX** [comment]
Сделано, будет работать в сл. обновлении
