### ISSUE TITLE
Натягивающиеся профили

### ISSUE THREAD

**Issue by Filnet82** [SBProX/SBProX-Dev#62]
Включите возможность натягивать профили на тиковом графике как это было в SBpro2.

**Comment by Filnet82** [comment]
![Снимок](https://user-images.githubusercontent.com/34250003/57525757-3f5c0680-7334-11e9-90dd-2c4238bbe8ff.JPG)

**Comment by SBProX** [comment]
Профиль на тиковом графике отлично натягивается.
