### ISSUE TITLE
Не работает прозрачность бара % в ДП для типа Volume

### ISSUE THREAD

**Issue by iz0t0pe** [SBProX/SBProX-Dev#620]
В настройках динам. профиля для типа Volume не работает пункт Прозрачность баров %, поэтому надо крутить в настройках Цвета бара А%.

**Comment by SBProX** [comment]
Да, там и задумано. Прозрачность для profile регулируется именно там где вы и сказали

**Comment by iz0t0pe** [comment]
> Да, там и задумано. Прозрачность для profile регулируется именно там где вы и сказали

Странно, для других типов (дельта и т.д.) работает пункт этот.
