### ISSUE TITLE
Симулятор после обновления

### ISSUE THREAD

**Issue by finast** [SBProX/SBProX-Dev#622]
После обновления не всегда стали срабатывать лимитные ордера
![Симулятор лимит](https://user-images.githubusercontent.com/50439357/65032269-3c18fd00-d95c-11e9-8c4e-8efa0cb35e75.jpg)

**Comment by SBProX** [comment]
Спасибо, проверим. Симулятор не трогали совсем.

**Comment by VeegoDamask** [comment]
Это старая проблема, она связана не с обновлением. Проблема чаще всего случается после того, как были использованы кнопки close all или reverse.

**Comment by finast** [comment]
> Это старая проблема, она связана не с обновлением. Проблема чаще всего случается после того, как были использованы кнопки close all или reverse.

Может быть. Но, у меня раньше такого не было.

**Comment by SBProX** [comment]
На данный момент проблема еще наблюдается?

**Comment by finast** [comment]
Сейчас всё нормально. Наверное, какой-то сбой был.

**Comment by SBProX** [comment]
Принято, спасибо.
