### ISSUE TITLE
прошу сделать -удалить все линии на графиках , сохранения раб.пространства с настройками симулятора , при линковке в симуляторе линии разными цветами не синхронизируються только серым, синхронизацию отрисовки фигур на всех графиках по линковке

### ISSUE THREAD

**Issue by Vegas3737** [SBProX/SBProX-Dev#624]
Доброго дня предлагаю сделать доработки в терминале элементарные

1. добавьте пожалуйста к меню выставления уровней кроме дублировать , вставить , дублир.на все графики еще опцию
 
     - удалить все линии на всех графиках 

2. сохранение рабочего пространства с параметрами настроек симулятора 

пример т.е я настроил себе симулятор у меня здесь 12 графиков 3 монитора я сохраняюсь  выхожу из сбпро загружаю тренировочный профиль рабочего пространства и вместо того чтоб загрузить мне ранее настроенный в режиме симулятора терминал , мне загружают исходное рабочее состоянии реальных торгов и симулятор окна мне надо опять настраивать заново вы можете это устранить , ибо это каждый день отнимает много времени ...  
3. можно сделать как tigertrade синхронизацию отрисовки фигур на всех графиках по линковке 
например я рисую на м5 прямоугольник и этот же прямоугольник рисуется на всех залинкованных графиках д1 ч1 м15 итд 
это касаеться линии  окружности  
4. Добавьте пожалуйста оповещение алерта на емэил !! ОЧЕНЬ ВАС ПРОШУ !! ОЧЕНЬ ВАЖНАЯ ФУНКЦИЯ ! 

спасибо большое за внимание

**Comment by Vegas3737** [comment]
дрУЗЬЯ КОМУ НРАВЯТСЯ УЛУЧШЕНИЯ ПОЖАЛУЙСТА СТАВЬТЕ ЛАЙКИ ИНАЧЕ НА НАС НЕ ОБРАТЯТ РАЗРАБОТЧИКИ ВНИМАНИЯ !! сПАСИБО вСЕМ

**Comment by SBProX** [comment]
Оформляйте тикет нормально:

1. Без капслоков
2. С запятыми (читать же невозможно!)
3. Для каждой задачи - свой отдельный тикет.
Пожалуйста не публикуйте в отдоном тикете 100500 задач.
