### ISSUE TITLE
Алерт по индикатору Bars Delta Highlight

### ISSUE THREAD

**Issue by pitbul1976** [SBProX/SBProX-Dev#628]
На 15М графике выставил активацию звука и уведомления по индикатору. И он "пищит" до того, как заканчивается 15М период, если в процессе формирования бара появляется "противонаправленная" дельта (как я понял). Вот бы сделать так, чтобы уведомление шло только по окончанию формирования бара.

**Comment by r0b4ik** [comment]
Присоединяюсь! Давно хотел это написать, но не доходили руки. Тоже самое относится и к volume highlight. При этом не хотелось бы, что бы сам индикатор только по окончанию периода подсвечивал бар, т.к. в моменте важно видеть появляется или пропадает дивергенция по дельте.
А вот сигнал должен появляться только по окончанию периода ТФ.

**Comment by SBProX** [comment]
Исправили, будет работать в сл. обновлении.
