### ISSUE TITLE
Cloud -позиционирование указателя

### ISSUE THREAD

**Issue by Filnet82** [SBProX/SBProX-Dev#63]
Поправить нужно места отображения клоудов, пример одно и тоже место в SBpro2 и SBproX, или это так задумано: в первом случае указатель в конце агрегации, во 2 случе в начале. А может лучше обозначить диапазон попавший в расчет алгоритма, так информативнее будет.
![Снимок2](https://user-images.githubusercontent.com/34250003/57526421-0e7cd100-7336-11e9-8ae1-272569e86ee6.JPG)

**Comment by SBProX** [comment]
Спасибо, в понедельник проверим.

**Comment by SBProX** [comment]
Можете сбросить настройки cloud?

**Comment by Filnet82** [comment]
Да обычные, ничего особенного ![Снимок3](https://user-images.githubusercontent.com/34250003/57553234-b74b2080-7376-11e9-9cab-fc45aef81633.JPG)

**Comment by Filnet82** [comment]
Может как то так добавите выделение начала и конца диапазона который попал в расчет алгоритма, тут думаю вам виднее как лучше выделение технически сделать
![Снимок4](https://user-images.githubusercontent.com/34250003/57555484-0f852100-737d-11e9-8cbb-a34ab5a7dc32.JPG)

**Comment by SBProX** [comment]
Исправлено
