### ISSUE TITLE
Не работает Алерты при подходе цены к уровню

### ISSUE THREAD

**Issue by jekagame** [SBProX/SBProX-Dev#631]
не работает звуковые оповещения - порбывал на разных графиках - звука нет
![image](https://user-images.githubusercontent.com/34160287/65231289-0862e200-dad8-11e9-8735-ec0bb44b3d52.png)
просьба исправить приоритетно)

**Comment by Vegas3737** [comment]
да подтверждаю , алерты не работают ни на младших ни на больших тф 
исправьте пожалуйста как можно скорее

**Comment by Kwadim** [comment]
Тоже не работают, месяца 2 назад работали

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении
