### ISSUE TITLE
подкорректируйте авто масштабирование Cluster bid-ask 

### ISSUE THREAD

**Issue by Expert-ks** [SBProX/SBProX-Dev#64]
В старой версии автоматом происходит при уменьшении масштаба и значения внутри видно в новой при уменьшении показаний нет
![2019-05-09 (10)](https://user-images.githubusercontent.com/50441386/57526814-17ba6d80-7337-11e9-9f02-d3d5541ad585.png)
![2019-05-09 (12)](https://user-images.githubusercontent.com/50441386/57526823-1ab55e00-7337-11e9-95b9-3393bb0edf0f.png)

**Comment by Artem074** [comment]
уже есть такой тикет https://github.com/SBProX/SBProX-Dev/issues/7

**Comment by SBProX** [comment]
Верно, такой тикет уже есть. Этот закроем.
