### ISSUE TITLE
Горизонтальный профиль рынка

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#641]
1. Не работает прозрачность динамичного профиля в режиме Volume.
![Screenshot_2](https://user-images.githubusercontent.com/55657161/65387399-ae6c5180-dd4f-11e9-9ecf-aa0cefc75f6f.png)

2. Отсутствует на всех индикаторах горизонтального профиля, кроме месячного, настройка прозрачности баров.
![Screenshot_3](https://user-images.githubusercontent.com/55657161/65387450-1e7ad780-dd50-11e9-8a04-70f21bb85d63.png)

**Comment by SBProX** [comment]
Прозрачность настраивается в настройках цвета (параметр А).
Все работает.
