### ISSUE TITLE
пожалуйста верните Ренко бары в сбпро

### ISSUE THREAD

**Issue by spyhant** [SBProX/SBProX-Dev#645]
пожалуйста верните Ренко бары в сбпро очень их не хватает

**Comment by SBProX** [comment]
В SBproX их и не было, и пока что не будет

**Comment by WillBegin1** [comment]
Поддерживаю, ренко были в обычной sbpro, не понятно прогресс в платформе идёт, а графики исчезают, то же за то чтобы добавить ренко график в sbproX. Из-за этого приходится открывать обе платформы, очень не удобно!

**Comment by SBProX** [comment]
Ренко не будет, мы об этом еще в мае говорили.
