### ISSUE TITLE
Фьючерсы отрисовываются не с начала контракта

### ISSUE THREAD

**Issue by Kwadim** [SBProX/SBProX-Dev#646]
Фьючерсы отрисовываются не с начала контракта, а когда становятся последним контрактом, что неудобно, т.к. при склейке не совпадают уровни
![контракт](https://user-images.githubusercontent.com/18749802/65537988-07361880-df0f-11e9-9011-42f14fc039a7.png)

**Comment by Kwadim** [comment]
Напр. по склейке кажется, что сегодня был выход из накопления, хотя выше видно, что реально он был вчера, а сегодня тест
![контракт2](https://user-images.githubusercontent.com/18749802/65538839-e40c6880-df10-11e9-970e-01a75e130138.png)
Что подтверждается акциями
![акции](https://user-images.githubusercontent.com/18749802/65538921-11f1ad00-df11-11e9-87ea-725e6948a56e.png)

**Comment by SBProX** [comment]
Непонятно о чем вы говорите. Что значит не сначала?

**Comment by Kwadim** [comment]
Фьючерс начинает торговаться за год sbrf - 12.19  с декабря 18, а отрисовка с 5.09.19. Раньше была возможность смотреть весь контракт

**Comment by CuJlaMblcJlu** [comment]
а у меня в режиме auto не идут котировки , если перезагрузить данные с сервера то всё начинает работать НО на следующий день с открытием рынка всё опять стоит . И приходится каждый таймфрейм перезагружать по каждому инструменту . Это началось после экспирации . Рынок ФОРТС .

**Comment by SBProX** [comment]
> Фьючерс начинает торговаться за год sbrf - 12.19 с декабря 18, а отрисовка с 5.09.19. Раньше была возможность смотреть весь контракт

1. Вы прислали обрезанные скриншоты, где не видно что вы ставите.
2. Если стоит Auto, то будет склейка контрактов. Если Вы выбираете в ручную контракт, то будет показываться отдельный контракт, но не за год. Мы включаем контракт примерно за 1 месяц до той даты, когда он становится ликвидным.
3. Раньше не было такой возможности, смотреть отдельный контракт за год, вы что-то путаете.

**Comment by SBProX** [comment]
> а у меня в режиме auto не идут котировки , если перезагрузить данные с сервера то всё начинает работать НО на следующий день с открытием рынка всё опять стоит . И приходится каждый таймфрейм перезагружать по каждому инструменту . Это началось после экспирации . Рынок ФОРТС .

Почему тикет не создаете?
