### ISSUE TITLE
ЖЕСТЬ с котировкой!

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#647]
Вчера писал коллеге о интересно моменте по клаудам и сохранил скрин. Сегодня открыл СБ, смотрю уровень есть а cloud пропал! Вспомнил про скрин, посмотрел, оказывается и объём изменился! Как это возможно???
![image](https://user-images.githubusercontent.com/50357928/65569143-31b2c080-df65-11e9-84cf-71bf3eb74013.png)

**Comment by SBProX** [comment]
Добрый день.

Какой это инструмент и контракт?
И настройки Cloud так же нужны (в виде скриншотов)

Высылайте сразу всю информацию.
Спасибо.

**Comment by SBProX** [comment]
Вероятно что ошибка носит какой-то редкий характер, потому что если бы ТАКОЕ было, то уже мы нас помидорами закидали.
Нужно разбираться. Можете сохранить ваш workspace и сообщить нам ваш логин и имя workspace. Мы у себя его запустим и проверим.
