### ISSUE TITLE
После начала торгов на Фортс не запускается котировка

### ISSUE THREAD

**Issue by AlTuzov** [SBProX/SBProX-Dev#648]
С начала этой недели заметил что после начала торгов котировка не запускается на инструментах Ri, SI, однако c BR всё нормально.  Приходится или обновлять графики кнопкой "применить" или перезапускать терминал.
Вероятно это как-то связано с последней экспирацией или последним обновлением.

**Comment by r35p3ct** [comment]
подтверждаю

**Comment by SBProX** [comment]
Проверим завтра утром.

**Comment by SeregaTS22** [comment]
да с фортс что то не то

**Comment by RoketAnny** [comment]
тоже самое и у меня на российском рынке
