### ISSUE TITLE
Cluster Seartch поиск определенного значения

### ISSUE THREAD

**Issue by Filnet82** [SBProX/SBProX-Dev#65]
Просьба добавить простую надстройку, в которой можно задать объем который хотелось бы отдельно видеть. В настоящее время есть только кнопка максимальный объем, которая отсекает диапазон от 0 до указанного значения. А мне, к примеру, нужно увидеть только одиночные сделки по 11 контрактов.
![Безымянный](https://user-images.githubusercontent.com/34250003/57527610-c9a66980-7338-11e9-9be6-d38f67f10185.png)

**Comment by SBProX** [comment]
В данном индикаторе нет такого как одиночные сделки и быть не может.
Либо мы вас не правильно поняли. 

Объясните понятнее пожалуйста

**Comment by Filnet82** [comment]
Давайте ещё раз попробую объяснить: тиковый график в данном софте, это та же лента, только в виде графика. Каждый кластер тикового графика отражает одну сделку совершенную по цене BID или ASK (или направлением покупка/продажа). В настоящее время, что клоуд алгоритм, что поиск кластера у вас организован по принципу выделения диапазонов значений по цветам. А я к примеру увидел участника торгов который торгует всегда только 11 контрактами и я его хочу увидеть и в клоуде 11 контрактов с помощью агрегации и в виде одиночного кластера объемом 11 контрактов. Т.е. не диапазон значений, а одно значение ровное заданному. Технически я понимаю, что это ведь программисту не сложно сделать.

**Comment by SBProX** [comment]
Вообще вы можете увидеть такое в Cloud. Не видим смысла делать такой фильтр в Cluster Search
![Screenshot_3](https://user-images.githubusercontent.com/16720120/57571986-a30e2e80-741d-11e9-9d16-78af92d47488.png)

**Comment by SBProX** [comment]
Так же можете поставить минимальный и максимальный фильтр на настройке тикового графика:
![Screenshot_4](https://user-images.githubusercontent.com/16720120/57572001-dfda2580-741d-11e9-963f-dc0fcaddbc35.png)

**Comment by SBProX** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/16720120/57572015-0ac47980-741e-11e9-8779-ef00c91026fe.png)
Либо такой вариант

**Comment by Filnet82** [comment]
Благодарю, вариант настройки предложенный в Cloud для поиска одиночных кластеров мне подходит, но нужна еще возможность в режиме агрегированных сделок тоже отражать искомое значение не только по минимальному значению, а еще и фильтром убрать суммы больше искомого значения. 
![1](https://user-images.githubusercontent.com/34250003/57575007-432e7c80-744b-11e9-83ff-f164d91fff7b.JPG)

**Comment by SBProX** [comment]
Это очень сомнительно в плане пользы, мы не можем делать настройку в программе если этим будете пользоваться только Вы.
