### ISSUE TITLE
Агрегированный стакан Depth & Sales

### ISSUE THREAD

**Issue by artmagic-Alt** [SBProX/SBProX-Dev#653]
Предлагаю реализовать стакан с агрегацией данных по принципу Jigsaw Ninjatrader
![2019-09-25_16-08-19](https://user-images.githubusercontent.com/55432591/65603761-ee7d3f80-dfae-11e9-80d9-dea950d01261.jpg)

Описание взял с сайта разработчика, на английском:
The Depth & Sales is Jigsaw’s interpretation of the Depth of Market (DOM). A tool that is the cornerstone of the proprietary trader’s decision making process. It is here we see the interaction between passive traders (limit orders) and active traders (market orders). This is where we get a visceral feel for trading activity. Regardless of how you will make decisions longer term (via the DOM or our more visual tools), spending time doing drills on our DOM will pay off huge dividends in terms of your market understanding.

**### The Depth & Sales shows:**
The impact of trades hitting the market
Where traders are getting stuck
Likely location of stop orders/where traders are positioned
Where traders are pulling(cancelling) their orders, to avoid a move
Where traders are stacking (iceberging) and front-running the market in anticipation of the market holding
Balance of trade/momentum

Сайт - https://www.jigsawtrading.com/platform/

**Comment by SBProX** [comment]
К сожалению, но пока что Level2 мы не можем подключить, нет данных.

**Comment by artmagic-Alt** [comment]
> К сожалению, но пока что Level2 мы не можем подключить, нет данных.

Жаль...
