### ISSUE TITLE
Значение горизонтального уровня накладывается на верт.шкалу

### ISSUE THREAD

**Issue by artmagic-Alt** [SBProX/SBProX-Dev#657]
Если сделать линию прозрачной, то ее плашка будет тоже прозрачной и ее значение наложится на вертикальную шкалу:

![2019-09-25_20-25-49](https://user-images.githubusercontent.com/55432591/65624602-e7682880-dfd2-11e9-942b-a04c10abe425.jpg)

Вероятно, прозрачность не должна распространяться на плашку

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении.
