### ISSUE TITLE
Улучшение линий

### ISSUE THREAD

**Issue by iz0t0pe** [SBProX/SBProX-Dev#658]
Уверен, многие отмечают у себя в терминале **области** поддержки и сопротивления. Было бы супер удобно, если бы толщина линий привязывалась бы еще к тикам графика, а не только к пикселям как сейчас. Тогда одним кликом можно было бы ставить области. 
Вот пример, как я вижу это 
![image](https://user-images.githubusercontent.com/33651181/65624672-05358d80-dfd3-11e9-81d0-b5404083f4a4.png)

Предлагаю не убирать существующую реализацию настройки толщины, а **добавить** опцию [Толщина в пикселях или тиках]. Тогда удобство работы с терминалом взлетит до небес))

**Comment by iz0t0pe** [comment]
> Уверен, многие отмечают у себя в терминале **области** поддержки и сопротивления. Было бы супер удобно, если бы толщина линий привязывалась бы еще к тикам графика, а не только к пикселям как сейчас. Тогда одним кликом можно было бы ставить области.
> Вот пример, как я вижу это
> ![image](https://user-images.githubusercontent.com/33651181/65624672-05358d80-dfd3-11e9-81d0-b5404083f4a4.png)
> 
> Предлагаю не убирать существующую реализацию настройки толщины, а **добавить** опцию [Толщина в пикселях или тиках].

**Comment by artmagic-Alt** [comment]
толщины в тиках не хватает, согласен

**Comment by SBProX** [comment]
Для этих целей будут другой инструмент для нанесения диапазонов.
Ничего с толщиной мы больше делать не будем.

**Comment by SeregaTS22** [comment]
я давно писал про толщину в тиках

**Comment by iz0t0pe** [comment]
> Для этих целей будет другой инструмент для нанесения диапазонов.

Отлично, тогда ждем.

**Comment by SeregaTS22** [comment]
> Для этих целей будет другой инструмент для нанесения диапазонов.
> Ничего с толщиной мы больше делать не будем.

Спасибо за ваш труд, пожалуйста сделайте тогда этот другой инструмент (тот который с толщиной в тиках) что б он тоже линковался как горизонт линия и что б была возможность видеть цену ну и переставлять как горизонт уровень, вообще мне кажется горизонт уровень идеальный инструмент и ему не хватает только толщины в тиках а так все есть цена начальная точка и алерт, кстати алерт тоже хотелось бы увидеть в новом инструменте спасибо.
