### ISSUE TITLE
Ссылка на скачивание программы не работает

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#66]
![2019-05-10_18-23-29](https://user-images.githubusercontent.com/35344271/57538411-067e5a80-7351-11e9-8c5c-4f655f0ac623.jpg)

**Comment by SBProX** [comment]
У вас какие-то проблемы с доступом на Google docs, у нас все прекрасно работает

**Comment by Dmitry1970** [comment]
Спасибо! Проверю.
