### ISSUE TITLE
не работает оповещение линий цены

### ISSUE THREAD

**Issue by ragodnar** [SBProX/SBProX-Dev#660]
Приветствую!
не работают звуковые сигналы, когда цена доходит до линии (левая шкала).
Я все звуки перепробовал на разных графиках с разными таймфреймами - не работает.
А сигналы индикаторов работают.(cluster search например)
кто-то сталкивался с этим?
после обновы беда

**Comment by SBProX** [comment]
Уже писали об этом. 
Пожалуйста перед публикацией тикетов немножко почитайте сам репозиторий.

**Comment by ragodnar** [comment]
> Уже писали об этом.
Пожалуйста перед публикацией тикетов немножко почитайте сам репозиторий.

чукча не читатель, чукча трейдер. )
спасибо за быстрый ответ! ждём фикса
