### ISSUE TITLE
Толщина линий.

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#661]
Здравствуйте уважаемые разработчики.

![image](https://user-images.githubusercontent.com/20509322/65657606-b3cee200-e056-11e9-9c17-cfd454bb7b15.png)

Меня интересует возможность, заполнять линией весь кластер. После обновления линии при ширине 10 пунктов заполняют кластер наполовину.

**Comment by Fen8fen** [comment]
![image](https://user-images.githubusercontent.com/20509322/65657790-846ca500-e057-11e9-8960-0b6426888466.png)
Вот как это было до обновления. 

Было очень удобно. а теперь линия из за того что заполняет наполовину кластер. Визуально цепляется за смежные ячейки.

у меня просьба доработать опцию чтобы при выборе ширины в  10 пунктов линия заполняла кластер полностью ( как до обновления от 25 авг.)
или в chart settings - general - lines. добавить опцию full cluster line.

![image](https://user-images.githubusercontent.com/20509322/65657967-62275700-e058-11e9-8e1c-0e9aba42e10d.png)

**Comment by Bolt022** [comment]
Разрабы походу не в курсе, что для кластеров такая тема не "прокатывает"... https://github.com/SBProX/SBProX-Dev/issues/568#issuecomment-535354346

**Comment by SBProX** [comment]
Вернули все обратно, можете обновиться.
