### ISSUE TITLE
Исчезновение перекрестия

### ISSUE THREAD

**Issue by iz0t0pe** [SBProX/SBProX-Dev#666]
[Если что это не мешает работать, онли фидбек:)]
Если 1 раз кликнуть на горизонтальную ось времени, то появится возможность поставить вертикальную линию. Но если все таки еще раз не кликнуть на ось (чтобы зафиксировать линию) и перейти на другую вкладку, то исчезает перекрестие. Появится оно, соответственно, если завершить фиксирование вертикальной линии.
![2019-09-2622-02-12](https://user-images.githubusercontent.com/33651181/65717731-b22f0980-e0aa-11e9-886c-d85652886712.gif)

**Comment by test-777** [comment]
Подтверждаю - так же появлялась данная проблема, к тому же еще и вкладки инструментов порой становятся черными (без текста)

**Comment by iz0t0pe** [comment]
> Подтверждаю - так же появлялась данная проблема, к тому же еще и вкладки инструментов порой становятся черными (без текста)

Кстати да, когда такое происходило со вкладками, то не работало ПКМ и вообще вел себя странно. Помогала только перезагрузка.

**Comment by test-777** [comment]
Добавлю иллюстрацию данного бага с исчезновением текста на вкладках:

![изображение](https://user-images.githubusercontent.com/18189627/66026344-4f51ce00-e501-11e9-8cbc-d9f5425031ae.png)

**Comment by SBProX** [comment]
С перекрестием исправили, со вкладками проверяем.
