### ISSUE TITLE
Бары.

### ISSUE THREAD

**Issue by ac33307** [SBProX/SBProX-Dev#669]
Здавствуйте. я занимаюсь побарным анализом . в настройках цвета бара  именно баров не работает окрас. бары окрашиваются только в меню свечей. При выборе профиля обьемов нет тела бара. много недоработок в основном меню. планы грандиозные но простые элементарные вещи должны работать . для развития побарного анализа нужно сделать в меню выбор какие харрактеристики выбрать в баре. например нужно для анализа чтобы не отображалась цена открытия бара а только закрытие. можно подссветить  место максимального обьема в баре. можно сделать толщину бара больше в зависимости от обьема. также не работает профиль дельты и обьема в баре одновременно.  доделайте бары пожалуйста потом можно будет и искуственный интеллект прикручивать.)) спасибо

**Comment by SBProX** [comment]
1. Как это не работает? Вы не можете поменять цвет баров? 
2. При выборе какого профиля объема нет тела бара?

Приложите два скриншота пожалуйста, может вы просто не разобрались в функционале?

**Comment by artmagic-Alt** [comment]
для окраски баров есть индикатор

**Comment by artmagic-Alt** [comment]
Но согласен с топикстартером - хорошо бы допилить элементарный функционал

**Comment by SBProX** [comment]
@artmagic-Alt мы как раз этим и занимаемся.
И мы написали о том, что мы этим занимаемся.

**Comment by r35p3ct** [comment]
По поводу подсветки баров, есть такая вещь, как Pit бар [Формула](https://tigertradesoft.ru/threads/pitbarlevel-uroven-pit-bara.1089/)

**Comment by ac33307** [comment]
![направление бара](https://user-images.githubusercontent.com/25118910/65838931-f7547500-e310-11e9-88de-b3ba497e14c5.png)
![кластер профиль бар](https://user-images.githubusercontent.com/25118910/65838934-00454680-e311-11e9-94cb-ede676a81667.png)

**Comment by ac33307** [comment]
настройка свечей это одно настройка баров совсем другое

**Comment by SBProX** [comment]
@ac33307 Вы не то настраиваете.
Указанные вами цвета настраивают направления бара на кластерных графиках.
Эти настройки вообще не применимы к баровом графику.
Для баровго графика можно просто поменять цвет самих баров.

Рекомендуем сначала почитать инструкцию.
