### ISSUE TITLE
Предложение по просмотру содержимого свечи

### ISSUE THREAD

**Issue by NikolaiBogachev** [SBProX/SBProX-Dev#67]
Можно но ли в увеличителе сделать опцию выбора просмотра свечи например: при просмотре свечи в увеличителе посмотреть кластер-профиль или объем-дельта. Потому что 
так приходиться постоянно график переключать или два окна держать. А тут сразу трех зайцев убить можно . Крайне удобная функция будет.

**Comment by SBProX** [comment]
Пока что вынуждены отклонить данное предложение, по причине сложности реализации.
