### ISSUE TITLE
Улучшение горячих клавишь

### ISSUE THREAD

**Issue by test-777** [SBProX/SBProX-Dev#670]
При переключении между типами графика комбинациями "CTRL" + "1, 2, 3" итд.  Клавишу ctrl обязательно приходиться отпускать т.к. при нажатой клавише комбинация "ctrl" +1 а затем "ctrl +2" уже не срабатывает.

**Comment by SBProX** [comment]
Вообще-то так везде работают горячие клавиши в программах.
Отпускать нужно, иначе как понять какая в итоге комбинация нажата?

**Comment by test-777** [comment]
ctrl то зачем отпускать?
