### ISSUE TITLE
Текущие даты на графиках не устанавливаются

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#671]
Здравствуйте!
Текущие даты на графиках приходится до сих пор устанавливать вручную. Из 10 раз 9 раз правлю вручную. Очень редко устанавливается дата на текущий день. Порой даты устанавливаются на несколько дней назад.  Вручную меняю даты и перезагружаю данные на все вкладки. Сделайте, что-нибудь, пожалуйста. Если не получается, то может какую-нибудь строку в меню, типа "Установить текущие даты" или что-то в этом роде. На старой версии такого не было. Спасибо!

**Comment by SBProX** [comment]
Добрый день.

Сообщите пожалуйста ваш логин и имя workspace который вы загружаете.
А так же примерное время по МСК.

Спасибо

**Comment by Dmitry1970** [comment]
логин: badl1970@mail.ru
workspace: X
время московское, загружаю утром

**Comment by Ravil124** [comment]
Здравствуйте. У меня такая же проблема. Переустановка шаблонов помогла, но через день опять то же самое.

**Comment by SBProX** [comment]
Произвели изменения в коде, проверили на вашем workspace - все нормально.
На этой неделе выйдет обновление - проверите как будет работать у вас.
