### ISSUE TITLE
Направление кластеров,баров.

### ISSUE THREAD

**Issue by Pro-metey** [SBProX/SBProX-Dev#673]
Возможно сделать отображение напрвление кластеров ввиде свечей.где есть тело и тень.Чтобы было ясное понимание где сформировался объем: тело,тень.Для более наглядного понимания.

**Comment by artmagic-Alt** [comment]
Это на "кластер-профиле" можно сделать, включив "показывать направление".
![2019-10-01_14-13-00](https://user-images.githubusercontent.com/55432591/65957469-95e9ee80-e455-11e9-91a8-bf009ac527ee.jpg)

**Comment by Pro-metey** [comment]
Я знаю как включить напрвление в баре.
Я предлагаю добавить направление ввиде свечи.Прилагаю пример из другой программы.

>Вторник,  1 октября 2019, 14:13 +03:00 от artmagic-Alt <notifications@github.com>:
>
>Это на "кластер-профиле" можно сделать, включив "показывать направление".
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Иван Иванович

**Comment by artmagic-Alt** [comment]
> Я знаю как включить напрвление в баре. Я предлагаю добавить направление ввиде свечи.Прилагаю пример из другой программы.

А где пример?..

**Comment by Pro-metey** [comment]
скрин.фишка в том чтобы ясно видеть тело и хвост свечи.где расположены объемы.


>Воскресенье, 13 октября 2019, 12:56 +03:00 от artmagic-Alt <notifications@github.com>:
>
>>Я знаю как включить напрвление в баре. Я предлагаю добавить направление ввиде свечи.Прилагаю пример из другой программы.
>А где пример?..
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

-- 
Иван Иванович
