### ISSUE TITLE
Не работает алерт на линиях

### ISSUE THREAD

**Issue by Quantum-G** [SBProX/SBProX-Dev#674]
![Annotation 2019-09-30 200118](https://user-images.githubusercontent.com/34577071/65900171-07765e00-e3be-11e9-828d-aafe61a2127e.jpg)

**Comment by WillBegin1** [comment]
тоже не работает

**Comment by SBProX** [comment]
Уже исправили, будет работать в сл. обновлении

**Comment by Quantum-G** [comment]
> 
> 
> Уже исправили, будет работать в сл. обновлении

Спасибо

**Comment by ragodnar** [comment]
> Уже исправили, будет работать в сл. обновлении

а когда это обновление?

**Comment by SBProX** [comment]
> > Уже исправили, будет работать в сл. обновлении
> 
> а когда это обновление?

На этой неделе.
