### ISSUE TITLE
Нижний край прямоугольника наезжает на цифры в кластерах

### ISSUE THREAD

**Issue by artmagic-Alt** [SBProX/SBProX-Dev#677]
![2019-10-01_14-01-02](https://user-images.githubusercontent.com/55432591/65956935-40f9a880-e454-11e9-94c5-bc30a797f50c.jpg)

Стандартный прямоугольник, линия толщиной 2 пикселя

PS. Пользуясь случаем хочу сказать, что кластерный график получился изумительным! Хорошо читаемый, цифры четкие, всё на месте! Благодарю! :)

Еще б тиковую дельту сюда, а то приходится на ниндзевский график подглядывать...

**Comment by SBProX** [comment]
Спасибо, учтем.

**Comment by Flawmaster** [comment]
> Стандартный прямоугольник, линия толщиной 2 пикселя

Не только на цифры, но если сжать график, то видно, что нарисованный прямоугольник наезжает на соседние ячейки кластеров сверху и снизу (хотя должен рисоваться между кластерами), а также линии не совпадают с прямоугольниками.
![косяк с рисованием](https://user-images.githubusercontent.com/50398637/65958633-8324e900-e458-11e9-9244-082c9b14400f.png)

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении
