### ISSUE TITLE
Предложение.Свечная двухсторонняя дельта.

### ISSUE THREAD

**Issue by alexanflint** [SBProX/SBProX-Dev#68]
![свечная  двухсторонняя дельта](https://user-images.githubusercontent.com/50513516/57567514-10e93480-73e3-11e9-893e-e14a3f57e6b8.png) 
 скрин с АТАСА

![дельта сбпро](https://user-images.githubusercontent.com/50513516/57567519-1e062380-73e3-11e9-9940-e6bb92ff1d1a.png)  скрин с SBProX
Уважаемые разработчики!
Есть ли возможность добавить подобную реализацию двухсторонней дельты в вашу новую программу?

**Comment by SBProX** [comment]
Пока возможности нет, но мы подумаем.

**Comment by Artem074** [comment]
Прикольная штука... не знал про такую... очень полезная!

**Comment by max4562** [comment]
Поддерживаю затею и голосую ЗА то чтобы такая возможность реализовалась. Очень нужная штука, которая помогает визуально определять где вливался противоположный объем.

**Comment by max4562** [comment]
Так же предлагаю в окне настроек графика увеличить шрифт. За целый день насмотришься на мелкий текст. А хотя бы в настройках сделать побольше. Это позволит не вглядываясь и быстро кое что поправить в настройках. В обычном СБПРО оптимальная величина шрифта окна настроек.
