### ISSUE TITLE
Несколько окон в одном большом окне.

### ISSUE THREAD

**Issue by danilp2** [SBProX/SBProX-Dev#688]
Сейчас при необходимости переноса на другой экран рабочего пространства из 3-4 окон приходится переносить каждое. У каждого свое меню. Было бы удобнее, если бы окна объединялись общим базовым окном, как, например, в xTick.

**Comment by WillBegin1** [comment]
лучше как сейчас в atase beta и tigertrade

**Comment by SBProX** [comment]
К сожалению мы так не можем сделать, придется переписывать кучу кода.
