### ISSUE TITLE
Раскрасить вертикальные объемы

### ISSUE THREAD

**Issue by bizlis** [SBProX/SBProX-Dev#69]
Просьба добавить возможность раскрасить вертикальные объемы, по следующему принципу:
пока объем растет - один цвет, скажем зеленый
пока объем падает - другой цвет, скажем красный
такой принцип реализован в МТ5

**Comment by SBProX** [comment]
Что имеется в виду под "пока растет"? Но всегда растет в баре.

**Comment by Artem074** [comment]
> Что имеется в виду под "пока растет"? Но всегда растет в баре.

видимо, имеется ввиду "растущий-падающий" бар... то же самое просили с Открытым интересом сделать https://github.com/SBProX/SBProX-Dev/issues/38

**Comment by bizlis** [comment]
Совершенно верно, "растущий-падающий" и на ОИ тоже такое надо, но меня больше объем интересует

**Comment by SBProX** [comment]
Поясните какой в этом смысл, вы же сами видите какой бар растущий, а какой падающий. Зачем ещё гистограмму красить?

**Comment by bizlis** [comment]
Бары красить не надо, нужна раскраска гистограммы самого объема, это облегчает более быстрое визуальное восприятие для анализа, особенно когда объем очень низкий на гистограмме и визуально почти одинаков.

**Comment by WillBegin1** [comment]
![Screen Shot 11 05 2019 at 22 05](https://user-images.githubusercontent.com/50406792/57573942-e629cb00-7438-11e9-8008-a7eaca0812ac.png)
Вот пример того,что человек имел ввиду, это больше для VSAшников, но функция для них действительно полезная

**Comment by r35p3ct** [comment]
Было бы лучше, если подкрашивать, если больше 2х предыдущих. Ну если просто больше предыдущего, то тоже сойдет.

**Comment by SBProX** [comment]
Сделали. Будет работать при следующем обновлении.
