### ISSUE TITLE
DOM (Depth of Market)

### ISSUE THREAD

**Issue by nopsynops** [SBProX/SBProX-Dev#690]
Здравствуйте, хотелось бы узнать будит ли возможность добавит Индикатор << Dom >>
в SBProX?
![DOM (Depth of Market)](https://user-images.githubusercontent.com/55189306/66108878-ce0f3f80-e5c3-11e9-8fca-c478b9942754.jpg)

**Comment by SBProX** [comment]
Добрый день.
На данный момент это невозможно, у нас нет данных.
Возможно это получится сделать через коннекторы, но пока что я не могу ничего сказать.
