### ISSUE TITLE
Сделайте пжл. график Кластер профиль объем+Дельта.Два столбца.

### ISSUE THREAD

**Issue by Pro-metey** [SBProX/SBProX-Dev#697]
Господа!! Очень прошу! Сделайте пжл. график Кластер профиль объем+Дельта.Два столбца.С фильтрацией соответственно объема и дельты.С балансом покупок и продаж.

**Comment by NikolaiBogachev** [comment]
Разработчики писали что будут делать конструтор для графиков объмов что пользователь сам мог настроить отображение графика на свое усмотрение если я не ошибаюсь .

**Comment by SBProX** [comment]
@NikolaiBogachev все верно.
В связи с этим данный тикет не актуален.
Постараемся сделать в ближайшее время, и сможете комбинировать графики.
