### ISSUE TITLE
!!! ВАЖНО !!! ДОРАБОТКА СБПРО !!! УЛУЧШЕНИЕ!!! РАБОЧЕЕ ПРОСТРАНСТВО!!! ШАБЛОНЫ  

### ISSUE THREAD

**Issue by SeregaTS22** [SBProX/SBProX-Dev#698]
НА ДАННОМ ЭТАПЕ ПРЕДЛАГАЮ РЕАЛИЗОВАТЬ СЛЕДУЮЩЕЕ:

1  ВОЗМОЖНОСТЬ СОРХРАНЕНИЯ ШАБЛОНА ДЛЯ ОКНА,В КОТОРОМ МОГУТ НАХОДИТЬСЯ НЕСКОЛЬКО ВКЛАДОК С ГРАФИКАМИ (НАПРИМЕР РАЗНЫЕ ТФ )  ОДНОГО ИНСТР. 
ОТКРЫЛ ОКНО И ЗАГРУЗИЛ ШАБЛОН ДЛЯ ОКНА ОДИН РАЗ,
 А ТО ПРИХОДИТЬСЯ ОТКРЫВАТЬ ОКНО И ЗАГРУЖАТЬ ТОЖЕ САМОЕ "ПЯТЬ РАЗ"
А ЕСЛИ ТАКИХ ОКНА ТРИ, ЭТО ЧТО 15 РАЗ НУЖНО ЗАГРУЗИТЬ ГРАФИКИ ? НА ЭТО УХОДИТ СЛИШКОМ МНОГО ВРЕМЕНИ. ПРИМЕР НА СКРИНЕ
![bandicam 2019-10-06 12-03-22-659](https://user-images.githubusercontent.com/54494083/66268238-19378580-e844-11e9-8677-3d7657cefd14.jpg)

СОХРАНЕНИЕ РАБОЧЕГО ПРОСТРАНСТВА НЕ СПАСАЕТ, НА ЭТУ ТЕМУ ВТОРОЕ ПРЕДЛОЖЕНИЕ

 2 СДЕЛАТЬ МАЛЕНЬКУЮ ПАНЕЛЬ НА ЭКРАНЕ, НАПРИМЕР КАК В ТЕРМИНАЛЕ "АЛЬФА ДИРЕКТ" ПРИМЕР МОЖНО УВИДЕТЬ НА ВИДЕО КОТОРОЕ НАХОДИТСЯ ПО ССЫЛКЕ 
( ПРОСТО СЮДА НЕ ПОЛУЧАЕТСЯ ЗАКИНУТЬ ) НА ВИДЕО ПОКАЗАНО КАК ЭТО РЕАЛИЗОВАНО В АЛЬФА ДИРЕКТ И В КОНЦЕ ПОКАЗАНО ПРЕДЛОЖЕНИЕ КАК ЭТО ХОТЕЛОСЬ БЫ УВИДЕТЬ В СБПРО  ВИДЕО КОРОТКОЕ, ДЛИТСЯ ДВЕ С ПОЛОВИНОЙ МИНУТЫ  ТАК ЖЕ БУДЕТ СКРИН
https://cloud.mail.ru/public/3tdj/5h8oysgup

ВООБЩЕМ СУТЬ В ТОМ, ЧТО БЫ НА ПАНЕЛЬКЕ ВВЕРХУ (К ПРИМЕРУ) БЫЛИ ВКЛАДКИ В КОТОРЫХ ОТКРЫТЫ ОКНА  ( НАПРИМЕР 3 ШТУКИ )
ПЕРЕКЛЮЧАЕШЬ ВКЛАДКИ И МЕНЯЕТСЯ РАБОЧЕЕ ПРОСТРАНСТВО ( НАПРИМЕР В ОДНОЙ ВКЛАДКЕ ТРИ ОКНА В ДРУГОЙ 2 ОКНА) 

 ТАКИМ ОБРАЗОМ РАБОЧЕЕ ПРОСТРАНСТВО МОЖНО УБРАТЬ, ВКЛАДКИ НА ПАНЕЛЬКЕ ЭТО И ЕСТЬ РАБОЧЕЕ ПРОСТРАНСТВО ГДЕ ОТКРЫТЫ ОКНА ( К ПРИМЕРУ ПЕРВАЯ ВКЛАДКА РАБОЧЕЕ ПРОСТРАНСТВО ДЛЯ РОС РЫНКА И ВТОРАЯ ДЛЯ АМЕРИК. ) КСТАТИ ТАК ЖЕ И В КВИКЕ СДЕЛАНО НО ТАМ НЕТУ ПАНЕЛЬКИ КАК В АЛЬФА ДИРЕКТ, А ЭТО ОЧЕНЬ УДОБНО,
И ДЛЯ ЭТИХ ВКЛАДОК ТОЖЕ СДЕЛАТЬ ШАБЛОН ( ВМЕСТО СОХРАНИТЬ РАБОЧЕЕ ПРОСТРАНСТВО ) ПРИ ЗАГРУЗКЕ КОТОРОГО ОТКРЫВАЮТСЯ 3 ОКНА В КОТОРЫХ ПО 5 ГРАФИКОВ, 

И ЕЩЕ ДОБАВИТЬ КНОПКУ ПОД НАЗВАНИЕМ "СКРЫТЬ ВСЕ ОКНА " ПРИ НАЖАТИИ КОТОРОЙ СКРЫВАЮТСЯ ВСЕ ОКНА И ОСТАЕТСЯ МАЛЕНЬКАЯ ПАНЕЛЬ НА ВВЕРХУ, А ТО ПОКА ВСЕ ОКНА СВЕРНЕШЬ ТОЖЕ МНОГО ВРЕМЕНИ УХОДИТ 
![bandicam 2019-10-06 14-10-20-641](https://user-images.githubusercontent.com/54494083/66268299-aed31500-e844-11e9-9e4a-bd65ff18dffc.jpg)

**Comment by SBProX** [comment]
Не нужно 15 раз ничего загружать, вы просто сохраняете рабочее пространство.
Извините, но уже менять что-то в рабочих пространствах или шаблонах мы не можем.
Пользователи себе уже сохранили настройки, если мы все изменим, например как вы предлагаете, то у пользователей все слетит.

**Comment by SBProX** [comment]
Спасибо за предложение, но это уже невозможно. Данные вещи проектируются на этапе разработки платформы.
