### ISSUE TITLE
Автомасштабирование текста в кластерах

### ISSUE THREAD

**Issue by ershner** [SBProX/SBProX-Dev#7]
![2019-05-06_16-38-42 (2)](https://user-images.githubusercontent.com/18483236/57242556-74b6da80-703c-11e9-871b-6ef0b1295a95.png)

**Comment by Artem074** [comment]
поддерживаю! стало не очень удобно смотреть кластера.

**Comment by SBProX** [comment]
Без масштабирования в Windows:
![Screenshot_6](https://user-images.githubusercontent.com/16720120/57618076-1bdec900-758b-11e9-8477-620607e9bd72.png)
С масштабированием 125%:
![Screenshot_8](https://user-images.githubusercontent.com/16720120/57618082-1e412300-758b-11e9-8780-3d64cfdfcadc.png)

Везде в новой платформе кластерах влезает больше.

**Comment by ershner** [comment]
))) @SBProX Правда так считаете?
![2019-05-13_14-59-12](https://user-images.githubusercontent.com/18483236/57620144-92ca9080-7590-11e9-8adf-8d323e1266e5.png)
![2019-05-13_15-04-27](https://user-images.githubusercontent.com/18483236/57620154-96f6ae00-7590-11e9-94ba-4cac753b5580.png)

**Comment by Artem074** [comment]
у меня тоже меньше кластеров стало... это максимальное сжатие по горизонтали и вертикали, при котором видны цифры.
![2019-05-13_172414](https://user-images.githubusercontent.com/50441291/57621104-0c1fae80-75a4-11e9-9294-c9fd5733a9cd.png)
![2019-05-13_172435](https://user-images.githubusercontent.com/50441291/57621105-0c1fae80-75a4-11e9-95fc-7c553754c247.png)
