### ISSUE TITLE
Таймер закрытия бара

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#70]
Уважаемые разработчики! Добавьте, пожалуйста, возможность включить отображение времени до закрытия текущей свечи/бара на ценовом тикере.

![Bar-Timer](https://user-images.githubusercontent.com/50398637/57574138-22aaf600-743c-11e9-82f1-6ba293db40c7.png)

**Comment by Cayman131** [comment]
+ поддерживаю

**Comment by SBProX** [comment]
Не находим полезным данное предложение

**Comment by Flawmaster** [comment]
Это полезно для тех, кто торгует на нескольких ТФ и кто входит четко по закрытию бара. В текущей платформе приходится постоянно отвлекаться, чтобы понять когда закрытие (а это потеря 2-3 секунд сразу), и, если учесть, что для входа надо переключиться на другую платформу, то это как раз секунд 5 выходит, что выливается в упущенные входы/входы по худшей цене, особенно, если торгуешь по секундам.
