### ISSUE TITLE
Изменение построения Линейного Графика

### ISSUE THREAD

**Issue by MAXK04** [SBProX/SBProX-Dev#703]
Здравствуйте. Исправьте/измените пож-та построение линейного графика на **Line On Close**, так как разлет довольно большой получается. У Вас видимо стоит построение по максимумам, а функции выбора нет. 

![1](https://user-images.githubusercontent.com/51521568/66495306-de02b400-eada-11e9-9c5f-5cafbfa25092.png)
![3](https://user-images.githubusercontent.com/51521568/66495307-de02b400-eada-11e9-9c48-fd14da68bb88.png)
![2](https://user-images.githubusercontent.com/51521568/66495308-de9b4a80-eada-11e9-9130-e03b0e340c1a.png)

**Comment by SBProX** [comment]
Совсем не понятно зачем вообще нужен линейный график по Close.
Такой график искажает реальную картину на рынке.
В SBPro линейный график мы делали для коррелятора, и в этом случае график по Close никак не нужен.

**Comment by MAXK04** [comment]
> Совсем не понятно зачем вообще нужен линейный график по Close.
> Такой график искажает реальную картину на рынке.
> В SBPro линейный график мы делали для коррелятора, и в этом случае график по Close никак не нужен.

Ну ОК, я сделаю через МА1 - получится то, что я просил (как оба графика выше). Так что проблема решена.

**Comment by SBProX** [comment]
@MAXK04 Вопросы был в том, в чем суть линейного графика, который по сути сглаживается по Close ценам. То что это есть в другим платформах - понятно. Но в чем польза? Ведь искажает картину.

**Comment by MAXK04** [comment]
@SBProX Понимаете, мне нужен был график именно по телам свечей, к сожалению вариант с МА (1) до меня на момент открытия данного тикета не дошел, так как использовал фьючерсный график в МТ4 или Ninja. А с МА даже удобнее, так что Вы оставляйте все как есть, а я закрываю тикет. (Пожалуйста, сделайте тикет #392 - с июля/августа жду.)
