### ISSUE TITLE
Вертикальные линии не отображаются на индикаторах - после обновы!

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#704]
![2019-10-09_205658](https://user-images.githubusercontent.com/51231827/66498453-831b8d80-ead7-11e9-987e-9feb24aa7929.png)

**Comment by Bolt022** [comment]
Линии не закрыть теперь... крестика не видно тоже.

**Comment by Bolt022** [comment]
с вопросом разобрался 
![2019-10-09_210416](https://user-images.githubusercontent.com/51231827/66499234-d9d59700-ead8-11e9-8aa5-db27b15c1494.png)

**Comment by Bolt022** [comment]
НО ТЕПЕРЬ РЯД ПРОБЛЕМ С ЛИНИЯМИ
![2019-10-09_210524](https://user-images.githubusercontent.com/51231827/66499289-f376de80-ead8-11e9-92fa-b8bae07d7510.png)

**Comment by Bolt022** [comment]
+ ПОСЛЕ СНЯТОЙ ГАЛОЧКИ ГРАФИК НАЕЗЖАЕТ НА ИНДИКАТОРЫ, А ЕСЛИ ГАЛОЧКА ЕСТЬ, ТО ЛИНИИ НЕ ВИДНО ТЕПЕРЬ...

**Comment by Bolt022** [comment]
ИЗ-ЗА ДУРАЦКОГО ТИКЕТА, ТЕПЕРЬ КРИВИЗНА НОВАЯ https://github.com/SBProX/SBProX-Dev/issues/642

**Comment by Bolt022** [comment]
![2019-10-09_211554](https://user-images.githubusercontent.com/51231827/66499889-1bb30d00-eada-11e9-932c-65e446dea1d9.png)

**Comment by SBProX** [comment]
Завтра подкорректируем. Спасибо.

**Comment by SBProX** [comment]
С этим исправили, можете обновиться.
