### ISSUE TITLE
Элементы рисования не следуют за указателем мыши

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#705]
В общем, где указатель мыши, а где элементы рисования после движений по экрану из одной 
 точки?!
![bandicam_2019-10-09_21-20-04-184](https://user-images.githubusercontent.com/51231827/66500535-228e4f80-eadb-11e9-82ab-0ab45efe48f7.gif)

**Comment by SBProX** [comment]
К сожалению наш прошлый программист, который писал всю эту систему рисования, написал ее настолько глючно, что теперь стоит вопрос о том, чтобы ее полностью переделать.
За 5 минут этот вопрос не решить, тикет останется открытым, будем решать вопрос.

**Comment by Bolt022** [comment]
как человек человека - я вас понимаю, но как потребитель - мне без разницы, какие у вас причины, мне нужно решение проблемы.

**Comment by SBProX** [comment]
@Bolt022 Мы не ваши наемные работники, чтобы от нас что-то требовать.
Вы купили сырую beta версию, а теперь в репозитории ведете себя агрессивно.
Вы что не знали что платформа сырая когда покупали? К чему вы вообще с нами так общаетесь? Что это вам даст? Быстрее от ваших слов мы ничего не сделаем.

**Comment by Bolt022** [comment]
> @Bolt022 Мы не ваши наемные работники, чтобы от нас что-то требовать.
> Вы купили сырую beta версию, а теперь в репозитории ведете себя агрессивно.
> Вы что не знали что платформа сырая когда покупали? К чему вы вообще с нами так общаетесь? Что это вам даст? Быстрее от ваших слов мы ничего не сделаем.

мы купили нормальную бета-версию, а вы своими ... руками еще ухудшаете... разницу чуете?
