### ISSUE TITLE
Снова про вертикальные линии - не портите программу разрабы!

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#706]
Верните ... обратно как было! Я оплачивал за нормальный на тот момент софт, а на текущий момент всё хуже и хуже... вы вообще тестируете то, что исправляете? а после тестирования головой думаете, к чему это может привести? Не портите ... софт. Уже без мата нельзя.

Пишите, что исправили ошибку с линиями... где вы её исправили??? линия теперь вообще перекрывает индикаторы!!! Информативность сильно уменьшили!

Только более менее программу сделали, надо теперь такую херню вытворять. В шоке снова от вас.

![2019-10-10_095855](https://user-images.githubusercontent.com/51231827/66540344-f0b1d300-eb44-11e9-89ec-92a919d07c75.png)

**Comment by Bolt022** [comment]
верните в нормальное состояние... не уродуйте программу!!!
![2019-10-10_101245](https://user-images.githubusercontent.com/51231827/66540859-a3cefc00-eb46-11e9-8a56-631e1f254655.png)

**Comment by Bolt022** [comment]
даже если прозрачность использовать (что неудобно), у индикаторов более яркие оттенки!
![2019-10-10_101703](https://user-images.githubusercontent.com/51231827/66540993-2b1c6f80-eb47-11e9-8265-4e32a303f6bb.png)

**Comment by Bolt022** [comment]
В идеале было бы так... 
1. линии в нормальное состояние привести с прозрачностью и над индикаторами!
2. разделитель периодов тоже заходит на индикаторы
3. элементы рисования (не мешает) и график (мешает) не заезжает на индикаторы

**Comment by SBProX** [comment]
@Bolt022 Исправили, теперь как раньше. Можете проверить.
