### ISSUE TITLE
Проблема с окнами

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#707]
Здравствуйте, описание на скрине
https://c2n.me/440Bpe5.png

**Comment by Bolt022** [comment]
> Здравствуйте, описание на скрине
> https://c2n.me/440Bpe5.png

у меня норм

**Comment by Bolt022** [comment]
А нет, проблема есть, когда окно из развёрнутого состояния выводишь ![2019-10-10_102122](https://user-images.githubusercontent.com/51231827/66541184-d299a200-eb47-11e9-9866-24655bea74f4.png)

**Comment by Bolt022** [comment]
2 окна, в одном ест, а в другом нет кнопочки...одно в развернутом, а другом в узком состоянии, когда его развёртываешь из узкого (2 раза мышью по верхней панели, где название окна), то кнопочка снова появляется
![2019-10-10_102418](https://user-images.githubusercontent.com/51231827/66541327-581d5200-eb48-11e9-9366-5a13605c4d01.png)

**Comment by SBProX** [comment]
Исправлено, можете обновить платформу.
