### ISSUE TITLE
Разрабы, сделайте откат или отказ от обновлений!

### ISSUE THREAD

**Issue by Bolt022** [SBProX/SBProX-Dev#708]
Получать непродуманные обновления, которые портят торговлю - никому не нужно!

**Comment by SBProX** [comment]
Мы не можем сделать отказ от обновлений, так как это будет ад для тех. поддержки.
У одного пользователя будет один функционал. у другого - другой, у третьего - третий, а некоторые вообще не будут обновлять платформу.
