### ISSUE TITLE
Не загружается сохранённый шаблон в новом окне графика

### ISSUE THREAD

**Issue by ANVIG** [SBProX/SBProX-Dev#71]
![не загружается сохранённый шаблон](https://user-images.githubusercontent.com/50530428/57574712-b5e92900-7446-11e9-8272-e85490ad2037.jpg)

**Comment by SBProX** [comment]
Добрый день.

Какой у вас логин?

**Comment by SBProX** [comment]
И название шаблона

**Comment by SBProX** [comment]
Сбрасывайте тогда шаблон на support

**Comment by ANVIG** [comment]
Добрый день. Логин   castle2006@mail.ru
Пробный шаблон   евро 5 мин
После загрузки нового окна графика из меню, пробую загрузить в нём единственный этот шаблон (GE), как без проблем делается в текущей версии V2, но не то что не загружается график с евро и всеми созданными отметками, а загружается график GA. Если создать новое окно нажав + слева внизу в открытом окне, что не даёт возможности одновременно визуально наблюдать два или несколько окон, то там загружается GE, но опять же без созданных отметок. Такое ощущение что сам шаблон не запоминается кроме его названия. Сама платформа воспринимается визуально чётче и яснее текущей, но из-за странного её поведения с шаблонами пользоваться не комфортно. При загрузке рабочего пространства отметки не теряются.


>Понедельник, 13 мая 2019, 13:38 +03:00 от SBPro X <notifications@github.com>:
>
>Добрый день.
>Какой у вас логин?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Анатолий Грибов

**Comment by SBProX** [comment]
Совсем не понятно в каких отметках идет речь.
В новой платформе шаблоны не запоминают в себе инструмент, тайм фрейм, даты и например, линии. Шалон запоминает только настройки фильтров, и индикаторы.

**Comment by ANVIG** [comment]
Понятно. Печально. В будущем шаблоны будут запоминать инструмент, отмеченные линии и всё остальное как в текущей версии ? У меня он даже валюту не запоминает. Если нет то было бы неплохо оставить в продаже текущую версию V2 на выбор с этой после 5 июня.  Получается вроде сохранение шаблона в меню есть, а он ничего не запоминает. На отмеченных линиях, которые к сожалению не запоминаются, стратегии строятся, которые в истории необходимо запоминать. Выходит так что загрузишь график в новом окне какого-нибудь дня месячной давности, или нескольких дней чтобы проработать хождение цены по отношению к крупным кластерам к примеру в 5 сек таймфрейме, наставишь линий для визуальности, проделаешь массу работы, и вся работа теряется при закрытии этого окна. Большая просьба сделать сохранение шаблонов полноценно как в V2

**Comment by ANVIG** [comment]
![Image 1](https://user-images.githubusercontent.com/50530428/59520444-a3915d80-8ed2-11e9-9356-754be5b33a28.jpg)
Это что за гэп такой сегодня? В МТ4 такого нет

**Comment by ANVIG** [comment]
![Image 2](https://user-images.githubusercontent.com/50530428/59521209-629a4880-8ed4-11e9-9fc6-ecc450362cd6.jpg)

**Comment by egk60793** [comment]
у меня та же проблема с шаблонами! Как решить?

**Comment by egk60793** [comment]
в тестере не прогружается начальная история а стартует сразу с нее, а не с начальной даты. Загружаю несколько инструментов для теста, но проигрывает только один! я купил недоработаную версию!!1

**Comment by egk60793** [comment]
окно с установками симулятора бесполезное, оно само не сворачивается, что очень раздражает. Во время симуляционных торгов от него нужны только две кнопки, стоп и пауза, а это хуёвина занимает добрую часть экрана

**Comment by egk60793** [comment]
из не сохранения шаблонов невозможно торговать!! второе окно с теми же инструментами тупо не сохраняется, приходиться заново прогружать все графики, выставлять уровни и все разметки. как с эти справиться?

**Comment by egk60793** [comment]
это хоть кто то читает?

**Comment by egk60793** [comment]
есть кнопка, в настрйках, "сохранить по умолчанию", но не "Востановить по умолчанию"
браво, разработчики!

**Comment by egk60793** [comment]
такое ощущение, что ее придумали спецом, чтоб бы
ло неудобно

**Comment by ANVIG** [comment]
> из не сохранения шаблонов невозможно торговать!! второе окно с теми же инструментами тупо не сохраняется, приходиться заново прогружать все графики, выставлять уровни и все разметки. как с эти справиться?

Вот именно. Из-за этого пользуюсь старой версией, там всё сохраняет.

**Comment by SBProX** [comment]
@egk60793 ошибки исправляются, ожидайте обновлений.
И если можно то общайтесь нормально.

**Comment by SBProX** [comment]
Доработано, проверяйте.
Старые шаблоны не работает, необходимо создавать новые.
