### ISSUE TITLE
Сетка окон (графиков)

### ISSUE THREAD

**Issue by Logser** [SBProX/SBProX-Dev#713]
Хочу выразить признательность, разработчикам платформы. Вы сделали, на мой взгляд, очень удобную штуку, а именно добавление вкладок в каждом окне (графике) это круто. Хотел бы узнать, планируется ли в дальнейшем создать сетку окон (графиков) наподобие МТ4, TOS? Если нет, то пожалуйста, сделайте этого очень не хватает. Спасибо.

**Comment by SBProX** [comment]
Уже было несколько похожих тикетов, но к сожалению мы не можем так сделать,
так как изначально архитектура была создана под формат "окно - вкладки".
