### ISSUE TITLE
Не копируются даты из ячейки в ячейку

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#715]
Здравствуйте уважаемые разработчики.
Перестала копироваться дата из одной ячейки в другую.
Этот нюанс появляется только на активных инструментах.  На Америке сессия закрыта и даты копируются. На Фортс с активным торговым днем ячейка с предыдущей датой не копируется.

На скриншоте хотел поставить 9 число но остается только 10 число.

![image](https://user-images.githubusercontent.com/20509322/66565476-2da5b600-eb95-11e9-8fab-038a1d0bf0c4.png)

**Comment by SBProX** [comment]
Добрый день.

Спасибо, исправим.

**Comment by Fen8fen** [comment]
Еще нюанс.
Дата не меняется совсем в активной сессии.
Вбивая ее вручную она также сбрасывается на активный день.

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении
