### ISSUE TITLE
Возможно это ошибка в настройках ценовой линии

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#725]
При выборе всех параметров не сохраняется Текст после выбора цвета.
Приходится заново открывать настройку для задания текста.
![Screenshot_1](https://user-images.githubusercontent.com/55657161/66718101-b4060600-ede8-11e9-8fb0-56018f8ba311.png)

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by SBProX** [comment]
Данной ошибки нет, скорее всего у вас какая-то устаревшая версия.
https://youtu.be/Ie_2n5J4N54
