### ISSUE TITLE
Кнопка ОК в настойках Fibo

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#726]
При нажатии кнопки ОК в настройках Fibo окно настройки не закрывается, как в настройках других инструментов.

**Comment by finast** [comment]
И добавить кол-во уровней желательно.

**Comment by SBProX** [comment]
Да строго говоря это специально сделано, иначе каждый раз приходилось бы заходить в окно настроек. Для фибо - много полей ввода, может человек хочет поменять значения и посмотреть.
Не вижу проблемы закрыть окно крестиком.
