### ISSUE TITLE
В плеере сделать еще дату показа графика

### ISSUE THREAD

**Issue by Pasha5729** [SBProX/SBProX-Dev#73]
Я две темы сделал, это комп глючит, случайно вышло. Я имею введу, чтобы с определенного дня проигрывался плеер, а до этого дня сразу прогружался график.  Просто в разных месяцах разное количество дней, праздники еще что-нибудь, и вот мне надо до определенного момента, в который я закончил торговать, прогрузить график. А какое это количество свечей? Фиг его знает. Приблизительно, то знаю, но всеравно, точно не попадаю, то плюс десять лишних свечей показало, тогда я уже их видел, и торговать с того момента не выйдет. А если плюс десять свечей вышестоящего или большого таймфрейма, тогда пару дней коту под хвост. Не помешало бы такую функцию. А если говорить про небольшие таймфреймы, то там уже от начала торгуемого дня потерпеть можно, показали график до определенного дня, а дальше уже просто проигрывают как обычно. У вас щас скорость не так как в прошлом сбпро, я смотрю, я про прошлую версию плеера думал. Ну ладно, функция всеравно не помешает.

**Comment by SBProX** [comment]
Уже был такой тикет, пожалуйста не дублируйте.

https://github.com/SBProX/SBProX-Dev/issues/47
