### ISSUE TITLE
Алерт на вертикальные профиля (Total Volume и Total Delta)

### ISSUE THREAD

**Issue by Anton144** [SBProX/SBProX-Dev#734]
Добавьте пожалуйста Алерт на вертикальные профиля (Total Volume и Total Delta) как в старой версии,и если вас не затруднит,было бы неплохо сделать возможность устанавливать несколько видов (под каждый фильтр свой сигнал)

**Comment by Anton144** [comment]
Подскажите где в настройках активируется алерт на вертикальный профиль объёма,немогу найти?!

**Comment by SBProX** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/16720120/67046599-3cfaa580-f139-11e9-8568-9b93c5e1a008.png)

Окно "Сигналы" или "Alerts" если у вас стоит англ. язык

**Comment by SBProX** [comment]
https://www.manula.com/manuals/sbprox/sbprox-manual/1/ru/topic/4-6

**Comment by Anton144** [comment]
Спасибо)

**Comment by SBProX** [comment]
Обращайтесь
