### ISSUE TITLE
Автоматическое обновление истории для каждого периода

### ISSUE THREAD

**Issue by Anton144** [SBProX/SBProX-Dev#735]
Автоматическое обновление истории для каждого периода,что я имею в виду:
Для каждого периода (1мин,15 мин и.т.д) мы загружаем определённое количество дней,получается,что каждый день программа подгружает новый день в историю загрузок! 
Это в первую очереджь касается малых таймфреймов,ведь на них наложенна основная часть индикаторов,что в последствии подтормаживает платформу,к примеру на (М1) истории  2-3 дня достаточно ,но поскольку иногда забываешь удолять лишние дни-они со временем накапливаются.
Хотелось бы иметь функцию в общих настройках (Включить или отключить автоматическое обновление истории,с возможностью выбирать периоды (1,5,15 мин итд)
Надеюсь кто нитбудь поддержит)

**Comment by SBProX** [comment]
Такая возможность есть, достаточно выставить кол-во дней для данной вкладке.
При следующей загрузке workspace загрузится необходимое кол-во дней.

![Screenshot_1](https://user-images.githubusercontent.com/16720120/66931244-7bf80080-f03e-11e9-900c-7e034b8d80b3.png)
