### ISSUE TITLE
Перенос цветовых настроек фильтров

### ISSUE THREAD

**Issue by Anton144** [SBProX/SBProX-Dev#736]
Пожалуйста сделайте возможным переносить все цветовые настройки как шаблон,например:
По одному инструменту у меня 7-8 фкладок,на все фильтры,всех основных профилей(Бид-Аск,Дельта,Кластер,гризонтальные и вертикальные профиля)-я использую одинаковые цвета.Чтобы на всех вкладках и во всех индикаторах у меня были единые цвета,мне приходилось (копировать-вставить) достаточно лолгий процесс. Для поиска новых инструментов это очень неоходимо,т.к облегчит рутину и высвободит время,которое лучше потратить на поиск цифр для фильтров!

**Comment by Anton144** [comment]
![Безымянный](https://user-images.githubusercontent.com/18700341/66785218-097c0900-eef6-11e9-8b5a-f964838bb91c.png)

**Comment by SBProX** [comment]
Можно просто сохранить шаблон - потом загрузить его в другом окне или вкладке, и просто поменять тип графика или что вы хотите. Цветовые настройки не должны теряться.
