### ISSUE TITLE
Проблема отображение Клаудов

### ISSUE THREAD

**Issue by Anton144** [SBProX/SBProX-Dev#737]
Есть такая проблемка,она ещё тянется с первой версии платфрмы-это когда несколько Клаудов накладываются друг на друга и очень сложно их открыть по отдельности,а с приходом новой версии,где разные Клауд алгоритмы можно объеденять в одном графике- это стало ещё сложнее,думаю сданной проблемой сталкивался не я один..) Надеюсь ,что то получится придумать!

**Comment by Anton144** [comment]
Да, тут есть над чем подумать,ну как вариант,к примеру,при наведении мышки на область скопления в диапозоне одного тика,появлялся выбор предметов(треугольник,круг итд)-не сказать,что это идеально,но пока на ум больше ничего не пришло )

**Comment by SBProX** [comment]
Вот и нам пока не приходит.
Вернемся позже к этому вопросу.
