### ISSUE TITLE
Ошибка переключения конечной даты

### ISSUE THREAD

**Issue by sbprosupport** [SBProX/SBProX-Dev#739]
В новом окне первый раз можно выбрать любой интервал загрузки истории. Если же один раз выбрать конечную дату, чтобы она совпадала с текущим днем, то после этих действий изменить конечную дату на другую (отличную от текущего дня) уже нельзя.

![Ошибка_переключения_дат](https://user-images.githubusercontent.com/50356876/66812968-89c55d00-ef3c-11e9-957c-5db180d3d6e2.gif)

**Comment by SBProX** [comment]
Да, знаем, это будет исправлено.

**Comment by SBProX** [comment]
Исправлено, будет работать в сл. обновлении
