### ISSUE TITLE
Улучшение (Индикатор Cluster search)

### ISSUE THREAD

**Issue by alexanflint** [SBProX/SBProX-Dev#74]
![наложение](https://user-images.githubusercontent.com/50513516/57594129-473fc480-7547-11e9-849d-190cf68a536a.png)
Здравствуйте,зачастую мною было замечено,что при работе с индикатором Cluster Search,возникали проблемы с читаемостью графика в особо ликвидных местах,несмотря на именение прозрачности индикатора.
Хотелось бы добавить в настройку индикатора побольше различных фигур отображения(например:ромб,треугольник),а также функцию одного выделения в баре,то есть  да бы не было таких наложений в одной свече,чтобы отображался один фильтр(например самый крупный) в свечке.
![выделение](https://user-images.githubusercontent.com/50513516/57594391-86224a00-7548-11e9-8027-9bd7a088146c.png)

**Comment by SBProX** [comment]
Не поддерживаем.
Теряется смысл индикатора.
