### ISSUE TITLE
Фибоначи ошибка

### ISSUE THREAD

**Issue by mscrigna** [SBProX/SBProX-Dev#741]
Добрый день!

У меня Фибоначи рисует всегда 100% на верх и 0% вниз - независимо откуда рисую его

https://www.screencast.com/t/bbsX6YUu

**Comment by mscrigna** [comment]
И еще пожалуйста, делайте что бы цифра могла быть в минусе ! Благодарю

**Comment by SBProX** [comment]
Исправлено, будет работать в следующих обновлениях
