### ISSUE TITLE
Не запускается платформа

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#743]
Здравствуйте, пишет что уже запущена, но это не так. Нажимаешь ок и всё ничего не происходит и платформа не запускается
https://c2n.me/446nTO3.jpg

**Comment by WillBegin1** [comment]
Теперь пропало таже это окно, не появляется

**Comment by WillBegin1** [comment]
Всё заработало, спасибо!

**Comment by X-man77** [comment]
Такая же байда  у меня сегодня утром. Висит процесс в диспетчере задач, прога не запускается.  Убивал процесс 2 раза - с 3-го раза запустилась платформа. Похоже чё-то не так с запуском.
