### ISSUE TITLE
 Баг отображения увеличителя (при отключенном отображении перекрестия)

### ISSUE THREAD

**Issue by AlTuzov** [SBProX/SBProX-Dev#744]
Не корректоно отображается увеличитель при отключённом отображении перекретия. Видео в архиве.
[Video_2019-10-16_121243.zip](https://github.com/SBProX/SBProX-Dev/files/3733521/Video_2019-10-16_121243.zip)

**Comment by AlTuzov** [comment]
Дополнение. Если отключить перекрестие и перезапустить платформу, то не будет отображаться даже пустое окно увеличителя.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении
