### ISSUE TITLE
Масштаб графика в режиме "кластер объём"

### ISSUE THREAD

**Issue by day-trade** [SBProX/SBProX-Dev#76]
Масштаб графика в режиме "кластер объём" с отображением значений кластеров в старой версии можно было делать мельче намного, чем в новой, при это больше графика было видно на экране со значениями в кластерах.  Сейчас в новой версии при попытке уменьшить масштаб, числа просто пропадают, а появляются при гораздо более значительном увеличении графика, чем в старой версии СБ про.  Сделайте пожалуйста этот момент, как в старой версии (чтобы помещалось больше графика на мониторе).

**Comment by SBProX** [comment]
Не дублируйте тикеты пожалуйста.

Уже есть: https://github.com/SBProX/SBProX-Dev/issues/7
