### ISSUE TITLE
График становится мутным при изменении масштаба

### ISSUE THREAD

**Issue by mosnfet** [SBProX/SBProX-Dev#762]
График становится мутным при изменении масштаба, если выбран серый фон за основу.
Поправьте пожалуйста, а то надо вглядываться. Очень неудобно.

[https://yadi.sk/i/CExXZO8Dqe7hpA](url)

**Comment by SBProX** [comment]
У нас нет абсолютно никакой мутности при масштабе.

**Comment by mosnfet** [comment]
Странно. Но еще более странно то, что на мониторе нормально, а не телевизоре при определенном масштабе вообще в молоко уходит. Значит у меня проблема.

**Comment by alex12mosk** [comment]
> Странно. Но еще более странно то, что на мониторе терпимо, но все равно немного меняется яркость баров при масштабировании, а на телевизоре при определенном масштабе вообще в молоко уходит.
> https://yadi.sk/i/ECWp3WaxTJEP3A

Сейчас бы телевизоры использовать для таких мелких вещей.

**Comment by SBProX** [comment]
Ей богу не понимаем где молоко на вашем видео.
Да, когда бары тонкие, то они не так четко видны, особенно при ваших цветах, темно синий на сером не очень контрастно. Но никакой супер размытости нет.
У нас 4k мониторы, все нормально.

Если у кого-то если размытость - пишите.

**Comment by iz0t0pe** [comment]
> График становится мутным при изменении масштаба, если выбран серый фон за основу.
> Поправьте пожалуйста, а то надо вглядываться. Очень неудобно.
> 
> [https://yadi.sk/i/CExXZO8Dqe7hpA](url)

Попробуй это http://windows10-dpi-fix.xpexplorer.com/
Скорее всего это не из-за платформы, а из-за винды, точнее ее способу масштабирования.

**Comment by mosnfet** [comment]
Мне удобней серый цвет, не так по глазам бьет. Мой вопрос в том что при определенном масштабе цвета сереют, посмотрите на бары объемов(они черного цвета). Потом когда еще мельче делаем или крупнее все опять становится контрастным. Это происходит при горизонтальном масштабировании.

> Да, когда бары тонкие, то они не так четко видны, особенно при ваших цветах, темно синий на сером не очень контрастно.

В черной схеме такого не происходит, да.
И повторюсь, на мониторе FHD 22 дюйма не так заметно. Но есть. Видно что свечи, что бары объемов становятся серее, при каком-то среднем масштабе.

> Ей богу не понимаем где молоко на вашем видео

На 42 телике Панасонике, тоже FHD, при заводских настройках, при определенном масштабе, все уходит в серость, и где точки(тики) там получается отлив серебристый. Я покрутил параметр четкость, в настройках телевизора. Если четкость поставить 100 отлив серебристый очень заметен, если 0 отлива нету, но телик показывает размыто. По умолчанию стоит 50.
Как показывает на телевизоре, мне не так важно. Но бывает смотрю на нем графики, и приходится туда-сюда постоянно увеличивать-уменьшать.

**Comment by mosnfet** [comment]
> Скорее всего это не из-за платформы, а из-за винды, точнее ее способу масштабирования.

Спасибо, сейчас у меня 10-ка стоит, но и на 7-ке так же было.

**Comment by SBProX** [comment]
Сообщите ваш логин и имя workspace - посмотрим у себя на ваших настройках.

**Comment by mosnfet** [comment]
szolotov@mail.ru, workspace 6e.
Проверил на другом компьютере, так же себя ведет. 
Графика встроенная Intel на обеих машинах.

**Comment by mosnfet** [comment]
Я понял в чем нюанс. Я увидел похожую ситуацию в другой утилите. Там это решается изменением толщины(жирности линий), 
Вот видео: [https://yadi.sk/i/DhSYGud_KyNyXA](url)

Посему прошу добавить в меню настройки выбор толщины линий для Графика и Объемов. Не сколько вариантов(например 3). В Мультичартс этот пункт называет weight.

**Comment by mosnfet** [comment]
Я не туда нажал и закрыл тему, сорян.

Я понял в чем нюанс. Я увидел похожую ситуацию в другой утилите. Там это решается изменением толщины(жирности линий),
Вот видео: https://yadi.sk/i/DhSYGud_KyNyXA

Посему прошу добавить в меню настройки выбор толщины линий для Графика и Объемов. Не сколько вариантов(например 3). В Мультичартс этот пункт называет weight.
