### ISSUE TITLE
Сортировка индикаторов

### ISSUE THREAD

**Issue by Quantum-G** [SBProX/SBProX-Dev#763]
В новой версии сделали каталог индикаторов с удобной системой их сортировки.
Но с последним обновлением, ничего этого нет. 
Верните! Ничего нового делать или создавать не надо здесь, просто верните.
![Screen Shot 21 10 2019 at 18 59](https://user-images.githubusercontent.com/34577071/67222717-8b0ff180-f436-11e9-9716-920627b7ccf2.png)

**Comment by SBProX** [comment]
Мы вообще не трогали сортировку, все должно быть на месте.

Попробуйте удалить и переустановить с сайта, это какой-то глюк.

![image](https://user-images.githubusercontent.com/16720120/67300435-9aef0a80-f4f6-11e9-9623-04d91a8cc730.png)
