### ISSUE TITLE
Вечерняя сессия

### ISSUE THREAD

**Issue by CuJlaMblcJlu** [SBProX/SBProX-Dev#765]
Рынок FORTS, не до конца показывает закрытие рынка
![22 10](https://user-images.githubusercontent.com/53310098/67262724-107eba80-f4a6-11e9-9fa4-e00dfc80bfa7.png)
А так на сайте Московской биржи
![22 10](https://user-images.githubusercontent.com/53310098/67262764-3015e300-f4a6-11e9-902c-09697b133022.png)

**Comment by r35p3ct** [comment]
Все на месте...
![image](https://user-images.githubusercontent.com/7328803/67266651-6446cf00-f4b9-11e9-950d-20a7569b5ff9.png)

**Comment by SBProX** [comment]
Перезакачали данные, проверьте пожалуйста.
Нужно перезагрузить данные с сервера.
