### ISSUE TITLE
Критическая ошибка платформы

### ISSUE THREAD

**Issue by iz0t0pe** [SBProX/SBProX-Dev#771]
Наконец-то записал этот баг. Причины возникновения неизвестны. На видео все видно, что происходит с интерфейсом. Не работает контекстное меню. Помогает только закрытие процесса через диспетчер. Или надо тупо ждать, пока все вернется в норму. Хорошо, что работает шорткат ctrl+s, а то все рисунки можно потерять...
На всякий случай, такое происходит и на 1 монике с разрешением 1366х768, и на 3-х мониторах по 1980х1080.
![bandicam2019-10-2321-54-08-302](https://user-images.githubusercontent.com/33651181/67425795-6906a280-f5e1-11e9-86d1-9a1d1be5b638.gif)

**Comment by SBProX** [comment]
Удивительно. 
Ok, выложим обновление - проверите.
Ни разу такого не видели, в репозитории тоже никто не писал о такой проблеме.

**Comment by iz0t0pe** [comment]
> Удивительно.
> Ok, выложим обновление - проверите.
> Ни разу такого не видели, в репозитории тоже никто не писал о такой проблеме.

Я написал, чтобы знали, если что. Она, наверное, ультраредкая, поэтому можно не париться).

**Comment by iz0t0pe** [comment]
> Ok, выложим обновление - проверите.

Обновился - проблема сохранена. ПО было свернуто минут 15-20, появились эти глюки, а затем исчезли, как видно на видосе.
![bandicam2019-10-2419-13-26-752](https://user-images.githubusercontent.com/33651181/67504858-d8889a80-f692-11e9-9195-bd827866080b.gif)

**Comment by SBProX** [comment]
На данный момент проблема не решена?

**Comment by iz0t0pe** [comment]
> На данный момент проблема не решена?

3 обновления назад проблема сохранялась. В текущем обновлении ещё не ловил этот баг.

**Comment by iz0t0pe** [comment]
Update.
Проблема сохраняется, только что опять словил.

**Comment by iz0t0pe** [comment]
Часто этот баг вылезает, когда нажимаю Свернуть все окна.

**Comment by iz0t0pe** [comment]
Кстати, при перемещении и изменении окон с помощью WindowGrid, платформа падает.

**Comment by iz0t0pe** [comment]
> Часто этот баг вылезает, когда нажимаю Свернуть все окна.

update: Точно! Только что нажал клавиши win+D, затем развернул окна и появился данный баг. Скорее всего это мой уникальный баг, связанный с данной сборкой винды, железом.

**Comment by SBProX** [comment]
Как ни пытались воспроизвести проблему - у нас все в порядке, полчаса пробовали мучать всевозможными способами
