### ISSUE TITLE
Размерность ширины ценового уровня при построении профиля объема

### ISSUE THREAD

**Issue by danilp2** [SBProX/SBProX-Dev#773]
Просьба дать возможность задавать размерность ширины ценового диапазона при построении профиля объема. Насколько я вижу, профиль строится по каждому ценовому уровню (шагу цены) в рамках выбранного диапазона. Было бы круто, если бы была возможность задавать ширину ценового уровня. Пример: выбираю диапазон для построения профиля. Плюс задаю ширину ценового уровня по которому будут считаться данные. Если стоит 1, то профиль считается по каждому шагу цены. Если стоит 100, то профиль суммирует данные по каждым 100 шагам цены.

**Comment by SBProX** [comment]
Это будет сделать проблематично, профили считаются из тех баров, которые отрисованы на графике. Кроме того как мы сможем нарисовать профиль с другим шагом цены на оригинальной ценовой шкале?

**Comment by danilp2** [comment]
также, как это сделано в xTick и трейдингвью
