### ISSUE TITLE
Верните пожалуйста прежние линии!

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#774]
Уважаемые разработчики!
После крайнего обновления, что-то произошло с горизонтальными линиями. Именно с линиями в стиле "Simple", они стали прозрачными от начальной точки и более тонкими что ли. Это очень не удобно! Пожалуйста, верните прежние линии. Когда сжимаешь график их практически не видно! Особенно не разобрать точку от которой эта линия проведена, это усложняет работу с графиком!
![image](https://user-images.githubusercontent.com/50597350/67555637-580d7c80-f71a-11e9-9aab-45e742f9b3ca.png)

**Comment by SBProX** [comment]
Да без проблем, сделаем опцию

**Comment by SBProX** [comment]
Сделали опция включения градиента, по умолчанию она выключена.
Сегодня вечером будет обновление.
