### ISSUE TITLE
Ошибки после обновления

### ISSUE THREAD

**Issue by finast** [SBProX/SBProX-Dev#776]
После обновления, при отрисовки фигур, их размер увеличивается или уменьшается при масштабировании и других операциях с графиками.
![рисунки](https://user-images.githubusercontent.com/50439357/67572296-5ca05800-f74f-11e9-97cf-d1758f086f90.jpg)

**Comment by SBProX** [comment]
Можете сообщить нам логин и workspace? 
Проверим.

**Comment by finast** [comment]
finast@yandex.ru
Рабочее пространство - 1

**Comment by SBProX** [comment]
Должно быть исправлено уже.

**Comment by finast** [comment]
Да, уже всё нормально
