### ISSUE TITLE
Не все тики агрегируются а только некоторые

### ISSUE THREAD

**Issue by DenisRvS** [SBProX/SBProX-Dev#78]
Здравствуйте!Почему в новой платформе не все тики агрегированные а только некоторые?
Настройки в SBPro  и Tigertrade показывают минимум 10 контрактов агрегированных посмотрите на разницу в контрактах там и там некоторые контракты вообще не агрегирует
Вот ссылка на видео: https://yadi.sk/i/QeWQyI2irNzNaw

**Comment by DenisRvS** [comment]
Еще ребят!Вот такой должен быть агрегированный график!Есть ли такая возможность сделать такой тиковый график?
![SBProTiger](https://user-images.githubusercontent.com/50508237/57619508-498a3900-75b0-11e9-865e-8e5db73b71d8.jpg)

**Comment by SBProX** [comment]
В Tiger у вас какой источник данных?

**Comment by DenisRvS** [comment]
Источник Rithmic demo регистрировал!Я даже сверял без агрегации тиков,что в SBProX что Tigertrade тики проходили одинаковые.В Tigertrade агрегация тиков в мили секундах!Еще я пробовал настраивать Cloud там правильно агрегирует но визуально лучше видеть на подобие что в Tigertrade

**Comment by SBProX** [comment]
Ок, мы сделаем ленту в виде списка и проверим правильна ли агрегация.

**Comment by DenisRvS** [comment]
А насчет склейки тиков,как выше в скриншоте возможна ли такая агрегация?

**Comment by SBProX** [comment]
У нас тоже агрегация по миллисекундам. Если вы говорите что без агрегации показатели одинаковые, то нужно проверять.

**Comment by DenisRvS** [comment]
Понятно!Спасибо!

**Comment by SBProX** [comment]
Какой у вас часовой пояс стоит для евро? 
Не можем найти это место.

**Comment by SBProX** [comment]
Все, нашли.

**Comment by SBProX** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/16720120/57624574-eb069000-759a-11e9-9105-dc4f0e94bb0f.png)

У нас все считается корректно.
Возможно в Tiger аккумуляция идет по другом алгоритму.

**Comment by DenisRvS** [comment]
Вот еще пара скринов 
![2019-05-13_20-45-31](https://user-images.githubusercontent.com/50508237/57628019-4f3d4a00-75c3-11e9-9591-89d6118362c2.jpg)

**Comment by DenisRvS** [comment]
![2019-05-13_20-57-05](https://user-images.githubusercontent.com/50508237/57628056-63814700-75c3-11e9-8c4d-b1ee55cc86d3.jpg)

**Comment by SBProX** [comment]
Вы ведь не правильно настраиваете. Нельзя ставить минимальный объем тика.
Тик (или трейд) - это как раз НЕ агрегированная сделка.
Минимальный объем тика должен оставаться = 0.

**Comment by DenisRvS** [comment]
А с чего вы взяли что если я ставлю минимальный объем тика допустим 10 это не агрегированная сделка,а как же фильтрация тиков?Если по рынку проходит допустим 5 агрегированных контрактов или 8 контрактов,а мне не нужно чтобы они отображались то я ставлю фильтр показывать минимум 10 контрактов чтобы лента мне показывала от 10 и выше агрегированных контрактов!Вы возможно меня не поняли!
Вот ссылка на обрезанный кусок вебинара https://yadi.sk/i/O3w_kCwP_ZlInw
Вот ссылка на полный вебинар https://www.youtube.com/watch?v=_ZQbXkZhg6o

**Comment by DenisRvS** [comment]
Вы просто меня не правильно поняли про минимальный объем тика!Я же ставлю мин.объем тика уже на ленте с включенной агрегацией!Вот пара скринов
![2019-05-14_07-18-11](https://user-images.githubusercontent.com/50508237/57663245-6c9f0200-761d-11e9-8f03-ae043adfaf11.jpg)

**Comment by DenisRvS** [comment]
![2019-05-14_07-31-40](https://user-images.githubusercontent.com/50508237/57663285-9526fc00-761d-11e9-99ad-36315046f6c2.jpg)

**Comment by SBProX** [comment]
Я вас прекрасно понимаю.
Минимальный объем тика отбирает НЕ агрегированные тики больше либо равно 10 в вашем случае. 
Из из этих отобранных тиков уже проводится агрегация. 
Вы неправильно используете этот фильтр. 

Нужно его оставить 0. А значение 10 нужно ставить в поле "первый фильтр".

**Comment by DenisRvS** [comment]
Спасибо!Можно хотя бы доработать склейку агрегированных тиков в один,я имею ввиду если допустим стоят лимиты на продажу на одном уровне 50 к и выше 50 к и по рынку проходит 100 к на покупку в одну миллисекунду чтобы агрегированный тик объединялся в один тик в 100 к а не на 2 тика по 50 к 
![2019-05-16_11-05-23](https://user-images.githubusercontent.com/50508237/57826223-83d02200-77cc-11e9-9f30-e584c9da812a.jpg)
