### ISSUE TITLE
Ну и последний баг из этой серии...

### ISSUE THREAD

**Issue by X-man77** [SBProX/SBProX-Dev#788]
Хотя и тянулось с лета, но спасибо что исправили: 
![Обнова](https://user-images.githubusercontent.com/33456972/67631526-98573100-f8b9-11e9-9407-fae128cbf4f6.png)

Теперь, надеюсь, последнее из этой серии. Вот график, на нём всё совпадает :
![График](https://user-images.githubusercontent.com/33456972/67631550-d5bbbe80-f8b9-11e9-853c-59d6082037ad.png)

Но стоит поставить Динам.Профиль получается вот это: 
![ДП](https://user-images.githubusercontent.com/33456972/67631621-99d52900-f8ba-11e9-9fed-40b7ea4c0df7.png)

Раньше несовпадение ДП тоже было, но поменьше. Сейчас не совпадает на пол-кластера. Тут уже глюк в координатах ДП, имхо. Причём **несовпадение есть только на свечах,  барах и линейном графике**. На остальных типах графиков ДП совпадает и с кластерами графика и с кластерами PeriodVolumeProfile.

**Comment by SBProX** [comment]
Исправили
