### ISSUE TITLE
Окно авторизации некорректно отображается если свернуть и развернуть

### ISSUE THREAD

**Issue by Ded-Griboed** [SBProX/SBProX-Dev#794]
Если свернуть и снова развернуть, то отображается нормально
![SharedScreenshot](https://user-images.githubusercontent.com/53970105/67670280-4b5d8280-f9bf-11e9-9307-6bd841f2e1da.jpg)

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
Спасибо.
