### ISSUE TITLE
Динамический профиль над панелью индикаторов

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#796]
Залезает в зону индикаторов, с инструментами рисования всё в порядке.
![Screenshot_2](https://user-images.githubusercontent.com/55657161/67734190-6eb11d80-fa11-11e9-8d03-d8d0c3b2e477.png)

**Comment by SBProX** [comment]
Спасибо, упустили.

**Comment by SBProX** [comment]
Исправлено
