### ISSUE TITLE
Line settings

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#798]
Здравствуйте, описание на скрине
https://c2n.me/44kbhMv.png

**Comment by SBProX** [comment]
Сделано, будет работать в сл. обновлении

**Comment by r35p3ct** [comment]
Теперь окно улетает за пределы видимости, если линия внизу:
![2019-10-30_22-20-04](https://user-images.githubusercontent.com/7328803/67891452-ae881a00-fb63-11e9-9d82-5b0ad24b72fe.png)

**Comment by sbpuser** [comment]
На двух мониторах (SBProX на левом) часть окна Line settings отображается на правом мониторе.
Второй (правый) монитор меньше левого, видимо поэтому если линия ниже середины экрана, то окно Line settings вообще улетает за пределы видимости экранов и я его не вижу, и ничего не могу с ним сделать.
Можно пока вернуть как было? А так вещь нужная, возможно, если прописать правила появления рядом с линией, но левее ценовой шкалы, то баг уйдет
