### ISSUE TITLE
vertical histogram

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#799]
Здравствуйте, с данной проблемой обращались уже не раз, исправьте уже раз и навсегда)
https://c2n.me/44kuEFT.png

**Comment by SBProX** [comment]
Вышлите пожалуйста полный скриншот окна, чтобы мы могли у себя поставить такой же график.

**Comment by WillBegin1** [comment]
https://c2n.me/44ncH5M.png

**Comment by SBProX** [comment]
Исправили, сможете проверить в следующем обновлении.
