### ISSUE TITLE
Даты на графике не обновляются. Загружается вчерашний день.

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#8]

**Comment by Samm2019** [comment]
![Количество дней](https://user-images.githubusercontent.com/50338402/57248457-d175bd80-705b-11e9-89e1-a3645dafa10e.png)
Ставим галочку и выбираем сколько дней загружать

**Comment by Dmitry1970** [comment]
Для чего тогда эти графы?
![2019-05-07_7-10-35](https://user-images.githubusercontent.com/35344271/57271239-63e78280-7097-11e9-9342-191f9181b6a7.jpg)

**Comment by Dmitry1970** [comment]
> ![Количество дней](https://user-images.githubusercontent.com/50338402/57248457-d175bd80-705b-11e9-89e1-a3645dafa10e.png)
> Ставим галочку и выбираем сколько дней загружать

Не помогает. Где-то вчерашний день, где-то вообще 29 апреля.

**Comment by Dmitry1970** [comment]
В старой версии всё работало. Время на графиках, т.е. последняя дата вверху, стояло как системное время на компьютере, т.е. текущая дата, а график отображал последнюю дату и время торгов.

**Comment by Dmitry1970** [comment]
Ещё раз проверил: где-то стоит 5 мая, где-то 6 мая, где-то 29.04. Кол-во дней для рабочего пространства выставил с запасом.

**Comment by Artem074** [comment]
есть такая беда... но она появляется тогда, когда перед этим сам ручками дату двигал при анализе... и котировка, соответственно, к этой дате и прилипает.

**Comment by SBProX** [comment]
Объясните пожалуйста последовательность действий.
Что именно вы делаете?

**Comment by SBProX** [comment]
Напишите последовательность действий развернуто.
Мы проверяли, даты работают.
