### ISSUE TITLE
Пересмотр 7 тикета! Изучите лучше комменты!

### ISSUE THREAD

**Issue by Artem074** [SBProX/SBProX-Dev#80]
https://github.com/SBProX/SBProX-Dev/issues/7

**Comment by SBProX** [comment]
Изучили.

Куда вы хотите еще меньше шрифт?
Меньше уже будет не читабельно.

Смотрите скриншот:
![Screenshot_9](https://user-images.githubusercontent.com/16720120/57622157-b2b08300-7595-11e9-8965-85846207f3cc.png)

**Comment by Artem074** [comment]
Откуда у вас такие мелкие циферки ?! нет у меня таких... смотрю Si...

**Comment by Artem074** [comment]
Видео сюда нельзя загрузить что ли? Так намного наглядней будет видно...

**Comment by Artem074** [comment]
сделал GIF
![bandicam_2019-05-13_18-12-05-308](https://user-images.githubusercontent.com/50441291/57624437-59534e80-75ab-11e9-951c-1792453602ae.gif)

**Comment by SBProX** [comment]
В окне логин у вас обновление от какого числа?

**Comment by Artem074** [comment]
от 08.05.2019

**Comment by Artem074** [comment]
> В окне логин у вас обновление от какого числа?

от 08.05.2019

**Comment by SBProX** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/16720120/57627684-20ae7780-75a1-11e9-8f2f-8eff4990c796.png)

Мельче уже будет не читабельно.
В старой платформе мелкий шрифт, даже на вашем gif видно что уже цифры не читабельны при низком масштабе.

**Comment by Artem074** [comment]
> ![Screenshot_11](https://user-images.githubusercontent.com/16720120/57627684-20ae7780-75a1-11e9-8f2f-8eff4990c796.png)
> 
> Мельче уже будет не читабельно.
> В старой платформе мелкий шрифт, даже на вашем gif видно что уже цифры не читабельны при низком масштабе.

У меня даже такого уплотнения кластера, как у вас на картинке! Может от разрешения зависит или от дюйма моника...

**Comment by Flawmaster** [comment]
Мельче делать точно не надо. Еще в чате телеграма просили сделать масштабирование, чтобы шрифт был больше. И ведь сделали - сейчас вроде по-лучше стало, чем в первых версиях. Все потому, что если смотреть на такой мелкий шрифт целый день, то глаза устают очень сильно.
Хотя, если вы просили уменьшить не сам шрифт, а его минимальный размер, при сжатии - то это вроде как неплохо (для того, чтобы быстро сжать и оценить общую картину, а потом снова увеличить график).

**Comment by Artem074** [comment]
> Мельче делать точно не надо. Еще в чате телеграма просили сделать масштабирование, чтобы шрифт был больше. И ведь сделали - сейчас вроде по-лучше стало, чем в первых версиях. Все потому, что если смотреть на такой мелкий шрифт целый день, то глаза устают очень сильно.
> Хотя, если вы просили уменьшить не сам шрифт, а его минимальный размер, при сжатии - то это вроде как неплохо (для того, чтобы быстро сжать и оценить общую картину, а потом снова увеличить график).

Разумеется, минимальный размер нужно... на то и тема"масштабирование"

**Comment by SBProX** [comment]
По нашему мнению насчет минимального шрифта, то вы придираетесь.
Давайте трезво смотреть на вещи, что можно оценить среди кучи мелких нечитабельных цифр?
Уменьшив масштаб, вы и так видите фильтры на графике - если хотите посмотреть что именно находится в какой-то конкретной точке, то вы можете немного увеличить график или использовать magnifier.

**Comment by SBProX** [comment]
Мелкий нечитабельный шрифт сильно портит внешний вид кластерного графика, выглядит это несуразно.

**Comment by Artem074** [comment]
> Мелкий нечитабельный шрифт сильно портит внешний вид кластерного графика, выглядит это несуразно.

шрифт не надо меня под постоянную константу, его надо меня при сжатии!

**Comment by SBProX** [comment]
Артем, мы не делаем аналог старой версии.
На наш взгляд делать мелкий шрифт при мелком масштабе граничит с бредом, так как это не несет практической ценности, так как шрифт становится не читабельным. Уже 20 раз я об этом написал.

**Comment by Artem074** [comment]
> Артем, мы не делаем аналог старой версии.
> На наш взгляд делать мелкий шрифт при мелком масштабе граничит с бредом, так как это не несет практической ценности, так как шрифт становится не читабельным. Уже 20 раз я об этом написал.

Ладно, всё равно мне это не нужно... думал, что человеку, который создал  тикет это полезней )

**Comment by ershner** [comment]
@Artem074 Спасибо, Артем!
@SBProX В текущей версии отображения шрифта кластеров меня не устраивает невозможность отображения текста на трехзначных кластерах в масштабе по х меньше 27. При такой конфигурации число кластеров в окне меньше чем в предвидущей версии. С учетом того что тикет на данную тему создал не только я один - проблема имеет место быть. Остальное решают разработчики...

**Comment by ershner** [comment]
В старой версии трехзначные кластера отображались с масштаба 16 и пользователь сам решал - что для него мелко, а что нет. В текущей версии - от 28.

**Comment by Artem074** [comment]
> В старой версии трехзначные кластера отображались с масштаба 16 и пользователь сам решал - что для него мелко, а что нет. В текущей версии - от 28.
ну вот...человек понимающий  в этом написал... сделайте 16 для трехзначных и всё... кому как надо, тот увеличил или уменьшил кластера.

**Comment by SBProX** [comment]
ok, делаем reopen - посмотрим как это можно обыграть будет.
Нам не нравится отображение шрифта в старой версии, если получится улучшить - сделаем.

**Comment by Artem074** [comment]
> ok, делаем reopen - посмотрим как это можно обыграть будет.
> Нам не нравится отображение шрифта в старой версии, если получится улучшить - сделаем.

в старой намного информативней и лучше отображение кластеров! сейчас смотрю на экран 27 дюймового монитора и влезает очень мало кластеров... я бы сказал беда-печаль...

**Comment by SBProX** [comment]
То что больше влезает, это понятно.

Но что значит информативнее и лучше отображение? Что именно лучше?

**Comment by Artem074** [comment]
> То что больше влезает, это понятно.
> 
> Но что значит информативнее и лучше отображение? Что именно лучше?

да даже визуально лучше + больше кластеров вмещается, в которых видны трехзначные числа (помимо зафильтрованных), тем самым кругозор у трейдера больше (не нужно совершать лишних движений по растягиванию и сжиманию графика), порой этой растяжки хватает, чтобы видеть всю картину в целом по дню, а когда побольше надо увидеть, лупа помогает.

**Comment by SBProX** [comment]
Улучшили по вашим просьбам.
Будет работать в следующем обновлении.

**Comment by SBProX** [comment]
Так лучше?
![Screenshot_14](https://user-images.githubusercontent.com/16720120/58427813-5e36f880-80a9-11e9-80c9-59de2a2dad92.png)

**Comment by ershner** [comment]
Да, спасибо.
