### ISSUE TITLE
Динамический профиль БАГ

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#800]
Я им редко пользуюсь, но раньше вроде бы он работал корректно.
![2019-10-30_18-54-17](https://user-images.githubusercontent.com/7328803/67875092-efbe0100-fb46-11e9-8730-fdaa10ceff89.gif)

**Comment by SBProX** [comment]
Только что выложили обновление. 
Можете проверить.
Если ошибка сохранится, можете сделать reopen тикета.
