### ISSUE TITLE
Расширение прямоугольника

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#801]
После сегодняшнего обновления прямоугольник продолжает самопроизвольно расширяться при его перемещении.
Что ещё странно, есть 2 прямоугольника, оба расширяются, создаёшь третий, он не расширяется, удаляешь один из 2-х расширяющихся и ставишь третий на место удалённого, и теперь он тоже начинает расширяться.

**Comment by SBProX** [comment]
Скриншот графика пожалуйста вышлите.
У нас вообще идеально работает, никаких багов нет

**Comment by SBProX** [comment]
Может у вас платформа не обновилась корректно, попробуйте удалить и переустановить её.

**Comment by SBProX** [comment]
Дело в том, что мы поменяли алгоритм перемещения объектов, и произовольное измените ширина невозможно с математической точки зрения.

Либо все таки у вас не встало обновление, либо мы что-то не досмотрели. 
Попробуйте переустановку.

**Comment by GetterN1** [comment]
Переустановил, не помогло. 
![Новый точечный рисунок](https://user-images.githubusercontent.com/55657161/67915321-b36cbe00-fba3-11e9-9030-4be09a26612a.png)

**Comment by GetterN1** [comment]
Расширяется везде только в левую сторону.

**Comment by SBProX** [comment]
Нашли ошибку, исправили, сейчас выложим обновление.

**Comment by SBProX** [comment]
Выложили, можете проверить.
