### ISSUE TITLE
Баг с фигурами для рисования

### ISSUE THREAD

**Issue by EV124** [SBProX/SBProX-Dev#805]
Если глубина (по временной шкале) инструмента, на который происходит копирование меньше, чем инструмента, с которого копируется (например область ПС в виде прямоугольника), то вставить копируемое невозможно. Т.е. если на М15 загружено 7 дней и нарисован прямоугольник на глубину всех этих дней, то он не вставится на график, например М1 с глубиной загрузки 3 дня.

**Comment by SBProX** [comment]
Почему же это баг?
Как можно вставить прямоугольник у которого другие начальные и конечные даты на график, где нет этих дат.
