### ISSUE TITLE
Показания объемов не совпадают.

### ISSUE THREAD

**Issue by gengal** [SBProX/SBProX-Dev#808]
![Показания не совпадают](https://user-images.githubusercontent.com/24631570/67951645-ab5e5e00-fc37-11e9-9094-87198dde9cf1.png)
На картинке видно, что показания объема индикатора и лупы смещены.

**Comment by SBProX** [comment]
Да, это просто визуальный баг.
Я думаю в данном случае очевидно что объемы одинаковые, просто линия ни тик ниже.
Исправим, спасибо.

**Comment by gengal** [comment]
![Сдвиг](https://user-images.githubusercontent.com/24631570/68593811-fdc63700-04e1-11ea-9190-2931de2194b3.png)
Пока всё без изменений.

**Comment by SBProX** [comment]
Обновления не выходят ежеминутно, дождитесь исправлений.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
