### ISSUE TITLE
Автоцентровка

### ISSUE THREAD

**Issue by ElizarovSS** [SBProX/SBProX-Dev#81]
При установке стрелочки авто смещение и нажатии четыре стрелочки от центра, оное отрубается.

**Comment by SBProX** [comment]
Суть проблемы не понятна.

**Comment by ElizarovSS** [comment]
Нажимаем http://prntscr.com/nnybxz следом http://prntscr.com/nnyc77 получаем снятие http://prntscr.com/nnycfu

**Comment by ElizarovSS** [comment]
Автоцентровка отрубается после приведения к реальному размеру

**Comment by SBProX** [comment]
Так и должно работать, в чем тут ошибка?
Стрелка право привязывается к последнему бару, а если вы смотрите историю то естественно что она отключается. Когда вы расширяете график то у вас отображается на экране история.

**Comment by ElizarovSS** [comment]
Авто центровка (стрелочка вправо) в старой версии постоянно была включена, независимо от того меняем масштаб или нет, тут отключается.

**Comment by ElizarovSS** [comment]
Потому что если смотришь младший таймфрейм это важно к примеру 10 сек увеличил-уменьшил график на том же месте.
