### ISSUE TITLE
Вопрос по расчёту ТФ

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#813]
Здравствуйте, https://c2n.me/44nq7C4.png

**Comment by SBProX** [comment]
Добрый день.

Он не может начинаться с 10.00, так как время считается с 00.00.

Последовательно: 00.00 - 06.00, 06.00 - 12.00, 12.00-18.00, 18.00 - 00.00

Первый бар подпадает под интервал времени 06.00-12.00, поэтому его начальное время и указывается.
