### ISSUE TITLE
Добавление коннекторов или увеличение количества инструментов

### ISSUE THREAD

**Issue by AlexLesha** [SBProX/SBProX-Dev#816]
Добрый день.

Я, как и многие другие наверное, купил платформу увидев обещание разработчиков добавить коннекторы CQG, Rithmic и Interactive Brokers в течение лета 2019. Это было опуликовано ( и все еще находится) на основном веб-сайте продукта. Лето прошло, и осень подходит к концу, но к сожалению обещанных коннекторов добавлено не было. Зато есть очень много обновлений линий, рюшечек и плюшек непонятного свойства. 

Уместно ли попросить разработчиков может быть сфокусироваться на допиле обещанных и столь ожидаемых коннекторов?  С оформлением линий разного фасона навреное можно было бы сделать перерыв - линии, на мой взгляд, оформлены прекрасно. 

Я понимаю, что некоторые функции которые тут заправшивают (как например торговый модуль) разработчики никогда не обещали и даже наоборот - говорили что никогда не будут этим заниматься. Но были же планы по разработке коннекторов.  Если процедурно это может сложно с CQG и Rithmic, то  Interactive Brokers, например, выдают API и официально его продвигают для сторонних соединений, и как я понимаю не требуют каких либо сложных процедур для разработчиков стороннего софта. 

Очень надеюсь что разработчики возобновят работу над коннекторами или добавят инструменты в SBPro (CME, CBOT, NYSE).

Спасибо.

**Comment by SBProX** [comment]
Добрый день.

Да, в целом вы во всем правы. 
Обновления в основном касаются исправления ошибок, которых достаточно много.
Именно поэтому, летом и сейчас, вместо того чтобы делать коннекторы и прочее, занимаемся исправлением ошибок. 

Многие части платформы, например систему графических объектов пришлось полностью переписать, так как она была глючная.

Работаем.

**Comment by AlexLesha** [comment]
Спасибо за ответ. 
Так расскажите пожалуйста, какие же планы по коннекторам?

**Comment by SBProX** [comment]
@AlexLesha После исправления багов займемся коннекторами.
