### ISSUE TITLE
Контракты по нефти

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#817]
По-моему странная последовательность 
![2019-11-01_13-53-37](https://user-images.githubusercontent.com/7328803/68020361-46dee580-fcaf-11e9-9d22-ca95a90382a4.png)

**Comment by SBProX** [comment]
Похоже на ошибку. Проверим.

**Comment by r0b4ik** [comment]
Насколько я понял СБпро в режиме контракта Auto следит за тем , на каком контракте больше объём и соответственно переходит на него. А тут объём скакал то в предыдущем был больше, то в следующем. Так что не совсем ошибка. Не баг, а фича :)))

**Comment by SBProX** [comment]
Все верно, однако это выглядит не очень.. попробуем разобраться.

**Comment by VeegoDamask** [comment]
Линия перехода должна быть не по объему, а по FND (First notice date)
