### ISSUE TITLE
Доработка в бары

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#819]
Здравствуйте, просьба увеличить длину Открытия/Закрытия бара и соответственно уменьшить расстояние между закрытием предыдущих баров и открытием текущих баров, например, как в ATAS или тот же Quik
SBPROX https://c2n.me/44o3LBh.png
QUIK https://c2n.me/44o40bO.png
ATAS https://c2n.me/44o46Ca.png

**Comment by EV124** [comment]
Опционально, плииз

**Comment by SBProX** [comment]
Мы не будем этого делать, бары и так нормально выглядят.
