### ISSUE TITLE
3 улучшения

### ISSUE THREAD

**Issue by bloip** [SBProX/SBProX-Dev#82]
1. добавить третий, четвертый бокс период
2. добавить  при нажатии колеса мыши в окне графика и передвижения мыши возможность просматривать количество не только pips(0,25) на ES, но и количество целых единиц![image](https://user-images.githubusercontent.com/50583511/57625760-90befc80-75a5-11e9-8fcc-a6f0b43b6410.png)

3. добавить   автоматическое выставление  выбранного стопа в симуляторе торгов на реальном рынке

**Comment by SBProX** [comment]
Создавайте отдельные тикеты пожалуйста.
