### ISSUE TITLE
Добавьте индикатор канал Линейной регрессии 

### ISSUE THREAD

**Issue by Alik269** [SBProX/SBProX-Dev#822]
Пожалуйста, добавьте индикаторы: канал Линейной регрессии или Сигмовидной регрессии

**Comment by SBProX** [comment]
SBPro это не платформа для тех анализа.

**Comment by Alik269** [comment]
Здравствуйте! Не могу удалить рабочее пространство RTS _5 м, не удаляется
никак! Удалите его из моей базы, пожалуйста

Александр

пн, 4 нояб. 2019 г. в 18:03, SBPro X <notifications@github.com>:
