### ISSUE TITLE
Ошибка отрисовки линий с начальной точкой на тиковом графике

### ISSUE THREAD

**Issue by r0b4ik** [SBProX/SBProX-Dev#823]
![image](https://user-images.githubusercontent.com/50357928/68110821-5d2ab280-fef6-11e9-9f84-90e44573e28a.png)

Какие то линии отрисовываются нормально, но у большинства начальная точка уходит в крайнюю левую сторону.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
