### ISSUE TITLE
Не запускается платформа

### ISSUE THREAD

**Issue by WillBegin1** [SBProX/SBProX-Dev#826]
Здравствуйте, перестала запускаться платформа. Пробовал переустанавливать не помогает. Вчера поменял HDD на SSD, сделал клонирование, всё прошло успешно. Может это как-то связано?

**Comment by SBProX** [comment]
Добрый день.

Вы имеете в виде не идет коннект, или вообще не запускается?
Так сходу тяжело разобраться.

**Comment by WillBegin1** [comment]
Вообще не запускается. Посмотрел не запускается не только sbprox, но и остальные программы, нажимаю на значок и всё ничего не происходит

**Comment by SBProX** [comment]
Тогда очевидно что тикет можно закрывать

**Comment by WillBegin1** [comment]
походу да)
