### ISSUE TITLE
Баг с прозрачностью линий и фигур

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#827]
Постоянно самостоятельно меняется прозрачность линий и фигур. Уже бесит. 
Огромная просьба ставить в максимальный приоритет  косяки всплывшие из-за изменений в обновлениях, а только потом править прочие "хотелки". Уже 11 дней прошло с поста об этих багах с линиями, куча людей поддержали, а результата нет.

**Comment by SBProX** [comment]
@alex12mosk Последние обновления как раз и должны были исправить.
Опишите пожалуйста при каких обстоятельствах сама меняется прозрачность, в процессе каких действий?

У кого еще такие же проблемы, напишите.

**Comment by SBProX** [comment]
Если можете то вышлите скриншоты для понимания проблемы.

**Comment by SBProX** [comment]
Поставили линии, фигуры, везде задали прозрачность, сохранили workspace, загрузили - все нормально. В процессе работы тоже прозрачность на месте.
Нам нужно понимать куда смотреть, нужно что-то от чего можно отталкиваться в поиске ошибки.

**Comment by alex12mosk** [comment]
Настройки сбрасываются после перезапуска платформы .
Захожу в настройки линий - там 0%, хотя было сохранено 100%. Ставлю 100%, сохраняю, в следующем запуске опять 0%. По-моему еще пару раз сбрасывались прямо во время работы.
![image](https://user-images.githubusercontent.com/50362894/68276742-b32a6200-007e-11ea-986d-dd2bcba64402.png)
Плюсом к этой проблеме открытая ранее тема https://github.com/SBProX/SBProX-Dev/issues/777
Нужно отделить прозрачность заливки фигур от прозрачности линий.

**Comment by alex12mosk** [comment]
@SBProX 
Вот еще нашел случай: ставлю на 100% , нажимаю применить,  опять захожу в настройки линий - стоит 100%, ничего не меняю, нажимаю на крестик в правом верхнем углу, затем опять захожу в настройки линий - там опять 0%.

**Comment by SBProX** [comment]
Спасибо за информацию, сейчас будет пробовать воспроизводить проблему

**Comment by SBProX** [comment]
> @SBProX
> Вот еще нашел случай: ставлю на 100% , нажимаю применить, опять захожу в настройки линий - стоит 100%, ничего не меняю, нажимаю на крестик в правом верхнем углу, затем опять захожу в настройки линий - там опять 0%.

Нашил ошибку, исправили.

**Comment by SBProX** [comment]
> @SBProX
> Настройки сбрасываются после перезапуска платформы .
> Захожу в настройки линий - там 0%, хотя было сохранено 100%. Ставлю 100%, сохраняю, в следующем запуске опять 0%. По-моему еще пару раз сбрасывались прямо во время работы.
> ![image](https://user-images.githubusercontent.com/50362894/68276742-b32a6200-007e-11ea-986d-dd2bcba64402.png)
> Плюсом к этой проблеме открытая ранее тема #777
> Нужно отделить прозрачность заливки фигур от прозрачности линий.

Здесь подразумевается загрузка workspace?

**Comment by alex12mosk** [comment]
"

> > @SBProX
> > Настройки сбрасываются после перезапуска платформы .
> > Захожу в настройки линий - там 0%, хотя было сохранено 100%. Ставлю 100%, сохраняю, в следующем запуске опять 0%. По-моему еще пару раз сбрасывались прямо во время работы.
> > ![image](https://user-images.githubusercontent.com/50362894/68276742-b32a6200-007e-11ea-986d-dd2bcba64402.png)
> > Плюсом к этой проблеме открытая ранее тема #777
> > Нужно отделить прозрачность заливки фигур от прозрачности линий.
> 
> Здесь подразумевается загрузка workspace?

да. сохранение workspace, потом загрузка после перезапуска

**Comment by SBProX** [comment]
Исправили, так же добавили сохранение всех параметров отдельно для каждого элемента.
Можете проверить.

**Comment by alex12mosk** [comment]
@SBProX Все работает. Только теперь я черчу линию и меняю после этого ее цвет,  применяю и эти настройки прописываются для всех дальнейших линий. Так быть не должно. Нужно настройки для начерченных элементов отдельно и заданные настройки по умолчанию отдельно.

**Comment by alex12mosk** [comment]
![image](https://user-images.githubusercontent.com/50362894/68318782-56ef2e80-00ce-11ea-9b78-037eec313f3d.png)
![image](https://user-images.githubusercontent.com/50362894/68318952-974eac80-00ce-11ea-9b12-e9777595de72.png)

**Comment by SBProX** [comment]
@alex12mosk Ну должно или не должно, дело спорное.
Если вы обычно чертите одним цветом, то тогда если будут дефолтные настройки отдельно, то каждый раз придется менять цвет на нужный, что в приципе не удобно.
Люди просили в репозитории сделать запоминание настроек отдельно каждого инструмента, сделали. Мы не можем под каждого подстраиваться, никак. Поймите нас.

**Comment by SBProX** [comment]
Если будет много народа жаловаться, то поменяем.

**Comment by alex12mosk** [comment]
@SBProX  Блин, изначально все было нормально - как в финкорсвиме, например. Сейчас неудобно

**Comment by alex12mosk** [comment]
Запоминание настроек - это настроил в меню дефолт и все, а все дальнейшие настройки уже начерченных фигур - это совсем другое

**Comment by alex12mosk** [comment]
Как раз таки не запоминание, а каждый раз меняется. Я не противоречу тем людям

**Comment by Flawmaster** [comment]
> Люди просили в репозитории сделать запоминание настроек отдельно каждого инструмента, сделали. Мы не можем под каждого подстраиваться, никак. Поймите нас.

Классно сделали, спасибо! Насчет отдельных настроек по умолчанию - все просто. Видимо alex12mosk не совсем понятно объясняет))) Он имеет ввиду, что пускай те настройки, что в панели инструментов задаются будут считаться настройками по умолчанию. Допустим, мы только что начертили прямоугольник, и у него нужно цвет и ширину поменять - тогда эти настройки из контекстного меню не надо сохранять как настройки по умолчанию, т.к. из-за этого одного прямоугольника придется каждый раз возвращать как было. Т.е. достаточно просто не сохранять настройки из контекстного меню элемента рисования, а сохранять настройки только если их задаем через панель инструментов наверху. Единственное, что мы не можем в верхней панели задать ширину элемента по умолчанию. Тогда нужно, наверное, добавить такую настройку в панель инструментов.
з.ы. меня сейчас вполне все устраивает, но как написал alex12mosk тоже логично и освобождает от лишних действий и ускоряет работу. Спасибо за внимание!

**Comment by alex12mosk** [comment]
То же самое написал flawmaster) Если разрабам так понятнее я только за.
