### ISSUE TITLE
Баг на кластерном графике

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#829]
Баг со шрифтом в инструменте 6J. И еще почему-то появились кластера без заливки, хотя настройки не менял и в фильтрах никаких настроек не выставлено.

![2019-11-06_11-39-14](https://user-images.githubusercontent.com/50398637/68282453-cf340080-008a-11ea-8c4f-744247027362.png)

**Comment by SBProX** [comment]
Это связано с последним обновлением. Сегодня исправим

**Comment by SBProX** [comment]
Исправили
