### ISSUE TITLE
Баг с элементом рисования "стрелка"

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#831]
Уважаемые разработчики! Поправьте, пожалуйста, баг - изменение ширины стрелок в настройках никак не влияет на стрелки.

![bug_arrow](https://user-images.githubusercontent.com/50398637/68329883-4bf2c900-00e3-11ea-9773-5e1a59bea102.gif)

**Comment by alex12mosk** [comment]
только по умолчанию оставьте 1, а то мало ли все стрелки перерисуются

**Comment by SBProX** [comment]
К сожалению к стрелке применить параметр толщины не получится на данный момент
