### ISSUE TITLE
Баг с рисованием на графике в режиме симулятора.

### ISSUE THREAD

**Issue by Alehus2** [SBProX/SBProX-Dev#832]
Добрый день. 
В режиме симулятора пытаюсь рисовать. Все элементы отрисовываются только с третьего часа работы симулятора. Только горизонтальная линия рисуется с первого бара. Не критично, но пока с этим разобрался, успел переустановить программу.

**Comment by alex12mosk** [comment]
У меня ни разу не было таких проблем. Значит что-то лично у Alehus2

**Comment by SBProX** [comment]
> Добрый день.
> В режиме симулятора пытаюсь рисовать. Все элементы отрисовываются только с третьего часа работы симулятора. Только горизонтальная линия рисуется с первого бара. Не критично, но пока с этим разобрался, успел переустановить программу.

Можете записать на видео?

**Comment by Alehus2** [comment]
Ок, сегодня сделаю, выложу.

**Comment by Alehus2** [comment]
[https://youtu.be/sB_p093G8HY](url)

**Comment by SBProX** [comment]
@Alehus2 Спасибо

**Comment by SBProX** [comment]
@Alehus2 Исправлено, будет работать в следующем обновлении.

**Comment by Moapsy99** [comment]
good morning.
there is an error when searching PRICE RATINGS. the search does not respect the scheduled date!

![sbpro](https://user-images.githubusercontent.com/52650303/71446416-57e22b00-2723-11ea-9aac-1206822276f3.jpg)
