### ISSUE TITLE
Ошибка с настройками профиля

### ISSUE THREAD

**Issue by test-777** [SBProX/SBProX-Dev#834]
При переходе в настройки профиля открывается черное окно, если начать перемещать его по экрану или свернуть/развенуть что появляется текст полей. Однако прокрутка не работает и в силу этого нет доступа ко всем настройкам:
![Настройки динамического профиля](https://user-images.githubusercontent.com/18189627/68385747-81db9000-016b-11ea-9ec3-59ec3573a228.jpg)

**Comment by X-man77** [comment]
Раньше это окно мгновенно заполнялось настройками, теперь надо ждать до нескольких секунд - 5-7.

**Comment by SBProX** [comment]
@test-777 напишите пожалуйста завтра на telegram @sbproofficial - будем подключаться смотреть.
Судя по скриншоту это какая-то дикость, такого никогда не было.

**Comment by test-777** [comment]
На домашней машине такой ситуации не было. Проблема на рабочей машине решилась переустановкой программы. Тикет можно закрывать.
