### ISSUE TITLE
Верните минимизацию окна загрузки графика

### ISSUE THREAD

**Issue by RoketAnny** [SBProX/SBProX-Dev#837]
Верните пожалуйста минимизацию.
Смысл смотреть на это окно загрузки?, да еще оно всегда поверх всех приложений.
При длительной загрузке очень раздражает, так как приходится его сдвигать туда сюда.
Уверен, что большинство используют свой комп не только для одной торговли, но и занимаются и другими делами.

![image](https://user-images.githubusercontent.com/18662109/68458992-3087db00-0215-11ea-921e-ade0859e12de.png)

**Comment by alex12mosk** [comment]
Да это окно уже просили удалить и поместить в настройки

**Comment by r35p3ct** [comment]
Оно вообще никакой нагрузки не несет, на вкладках есть индикатор загрузки.
В принципе его можно смело закрывать.

**Comment by alex12mosk** [comment]
> Оно вообще никакой нагрузки не несет, на вкладках есть индикатор загрузки.
> В принципе его можно смело закрывать.

Тем более оно каждый раз не нужно. Как и выбор коннектора

**Comment by SBProX** [comment]
@RoketAnny Закройте его, и все. В чем здесь проблема?

**Comment by SBProX** [comment]
Сделано, будет в следующем обновлении
