### ISSUE TITLE
ВАЖНО! Нет обновления графика с начала торговой сессии!!!

### ISSUE THREAD

**Issue by AlexandrBik** [SBProX/SBProX-Dev#838]
Уважаемые разработчики! Уже вторую неделю наблюдаю такой момент. График и время и данные не обновляются с предыдущей сессии. Если платформу не закрывать, данные с утра автоматически не обновляются. После перезапуска такая же ситуация.

![image](https://user-images.githubusercontent.com/52658923/68466349-469d9780-0225-11ea-8b1f-5c556d596a79.png)
![2019-11-08_124409](https://user-images.githubusercontent.com/52658923/68466489-92504100-0225-11ea-8952-5eab0b499926.jpg)

**Comment by SBProX** [comment]
Кажется причина понятна, будем исправлять.
Спасибо.

**Comment by SBProX** [comment]
Было исправлено
