### ISSUE TITLE
не возможно изменить прозрачность баров 

### ISSUE THREAD

**Issue by staspak1** [SBProX/SBProX-Dev#84]
в меню инструменты --- при отрисовке динамического профиля --- в настройках (settings)  - прозрачность баров --- не меняется прозрачность баров 
![2](https://user-images.githubusercontent.com/50586120/57629009-d6d38a80-75bc-11e9-8f66-a20d59c8e945.jpg)

**Comment by SBProX** [comment]
Прозрачность меняется в настройках цвета профиля, а не в поле "Прозрачность баров".
Эта настройка влияет только для delta/bid/ask вариации отображения профиля.
