### ISSUE TITLE
Платформа виснет на стади подключения

### ISSUE THREAD

**Issue by SavosRU** [SBProX/SBProX-Dev#841]
Писал в Телеграмм. Дублирую сюда...

По какой-то непонятной причине зависает на стадии подключения. Сегодня уже третий раз пробую - виснет. Висит так минут 5 и вылетает без предупреждения... 
Перезагружаю компьютер на всякий случай, пробую снова - виснет... 
Ни ошибок, ни каких-то сообщений, просто висит окно логина с надписью "Connecting..."

Да еще при этом само окно будто обрезано со всех сторон на несколько пикселей (до нажатия на кнопку CONNECT ничего подобного). 
Окно так повисит-повисит - и снова программа вылетает без сообщений...

Если нужны подробности: операционная система Windows 10, лицензия, антивирус Касперского лицензия, никакой гадости на машине нет... Аккаунт полноценный, не демо.

**Comment by SBProX** [comment]
Написали вам в telegram
