### ISSUE TITLE
Не работает PrintScreen

### ISSUE THREAD

**Issue by Alexey-Ru** [SBProX/SBProX-Dev#842]
Команда не работает, если активно окно SBPro.
Если же тыкнуть в любое другое место на экране, то команда срабатывает.
Хотелось бы снимать скрины в максимально развернутом окне, то есть чтобы кнопка срабатывала при активной SBPro.

**Comment by Alehus2** [comment]
Кликаю внизу экрана на пустом месте, где все кнопки быстрой загрузки находятся. Тогда SBPro  теряет фокус, но остается открытым во весь экран. Тогда помогает. Но если честно, бесит. Поддержу, сделайте нормальной работу PrintScreen.

**Comment by Alympus** [comment]
Поддерживаю, после какого то обновления отвалилась команда PrintScreen. До обновления все работало исправно. Верните такую возможность по возможности)

**Comment by SBProX** [comment]
@Alexey-Ru @Alympus платформа никак не взаимодействует с PrintScreen.
У нас работает. Но мы проверим, почему такое может быть.

**Comment by Alexey-Ru** [comment]
Пардон, не уточнил важную вещь.
Виндовский принтскрин работает.
Команда не работает через Lightshot. В других приложениях такой проблемы не замечено.
![image](https://user-images.githubusercontent.com/57641739/69081651-821f3980-0a4f-11ea-885c-51745e7d4806.png)

**Comment by Alympus** [comment]
Да именно через Lightshot не работает. Если бы не работала изначально, тогда другой вопрос, но до какого то обновления скрины все работало исправно

**Comment by Alympus** [comment]
Да именно через Lightshot не работает. Если бы не работала изначально, тогда другой вопрос, но до какого то обновления все работало исправно

**Comment by SBProX** [comment]
Смотрите: https://www.youtube.com/watch?v=f3UEcL6PdEs&feature=youtu.be

Сами пользуемся Lightshot и уже очень давно. Никаких проблем. (версия Lightshot 5.5.0.4)

**Comment by Alexey-Ru** [comment]
https://www.youtube.com/watch?v=wmGXBlx47lQ&feature=youtu.be у меня вот так.
Обновил Lightshot до 5.5.0.4. По-прежнему не работает.

**Comment by SBProX** [comment]
@Alexey-Ru не знаю что сказать. У вас не работает, у нас работает (причем на всех компьютерах).

**Comment by SBProX** [comment]
платформа вообще никак не причастна к скринингу экрана, вероятно какой-то локальный конфликт есть.

**Comment by Alexey-Ru** [comment]
Понял. Спасибо.

**Comment by Alehus2** [comment]
Ситуация такаяже. Если вызываю lightshot из SbPro, то команда не работает. В любых других приложениях, работает без проблем. Но если фокус с окна убрать, то принтскрин работает.
Думаю все же косяк в программе сбпро.
