### ISSUE TITLE
Настройки часового пояса графиков слетели

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#844]
1) Почему слетели настройки часового пояса? 
2) Можно сделать галочку чтоб для всех инструментов было одно время? Столько времени теперь тратить на перенастройку часового пояса для каждого инструмента....

**Comment by SBProX** [comment]
1. Зайдите на вкладку со временем, и восстановите системные настройки.
2. Установите нужное время для нужных инструментов
3. Сохраните по умолчанию.

Сделать не должно.

Слетело потому что исправляли баг, и так вышло.

**Comment by alex12mosk** [comment]
@SBProX я правильно понял? В одном окне восстанавливаю настройки времени на системные, меняю все на+3, сохраняю по умолчанию и во всех моих двадцати окнах и вкладках автоматически время будет +3? Или как?

**Comment by SBProX** [comment]
@alex12mosk Да, настройки времени одни для всей платформы.
