### ISSUE TITLE
выкидывает из программы после обновления

### ISSUE THREAD

**Issue by SeregaTS22** [SBProX/SBProX-Dev#849]
иногда виснет программа и выкидывает до обновы такое тоже было и после, и когда запускаешь рейтинг цен тоже виснет и частенько выкидывает

**Comment by SeregaTS22** [comment]
вот видео
https://cloud.mail.ru/public/5Arf/45vyFQopJ

**Comment by SeregaTS22** [comment]
и еще слетают настройки, цвет перекрестия и цвет разделителей периода

**Comment by SBProX** [comment]
Спасибо, рассмотрим.

**Comment by jekksnn** [comment]
проблема с аварийным завершением программы после обновления (по авторизации) есть и довольно часто возникает. Переустановка не помогает.

**Comment by SBProX** [comment]
Исправили, можете проверять
