### ISSUE TITLE
Сброс UTC на стандартные (-6 UTC)

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#853]
Здравствуйте!
После обновления вот такая ситуация...
1. Запускаю платформу и вижу что графики "кривые". Т.е. сбросились все графики на стандартный часовой пояс -6. Время запуска платформы 07:30 (+2 UTC значит по Чикаго -6 UTC это 23:30).
2. Выставляю в настройках времени нужный мне часовой пояс +2 UTC.
3. В 08:00 (при +2 UTC значит в Чикаго -6 это 00:00) снова все временные настройки сбиваются на стандартные. 
4. Снова выставляю нужный мне +2 UTC.
Итак каждый день после последнего обновления! 

http://prntscr.com/pw9nv5
http://prntscr.com/pw9oft

**Comment by SBProX** [comment]
Исправили - попробуйте сохранять и загружать.
