### ISSUE TITLE
Прямоугольники на инструменте GC

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#856]
Сегодня очень странно чертятся прямоугольники на золоте. Т.е. если чертить недалеко от настоящего то прямоугольник "перекидывает" в будущее, а если чертить в далеком прошлом, то прямоугольник моментально "дочерчивается" до настоящего. 
Уважаемые разработчики, поправьте пожалуйста. Хотя баг не очень критичный, т.к. проявился только сегодня на золоте, но возможно он еще проявит себя в будущем.

![rect_bug](https://user-images.githubusercontent.com/50398637/68839071-fd3fc300-06d0-11ea-9ba6-3553aea17ce6.gif)

**Comment by SBProX** [comment]
Как ни пытались, не смогли воспроизвести ошибку (
