### ISSUE TITLE
В симуляторе окно с позицией закрывает кнопки тулбара

### ISSUE THREAD

**Issue by NeveBee** [SBProX/SBProX-Dev#86]
В режиме симулятора если открыть панель инструментов через кнопку Tools bar, то окно с позицией закрывает несколько кнопок. Невозможно воспользоваться динамическим профилем.
![2019-05-13_21-35-16 (2)](https://user-images.githubusercontent.com/24254729/57645823-cb399100-75c7-11e9-899b-0015a5fca1b5.png)

**Comment by SBProX** [comment]
Спасибо исправим.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
