### ISSUE TITLE
Проблемы с графиком кластер профиль

### ISSUE THREAD

**Issue by affectus1** [SBProX/SBProX-Dev#861]
Добрый день! При сужении графика наблюдаю полосы.
![1](https://user-images.githubusercontent.com/51283220/68988203-42492e00-0866-11ea-9ab0-c859063c2e42.png)

**Comment by SBProX** [comment]
Я не вижу никаких дефектов на графике. Какие линии?

**Comment by affectus1** [comment]
> Я не вижу никаких дефектов на графике. Какие полосы?

Я на графике отметил места где есть полосы они проходят через весь график.

**Comment by affectus1** [comment]
> Я не вижу никаких дефектов на графике. Какие полосы?

Я указал на графике стрелочками. как будто разрыв на миллиметр на графике в виде полосы идущей через весь график и их много если присмотреться. Загрузил картинку еще сюда http://www.picshare.ru/view/10360770/ вдруг будет лучше видно.  
![1](https://user-images.githubusercontent.com/51283220/69115825-ab29e380-0abc-11ea-8f8d-2f8906aea770.png)

**Comment by SBProX** [comment]
Это не полосы, это расстояние между ячейками профиля, при низком масштабе такая отрисовка.
