### ISSUE TITLE
Проблема с алертами

### ISSUE THREAD

**Issue by Labama** [SBProX/SBProX-Dev#862]
Устанавливаю линию на ценовом уровне, отмечаю в свойствах линии галочку "Сигнал" и отступ = 1. После нажатия ОК в течении нескольких секунд,  срабатывает сигнал, независимо от того насколько далеко находится цена от линии. 
Это проявляется только при первой установке галочки. Если на том же уровне, после ложной сработки, установить туже галочку "Сигнал", то сигнал работает корректно. 
![изображение](https://user-images.githubusercontent.com/55188444/68989374-7d3f6780-084e-11ea-9796-bb8a8e76b05e.png)

**Comment by SBProX** [comment]
Спасибо, все проверим.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
