### ISSUE TITLE
Закрытие ПО при пропадании связи

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#864]
Может это фишка, но по-моему это не правильно, что программа закрывается, если связь прерывается на примерно секунд 15-30(достаточно преключиться с одной сети на другую)

**Comment by r35p3ct** [comment]
Вижу подобный тикет.

**Comment by SBProX** [comment]
Сейчас проверим у себя, отключив сеть.

**Comment by SBProX** [comment]
Какой у вас логин?

**Comment by SBProX** [comment]
Платформа вылетает с ошибкой, или просто закрывается при смене сети?

**Comment by r35p3ct** [comment]
deito@bk.ru
Просто закрывается без ошибок.

**Comment by alex12mosk** [comment]
У меня вчера пропал интеренет и платформа зависла безвозвратно. Почему программа вообще зависает из-за связи?

**Comment by jekksnn** [comment]
после обновления 21.11. пока платформа работает стабильно и не вылетает при закрытии ноутбука и возобновлении работы.

**Comment by SBProX** [comment]
@alex12mosk С последним обновлением должно быть исправлено уже.
