### ISSUE TITLE
CL не корректные графики

### ISSUE THREAD

**Issue by stason251187** [SBProX/SBProX-Dev#867]
Здравстсвуйте!
Запускаю платформу. Вижу на Д1 нет экспирации и нет объёма последнего бара. При этом на Н1 всё нормально
Д1 - http://prntscr.com/pyx59v
Н1 - http://prntscr.com/pyx5k8

Далее, значит "Перезагрузка данных с сервера" и результат...
Н1 - http://prntscr.com/pyx62b

Перезапуск платформы не помогает.
Спасибо!

**Comment by SBProX** [comment]
@stason251187 подскажите какой часовой пояс у вас стоит для CL

**Comment by SBProX** [comment]
возможно ошибка именно в workspace - сообщите нам ваш логин в платформе и имя workspace
