### ISSUE TITLE
ОШИБКА ПРОФИЛЬ ДЕЛЬТЫ

### ISSUE THREAD

**Issue by SeregaTS22** [SBProX/SBProX-Dev#868]
https://cloud.mail.ru/public/2bnz/4UzspW378

**Comment by SeregaTS22** [comment]
не обновляется дельта

**Comment by SBProX** [comment]
Сообщите пожалуйста ваш логин в платформу и имя workspace.

**Comment by SBProX** [comment]
В какое время был сегодня загружен workspace?

**Comment by SBProX** [comment]
Исправили, можете обновиться.
Такая же ошибка были и в Bid-ask profile
