### ISSUE TITLE
Инструмент для выделения всей зоны

### ISSUE THREAD

**Issue by Ardoti** [SBProX/SBProX-Dev#869]
Добавьте пожалуйста инструмент, который бы выделял бы всю зону и не приходилось бы рукой растягивать выделенный фрагмент, что сказывается на точности. Вот смотрите, как это реализовано в Ниндзя трейдер 8. 
[Presentation1.pptx](https://github.com/SBProX/SBProX-Dev/files/3863619/Presentation1.pptx)

**Comment by weeclemans** [comment]
DUB
[https://github.com/SBProX/SBProX-Dev/issues/334](url)

**Comment by GetterN1** [comment]
Что вас в существующем решении не устраивает?
![Screenshot_4](https://user-images.githubusercontent.com/55657161/69368762-c7d83e00-0cab-11ea-94ab-7daa674770ad.png)

**Comment by SBProX** [comment]
Сделали
