### ISSUE TITLE
закрытие SbPro X

### ISSUE THREAD

**Issue by calnago** [SBProX/SBProX-Dev#870]
программа сама закрывается проработав 1-30 мин.
пробывал без загрузки рабочего пространства,тоже самое.v.2 работает без проблем.общался с вашим сотрудником по тимвью,он сослался на загрузку больших объемов  графиков.все уменьшил периоды--не помогло.проверял сеть в командной строке -- без ошибок.регил демку две недели назад,ни одного вылета.сеть---оптоволокно.

**Comment by SBProX** [comment]
Добрый вечер.

Платформа закрывается с ошибкой, или просто закрывается?

**Comment by SBProX** [comment]
Пробуйте сейчас

**Comment by jekagame** [comment]
тоже начала вылетать после предпоследнего обновления
непонятно почему за день 1-2 раза

**Comment by Fen8fen** [comment]
Программа закрывается возможно из за недостатка оперативной памяти. (у меня 4ГБ)
При старте (сбпро) в диспетчере задач она  занимает 200- 300 мб. через 4 часа работы она занимает 1000 мб. Причем это значение прыгает если в настоящем дне начать загружать предыдущие дни) если этого не делать то она занимает 300 - 400 мб
Далее при листании графика, окно графика становится белым и появляется окно ожидание отклика программы или закрытие программы.

**Comment by calnago** [comment]
сегодня.20.11.с утра два раза закрылась.
оперативка тут не причем по крайней мере в моем случае..выше же написал,что закрывается в режиме без загрузки рабочего пространства,v.2 работает без проблем 5 окон около 20 графиков.

**Comment by jekksnn** [comment]
После обновления до последней версии (согласно регомендации из-за проблем с авторизацией) программа стала регулярно самопроизвольно аварийно завершать работу. Это в основном проявляется после закрытия ноутбука и возобновления работы. До обновления программы таких проблем не было ни разу. Переустановка не помогает. Программа SBProV работает стабильно. Остальные программы тоже.

**Comment by r35p3ct** [comment]
> После обновления до последней версии (согласно регомендации из-за проблем с авторизацией) программа стала регулярно самопроизвольно аварийно завершать работу. Это в основном проявляется после закрытия ноутбука и возобновления работы. До обновления программы таких проблем не было ни разу. Переустановка не помогает. Программа SBProV работает стабильно. Остальные программы тоже.

я уже ниже описал почему она вылетает. Пропадает связь(спящий режим), потом программа просто закрывается.

**Comment by calnago** [comment]
https://github.com/SBProX/SBProX-Dev/issues/870#issuecomment-555963541
программа вылетает при работе,причем тут сон.сегодня с 8:00 до 15:00(МСК) сама закрылась около 15 раз.потом проработала около 3 часов.сейчас не могу запустить закрывается  в момент загрузки графиков.
по задержкам диапазон 78-83msec.то есть 100 не наблюдал,вылетает и на 77 и 85.

**Comment by SBProX** [comment]
Проблему мы нашли, сегодня поздно вечером будет обновление.

**Comment by jekksnn** [comment]
У меня работа программы не зависит от наличия связи. Отключаю сеть, потом включаю и все в порядке, а вот после закрытия крышки и возобновления работы прекращает работу в 100% случаев.

**Comment by SBProX** [comment]
@jekksnn Выложили только что обновление, теперь должно быть все в порядке.

**Comment by calnago** [comment]
к сожалению,лично у меня без изменений

**Comment by SBProX** [comment]
@calnago Можете выслать скриншот окна логин?
Возможно у вас платформа не обновилась.

**Comment by calnago** [comment]
https://prntscr.com/q04aft

**Comment by SBProX** [comment]
@calnago 

Выбивает вас не по причине ошибки в платформе.
Данные логин мы уже не раз замечаем в использовании - VolumesTrade1@yandex.ru

Вас просто выбивает другой пользователь.
Где Вы взяли этот логин?

Напишите нам в telegram @sbproofficial, будем разбираться.

**Comment by SBProX** [comment]
> У меня работа программы не зависит от наличия связи. Отключаю сеть, потом включаю и все в порядке, а вот после закрытия крышки и возобновления работы прекращает работу в 100% случаев.

Ок, спасибо
