### ISSUE TITLE
Опять слетела разметка

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#871]
Почему опять слетела разметка в рабочем пространстве?
![image](https://user-images.githubusercontent.com/50362894/69221792-2c4eac80-0b89-11ea-8076-0c0b5d8dd8b8.png)

**Comment by alex12mosk** [comment]
Это вы так баг со временем поправили что все сдвинулось на час? Поправьте теперь разметку. С историей работать невозможно.

**Comment by 63vova** [comment]
https://user-images.githubusercontent.com/24702380/69238475-31235880-0ba9-11ea-8347-089ae140d6ce.png

**Comment by SBProX** [comment]
Что такое разметка? Можете писать так, чтобы и нам было понятно.

**Comment by alex12mosk** [comment]
@SBProX  Разметка - все графические фигуры: стрелки, линии, прямоугольники.

**Comment by SBProX** [comment]
@63vova с коррелятором поправили, сегодня поздно вечером будет обновление

**Comment by SBProX** [comment]
@alex12mosk Правильно ли я понимаю, что все нарисованные графические объекты "сдвинулись" на час. Если да, то час вперед или назад? Тяжело понять в чем проблема, так как нет скриншота "до".

**Comment by alex12mosk** [comment]
@SBProX мы с вами явно на разных языках общаемся, но надеюсь найдем понимание.
![image](https://user-images.githubusercontent.com/50362894/69317941-1aced880-0c4d-11ea-9b7c-5e1f60ee12fe.png)
На скрине обведенная стрелка была нарисована под свечкой в 16-40. Я заметил, что она по прежнему в 16-40, но сам график уехал на час и теперь эта свечка в 17-40. Отмеченные всплески объемов в начале открытия американской фондовой биржи в 16-30. Тут явно косяк с временем на графике, ибо 15 октября было все нормально при таком же московском времени +3. Предполагаю проблема из-за перевода часов в штатах и программа с этим не стыкуется

**Comment by SBProX** [comment]
@alex12mosk Исправили, можете проверить.

**Comment by alex12mosk** [comment]
@SBProX все отлично. спасибо огромное!

**Comment by SBProX** [comment]
@alex12mosk Вам спасибо
