### ISSUE TITLE
Косяк с отображением перехода на новый контракт 

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#872]
Уважаемые разработчики, приветствую! Заметил сегодня вот такой баг на CL
![image](https://user-images.githubusercontent.com/50597350/69239015-549ad300-0baa-11ea-8fc0-d5341605a4fe.png)

**Comment by SBProX** [comment]
Это не баг. Платформа отображает тот контракт при склейке, который наиболее ликвидный.
Это такой частный случай произошел.

17.11 объем стал больше на 01-20 контракте, поэтому нарисовалась линия.
18.11 объем стал больше на 12-19
19.11 объем уже окончально перешел на 01-20
