### ISSUE TITLE
Ошибка. При смене временного пояса слетает положение лучей

### ISSUE THREAD

**Issue by Fobos25** [SBProX/SBProX-Dev#873]
Если провести луч на графике, а затем, поменять настройки временного пояса, то луч перемещается на оси времени.

**Comment by Fobos25** [comment]
При чём при смене с "Центральное время США и Канада" на "Москва" с первого раза, по кнопке "Применить", ничего не меняется. Меняется только если перевыбрать потом "Минск", например.

**Comment by SBProX** [comment]
Спасибо, проверим.

Возможно это так же связано с этим тикетом https://github.com/SBProX/SBProX-Dev/issues/871

**Comment by SBProX** [comment]
Баг не обнаружен, все линии на месте после смены пояса - попробуйте скачать с сайте платформу и переустановить
