### ISSUE TITLE
Проблема с объемами

### ISSUE THREAD

**Issue by Alehus2** [SBProX/SBProX-Dev#874]
Не совпадает объем пройденного дня и open/close дня отличается.
![Screenshot_1](https://user-images.githubusercontent.com/56960322/69312545-54e5ad80-0c40-11ea-9a25-42a404eaa4fe.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/56960322/69312553-59aa6180-0c40-11ea-8390-3e8173091fa9.jpg)

**Comment by SBProX** [comment]
Какой часовой пояс стоит для CL?

**Comment by SBProX** [comment]
![image](https://user-images.githubusercontent.com/16720120/69347501-4073d600-0c7d-11ea-9671-296642c4302c.png)

**Comment by SBProX** [comment]
Это у вас платформа в реал-тайме постоянно работала?
При перезагрузке графиков проблема решается?

**Comment by Alehus2** [comment]
Это с утра был запущен терминал. Но перезагрузка помогла решить проблему.

**Comment by Alehus2** [comment]
Добрый день
Смотрю проблемы с объемами продолжаются
![4](https://user-images.githubusercontent.com/56960322/71070499-f56db580-218b-11ea-9432-2df140d9e418.jpg)
