### ISSUE TITLE
Динамичный профиль на индикаторах

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#876]
Опция "Индикаторы над графиком" включена
Инструменты рисования не залезают
![Screenshot_2](https://user-images.githubusercontent.com/55657161/69369266-ceb38080-0cac-11ea-9690-2ed5571fa1b3.png)

**Comment by SBProX** [comment]
Хм, ок - проверим, и исправим.

**Comment by SBProX** [comment]
Исправлено, будет работать в следующем обновлении.
