### ISSUE TITLE
Мелкий баг вертикальной линии

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#877]
![Screenshot_6](https://user-images.githubusercontent.com/55657161/69369888-e8a19300-0cad-11ea-9832-e05fdd22896e.png)

**Comment by SBProX** [comment]
Спасибо, поправим.

**Comment by SBProX** [comment]
У вас скорее всего не обновлена платформа, такого бага нет.
Скачайте с сайта и переустановите - теперь система обновления будет по другому работать, и вы точно будете получать все обновления

**Comment by SBProX** [comment]
Хотя нет, есть баг.

**Comment by SBProX** [comment]
Исправили, будет работать в следующем обновлении, спасибо
