### ISSUE TITLE
Вертикальные линии (временная шкала) (нет крестика для закрытия)

### ISSUE THREAD

**Issue by Fen8fen** [SBProX/SBProX-Dev#879]
Здравствуйте. 

После обновления исчез крестик (закрытие) у вертикальных линий.

**Comment by Alexey316** [comment]
А где там вертикальные линии? У меня только наклонные и горизонтальные.

**Comment by Fen8fen** [comment]
> А где там вертикальные линии? У меня только наклонные и горизонтальные.
- кликнете по временной шкале

**Comment by Alexey316** [comment]
> 
> 
> > А где там вертикальные линии? У меня только наклонные и горизонтальные.
> 
>     * кликнете по временной шкале

Спасибо. Не знал. )) Крести у меня есть.

**Comment by Fen8fen** [comment]
`Спасибо. Не знал. )) Крестик у меня есть.`
Обновите платформу 21.11.2019 update

**Comment by Alexey316** [comment]
А она не автоматически обновляется при запуске? Я ещё не освоился.

**Comment by Fen8fen** [comment]
`А она не автоматически обновляется при запуске? Я ещё не освоился.`
скачайте с официального сайта

**Comment by SBProX** [comment]
Да, уже исправили, сегодня выложим обновление.
Случайно сломали.
