### ISSUE TITLE
Ошибка.

### ISSUE THREAD

**Issue by vik62** [SBProX/SBProX-Dev#88]
При подключение программы через коннектор QUIK платформа зависает.Через коннектор SBProX работает нормально.

**Comment by SBProX** [comment]
А вы коннектор настроили?

**Comment by SBProX** [comment]
Просьба называть тикеты нормально. А не "Ошибка".

**Comment by vik62** [comment]
да коннектор настроен

**Comment by SBProX** [comment]
Напишите завтра в саппорт, потому что это нужно смотреть в живую.
