### ISSUE TITLE
Не обновляются данные

### ISSUE THREAD

**Issue by Alexey316** [SBProX/SBProX-Dev#886]
Данные не подгружаются. Рынок открыт уже больше часа. Котировки не поступают.
![Данные](https://user-images.githubusercontent.com/58070921/69523552-bdad8c80-0f96-11ea-8494-ad6d45db2fe3.png)

**Comment by CuJlaMblcJlu** [comment]
Тоже такая проблема , написал в тех поддержку пол часа назад, ответа нет.

**Comment by Flawmaster** [comment]
То же самое.

**Comment by alex12mosk** [comment]
Вообще не коннектится к серверу сбпро

**Comment by Alexey316** [comment]
При перезагрузке долго соединяется, а потом выдает ошибку

![Коннект](https://user-images.githubusercontent.com/58070921/69525051-de2b1600-0f99-11ea-8946-cc551cf9751b.png)

![коннект 2](https://user-images.githubusercontent.com/58070921/69525062-e3886080-0f99-11ea-922f-bc5e2c0cbfbf.png)

**Comment by X-man77** [comment]
Такая же беда как у Alexey316, но только при первичной загрузке  после обновления.

**Comment by alex12mosk** [comment]
Я подключился без коннекторов, потом пытался сохранить рабочее пространство и сбха вообще зависла

**Comment by Alexey316** [comment]
Ждем.... уверен, что программеры работают над решением ))

**Comment by 11-12** [comment]
С коннектором QUIK тоже ничего не работает!!!

**Comment by stason251187** [comment]
Да, котировки не идут... ((((((

**Comment by CuJlaMblcJlu** [comment]
Спасибо большое, всё работает как и раньше!

**Comment by Alexey316** [comment]
Да. Заработало.

**Comment by SBProX** [comment]
Техническая поддержка же есть, зачем писать в репозиторий..
