### ISSUE TITLE
Нет движения цены второй день!

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#891]
Здравствуйте!
Начиная с понедельника 25.11 нет движения цены на графике. Время замораживается и не двигается. на одних графиках - 10 часов, на других - 11 часов с минутами. Обновление графика, перезапуск платформы не помогает. Проверьте, пожалуйста.

**Comment by SBProX** [comment]
Можете скриншоты высылать?
У нас все работает.

Платформа у вас обновленная?

**Comment by Dmitry1970** [comment]
После сегодняшнего обновления всё заработало. Спасибо!
