### ISSUE TITLE
SP-Pro v2 ОШИБОЧНО РИСУЕТ ГЕП

### ISSUE THREAD

**Issue by SergeyKRR** [SBProX/SBProX-Dev#892]
SB-Pro v2 – нарисовал ГЕП по GC в 72 пункта , которого нет на фьючерсах. Проверял данные  ClusterDelta и ThinkorSwim - ГЕПА нет.  Заново загрузить данные с севера - не помогает. Скриншот прилагаю.
![изображение](https://user-images.githubusercontent.com/58248874/69703356-4137bc80-1102-11ea-9257-8551b2bcf4a1.png)
SBPro v2 scren
![изображение](https://user-images.githubusercontent.com/58248874/69703423-675d5c80-1102-11ea-972f-70affcc08536.png)
ThinkorSwim  scren

**Comment by SBProX** [comment]
Сергей, это репозиторий для SBProX.
По поводу гепа - это склейка контрактов.

Почитайте здесь: https://www.manula.com/manuals/sbprox/sbprox-manual/1/ru/topic/3-1
