### ISSUE TITLE
Не работает шаг цены в симуляторе

### ISSUE THREAD

**Issue by Milishnikoff** [SBProX/SBProX-Dev#9]
На часовом таймфрейме шаг цены переключился на нужный, а на дневном нет. 

![H1](https://user-images.githubusercontent.com/50336416/57248975-725c7c80-704c-11e9-830f-07eedc8e74d4.png)
![D1](https://user-images.githubusercontent.com/50336416/57249017-87391000-704c-11e9-9497-8eecffd83cf2.png)
До этого не работал на обоих графиках.

**Comment by SBProX** [comment]
Почему вы решили что не переключился? На скриншотах этого не понять.

**Comment by Milishnikoff** [comment]
Ну по профилю баров видно.

![D2](https://user-images.githubusercontent.com/50336416/57252659-5f01df00-7055-11e9-9948-c373f505efc5.png)

Вот бары с шагом цены 100

**Comment by Milishnikoff** [comment]
Сейчас перезагрузил платформу заново. Теперь на дневке шаг цены нормальный, а на часовике не правильный. В общем ставится только на один график.

**Comment by SBProX** [comment]
Исправлено.
После обновления проверите - если не будет работать, то сделайте ReOpen тикета.
