### ISSUE TITLE
Добавление функционала в меню "инструменты"

### ISSUE THREAD

**Issue by vasiliyyun** [SBProX/SBProX-Dev#90]
Добавьте пожалуйста в меню "инструменты" обычную горизонтальную линию. Текущая линия по сути является отрезком, а нужна обыкновенная горизонтальная линия которую просто выставляешь по нужному ценовому уровню. Также не хватает трендовой линии и трендового канала.

**Comment by SBProX** [comment]
SBPro это платформа для анализа объемов, а не трендовых линий, каналов и прочего.

**Comment by vpaks** [comment]
А можно панель инструментов сделать не таким ярким, а значки более мелким по размеру, да и сама панель слишком крупная, относительно красиво сделанного меню.

**Comment by SBProX** [comment]
Пожалуйста создавайте отдельные тикеты.
Когда вы пишете предложения в комментариях, то образуется каша.
