### ISSUE TITLE
Рейтинг цен неправильно высчитывает значения

### ISSUE THREAD

**Issue by exclim89** [SBProX/SBProX-Dev#904]
Неправильно высчитываются значения. На одну и ту же дату, на одно и то же время представлено множество копий с разными значениями.
![SBPro PriceRating](https://user-images.githubusercontent.com/53253572/69924088-dbc24200-14ec-11ea-8b1a-8f4dce354b23.jpg)

**Comment by SBProX** [comment]
В этом ошибки нет, счетчитк показывает все найденные значения, а не только максимальные.
Чтобы увидеть максимальные, отсортируйте по объему.
