### ISSUE TITLE
Не обновляются котировки по rsBR 01-20

### ISSUE THREAD

**Issue by sbprosupport** [SBProX/SBProX-Dev#905]
Не обновляются котировки реалтайм по фьючерсу rsBR 01-20 (и по склеенному фьючерсу "Auto" соответственно) при подключении через коннектор "Quik".

Если же подключить для анализа предыдущий контракт rsBR 12-19 через коннектор "Quik" - все работает. Остальные инструменты также корректно работают через коннектор "Quik".
И при подключении через коннектор "SBPro" все инструменты корректно отображаются.

Добавлю, что также не обновляются котировки по контракту 03-20 по инструментам rsSBRF, rsGOLD, rsED, rsSILV, rsSi, rsRTS при подключении через коннектор "Quik".

**Comment by X-man77** [comment]
Абсолютно тоже самое. Началось после последней смены контракта и последнего обновления.

**Comment by SBProX** [comment]
На данный момент тоже не обновляется?

**Comment by X-man77** [comment]
Не обновляются, по всем контрактам rsBR и auto. Обновление графика только по "enter".

**Comment by sbprosupport** [comment]
Добавлю, что также не обновляются котировки по контракту 03-20 по инструментам rsSBRF, rsGOLD, rsED, rsSILV, rsSi, rsRTS при подключении через коннектор "Quik".

**Comment by SBProX** [comment]
Исправлено, можете проверять.
