### ISSUE TITLE
Daily Volume Profile - IsPocLine shortens when zooming into chart

### ISSUE THREAD

**Issue by traderepla** [SBProX/SBProX-Dev#910]
I made a video about the problem I found:

https://drive.google.com/file/d/1BYNqWD1L5CJp-CqBp1gZRoo0A979av8T/view?usp=sharing

If the IsPocLine is aktivated in the Daily Volume Profile Indikator and I zoom into the chart the line disappear

**Comment by weeclemans** [comment]
approved
подтверждаю, встречался с такой проблемой

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by SBProX** [comment]
Fixed.

You will be able to see the changes in the next update.
