### ISSUE TITLE
Линкованные линии в симуляторе

### ISSUE THREAD

**Issue by AlTuzov** [SBProX/SBProX-Dev#913]
Линкованные линии в симуляторе не меняют свой цвет если поменять цвет на одной из них.

**Comment by AlTuzov** [comment]
Сделал видео с данным багом. Также хочу обратить внимание что в режиме симулятора не работают стрелочки масштабирования. Этот баг так-же продемонстрирован на видео.
[Video_2019-12-11_212746.zip](https://github.com/SBProX/SBProX-Dev/files/3951999/Video_2019-12-11_212746.zip)

**Comment by AlTuzov** [comment]
Точнее не работает стрелочка (-->) ориентирующая график по правому краю.

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by AlTuzov** [comment]
Также не переносится текст на залинкованных линиях.

**Comment by SBProX** [comment]
Исправлено, после обновления проверите, если не будет работать сделайте пожалуйста ReOpen тикета
