### ISSUE TITLE
Быстрое сжатие графика

### ISSUE THREAD

**Issue by Flawmaster** [SBProX/SBProX-Dev#916]
Здравствуйте! Если при сжатом графике сначала нажать кнопку "развернуть график" (для оценки ситуации на крупном графике), а затем нажать эту же кнопку для быстрого сжатия графика, то график сожмется чуть сильнее, чем до разворота (увеличения), поэтому каждый раз после такого приходится вручную чуток уменьшать сжатие.
Уважаемые разработчики, поправьте, пожалуйста данный недочет.

![bug](https://user-images.githubusercontent.com/50398637/70778763-0d13fb00-1d94-11ea-8d74-24c392e2f1ad.gif)

**Comment by SBProX** [comment]
Спасибо, проверим.

**Comment by r35p3ct** [comment]
Можно ли сделать так, чтобы было 2 состояния просмотра: нормальный и, к примеру, суженный режим(просмотр большей истории) и потом этой кнопкой их переключать? Может это так и задумывалось...

**Comment by Flawmaster** [comment]
> Можно ли сделать так, чтобы было 2 состояния просмотра: нормальный и, к примеру, суженный режим(просмотр большей истории) и потом этой кнопкой их переключать? Может это так и задумывалось...

Я вообще и думал, что это примерно так и должно работать. Т.е. я в основном работаю на сжатом графике, а потом нажатием этой кнопки делаю кластера нормальными. Ну, а повторное нажатие для возврата на прежний масштаб (сжатый график).

**Comment by r35p3ct** [comment]
> Т.е. я в основном работаю на сжатом графике, а потом нажатием этой кнопки делаю кластера нормальными.

Я смотрю часовик, где обычно отображается чуть больше недели, а при нажатии хочу видеть уже несколько месяцев.
Тут главное сделать смену 2х разных приближений, а уж размер каждый себе подстроит под себя.

**Comment by flyserg** [comment]
Согласен, было реально удобно!

**Comment by SBProX** [comment]
Проверили ошибку, все нормально, никаких изменений до и после нет
