### ISSUE TITLE
Цвета

### ISSUE THREAD

**Issue by Oleksandr70** [SBProX/SBProX-Dev#920]
Сделайте пожалуйста привычный веб набор цветов как это было в сб про 2 ,Это просто невозможно в новой платформе выбрать тот классический цвет который был доступен в веб версии цветов на старой платформе.

**Comment by Oleksandr70** [comment]
Сделайте пожалуйста цвета ВЕБ как это было в сб про 2 где можно было выбрать любой классический цвет по названию цвета.Здесь просто очень трудно выбирать нужный цвет практически невозможно.

**Comment by SBProX** [comment]
У вас есть куча разных палитр, которые вы можете выбрать в нижней части окна.
Не видим в этом какой-то проблемы.
