### ISSUE TITLE
Снова проблемы с объемами

### ISSUE THREAD

**Issue by Alehus2** [SBProX/SBProX-Dev#926]
Добрый день
Смотрю проблемы с объемами продолжаются
Перезагрузка не решает проблему
На скрине 1Н и Day тф.
![4](https://user-images.githubusercontent.com/56960322/71160123-071c8f00-2258-11ea-9ce9-8883dbd7f00e.jpg)

**Comment by SBProX** [comment]
Добрый день.

Будем смотреть и разбираться, отпишем вам в данном тикете.

**Comment by SBProX** [comment]
уже сразу по скиншоту видно что по профилю вы захватываете несколько дней, а сравниваете с дневными объемами. В чем логика?

**Comment by Alehus2** [comment]
Точно, что-то я накосячил
