### ISSUE TITLE
Толщина Бара индикатора цвета баров

### ISSUE THREAD

**Issue by r35p3ct** [SBProX/SBProX-Dev#93]
Хотелось бы помимо окрашивания бара добавить ему выбор толщины для наглядности.

**Comment by SBProX** [comment]
Непонятно о какой толщине и каком индикаторе идет речь, описывайте предложение детально.

**Comment by r35p3ct** [comment]
С системе SBProX есть индикатор Bars Volume Highlight, он по заданному объему подкрашивает бар заданным цветом. 
Вот бы было супер, если помимо выделения цветом добавить возможность сделать его жирнее, изменить толщину.

**Comment by SBProX** [comment]
Это невозможно, движок графика так не умеет
