### ISSUE TITLE
Баг в Бокс чарт

### ISSUE THREAD

**Issue by GetterN1** [SBProX/SBProX-Dev#934]
![Screenshot_4](https://user-images.githubusercontent.com/55657161/71424785-aa313680-26a6-11ea-9fb8-15be8bfe566a.jpg)

**Comment by SBProX** [comment]
Принято, проверим.

**Comment by SBProX** [comment]
![Снимок](https://user-images.githubusercontent.com/16720120/79671153-dbdb8980-81d0-11ea-97e9-c07af506ec8f.PNG)

Посмотрели, вроде все хорошо, возможно уже до вашего тикета исправили.
После обновления проверите результат.
