### ISSUE TITLE
Отсутствие торговых дней в графике

### ISSUE THREAD

**Issue by S9242590100** [SBProX/SBProX-Dev#935]
Добрый день, обнаружил отсутствие некоторых торговых дней в графике фьючерса на индекс РТС. Пример 25.12.2018 года этот день у меня на графике отсутствует как на дневном так и на часовом. У другого пользователя этот день есть.  Версия программы одинаковая, обновления устанавливаю. Пробовал создать новое окно с графиком , ни чего не изменилось. Вероятно есть и другие дни отсутствующие на графике
![тренд](https://user-images.githubusercontent.com/59223195/71442063-013f1600-2750-11ea-8712-acd326a67ca9.jpg)
.

**Comment by SBProX** [comment]
Добрый день.

Да, этого дня нет, и пока что нет возможности подкачать историю.
Как у другого пользователя может быть этот день на SBProX?
У нас на сервере за этот день нет данных.

**Comment by SBProX** [comment]
Данный с большим трудом удалось найти и подкачать, но к сожалению без ОИ
