### ISSUE TITLE
Пропал пункт меню Тиковый График

### ISSUE THREAD

**Issue by implight** [SBProX/SBProX-Dev#939]
У меня был открыт грфик, кажется, Cluster Volume, не помню точно, но не тиковый. Я зашел в Chart Settings / Charts / Tick chart, поставил Min Tick Filter, нажал Save, Apply и выбор Tick chart из меню графика пропал, причем для всех инструментов и перезагрузка программы не помогает.

![image](https://user-images.githubusercontent.com/36406916/71464029-5b2ff200-27c9-11ea-9313-851597a0d89e.png)

**Comment by Vegajav** [comment]
Тиковый просмотр выбирается в "Периоде"(там где минуты, часы)

**Comment by implight** [comment]
Спасибо! Видимо меня вчера ночь глюкануло, я был уверен, что видел его в этом списке.
