### ISSUE TITLE
Надо ли переустанавливать программу после обновления от 13.05?

### ISSUE THREAD

**Issue by Dmitry1970** [SBProX/SBProX-Dev#94]
У Вас написано в п.4 обновления от 13.05: 
4. Исправлены ошибки в системе обновления (необходимо переустановить платформу по ссылке: https://drive.google.com/file/d/1yvw5ErPxAt11rKuhZpyJhj451BHaMCSi/view)

Надо ли переустанавливать программу?

**Comment by SBProX** [comment]
Очевидно что надо.
