### ISSUE TITLE
Добавить параметр Min tick volume в индикаторы Horizontal Volumes

### ISSUE THREAD

**Issue by implight** [SBProX/SBProX-Dev#942]
Рассмотрите возможность реализации фильтрации тиков при построении горизонтальных объмов.

**Comment by SBProX** [comment]
Вы можете выставить этот фильтр в chart setting и все будет работать.
Отдельно для индикатора мы этого сделать не можем, иначе придется считать данный индикатор из тиков, что существенно замедлит загрузку графика.
