### ISSUE TITLE
Добавить параметр Min tick volume в индикаторы Vertical Volumes

### ISSUE THREAD

**Issue by implight** [SBProX/SBProX-Dev#943]
Рассмотрите возможность реализации фильтрации тиков при построении вертикальных объмов, кроме Open Interest.

**Comment by SBProX** [comment]
Вы можете выставить этот фильтр в chart setting и все будет работать.
Отдельно для индикатора мы этого сделать не может, иначе придется считать данный индикатор из тиков, что существенно замедлит загрузку графика.
