### ISSUE TITLE
Добавить параметр Min tick volume в раздел Volume filters индикатора Cluster Search

### ISSUE THREAD

**Issue by implight** [SBProX/SBProX-Dev#944]
Рассмотрите возможность реализации фильтрации тиков при поиске кластеров.

![image](https://user-images.githubusercontent.com/36406916/71467312-84ee1680-27d3-11ea-8e7e-81e914418b63.png)

**Comment by SBProX** [comment]
Вы можете выставить этот фильтр в chart setting и все будет работать.
Отдельно для индикатора мы этого сделать не может, иначе придется считать данный индикатор из тиков, что существенно замедлит загрузку графика.
