### ISSUE TITLE
Предложение по индикатору Total Delta

### ISSUE THREAD

**Issue by poshted1** [SBProX/SBProX-Dev#947]
Индикатор Total Delta можно сделать еще информативнее, если к отображению столбиков добавить "хвосты" показывающие динамику изменения дельты за время формирования свечи. Картинку приаттачил.
С уважением к разработчикам и с Наступающим.
![total Delta](https://user-images.githubusercontent.com/58929207/71535269-bb33af00-2915-11ea-9908-c369507d07e8.jpg)

**Comment by SBProX** [comment]
Чтобы сделать с хвостами, нужн считать гистограмму из тиков, что в корне замедлит загрузку графиков. Пока что у нас нет ответ на этот вопрос, боюсь что мы не сможем этого сделать в ближайшее время.
