### ISSUE TITLE
проблема решена

### ISSUE THREAD

**Issue by in1moment** [SBProX/SBProX-Dev#948]
Сделайте, пожалуйста, возможность выставлять свои звуки на сигналы. Закидываю в папку \SBProX\Alerts ,но программа их не воспринимает.

**Comment by in1moment** [comment]
Сделайте, пожалуйста, возможность выставлять свои звуки на сигналы. Закидываю в папку \SBProX\Alerts ,но программа их не воспринимает.

**Comment by SBProX** [comment]
Сделаем.
