### ISSUE TITLE
Не работает Отступ в настройках горизонтальной линии. Хотелось бы иметь возможность выводить текст слева на графике

### ISSUE THREAD

**Issue by kamalligator** [SBProX/SBProX-Dev#95]

**Comment by SBProX** [comment]
Текст слева - понятно.
А отступ вы как используете?
Это отступ на алерт, а не на положение текста.

**Comment by kamalligator** [comment]
Понятно, я думал что отступ относится к положению текста относительно горизонтальной линии. Такой функциональности не хватает. Спасибо
