### ISSUE TITLE
добавьте пожалуйста индикатор Блла Вильямса "Аллигатор" 

### ISSUE THREAD

**Issue by wolfichsb** [SBProX/SBProX-Dev#955]
уважаемые разработчики, добавьте пожалуйста индикатор Блла Вильямса "Аллигатор" или хотя бы в скользящие средние добавьте возможность смещать их вперед в будущее скажем так, очень прошу, думаю труда вам это не составит, заранее благодарю.

**Comment by wolfichsb** [comment]
![мовинг](https://user-images.githubusercontent.com/59562025/71814692-44718100-308e-11ea-8afe-36c7dd1509e8.PNG)

**Comment by SBProX** [comment]
Мы не будем добавлять ничего из тех. анализа.
