### ISSUE TITLE
После обновления 13,05,2019 неправильно отображаются EMA

### ISSUE THREAD

**Issue by AlexanderStroitelev** [SBProX/SBProX-Dev#98]
![Screenshot_4](https://user-images.githubusercontent.com/36483253/57680440-4b96db00-7636-11e9-8901-7c3b6084c011.png)
неправильная отрисовка
![Screenshot_5](https://user-images.githubusercontent.com/36483253/57680441-4c2f7180-7636-11e9-8f86-955412795d53.png)
.....после того как зашел в индикаторы и нажал Применить они изменились, но после снова отрисовываются неправильно!

**Comment by SBProX** [comment]
Исправлено
