### ISSUE TITLE
Индикаторы Volume Profile

### ISSUE THREAD

**Issue by oy-nikolay** [SBProX/SBProX-Dev#982]
Добрый день. 
Можете добавить в настройках горизонтального объема функцию "прозрачности" 
Данная функция ранее была на версии программы SBpro v2. Данная функция очень удобна. 

Основной индикатор Volume Profile можно добавить функцию в настройках  
"временной период": месяц, неделя, день.  Что позволит не менять основной временной период на графике, а анализ горизонтальных объемов станет лучше. Либо сделать выбор периода горизонтального объема ( с такой даты по такую) 

Спасибо.

**Comment by SBProX** [comment]
Добрый день.

Прозрачность настраивается в окне настройки цвета.
Там есть параметр "А".

**Comment by oy-nikolay** [comment]
Спасибо за первую часть вопроса
Вторая часть: 
Основной индикатор Volume Profile можно добавить функцию в настройках
"временной период": месяц, неделя, день. Что позволит не менять основной временной период на графике, а анализ горизонтальных объемов станет лучше. Либо сделать выбор периода горизонтального объема ( с такой даты по такую)
Насколько возможно сделать данный функционал?

**Comment by SBProX** [comment]
Это сильно усложнит архитектуру платформы и индикаторов.
Мы этого делать не будем. В прошлой версии было такое, о чем вы говорите - в итоге удалили.
Слишком много переплетений получается из-за этих периодов, и кроме того что профиля нужно отдельно подгружать и читать данные. 
Извините, но нет.

**Comment by SBProX** [comment]
Есть же месячные и недельные профиль в виде отдельных индикаторов, и дневные тоже.
