### ISSUE TITLE
Обновление опять не помогло с VWAP. Мувинги тоже перерисовываются

### ISSUE THREAD

**Issue by alex12mosk** [SBProX/SBProX-Dev#99]
Обновление опять не помогло с VWAP. Мувинги тоже перерисовываются. Если у вас не получается закрепить VWAP и мувинги, то может сделать их обновление раз в минуту, а не на каждом тике?
![image](https://user-images.githubusercontent.com/50362894/57680503-72551180-7636-11e9-8d53-15d6379494a3.png)
![image](https://user-images.githubusercontent.com/50362894/57680567-94e72a80-7636-11e9-8382-95a8854af5cf.png)

**Comment by alex12mosk** [comment]
в кластердельте есть функция выбора как часто обновлять VWAP(1 минута/ 5 минут)

**Comment by SBProX** [comment]
Исправлено

**Comment by alex12mosk** [comment]
Если выбрать один день, то все отлично. Если выбрать несколько дней, то перерисовывается

**Comment by alex12mosk** [comment]
> Исправлено

Если выбрать один день, то все отлично. Если выбрать несколько дней, то перерисовывается

**Comment by SBProX** [comment]
Исправили, проверяйте
