### ISSUE TITLE
Внедрение тикеров и улучшений

### ISSUE THREAD

**Issue by Quantum-G** [SBProX/SBProX-Dev#990]
Уважаемые разработчики, давайте начнём голосовать долларом. Кто и сколько готов заплатить  за ту или иную функцию из рассматриваемых.
Например, за тикер Платины - столько-то денег, готовы ли пользователи заплатить;
за то или иное улучшение в режиме голосования, например.
А то на халяву всё сразу хотят.
Так как недавно в Телеграм какнале вы говорили, что в доп финансировании не нуждаетесь (хотя вы дали понять, что инвесторов не приемлите, а насчёт финансирования очень пространно), тем не менее - когда человеку нужно заплатить за то или иное, он уже осознанней будет подходить к процессу выбора.

Уважаемые пользователи, кто из вас разделяет мою точку зрения поставьте "лайк" (нажмите на смайлик сбоку от сообщения)

**Comment by SBProX** [comment]
Мы не будем брать никаких денег и разрабатывать на заказ какой-то функционал.
Это не наш профиль.
